### ISSUE TITLE
Improve bounded CHOOSE in TLC

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#10]
[fl:](https://groups.google.com/forum/#!topic/tlaplus/7fNj_Ug44Yw)

> Choose x \in A : P" is a nice construct that allows to express ideas succinctly but
> TLC evaluates it that way: it generates all the elements in A and then filter them using P.
> If A is large, an exception is thrown.
> 
> A better way to evaluate the construct would be to generate an element of A, check that P is true,
> if yes stop the algorithm in the other case continue. Obviously we can get too long a loop in that
> case but in the better case we can have the opportunity to find the right element in a decent
> time interval which cannot happen with the current algorithm. (Obviously if the loop is too
> long we need a way to stop it.)
> 
> Generating one element at a time and then visiting it, is
> the basic philosophy to evaluate combinatorial objects such as all trees or all permutations favored
> by Knuth in TAOCP 4A. 

The spec below can be used to debug CHOOSE:

```
------------------------------- MODULE Choose -------------------------------
EXTENDS Naturals, TLC

CONSTANT S
VARIABLE x

Init == x = 0

Next == /\ PrintT(CHOOSE s \in S : s > 0)
        /\ UNCHANGED<<x>>
Spec == Init /\ Next 
===================
```

xxyzz:

> CHOOSE is implemented the way it is to ensure that S = T implies CHOOSE x \in S : P(x) = CHOOSE x \in T : P(x).
> The only way I know to ensure this property is to evaluate the set and put it in normal form before choosing an element from it.

**Comment by hwayne** [comment]
What happens in the case where several x satisfy P(x) but one causes a safety violation? The optimization might not catch that.

**Comment by pron** [comment]
@hwayne The semantics of CHOOSE are deterministic (thought perhaps unknown), and `CHOOSE x : P(x)` is always the the same value. CHOOSE never "tries" multiple matching values.

**Comment by johnyf** [comment]
The evaluation of a `CHOOSE` statements seems to be at [`tlatools/src/tlc2/tool/Tool.java#L1435`](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/tlatools/src/tlc2/tool/Tool.java#L1435) and [`Tool.java#L1448`](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/tlatools/src/tlc2/tool/Tool.java#L1448).

Both of these iterate `while ((val = enumSet.nextElement()) != null)`, and return `val` in the earliest iteration that encounters a satisfying choice (`if (((BoolValue)bval).val) return val;`). Thus, it appears that one choice is returned, from possibly many that would satisfy `CHOOSE x \in S:  P(x)`.

As [commented above](https://github.com/tlaplus/tlaplus/issues/10#issuecomment-269432559), the axioms about `CHOOSE` on p.295 do not specify which choice among multiple ones is made. Different interpretations of the `CHOOSE` operator can make different choices, as long as the relevant Zermelo-Fraenkel+`CHOOSE` axioms are satisfied. Nonetheless, a given interpretation should consistently make the *same* choice throughout different expressions and states of a behavior (for example, if at the initial state `v = CHOOSE x \in S:  P(x)`, and later `v` is compared to `CHOOSE x \in S:  P(x)`, then the choices should be the same).

In this respect, the axioms permit some "freedom", in that which satisfying value is selected by `CHOOSE` is independent of the axioms (meaning that we could create different new theories where we add extra axioms that restrict these choices, and those theories wouldn't be inconsistent).
