### ISSUE TITLE
Implement mechanism to inform users of noteworthy news

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#100]
Use case: Inform the user of upcoming changes, significant bugs we found... (no ads!)

UI: A button on the status line which changes its UI state (e.g. enablement) on unread news.

On the server side the news could be hosted at INRIA or in git (Github) as an RSS feed.

**Comment by lemmy** [comment]
Eclipse Oxygen ships with a [built-in RSS reader](https://youtu.be/wI3VC1lhbK8). Also see [Eclipse bug 521514](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521514).

**Comment by quaeler** [comment]
[Link jumping to the timestamp discussing the RSS reader plugin](https://youtu.be/wI3VC1lhbK8?t=6m51s)

**Comment by quaeler** [comment]
Alternatively, we could do something like [KNIME](https://www.knime.com/knime-analytics-platform) does which is to have a dynamically updating 'Welcome Page' - the problem of course is that if a user doesn't keep it open or check it, then they'll miss the updates.

We can get around that problem by opening it for them when there are updates, though some may find that intrusive (so i we could provide a preference to prevent that from happening (not default behaviour.))

**Comment by lemmy** [comment]
There is a mechanism to force-open the welcome screen if changes are detected upon Toolbox start-up. However, that won't work for users who keep the Toolbox running for long periods of time. Ideally, we would use a notification mechanism similar to the update mechanism: Show an item (button) in the status line (and additionally a popup) that opens  the news when clicked.

**Comment by quaeler** [comment]
Well, we could force open an editor pane whenever we want, as you know - so it seems like long-running is a non-issue.

But ok - status line thing-a-ma-jig. When you say "open the news", do you mean:
* opens the welcome page editor pane, which has been modified to load dynamic content
* opens a not yet written new editor pane that loads dynamic content (so that we leave the welcome view untouched)
* opens a web page in an external browser
* door D

?

**Comment by lemmy** [comment]
The mechanism shouldn't be intrusive like an editor pane that suddenly grabs focus.

Technically, I would lean towards door D and check how easy it is to integrate the RSS viewer. The only thing that's missing is for its status line icon to indicate new news.

**Comment by quaeler** [comment]
It wouldn't suddenly grab focus as it would be the result of a user action (clicking on the status line widget notification.)

I'll grab the RSS viewer and see about what can be done to modify its status line contribution UI.

**Comment by quaeler** [comment]
The plugin code [is licensed under EPL](https://git.eclipse.org/c/recommenders/org.eclipse.recommenders.git/)

Under regular installation, it is populated with the Code Recommenders feed, which our users probably have no interest in reading; given that, and that it has a status line presentation which isn't exactly in line with what we want: thoughts on cloning off the latest stable release and including/building that source in our repository?

**Comment by lemmy** [comment]
Lets try to avoid a fork.

Is the feed address hardcoded or configurable via e.g. an extension point? The status line presentation sounds sufficiently generic to me that upstream is likely to welcome a patch.

**Comment by quaeler** [comment]
Actually, i think i'm going to backtrack on that assertion - if one installs only the "news" feature from code recommenders, there are no feeds populated. If one installs the kit-and-kaboodle Code Recommenders RCP feature set which includes the news feature, the ~parent feature does [define a feed (via extension point.)](https://git.eclipse.org/c/recommenders/org.eclipse.recommenders.git/tree/plugins/org.eclipse.recommenders.rcp/plugin.xml#n99)

Ok, no fork; worst case, introduce flexibility to their code and introduce a PR to their product.

**Comment by quaeler** [comment]
Ok to delete my branch now?
