### ISSUE TITLE
MainModelPage's initFormulaSource and nextFormulaSource have heavy weight listeners

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#102]
Each instance of `SourceViewer` (`initFormulaSource` and `nextFormulaSource`) upon construction, have attached a listener (`DirtyMarkingListener` constructed with an instance of `ValidateableSectionPart`) which, when it receives a text change event (for example on key-press), it asks that the entire page be validated (via the `ValidateableSectionPart` instance.)

This causes [what i would call] a notable UX issue; perhaps we could only validate on focus loss?

**Comment by lemmy** [comment]
Does this cause a notable system load on your machine?

**Comment by quaeler** [comment]
It does create halting text entry... maybe i'm a super speed typer, but i can 'feel' a lag trying to get all of the characters of a spec name entered into one of those text fields.

Perhaps it's because the entire validation is happening on the EDT? (conjecture... i haven't followed the rabbit that far down the hole yet)

If you had a gradation of issue severity - this is definitely a minor, IMO.

**Comment by lemmy** [comment]
I once embarked on the project to decouple all long running task from the UI thread (there are some UI tests using AspectJ to check if IO runs in the UI thread). I eventually gave up when I realized that it would constitute a rewrite of a significant portion of the UI.

**Comment by quaeler** [comment]
The `DirtyMarkingListener` instance constructed for these two widgets is presently configured to not validate the model on input change - so this is now a non-issue.
