### ISSUE TITLE
Implement snapshot history depth preference functionality

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#104]
As first raised in #95, change the checkbox preferences widget present starting in 1.5.4 which turns snapshotting on and off to a spinner that defines how many snapshots to keep (with zero meaning perform no snapshotting.)

Implement the janitorial functionality as part of the snapshotting process.

**Comment by lemmy** [comment]
Applied your changes in commit https://github.com/tlaplus/tlaplus/commit/3c087ca428554d796ad7404941fa7ae695b7a1dd. In the future don't bother to open pull requests. Just send me the commit id and I will cherry-pick from your fork.
