### ISSUE TITLE
Implement diff'ing of snapshots

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#105]
As first proposed in #95, now that we have saved snapshots comprising a versioned spec and results from TLC, we should provide a way for a user to diff two selected snapshots, and then present the results of this diff in a coherent manner to the user (since the diff will be comprised of the diffs of two different entities.)

**Comment by lemmy** [comment]
As a very basic but also easy to implement first step, diffing two snapshots should simply diff the two corresponding spec snapshots.  This is indirectly possible by looking at the specs history (Team > Show Local History) and manually matching snapshot timestamps to spec edits.

Instead, the spec explorer should display a "Compare each other" command if two models are selected in the spec explorer.  The command will technically diff the two spec snapshots archived with the model snapshot (no need to use the main spec history).

**Comment by lemmy** [comment]
Can't do due to lack of resources.

**Comment by lemmy** [comment]
Closing because this is too much work to be implemented in the Toolbox.  The '-generateSpecTE' makes this trivial on the command-line.
