### ISSUE TITLE
F3 shortcut does not work for identifiers in subscripts

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#106]
xxyzzn: "I just discovered that if an identifier _id_ appears as a subscript, as in _[][A]_id_ or _WF_id(A)_, then the F3 command doesn't work on _id_.  (If _id_ appears inside a subscript expression, as in _[][A]_<<id, y>>_, then F3 does work on _id_.)"

This issue is potentially related to issue #53. If both problems have the same cause, then it probably means that the cause is some simple bug in SANY's data structure.

@lemmy: Read mails with subject "a possibly enlightening  bug" (31.10.2017) and "recent group posting" (19. - 25.5.2017) for additional context.

**Comment by lemmy** [comment]
Another one by xxyzzn: "If a module defines the identifier Foo and has an INSTANCE Foo statement, then selecting the Foo in the INSTANCE statement and typing F3 takes you to the definition of Foo rather than to module Foo."

**Comment by quaeler** [comment]
To confirm the expected behaviour WRT the Foo sub-issue, the desired behavior is that a new editor pane is opened with the spec containing the module Foo - yes?

**Comment by quaeler** [comment]
Similarly the targets of symbol substitution (resolved as FormalParamNode instances) do not Goto the correct declaration spot in a different module.

**Comment by lemmy** [comment]
Fixed with commit 2e9557809b2a17fa73778b1b0062453bb71e838a
