### ISSUE TITLE
disabled menu entries on mac os high sierra

### ISSUE THREAD

**Issue by jusschwitalla** [tlaplus/tlaplus#108]
I just have installed the toolbox on mac os high sierra with jdk 1.9. It starts ok but then the drop down menus appear to be disabled so that I cannot call "open spec".

Here is the content of the .log file:
!SESSION 2017-11-02 13:36:19.107 -----------------------------------------------
eclipse.buildId=1.5.4
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE
Framework arguments:  -keyring /Users/juergen/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/juergen/.eclipse_keyring

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2017-11-02 13:36:20.378
!MESSAGE TLA+ Toolbox started without arguments.

!ENTRY org.eclipse.core.net 1 0 2017-11-02 13:36:24.382
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

thanks in advance for your help

**Comment by lemmy** [comment]
I cannot reproduce your issue with JDK 9.0.1 on High Sierra 10.13.1. What exactly did you do before the entries went disabled? Does it help to restart the Toolbox?

**Comment by jusschwitalla** [comment]
I'm completely new to TLA and I only downloaded the toolbox and moved it from Downloads to another directory and started the toolbox using the command line. The welcome page appears as described in the video but the menu entries are disabled right from the beginning. I tried to restart the Toolbox using different working directories and I also tried ´xattr -dr com.apple.quarantine Develop/TLA+\ Toolbox.app´which I found in the google group.

**Comment by lemmy** [comment]
Can you post the exact steps and commands taken?

If I download 1.5.4 and move it from ~/Downloads to ~/Applications and launch the Toolbox from ~/Applications/TLA+ Toolbox.app/Contents/MacOS/ by executing ./toolbox in Terminal, I can still access the menu afterwards.

Note that you can start completely fresh by deleting the ~/.tlaplus/ directory.

By the way, is it just the menu bar that's disabled or just about everything (e.g. can you close the welcome view, does the help open when you click "Getting Started")?

"~" is synonymous with your Home folder.

**Comment by jusschwitalla** [comment]
after download:
mv ../Downloads/TLA+\ Toolbox.app/ .    (pwd:/Users/juergen/Develop)
Then I recognised that I had no java installed and installed it.
Then I called  cd TLA+\ Toolbox.app and Contents/MacOS/toolbox with the described result.
I can close the welcome view but the menu entries in "file", "window" and "help" are all disabled. Only the entries in the "TLA+ Toolbox" menu are enabled. 

I see some Warnings on the terminal:
As-MacBook-Pro:TLA+ Toolbox.app juergen$ Contents/MacOS/toolbox
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.emf.ecore.xmi.impl.XMLHandler (file:/Users/juergen/Develop/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.eclipse.emf.ecore.xmi_2.13.0.v20170609-0707.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.eclipse.emf.ecore.xmi.impl.XMLHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jusschwitalla** [comment]
The following works:
Contents/MacOS/toolbox -nl EN_en

my default is DE_de

**Comment by lemmy** [comment]
The warnings in https://github.com/tlaplus/tlaplus/issues/108#issuecomment-341430721 are not relevant/red herrings.

My Toolbox defaults to _EN_de_. When I launch with "_-nl DE_de_" or "de_DE" the _TLA+ Toolbox_ menu is in German, but the other menus remain English **and** functional/enabled.

**Comment by lemmy** [comment]
Note that you can set _-nl EN_en_ permanently in _toolbox.ini_ before _-vmargs_. Just make sure it splits across two lines.

**Comment by jusschwitalla** [comment]
I just checked once more without the nl option: The menu entries again are disabled and if I have a look in "About ../Installation Details/Configuration" I see  "osgi.nl=de_DE" (I mixed up lower and upper case in my previous post). 
In any case - I am able now to go on with the tutorial. So thanks for the quick response. Let me know if you would like some more information about my settings.
