### ISSUE TITLE
Use of TLCSet and TLCGet across multiple workers

### ISSUE THREAD

**Issue by craft095** [tlaplus/tlaplus#1083]
I generate state diagrams from TLA+ specifications and use `TLCSet` and `TLCGet` operators to collect state information. Here is an example of action property that does this:

```tla
Capture ==
    LET
        curr == CurrentState
        next == CurrentState'
    IN
        curr /= next =>
          TLCSet(IxTr, TLCGet(IxTr) \union { Transition(curr, next) })

ASSUME TLCSet(IxTr, {})

CaptureProp == [][Capture]_vars

```

The problem is that getting a value with `TLCGet`, updating and setting it back with `TLCSet` is not thread safe because there is no synchronization that would enforce atomicity of this operation.
As of now I run TLC with `-workers 1`. That works but it takes much time for large specifications.

It would be great to have support for such synchronization.

One idea I thought of is to support `TLCGet("worker-id")`. If I had this one I could collect information locally for each worker and merge it at the very end using `POSTCONDITION`.

Another idea is to use synchronized `TLCGetAndSet` #858 . My concern with this method is that I also need to query this information from time to time with `TLCGet`. E.g. I am not sure if it is safe to use them like this to avoid excessive locking:

```tla
        curr /= next /\ Transition(curr, next) \notin TLCGet(IxTr) =>
          TLCGetAndSet(IxTr, LAMBDA set : set \union { Transition(curr, next) })
```

**Comment by lemmy** [comment]
@craft095 Could you please provide a reproducible test case? I’m having trouble understanding your race condition.

The expression `TLCSet(IxTr, TLCGet(IxTr) \union { Transition(curr, next) })` is evaluated atomically when the current [worker checks the implied action on the current pair of states](https://github.com/tlaplus/tlaplus/blob/fa98279f7459336cb3a932f63a797c4a655b1268/tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java#L418-L491). During this evaluation, `TLCGet` and `TLCSet` are scoped to the current worker’s thread-local storage.

Aggregation of these values can be performed later in the postcondition using TLCGet("all").

```tla
PostCondition ==
    LET F == INSTANCE SequencesExt
    IN PrintT(<<F!FoldSeq(LAMBDA a,acc: a+acc, 0, TLCGet("all")[IxTr]), TLCGet("all")[IxTr]>>)
```

Consider the following spec/model where TLC consistently reports the same "aggregate" regardless the number of workers:

```tla
--------------------------- MODULE BlockingQueue ---------------------------
EXTENDS Naturals, Sequences, FiniteSets, TLC

CONSTANTS Producers,
          Consumers,
          BufCapacity

ASSUME Assumption ==
       /\ Producers # {}
       /\ Consumers # {}
       /\ Producers \intersect Consumers = {}
       /\ BufCapacity \in (Nat \ {0})
       
VARIABLES buffer, waitSet
vars == <<buffer, waitSet>>

NotifyOther(Others) == 
    IF waitSet # {}
    THEN \E t \in waitSet : waitSet' = waitSet \ {t}
    ELSE UNCHANGED waitSet

Wait(t) == /\ waitSet' = waitSet \cup {t}
           /\ UNCHANGED <<buffer>>

Put(t, d) ==
/\ t \notin waitSet
/\ \/ /\ Len(buffer) < BufCapacity
      /\ buffer' = Append(buffer, d)
      /\ NotifyOther(Consumers)
   \/ /\ Len(buffer) = BufCapacity
      /\ Wait(t)
      
Get(t) ==
/\ t \notin waitSet
/\ \/ /\ buffer # <<>>
      /\ buffer' = Tail(buffer)
      /\ NotifyOther(Producers)
   \/ /\ buffer = <<>>
      /\ Wait(t)

Init == /\ buffer = <<>>
        /\ waitSet = {}

Next == \/ \E p \in Producers: Put(p, p)
        \/ \E c \in Consumers: Get(c)

Spec == Init /\ [][Next]_vars

IxTr == 1
ASSUME TLCSet(IxTr, 0)

Monitor ==
    [][TLCSet(IxTr, TLCGet(IxTr) + Cardinality(waitSet))]_vars

PostCondition ==
    LET F == INSTANCE SequencesExt
    IN PrintT(<<"aggregate", F!FoldSeq(LAMBDA a,acc: a+acc, 0, TLCGet("all")[IxTr]), TLCGet("all")[IxTr]>>)

=====    

CONSTANTS
    BufCapacity = 6
    Producers = {p1,p2}
    Consumers = {c1,c2}

SPECIFICATION Spec
PROPERTY Monitor
POSTCONDITION PostCondition
```

**Comment by craft095** [comment]
@lemmy , thank you for clarification! I misunderstood how TLCGet and TLCSet actually work. Your example is very helpful.
