### ISSUE TITLE
Apply TLA+ concepts to implementation languages such as .NET

### ISSUE THREAD

**Issue by AceHack** [tlaplus/tlaplus#109]
Please explain or give me a way to apply these same concepts to .NET core.  I would like to be sure my .NET core code matches exactly my specification and/or just verify my C# code.  Thanks.

**Comment by lemmy** [comment]
Formal verification of implementation languages such as C# is (currently) out of scope of TLA+. We would very much like to have a generator from TLA+ or PlusCal to C# or Java though, but there is nobody working on it. You might want to check out [Spec#](https://www.microsoft.com/en-us/research/project/spec/) and [Boogie](https://www.microsoft.com/en-us/research/project/boogie-an-intermediate-verification-language/). 

Personally, I successfully combined TLA+ with [Java PathFinder](http://babelfish.arc.nasa.gov/trac/jpf) to verify the (manually written) Java implementation of a high-level TLA+ specification. While this approach still requires manual work and thus can introduce bugs, it gets you quite far.

**Comment by lemmy** [comment]
[PGo](https://bitbucket.org/whiteoutblackout/pgo/overview) is the attempt to generate Go code from PlusCal specifications. It currently handles a very limited subset of TLA+.
