### ISSUE TITLE
Proposal: Add reference to errors pointing to a page on the wiki

### ISSUE THREAD

**Issue by FedericoPonzi** [tlaplus/tlaplus#1091]
I was thinking of ways to improve the UX for new users. Similar to what c# and rust do, we could add a reference to each error. The user unfamiliar with this error, can go on the wiki and search it to find an explanation about what when wrong and how to fix it.
Ref: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs8515 or https://doc.rust-lang.org/error_codes/error-index.html

Sample instance of a user confused by an error message: https://www.reddit.com/r/tlaplus/comments/1g4mb4h/error_in_tla_model_checker_the_variables_are_not/

Any thoughts?

**Comment by ahelwer** [comment]
Synchronicity! https://github.com/tlaplus/rfcs/issues/15

**Comment by FedericoPonzi** [comment]
Nice! In this case, I'll close my issue and we can discuss over the rfc issue, thanks @ahelwer
