### ISSUE TITLE
Preference storage is bifurcated between activators

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#110]
Noticed while working on #104, we actually were setting the snapshotting preference default on preference initialization into the preferences hanging [off the `TLCUIActivator`](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/ui/preference/TLCPreferenceInitializer.java#L36).

On value change, it got set into the preferences hanging [off the `TLCActivator`](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/ui/preference/TLCPreferencePage.java#L37)

As part of the TLC execution the preference is checked in the preferences hanging [off the `TLCActivator`](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/launch/TLCModelLaunchDelegate.java#L992).

Ideally, we would have preferences stored against one Activator; `TLCActivator` would not require plugin dependency modifications, but the preferences page is not configured to pull from those preferences. `TLCUIActivator` supports the preferences page, but would introduce dependency requirements to the plugin containing `TLCModelLaunchDelegate`.  ...

Regardless, i'm going to finish implementing #104 in a version of this bifurcation which fixes the initialization issue; then we can further address this later.

**Comment by lemmy** [comment]
Is this still an issue?

**Comment by quaeler** [comment]
It is.

**Comment by lemmy** [comment]
Do we need to fix it?

**Comment by quaeler** [comment]
It's an architectural detail but not necessary.
