### ISSUE TITLE
Please tell me *which* "Successor state is not completely specified by the next-state action."

### ISSUE THREAD

**Issue by jazzdelightsme** [tlaplus/tlaplus#118]
I have a lot of variables already. As I am developing stuff (perhaps adding more steps, or adding yet another variable), I sometimes forget to completely specify the next state for some step. In this case, the model checker gives me an error alerting me to this indiscretion. It would be very helpful if it could also tell me *which* variables have not been updated (or specified as `UNCHANGED`).

**Comment by jazzdelightsme** [comment]
Workaround: in the error trace, in the very last step, the changed variables are highlighted. If one or more of them are "null", they did not get specified.

(But it would still be a nice usability enhancement to just put the missing vars in the error message.)

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/fe8a2e39f0ae82715d59e8d71e5d5cdcd98d84c0
