### ISSUE TITLE
Build with Java 11

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#120]
Travis and Jenkins should be set to bulid with Java 9.

**Comment by lemmy** [comment]
Eclipse Tycho [is not ready yet to compile](http://dev.eclipse.org/mhonarc/lists/tycho-user/msg07776.html) with Java 9. Postponing indefinitely until Tycho is up to it.

**Comment by lemmy** [comment]
Waiting for https://github.com/mojohaus/aspectj-maven-plugin/issues/24 now.

**Comment by lemmy** [comment]
Tycho 1.3 [will add support](https://bugs.eclipse.org/bugs/show_bug.cgi?id=532302) for Java 11.

https://wiki.eclipse.org/Tycho/Release_Notes/1.3

**Comment by lemmy** [comment]
@quaeler Do you want to close this?

**Comment by quaeler** [comment]
Closed!
