### ISSUE TITLE
TLC command line output should be enhanced

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#121]
Currently the boundary between the toolbox and TLC functions as robust text parsing.

It would make life, and extensibility for RFEs like #115, #117, #118, ..., were TLC to also output (slash, output on request) serialized objects containing more diagnostic information concerning the checking; ideally the serialized objects would be in JSON to provide the widest scope for third party applications to piggyback on TLC.

**Comment by lemmy** [comment]
Instead of JSON output I'd prefer to format output as (valid) TLA+ with a mechanism for users to evaluate TLA+ expressions on it.

**Comment by saffroy** [comment]
TLA+ output means that a TLA+ parser is required for a tool to use the output; I would think this seriously limits how one can feed this output to custom tools (AFAIK the only robust TLA+ parser is Java code living in TLA tools?).

For example, when I have a long (20+) error trace from TLC, the trace viewer in the toolbox becomes hard for me to use, and I would like to be able to transform and/or display it with custom scripts (in, say, Python or JS).

Without a widely used format like JSON (or XML, or whatever), it seems difficult to achieve.

**Comment by lemmy** [comment]
@saffroy Encoding error-traces as TLA+ *combined with* the possibility to evaluate arbitrary TLA+ expressions would allow users to convert traces into any format.  E.g. you could evaluate the trace to Json with the help of the [Json module](https://github.com/tlaplus/CommunityModules/blob/master/modules/Json.tla).

**Comment by lemmy** [comment]
@saffroy By the way, why is it hard to use the Toolbox trace viewer with longer traces?

**Comment by lemmy** [comment]
Implementation sketch:  Refactor Toolbox and TLC by moving the functionality to generate TE.tla and TE.cfg into TLC.  Both files could then automatically be generated when TLC finds a violation.

**Comment by saffroy** [comment]
When digging in a "long" error trace, I find that it would be easier for me:

- with a smaller font and/or , so I can see more in a page (maybe I missed how to do that)

- in table form, with variables in columns, so I can focus on some variables or ignore others, by changing the order of columns

- with highlighting of precise changes in sub-expression

At some point I wrote a (fragile) regex-based script to parse MC.out and render it in a way that worked slightly better for me, without interpreting the values in TLA+ (which I would have liked to do).

I also think that being able to generate graphics from traces (with domain-specific rules, e.g. representing message passing between processes) would be very useful, though I never did it myself.

@lemmy I didn't quite get how your proposal would work for model developers: would one be able to apply a generic transformation (e.g. ToJSON) over the trace and export it?

**Comment by lemmy** [comment]
> When digging in a "long" error trace, I find that it would be easier for me:
> 
>     * with a smaller font and/or , so I can see more in a page (maybe I missed how to do that)

https://github.com/tlaplus/tlaplus/issues/162

>     * in table form, with variables in columns, so I can focus on some variables or ignore others, by changing the order of columns

https://github.com/tlaplus/tlaplus/issues/274

>     * with highlighting of precise changes in sub-expression

https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/executing-tlc.html end of "The Trace View"

> 
> At some point I wrote a (fragile) regex-based script to parse MC.out and render it in a way that worked slightly better for me, without interpreting the values in TLA+ (which I would have liked to do).
> 
> I also think that being able to generate graphics from traces (with domain-specific rules, e.g. representing message passing between processes) would be very useful, though I never did it myself.

https://youtu.be/mLF220fPrP4?t=702
https://github.com/tlaplus/tlaplus/issues/191
https://github.com/tlaplus/tlaplus/pull/310

> @lemmy I didn't quite get how your proposal would work for model developers: would one be able to apply a generic transformation (e.g. ToJSON) over the trace and export it?

Exactly, https://raw.githubusercontent.com/tlaplus/tlaplus/master/general/docs/changelogs/screencasts/ExportErrorTrace.gif hints at how this is done with the Toolbox.

**Comment by saffroy** [comment]
> #162

Thanks!

> > ```
> > * in table form, with variables in columns, so I can focus on some variables or ignore others, by changing the order of columns
> > ```
> 
> #274

Nice that we can hide some variables; but to me it is equally important (if not more) that I can re-order the variables that stay visible, that makes it easier for me to compare values of related variables and exhibit patterns.

Also, a table form (with variables in columns, states in rows) means that I can push less interesting variables to e.g. the right side, such that they are usually hidden if there are too many, but I can still easily check their value by scrolling.

> > ```
> > * with highlighting of precise changes in sub-expression
> > ```
> 
> https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/executing-tlc.html end of "The Trace View"

It seems to me that the highlighting doesn't go arbitrarily deep into expressions, but maybe I'm missing something?

(On animations)
> https://youtu.be/mLF220fPrP4?t=702
> #191
> #310

Well, great if people manage to do all that with TLA+, but that's a route I myself wouldn't want to take. While TLA+ is a great environment for modeling, I would much prefer being able to leverage a variety of programming tools (i.e. those I'm used to) to do further processing, including animations, presentations, test case generation, etc. And I don't want to become an Eclipse hacker for this either. ;)

> > @lemmy I didn't quite get how your proposal would work for model developers: would one be able to apply a generic transformation (e.g. ToJSON) over the trace and export it?
> 
> Exactly, https://raw.githubusercontent.com/tlaplus/tlaplus/master/general/docs/changelogs/screencasts/ExportErrorTrace.gif hints at how this is done with the Toolbox.

Interesting, however it seems that:

- working from the toolbox is required (as opposed to simply running TLC)

- given an error trace, one has to copy-paste the trace (okay), and then re-run TLC in the toolbox to evaluate a transformation of the trace: that can be slow (if checking the model takes time) or somewhat cumbersome (if I paste into an empty model just to do the transform)

So I'll take whatever tool that works (including improvements to the trace viewer in the toolbox, even if it has to remain model-agnostic), but I still see much value in the approach suggested by @quaeler above. FWIW I think [this post](https://tkf.github.io/2013/06/04/Emacs-is-dead.html) gives some more general reasons for wanting an "escape hatch".

Thank you!

**Comment by lemmy** [comment]
Can't do due to lack of resources.
