### ISSUE TITLE
Improve OS browser detection on non-standard environments

### ISSUE THREAD

**Issue by has2k1** [tlaplus/tlaplus#125]
Clicking on any of the links e.g `+ Getting Started` gives

```
Unable to open web browser on {0}
```

The solution [here](https://answers.dynatrace.com/questions/104801/linux-client-web-browser-configuration.html) of creating an appropriate symlink worked for me, but as explained there this is not a short-coming on my end.

**Comment by lemmy** [comment]
@has2k1 What's your environment (e.g. what Linux distribution)?

**Comment by has2k1** [comment]
I am using gentoo linux. The issue is there is no `firefox`, `mozilla`, `netscape`, ... in my path.

My exact solution was

```bash
ln -s /usr/bin/google-chrome ~/.local/bin/netscape
```

**Comment by lemmy** [comment]
In other words, the only browser installed on your system is chrome?

**Comment by has2k1** [comment]
I have `firefox`, `google-chrome`, `opera` and a few other smaller browsers. `google-chrome` is my preferred/default option (i.e the value of `$BROWSER`), `firefox` is installed from a binary, so it's executable is `firefox-bin`.

**Comment by lemmy** [comment]
Closing as WONTFIX as we don't have the manpower to address it in the foreseeable future.  Happy to accept a patch though.
