### ISSUE TITLE
Create formula text area widget

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#127]
As a "nice to have," we could make a new widget which would replace existing toolbox SWT.MULTI Text widgets that support formula entry (e.g Model Properties) which would still allow "ASCII entry" of the formulas but render them within the widget as LaTeX'd output.

**Comment by lemmy** [comment]
This is somewhat related to issue #64

**Comment by quaeler** [comment]
Ya - i was navel staring about that.

In one implementation, it could block on unicode being implemented and then actually convert the 'ASCII' entry into the symbol'd-in-unicode version of the text.

In another (presently foggy) implementation, we could mux in PDF rendering with text input in the same widget glom.

**Comment by lemmy** [comment]
You might wanna check out the pron-unicode branch to see what's there already.
