### ISSUE TITLE
Preferences > General > Editors warns about missing preference pages

### ISSUE THREAD

**Issue by evelynmitchell** [tlaplus/tlaplus#128]
Download of 64bit Linux as of 2017-12-22. 
File: Preferences: General: Editors 
  does not have an editor selected, nor does it pick up the system editor, or allow me to specify one.
The editors are listed as:
org.eclipse.ui.preferencePages.FileEditors not found
org.eclipse.ui.preferencePages.ContentTypes not found 

Configuration https://gist.github.com/evelynmitchell/b65fa69e446777d95d515af0793df226

Ubuntu 16.04, 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

This is Version 1.5.4 of 06 October 2017 and includes:
  - SANY Version 2.1 of 23 July 2017
  - TLC Version 2.10 of 28 September 2017
  - PlusCal Version 1.8 of 07 December 2015
  - TLATeX Version 1.0 of 20 September 2017

**Comment by quaeler** [comment]
I can confirm this on Mac as well. What undesired behaviour in the usage of the Toolbox is this presenting?

**Comment by lemmy** [comment]
Some preferences under the Generals sections are not relevant to the Toolbox and shouldn't be there in the first place. Unfortunately, unwanted preferences have the tendency to sneak into the Toolbox with each update of the underlying Eclipse framework. In other words, this is a cosmetic problem without any deeper effects on functionality. Please comment if this is issue is about broken functionality though.

**Comment by evelynmitchell** [comment]
It's not clear to me, after exploring a bit more, if this prevented me from doing anything. But it was puzzling at the time, because I was looking at the preferences while working through the tutorial, and this was not available.

Thank you.

**Comment by lemmy** [comment]
Those affected please raise an [Eclipse bug](https://bugs.eclipse.org).  Nothing *we* can do about it.
