### ISSUE TITLE
An internal error occurred during: "TLC run for Model_1". tlc2.tool.fp.OffHeapDiskFPSet.isSupported()Z

### ISSUE THREAD

**Issue by saffroy** [tlaplus/tlaplus#133]
Today I let the toolbox install an update, after which I can no longer run TLC:

> An internal error occurred during: "TLC run for Model_1".
> tlc2.tool.fp.OffHeapDiskFPSet.isSupported()Z

This toolbox was initially installed as 1.5.3 then upgraded to 1.5.4, and finally today 1.5.5. The OS is Debian 8.7 with PATH set to use openjdk 8 (8u111-b14-2~bpo8+1).

Any clue?

**Comment by quaeler** [comment]
A user on the [Google Groups reported](https://groups.google.com/forum/#!topic/tlaplus/Aumn08-RdLg) that a fresh-install of 1.5.5 quashes the issue.

**Comment by lemmy** [comment]
@saffroy Does TLC run correctly when you install a fresh 1.5.5 Toolbox from the zip file?

**Comment by saffroy** [comment]
I confirm that a fresh install solves the issue, thanks!

Do you need more information? I still have the broken install.

**Comment by lemmy** [comment]
@saffroy Can you zip up the broken install and make it available to me?

**Comment by lemmy** [comment]
I can reproduce the issue if I upgrade a 1.5.3 Toolbox to 1.5.4 first and then to 1.5.5 subsequently.
