### ISSUE TITLE
PlusCal translator silent failure

### ISSUE THREAD

**Issue by dricketts** [tlaplus/tlaplus#134]
Running the PlusCal translator on the following algorithm should (I think) fail with a syntax error because the with statement has no body. Instead, the translator does not produce an error or a translation.

    begin
        with x = 0 do
        end with;
    end algorithm

This is on version 1.5.4 of the Toolbox.

**Comment by hwayne** [comment]
The following two pluscal specs show the same error on 1.5.7:

```
begin
  await;
```

```
begin
  if TRUE then 
  end if;
```

Replacing `then` with `then;` does not cause the bug.
