### ISSUE TITLE
Some operators in the Bags module return an error  when evaluated on any arguments

### ISSUE THREAD

**Issue by jorgeadriano** [tlaplus/tlaplus#139]
Some operations from the Bags module fail  when evaluated (via model checker). More specifically the following fail: `BagIn`, `(+)`, `(-)`, `\sqsubseteq`, `BagOfAll` and `CopiesIn`. 

The returned errors are similar for all operators. For e.g. `BagIn` it is:

    The `Evaluate Constant Expression� section�s evaluation failed.

    Attempted to apply the operator overridden by the Java method      
    public static tlc2.value.BoolValue tlc2.module.Bags.BagIn(tlc2.value.Value,tlc2.value.Value), 
    but it produced the following error:
    %2%

Note that unfolding the operator's definition results in a successful evaluation. That is, evaluating `BagIn(1, <<1>>)` fails, but evaluating `1 \in BagToSet(<<1>>)`  successfully returns `TRUE`. Likewise, evaluation works if, rather than extending the Bags module, one simply copies the `BagIn` definition to one's own module.

My setup consists on the latest toolbox, version 1.5.6 of 29 January 2018, an up to date OpenSUSE Tumbleweed with OpenJDK 8. Updating Java to OpenJDK 10 made no difference. 

```TLA
----------------------------- MODULE Test -----------------------------

EXTENDS Bags

\* evaluating any of the following expressions results in an error  

C0 == BagIn(1,<<1>>)
C1 == <<1>> (+) <<1>>
C2 == <<1>> (-) <<1>>
C3 == <<1>> \sqsubseteq <<1>>
C4 == BagOfAll(LAMBDA x : TRUE, <<1>>)
C5 == CopiesIn(1, <<1>>)


\* if definitions of Bag operators are redefined, then evaluation succeeds   

RedefBagIn(e,B) == e \in BagToSet(B)
D0 == RedefBagIn(1,<<1>>)

----------------------------------------------------------------------------

=============================================================================
```

**Comment by lemmy** [comment]
`<<1,1,1>>` is internally represented by a [TupleValue](../blob/master/tlatools/src/tlc2/value/TupleValue.java) which gets converted by the [Bags](../blob/master/tlatools/src/tlc2/module/Bags.java)  module overwrite into [FcnRcdValue](../blob/master/tlatools/src/tlc2/value/FcnRcdValue.java). A FcnRcdValue normally represents its domain by a Value[]. However, in case of a TupleValue the domain is for efficiency reasons represented by an [IntervalValue](../blob/master/tlatools/src/tlc2/value/IntervalValue.java). Bags does not recognize this case and subsequently runs into a NullPointerException which results in the error above.

**Comment by jorgeadriano** [comment]
I see. That is rather tricky. Even more considering that if one evaluates e.g., 

    (1:>2) (-) (1:>1)

which indeed succeeds, the output is of the form, 

    <<1>>
