### ISSUE TITLE
Build TLA+ Toolbox for OpenBSD

### ISSUE THREAD

**Issue by ligurio** [tlaplus/tlaplus#141]
Every TLA Toolbox release contains archives for three OSes: Linux, Darwin and Windows. I'm using OpenBSD on my laptop and want to use Toolbox too.
I have learned how to build TLA console tools on OpenBSD, but Toolbox is more convenient and more feature-rich than CLI. 
Is it possible to build Toolbox for OpenBSD and publish these builds on a new release?

**Comment by quaeler** [comment]
I don't believe there is a modern Eclipse port to OpenBSD (internet rumors say 3.2 from the mid 2000s was the last time.)  If this is true, it won't be possible to build the Toolbox for OpenBSD (as the Toolbox is an Eclipse rich client.)

**Comment by lemmy** [comment]
Besides the technical problems, there just isn't sufficient demand to justify adding another OS to the list of supported platforms. Unless the community steps up and helps with the release engineering burden,  it is unlikely that we generally add another platform. We already struggle to support the current list as is and thus plan to discontinue the 32bit zips.
