### ISSUE TITLE
TLC seemingly fails to run on PaxosCommit example from video series

### ISSUE THREAD

**Issue by briangreenery** [tlaplus/tlaplus#149]
When I click the button to run TLC, the "Spec Explorer" changes to show that the model is `[ modelchecking ]`, but the model checker never seems to actually start, and the TLA+ Toolbox is only using minimal CPU. Like the dialog box that shows that a model check is in progress never appears. 
 Here's a screenshot of it in that state:

<img width="900" alt="paxos-tlc-frozen" src="https://user-images.githubusercontent.com/370343/36954534-a26858a2-1fd7-11e8-9e4d-27eb028f16d9.png">

The only indication that anything might be happening is the `[ modelchecking ]` text in the left bar. The other examples from the video series have all worked for me so far, this is the first one that has frozen like this.

I'm running:

```
TLA+ Toolbox provides a user interface for TLA+ Tools. 

This is Version 1.5.6 of 29 January 2018 and includes:
  - SANY Version 2.1 of 23 July 2017
  - TLC Version 2.12 of 29 January 2018
  - PlusCal Version 1.8 of 07 December 2015
  - TLATeX Version 1.0 of 20 September 2017
```

**Comment by lemmy** [comment]
@briangreenery I believe this problem is a duplicate of issue #143 and [fixed in recent nightlies](https://tla.msr-inria.inria.fr/tlatoolbox/ci/products). Can you please check?

**Comment by briangreenery** [comment]
That seems to fix it. It reported an error in the model. Thanks!
