### ISSUE TITLE
False-positive "A parameter name has been omitted" and "The Next formula must be provided" errors

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#153]
Bug repro steps:

1. Open below spec in the TLA Toolbox (tested in version 1.5.6 on Windows 10 64-bit)
2. Create a model for the spec
    - (Possible) bug: "Next" is not auto-detected as the next-state relation
3. Specify "Next" as the next-state relation
    - Bug: the "Next formula must be provided" error does not disappear
4. Specify the value of the Increment(_) constant as IncrementImpl(c)
    - Bug: the "A parameter name has been omitted" error does not disappear
5. Click run; TLC starts despite reported existence of two errors, which then disappear

```
-------------------------------- MODULE Bug --------------------------------

EXTENDS Naturals

CONSTANT Increment(_)

VARIABLE counter

-----------------------------------------------------------------------------

IncrementImpl(c) == c' = c + 1

TypeInvariant == counter \in Nat

Init == counter = 0

Next == Increment(counter)

=============================================================================
```

**Comment by lemmy** [comment]
As per design: The model editor validates its input upon save.  Running TLC triggers auto-save which - in turn - validates the model. Manually saving the model after 4) correctly removes the errors.
