### ISSUE TITLE
Annotation variables/Better support for view maps

### ISSUE THREAD

**Issue by DaveCTurner** [tlaplus/tlaplus#158]
It'd be awfully useful to be able to annotate transitions with a string (or other expression) to provide some extra context when interpreting error traces. This is particularly true when using PlusCal, since it takes considerable effort to link the transitions in an error trace back to the original PlusCal code.

It is clearly possible to add an `annotation` variable and set it to a new value on each transition, but this can make the state space significantly larger: it separates out otherwise-equivalent states at which TLC arrived by distinct paths.

One possible solution could be the ability to mark a variable as "irrelevant to state equivalence", avoiding the increase in state space size. I see that this feature would introduce a risk of restricting the state space exploration, if such a variable were ever read, but I'm not sure if that's a big problem or not.

**Comment by DaveCTurner** [comment]
TIL, thanks, that looks like exactly what I'm after.

I was going to close this but I note that you've labelled this [enhancement]. Could you clarify what the enhancement you have in mind is? Perhaps to expose this functionality in the GUI?

**Comment by lemmy** [comment]
A view can already be declared and activated on the advanced model editor page (enter its name into the view box and pass "-view" parameter to TLC). This is one area that could be enhanced at the Toolbox level.

Another enhancement would be for TLC or the PlusCal translator to be more clever when it comes to naming/generating actions.

**Comment by DaveCTurner** [comment]
I tried adding an annotation variable and defining a view as the tuple of all the other variables, and ran into a couple of issues. When TLC outputs an error trace when using `-view` it seems to show the value of the view function at each transition, which looks like this (line breaks added for clarity):

    6: <Action line 790, col 21 to line 815, col 79 of module ReplicaEngine> <<2,
    {}, DocA, TRUE, FALSE, [type |-> UPDATE, seqno |-> 1],
    [UnsafeSeqnoIncreaserProcess |-> "UnsafeSeqnoIncreaserProcessLoop",
    SafeAccessEnabler |-> "SafeAccessEnablerLoop", UnsafePutter |->
    "UnsafePutterLoop", MaxUnsafeAutoIdTimestampIncreaser |->
    "MaxUnsafeAutoIdTimestampIncreaserLoop", ReplicaLucene |-> "LuceneLoop",
    DeleteCollector |-> "DeleteCollectorLoop", LocalCheckpointTracker |->
    "LocalCheckpointTrackerLoop", Consumer |-> "ConsumerLoop"], NULL, <<[type |->
    Lucene_addDocuments, seqno |-> 2, content |-> DocA], [type |->
    Lucene_addDocuments, seqno |-> 1, content |-> DocA]>>, 0, {1, 2}, 2, 0, 999,
    [type |-> ADD, seqno |-> 1, content |-> DocA, autoIdTimeStamp |-> 1000],
    "optimisedAppendOnly", defaultInitValue, defaultInitValue, TRUE, FALSE, TRUE>>

When not using `-view` the error trace looks more like this:

    6: <Action line 790, col 21 to line 815, col 79 of module ReplicaEngine>
    /\ versionMap_isUnsafe = FALSE
    /\ lucene_buffer = <<[type |-> Lucene_addDocuments, seqno |-> 2, content |-> DocA], [type |-> Lucene_addDocuments, seqno |-> 1, content |-> DocA]>>
    /\ maxSeqNoOfNonAppendOnlyOperations = 2
    /\ request_count = 2
    /\ expected_doc = DocA
    /\ duplicationCount = 0
    /\ useLuceneUpdateDocument = FALSE
    /\ pc = [ UnsafeSeqnoIncreaserProcess |-> "UnsafeSeqnoIncreaserProcessLoop",
      SafeAccessEnabler |-> "SafeAccessEnablerLoop",
      UnsafePutter |-> "UnsafePutterLoop",
      MaxUnsafeAutoIdTimestampIncreaser |-> "MaxUnsafeAutoIdTimestampIncreaserLoop",
      ReplicaLucene |-> "LuceneLoop",
      DeleteCollector |-> "DeleteCollectorLoop",
      LocalCheckpointTracker |-> "LocalCheckpointTrackerLoop",
      Consumer |-> "ConsumerLoop" ]
    /\ versionMap_entry = [type |-> UPDATE, seqno |-> 1]
    /\ replication_requests = {}
    /\ maxUnsafeAutoIdTimestamp = 999
    /\ currentlyDeleted = defaultInitValue
    /\ req = [type |-> ADD, seqno |-> 1, content |-> DocA, autoIdTimeStamp |-> 1000]
    /\ lucene_document = NULL
    /\ indexIntoLucene = TRUE
    /\ annotations = <<>>
    /\ versionMap_needsSafeAccess = TRUE
    /\ deleteFromLucene = defaultInitValue
    /\ currentNotFoundOrDeleted = TRUE
    /\ plan = "optimisedAppendOnly"
    /\ localCheckPoint = 0
    /\ completedSeqnos = {1, 2}

One consequence is that the error trace shown in the GUI is empty, I'm guessing because the parser expects the latter format and not the former. A second consequence is that the annotations are not even available to look at in the error trace, because they're not in the view, which was the whole point.

**Aside:** Possibly an obvious point but I'm writing it down in case I forget later: I also think that a preferable UI for ignoring variables would be be subtractive rather than additive: if I define a view with all my _current_ variables then it feels like there's a big risk I'll add a variable and forget to update the view, whereas if we can define the variables that should be ignored then that feels more robust to future changes. I think this could be more of a UI question than anything fundamental.

**Comment by lemmy** [comment]
@DaveCTurner Please try a recent [nightly](https://tla.msr-inria.inria.fr/tlatoolbox/ci/products/). Commit 8c342af1419fa87ae9776cbef9a960593c16d69c is a best effort approach to mitigate the error trace problem.

**Comment by DaveCTurner** [comment]
Ok, I tried `1.5.7.201804080816` and the error trace in the GUI is populated there, thanks. However, it still doesn't include the `annotation` variable.

**Comment by lemmy** [comment]
Commit 5a629454ed5286076f5f6012b382e852448d165c should stop TLC from showing incorrect variable to value mappings in error traces with viewmaps.

**Comment by lemmy** [comment]
I believe this has been addressed.

**Comment by lemmy** [comment]
@DaveCTurner Please have a look at #267 with which it should be possible to add an "annotation variable" to a trace without increasing the model's state space.
