### ISSUE TITLE
First-class Strings in TLC

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#159]
In [this](https://lamport.azurewebsites.net/tla/current-tools.pdf) document, Lamport claims TLA+ defines strings to be sequences, but TLC does not. It would be nice if TLC also defined strings as sequences, with all the associated niceties (indexing, modification using EXCEPT, etc.) I recently [wrote a spec](https://groups.google.com/d/msg/tlaplus/nDKyc3FUoMM/0gQiNauZAAAJ) which would have benefited from this improved string functionality. Defining strings as sequences would also better-enable PlusCal to achieve its goal of becoming the standard for pseudocode, as there are many interesting algorithms on strings which could then be specified & model-checked in the language.

**Comment by lemmy** [comment]
From the aforementioned document [current-tools.pdf](https://lamport.azurewebsites.net/tla/current-tools.pdf):

```
2.2.2 Strings
TLA + defines strings to be sequences, but the TLC implementation does
not regard them as first-class sequences. The Java implementation of the
Sequences module has been enhanced so that ◦ and Len do what they should
for strings. For example, TLC knows that “ab” ◦ “c” equals “abc” and
that Len(“abc”) equals 3. However, Len does not work right for strings
containing special characters written with “\”. (See the bottom of page 307
of the TLA + book.)
```
----
Additionally, SANY does not properly handle the escaped characters  ```\\``` and ```\"``` whereas the other pairs of characters discussed in _Specifying Systems_ ([section 16.1.10 p. 307](https://lamport.azurewebsites.net/tla/book-02-08-08.pdf)) are handled as described.

**Comment by lemmy** [comment]
Below is a JSON module with a hacked TLC module overwrite to print TLA+ function record as a JSON object:

```tla
------------------------------ MODULE JSON----------------------------------
ToJSONObject(v) == (CHOOSE x \in [a : v, b : STRING] : TRUE).b
   (************************************************************************)
   (* This equals a string that is the JSON representation of the value    *)
   (* that TLC obtains by evaluating v.                                    *)
   (************************************************************************)

=============================================================================
```

```java
package tlc2.module;

import tlc2.tool.FingerprintException;
import tlc2.tool.coverage.CostModel;
import tlc2.value.IValue;
import tlc2.value.ValueConstants;
import tlc2.value.impl.FcnRcdValue;
import tlc2.value.impl.StringValue;
import tlc2.value.impl.Value;
import util.UniqueString;

public class JSON implements ValueConstants
{
	public static final long serialVersionUID = 20190410L;

    /* Returns the a JSON object for the string representation of v. */
    public static IValue ToJSONObject(final Value v)
    {
    	if (v instanceof FcnRcdValue) {
    		final FcnRcdValue frv = (FcnRcdValue) v;

    		final StringBuffer buf = new StringBuffer();
    		buf.append("{");
    		
    		final Value[] domain = frv.getDomainAsValues();
    		for (int i = 0; i < domain.length; i++) {
				final Value key = domain[i];
				buf.append("\"");
				buf.append(key.toString());
				buf.append("\":");
				
				Value value = frv.values[i];
				buf.append(value);
				if (i < domain.length - 1) {
					buf.append(", ");
				}
			}
    		
    		buf.append("}");
    		
    		return new JSONValue(UniqueString.uniqueStringOf(buf.toString()), v.getCostModel());
    	}
        return new StringValue(v.toString());
    }
    
    public static class JSONValue extends StringValue {

		public JSONValue(UniqueString us, CostModel cm) {
			super(us, cm);
		}

		/* (non-Javadoc)
		 * @see tlc2.value.impl.StringValue#toString(java.lang.StringBuffer, int)
		 */
		@Override
		public StringBuffer toString(StringBuffer sb, int offset) {
			try {
				return sb.append(val.toString());
			} catch (RuntimeException | OutOfMemoryError e) {
				if (hasSource()) {
					throw FingerprintException.getNewHead(this, e);
				} else {
					throw e;
				}
			}
		}
    }
}
```

**Comment by JankoJerinic** [comment]
Hello,

I may be over-simplifying the problem, but it seems to me that, fundamentally, we want to align the behavior of strings (literals) with Sequences, with respect to operators that are defined in Sequences (i.e. Head, Tail). Based on my cursory initial exploration of the code base, it doesn't seem like too difficult a change and I'd be very happy to make a contribution. What do you think?

Best,
Janko

**Comment by lemmy** [comment]
@JankoJerinic Can you out-line the set of operators and their behavior that you think would be useful for strings? Technically, it would be possible to create a TLA+ module called Strings with TLC module overrides similar to how the existing standard modules are specified and implemented in Java.

**Comment by JankoJerinic** [comment]
Hi @lemmy,

Of course. I'm mostly interested in operations involving lexicographic comparison of strings, ordered traversal and prefix queries, so I use operators like the below:

```
Equals(S1, S2) == /\ Len(S1) = Len(S2)
                  /\ \A i \in 1..Len(S1) : S1[i] = S2[i]
                 
RECURSIVE Compare(_, _)            
Compare(S1, S2) == IF Len(S1) > 0 /\ Len(S2) > 0 
                   THEN CASE Head(S1) = Head(S2) -> Compare(Tail(S1), Tail(S2))
                        [] Head(S1) > Head(S2) -> 1
                        [] OTHER -> -1
                   ELSE IF Len(S1) = 0 /\ Len(S2) = 0 
                        THEN 0
                        ELSE IF Len(S1) = 0 THEN -1 ELSE 1
 
RECURSIVE IsPrefix(_, _)                    
IsPrefix(Prefix, S) == \/ Len(Prefix) = 0 
                       \/ /\ Len(Prefix) <= Len(S)
                          /\ Head(Prefix) = Head(S) 
                          /\ IsPrefix(Tail(Prefix), Tail(S))   
```

In essence, if Strings would actually behave like Sequences in practice, like the original TLA+ spec claims, ``Head`` and ``Tail`` would just work. However, as we all know, only sequence-like operators that work on strings are ``Len`` and ``/o``.

So, in a nutshell, I'd personally need ``Head`` and ``Tail`` for my own selfish reasons, but perhaps there's a bigger opportunity here - to completely fill the gaps between Sequences and Strings by filling in the blanks in ``Sequences.java``.

For instance, it seems that implementing [Head](https://github.com/tlaplus/tlaplus/blob/3e9cdcb7b947e7be710babfbb991451fa0de081b/tlatools/src/tlc2/module/Sequences.java#L74-L74) would be trivial -  a few lines above, at line #60, we implement ``Len`` for strings by handling them specifically:
```
if (s instanceof StringValue)
    {
        return IntValue.gen(((StringValue) s).length());
    }
```

We could replicate this pattern in ``Head`` and ``Tail`` and extend the ``StringValue`` class with simple methods that would allow us to index into a string, or splice it in any other way. While we're at it, why not have ``StringValue`` implement ``ITupleValue``, which is also trivial, and have strings be formally aligned with tuples, which they, in practice, are - tuples of characters, or perhaps their UTF-8 values. 

I'm sure there are tons of intricacies required to make it work completely within TLC, but just the foundational work doesn't seem to go much beyond the scope I outlined above. What do you think?

Best,
Janko

**Comment by lemmy** [comment]
@JankoJerinic Thanks for volunteering.  We are in the process of setting up a [community modules repository](https://github.com/tlaplus/CommunityModules) which is intended to host additions such as the one proposed above.  Extending the existing built-in standard modules on the other hand has a significant higher bar though. That said individual community modules might graduate at some point.

**Comment by JankoJerinic** [comment]
Absolutely, I'd be very happy to contribute, not just in extending the community modules, but the core code base of TLC. 

I've successfully built a version of TLC in which Tail() also works on Strings, and comparison operators (<, <=, >, >=) are implemented in Java. 

Are you guys happy to take pull requests? Personally, I'm seeing a lot of potential to refactor and make the codebase more sustainable and better organized, but I'm not sure how welcoming you'd be to some deeper cuts. For instance, you're likely aware that Naturals and Integers define a number of operator implementations and put them into the TLA registry and implementations of certain operators even differ between the two modules. This is something that can lead to some quite subtle bugs and should be refactored. So, I was considering fixing all of that and moving Comparison operators on different types to a separate module.

**Comment by lemmy** [comment]
@JankoJerinic We live by the mantra to _don't fix it if it ain't broken_ to reduce the risk of introducing soundness or completeness bugs.  In other words, TLC refactorings should be discussed in detail before changes are made.

**Comment by lemmy** [comment]
> Stephan is incorrect when he says that TLC treats strings as primitive objects.  It treats them as sequences, but of elements that it can't handle.  Some sequence operations (I believe \o is one of them) work on strings.  The documentation on the latest versions of the tools should tell you which operators work, or you can just experiment.  TLC may be able to handle a spec that does what you want. http://discuss.tlapl.us/msg03137.html

**Comment by lemmy** [comment]
@JankoJerinic Are you still interested to contribute your work to the [community modules repository](https://github.com/tlaplus/CommunityModules)?

**Comment by lemmy** [comment]
With this simple change in src/tlc2/value/impl/StringValue.java, the operators ```Head```, ```Append```, and ```SelectSeq``` defined in ```Sequences``` would work for string. 

Old vs. new behavior:
```tla
Head("abc") --> The argument of Head should be a sequence, but instead it is: "abc"
Head("abc") --> "a"

Append("abc", "b") --> Evaluating an expression of the form Append(v, s) when s is not a sequence: "abc"
Append("abc", "b") --> <<"a", "b", "c", "b">>

SelectSeq("ahahah", LAMBDA e : e = "h") --> The first argument of SelectSeq should be a sequence, but instead it is: "ahahah"
SelectSeq("ahahah", LAMBDA e : e = "h") --> <<"h", "h", "h">>
```

```java
  @Override
  public final Value toTuple() {
             final String s = val.toString();
             Value[] vals = new Value[s.length()];
             for (int i = 0; i < s.length(); i++) {
                     vals[i] = new StringValue(Character.toString(s.charAt(i)));
             }
             return new TupleValue(vals);
  }
```

**Comment by lemmy** [comment]
@ahelwer Your initial request is open-ended. Please re-open if 2d2d18e does not cover it.
