### ISSUE TITLE
Allow customizable font size for the Toolbox's Error Trace viewer

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#162]
Being able to adjust the font size of the elements in the `Error-Trace` view of the TLA+ Toolbox would be nice. Perhaps this could be added as an option under the 
```
Preferences > Appearance > Colors and Fonts
```
configuration section. There is already an entry there for the "TLC Output" font size.

**Comment by yomigold** [comment]
Hi Willy... Is there a way we can have a private chat? And on what platform? I have gone through your works and its so impressive and I have a proposal for you, kindly reply back on this thread so as to know where to communicate further.
Thanks.

**Comment by lemmy** [comment]
@quaeler Please close issue with a screen-cast for the changelog.

**Comment by quaeler** [comment]
Closing issue.
![162_ubu_18 04](https://user-images.githubusercontent.com/22581048/54394405-02440280-466a-11e9-838c-cf86d796c218.gif)
