### ISSUE TITLE
TLA+ Toolbox: Could not delete the model, because it is being model checked

### ISSUE THREAD

**Issue by estrehle** [tlaplus/tlaplus#163]
Today I installed the latest version of the TLA+ Toolbox on Ubuntu 18.04 (with OpenJDK 10.0.1).

To play around with the language, I used the `Evaluate Constant Expression` field in `Model Checking Results` and typed in a simple expression. But I forgot to switch to `No Behavior Spec` and chose `Temporal Formula` instead. Then I ran the model by pressing F11.

Now the info bar on the left says that my model is `[modelchecking]`, but the `Stop TLC model checker run` button is greyed out. This situation appears to be permanent and pressing F11 again does nothing, no matter what I change in the model.

When I try to delete the model, I get the error message: 'Could not delete the model Model_1, because it is being model checked.'
I have only managed to stop it with a reboot of my entire system. Is this a bug? How can I stop the model check?

![Screenshot](https://user-images.githubusercontent.com/20908872/40426626-d861b9fa-5e9b-11e8-94dc-f5bcc27dee5a.JPG)

**Comment by lemmy** [comment]
@estrehle Can you please verify that this problem still exists with the [current nightly build](https://tla.msr-inria.inria.fr/tlatoolbox/ci/products/)?

**Comment by dbc60** [comment]
FYI, the nightly build (from 5/23/18) allows one to run **Evaluate Constant Expression** multiple times, with different expressions. I was going to post a bug that it would run only once (TLA+ 1.5.6, on Windows 10), but changing the expression and rerunning did nothing.

Then I saw this bug and tried the nightly build. I don't know if it solves the specific problem posted here, but it solves mine. Well done!

**Comment by lemmy** [comment]
Please reopen if this is still an issue with 1.5.7 or above.
