### ISSUE TITLE
Disambiguate action constraint description in toolbox

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#165]
When specifying an action constraint in the toolbox, I can never remember whether a constraint formula disables a step when it is true, or disables a step when it is false. It would be nice if the toolbox description specified this.

**Comment by quaeler** [comment]
Addressed with https://github.com/tlaplus/tlaplus/commit/7108517aca8d5f1c9de9ccc2719ac6c90af93c87
