### ISSUE TITLE
Init and Next fields of the "What is the Behavior Spec" should accept multi-line text

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#168]
LL: "The Init and Next fields of the "What is the Behavior Spec" section are single-line text fields.  They should hold multiple lines of text.  Here's why.

Remember the trick of starting TLC from an initial state copied from an error trace.  The obvious way to do that is to define a predicate TestInit in the spec and set its definition to be the formula copied from the error trace.  But that doesn't work because that formula usually has model values declared in the model, which are not defined in the spec.  It does work if the formula is copied into the Init field of the model, because that formula is put in the MC file in which the model values are declared as constants.  Or more precisely, it would work if the formula could be copied into the Init field, which it seldom can because that field is now just a single line.  Now, one has to build the complete spec in the Spec field.

The Toolbox was deliberately designed to accept arbitrary expression in those fields, not just the names formulas as TLC requires.  Making Init and Next one-line fields was a mistake.  (In fact, I assumed they were just showing the first line of a multi-line field and somehow, in all these years, I had never tried an example of a multi-line formula.)

I suggest that the Init and Next fields be made multiple-line text fields.  One could still display only a single line, but I think there's enough space to display two lines.  That way, the user will expect that he can copy multi-line formulas into them, even though they're too small to actually compose such formulas in it.  Actually, a cool interface would keep them single lines, but if a Return is typed or copied into it, a new text window pops up which behaves just like the window that pops up when you add an invariant.  When that window is closed, the formula could be displayed on a single line the way invariants are.  However, since the Eclipse interface doesn't have such a thing, I presume it's essentially impossible to implement in Eclipse."

**Comment by lemmy** [comment]
https://github.com/quaeler/tlaplus/commit/f6b721cee9d0be0a7ca3179203f252f39c9eeb53

**Comment by quaeler** [comment]
Closed with 57d926ae2daf8f0ab45abf3b82dc8f0fd5783810
