### ISSUE TITLE
Error stack not shown for TLCState that caused it

### ISSUE THREAD

**Issue by inieves** [tlaplus/tlaplus#174]
While looking into an output bug related to an init failure…

I noticed that the state that caused the initial init failure was _not_ the same state that the call stack was showing a trace for.

I noticed that just before init is replayed, the FPSet size is 1.  Not 0.

I haven’t looked into FPSet much, but my intuition tells me FPSet should be somehow reset to size 0 before replay.

I looked through the newest commits since my last checkout a few weeks ago, and I did not see any commit that seems to talk about this.  I also didn’t see any open bugs for this.

**Comment by lemmy** [comment]
@inieves Please check if the commit fixes the issue for you.  The reasons why we don't want to empty the FPSet before the second TLC run is, that it would write redundant data to the trace file.

The same bug also exists for next but is more difficult to address if we want TLC to report a proper error stack.  If next gets changed to just forcefully re-evaluate invariants for known states, TLC shows the error message related to FingerprintException.  This is obviously bogus.  To handle this, we need to know if Value evaluation is happening as part of TLCState#fingerPrint and only throw the FingerprintException if so.

For Java 9 and above, this can be detected with the new StackWalker with the following hack to Value#hasSource:

```Java
	public boolean hasSource() {
		if (source == null) {
			return false;
		}
		return StackWalker.getInstance()
				.walk(frame -> frame.anyMatch(sf -> ("fingerPrint".equals(sf.getMethodName()) // Match all implementations of TLCState::fingerPrint
						&& (TLCStateMut.class.getName().equals(sf.getClassName())
								|| TLCStateMutSource.class.getName().equals(sf.getClassName())))));
	}

```

I'm not sure we want to bump TLC's dependency to Java 9 though.  Looking at http://www.oracle.com/technetwork/java/javase/eol-135779.html , Java 8 appears to be EOLed but the webpage lists dates in the future for Java 8 at the end.

**Comment by inieves** [comment]
@lemmy 6bb288c appears to not have fixed the problem.  FPSet size is still 1 at just before init is called the second time (for replay).

**Comment by lemmy** [comment]
@inieves This is expected as the fix does not reset the FPSet.  Instead, it causes TLC to evaluate the invariants even for known states when requested.  This causes TLC to report the same/identical state in the second run that caused the evaluation to fail in the first run.

If you look at https://github.com/tlaplus/tlaplus/commit/6bb288c9ed8b3cc77952e387305c021d5d7147d0#diff-136bca9ea057ae984bcfe322cf5bde70 you will see that the fix causes TLC to correctly generate a single (= the error) state.

**Comment by inieves** [comment]
@lemmy aha, OK I understand, and I see your fix.  I understand that the FPSet will not be reset.  I did also verify at my end that the failure is now replayed correctly.
