### ISSUE TITLE
PlusCal user manual: \neq mentioned

### ISSUE THREAD

**Issue by hcs64** [tlaplus/tlaplus#175]
The PlusCal user manual says in section 2.1 that \neq can be used as well as # or \=. However this doesn't seem to work, and it doesn't appear in the table of translations.

(Sorry if this isn't the right place for such a report, I wasn't able to find the source for the doc anywhere)

**Comment by lemmy** [comment]
The manual will be corrected.

**Comment by hcs64** [comment]
Thanks! I'm working my way through the rest of the manual and I'll combine the other issues I've found into one Issue when I'm done.

**Comment by lemmy** [comment]
I believe this has been fixed
