### ISSUE TITLE
Ctrl-Z closes view instead of undoing in Toolbox

### ISSUE THREAD

**Issue by nano-o** [tlaplus/tlaplus#177]
I am using the TLA+ Toolbox version 1.5.7 of 18 July 2018 on Debian Testing.
When editing a specification, pressing Ctrl-Z or Ctrl-Shift-Z closes the editor view instead of undoing or redoing my last change.
This is annoying because clicking Edit->Undo is much slower than Ctrl-Z.

**Comment by lemmy** [comment]
Is 1.5.7 a fresh install or upgraded from an earlier version?  What JVM version are you running the Toolbox with (Help > About > Installation Details > Configuration)?

Can you also try to:

1. Close the Toolbox
2. Move ~/.tlaplus to ~/.tlaplus.bak
3. Re-launch the Toolbox with a fresh workspace
4. Check if the bug persists

(I'm on Ubuntu 18.04 and do not observe the bug)

**Comment by nano-o** [comment]
It is a fresh install. I am running OpenJDK version 10.0.2+13-Debian-1.

**Comment by lemmy** [comment]
Did you also try with a fresh workspace?

**Comment by nano-o** [comment]
Yes, and that did not fix it.

**Comment by lemmy** [comment]
Is it possible that your WindowManager reassigns the keyboard shortcut? Can you also check the key mappings under File > Preferences > General > Keys?

**Comment by nano-o** [comment]
I noticed that Ctrl+Z behaves like Ctrl+W, Ctrl+W behaves like Ctrl+Z, Ctrl+Q behaves like Ctrl+A, etc.
This happens only in Eclipse (on Eclipse Photon too), and with no other applications (even other Java applications). 

My main keyboard layout is US but I also have French as a secondary layout, which swaps W/Z and A/Q compared to the US layout. Could this be related? I'm quite puzzled but I don't have time to investigate this further for now, and I will just use Ctrl+W instead of Ctrl+Z.

**Comment by lemmy** [comment]
https://bugs.eclipse.org/531619 seems to describe the same issue.

**Comment by peter-jerry-ye** [comment]
Hello there,
I'm the one who reported the [https://bugs.eclipse.org/531619](url). As I've also experienced other issues with Eclipse under Linux such as the window for javadoc doesn't display correctly, so I've moved to IntelliJ. Sorry that I can't provide any more information.
The only thing that I want to point out is that I also have French as a secondary layout (with iBus). And as I said in the bug report, it doesn't affect typing the code and when using Ctrl+Shift+L, it is exactly what it should be (Ctrl+Z for undo).

**Comment by peter-jerry-ye** [comment]
The correct URL should be [https://bugs.eclipse.org/bugs/show_bug.cgi?id=531619](url)

**Comment by lemmy** [comment]
From bugzilla #531619:

> Andrey Loskutov CLA Friend 2018-07-31 10:34:20 EDT
>
> There was/is SWT bug on GTK3 if the system has two keyboard layouts defined, we use the first one, independently which locale is set."

**Comment by lemmy** [comment]
@nano-o We recently upgraded the Eclipse foundation to its most recent release. Can you give the [Toolbox nightly build](https://tla.msr-inria.inria.fr/tlatoolbox/ci/products/) a spin and report back if it fixes your problem?

**Comment by nano-o** [comment]
The problem does not appear anymore in my existing installation of the toolbox version 1.5.7 (probably a system update solved it). I didn't pay attention to exactly to when this happened so I can't give much indication as to what might be the cause. The issue also does not appear in the nightly build linked above.

**Comment by lemmy** [comment]
Closing under the assumption issue is fixed. Please reopen if necessary.
