### ISSUE TITLE
Error-Trace Popup Prevents Scrolling

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#183]
**Snippet:**

```
EXTENDS Integers

VARIABLES x

TypeOk == x < 20
Init == x = 0

Next == /\ x' = x + 1

Spec == Init /\ [][Next]_x
```

**Steps:**

1. Create a model with `INVARIANTS TypeOk`.
1. Run the model.
1. When error appears, hover over the error trace.
1. Try to scroll with a mousewheel or touchpad.

**Error:** The tooltip pops up and prevents scrolling.

**Screenshot:**

![2018-08-16 1](https://user-images.githubusercontent.com/2660212/44234503-59353800-a16c-11e8-9e6b-676d3387659a.png)

**Note:** Tested on Windows 10. Unsure if this also appears on other OSes.

**Comment by lemmy** [comment]
Same is true for Linux but sounds too far down the stack to be something we can fix. Do you actually want to scroll with the popup open?

**Comment by hwayne** [comment]
It's more that while I'm scrolling, the popup opens and prevents me from scrolling more, so I have to wiggle the mouse to continue scrolling for another second before the popup reappears (and prevents me from scrolling again).

**Comment by hwayne** [comment]
What if tooltips were disablable? Think that would be a simpler fix than trying to figure out the UI logic, (it seems to me at least).

**Comment by lemmy** [comment]
Where would you put the hint of the tooltip instead?

**Comment by hwayne** [comment]
At least in this formulation of the solution, it would be presumably disabled by a person who already knew the tooltip information, including that they already know they can double-click to go to the action.

**Comment by lemmy** [comment]
@hwayne The [nightly Toolbox builds](http://dl.tlapl.us/tlatoolbox/ci/products/) have been updated to a newer SWT version. Can you please check if scrolling is still blocked with an open tooltip (it doesn't seem to be the case of Linux)?

**Comment by hwayne** [comment]
I've mostly switched to Linux, but I'll boot it up on Windows tomorrow and check it out.

**Comment by lemmy** [comment]
@hwayne Can be closed as I assume you've booted Windows sometime within the last two months? ;-)

**Comment by quaeler** [comment]
Closing this - please reopen if it's still an issue @hwayne
