### ISSUE TITLE
Emit warning if PROPERTY checks a state predicated

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#184]
**Snippet:**

```
VARIABLES x

TypeOk == x /= 1
Init == x = 0

Next == x' = 1

Spec == Init /\ [][Next]_x
```

When a model is run with `TypeOk` as a _property_, not an invariant, the model passes. Formally, this makes sense: the only way for a state predicate to be false as a temporal property is if it is violated in the initial state. However, _usually_ if a person puts a state predicate as a property, they meant for it to be an invariant and put it in the wrong place.

**Suggestion:** if a temporal property is not a temporal formula, we should show a warning.

**Comment by lemmy** [comment]
How do you want to identify a temporal property? It will be quite some work to use SANY to parse the actual formula before it gets serialized by the ModelEditor: https://github.com/tlaplus/tlaplus/blob/23e6c3fc36778764ae155a6e89bd9976b17f140d/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/ui/editor/page/MainModelPage.java#L943 (as far as I remember, SANY doesn't even support parsing partial expressions).

**Comment by lemmy** [comment]
SANY parses the generated MC.tla but ignores MC.cfg (which tells us that TypeOK is set to be a PROPERTY). Unless you want to handle this at the UI layer, probably the best approach is to emit a warning at TLC start-up: Check ExprNode in https://github.com/tlaplus/tlaplus/blob/23e6c3fc36778764ae155a6e89bd9976b17f140d/tlatools/src/tlc2/tool/Spec.java#L1234-L1332 e.g. WRT https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/LevelConstants.java
