### ISSUE TITLE
"New" Hotkey opens unsupported wizard

### ISSUE THREAD

**Issue by sethp** [tlaplus/tlaplus#187]
Steps I took:

1. Launched the TLA+ Toolbox version 1.5.7 (from a `brew cask install tla-plus-toolbox`)
2. Command-N to open the "new" dialog
3. Click on "TLA+ Specification" and click "Next"

At this point, I see the following error message:

```
The selected wizard could not be started.
Plug-in "org.lamport.tla.toolbox" was unable to instantiate class "org.lamport.tla.toolbox.ui.wizard.NewSpecWizard".
org.lamport.tla.toolbox.ui.wizard.NewSpecWizard
```

I can't find any more information on it than that (the `.log` file has nothing to say on the matter).

From searching the issues, this seemed like a Java 9-related problem, but I believe I see the same error with Java 8. At first I was using:

```
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
```

Then I added `<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java</string>` added to the `Info.plist`'s `Eclipse` key. That binary reports as 1.8:

```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by lemmy** [comment]
To isolate the issue, do you run into the same problem when you install the Toolbox from the [regular download](https://github.com/tlaplus/tlaplus/releases/tag/v1.5.7) without brew?

**Comment by sethp** [comment]
Thanks for your response! On further investigation, it appears that my issue was in step #2 above: I can't seem to find my way to that dialog without using the hotkey, and the "Open Specs -> Create New Spec..." flow works just fine.

Is it possible that whatever "new" dialog I discovered at the other end of the "Command-N" (probably Ctrl-N on other platforms?) is somewhat vestigial? For reference, here's the dialog:

<img width="530" alt="screen shot 2018-09-03 at 9 24 55 am" src="https://user-images.githubusercontent.com/241129/44996202-653a3b80-af5b-11e8-9edb-20264e820665.png">

**Comment by lemmy** [comment]
I see, the "New" wizard isn't supported by the TLA Toolbox. The way to open/create a spec is indeed via "Open Specs -> Create New Spec...". We should change the Toolbox to not open the "New" wizard on Command-N.

**Comment by sethp** [comment]
That makes sense. I went ahead and changed the title, since I am perfectly able to create new specs. Thank you for your help!

**Comment by lemmy** [comment]
Fixed with commit
