### ISSUE TITLE
macosx v1.5.7 release app does not launch

### ISSUE THREAD

**Issue by shahdewang** [tlaplus/tlaplus#188]
On launching the v1.5.7 release for macosx, I get "TLA+ Toolbox.app is damaged and can't be opened" error.
Device: MacBook Pro (2017)

**Comment by lemmy** [comment]
Please check if you are affected by Apple's too strict app restrictions: https://github.com/tlaplus/tlaplus/issues/83#issuecomment-336662490

**Comment by lemmy** [comment]
@shahdewang Any news?

**Comment by asmyers** [comment]
I'm seeing the same thing on MacOS 10.12.6.

I don't believe this is app restrictions, that's a different message and you can still open the app by right clicking in finder and clicking open.
