### ISSUE TITLE
Animation Support for Traces

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#191]
## Goals and Motivation
The [Animation](https://github.com/will62794/tlaplus_animation) module is a TLA+ module that provides operators that serve as the basis of a simple vector graphics description language, as well as the ability to animate TLC execution traces. The current instructions for using this module are described in the linked Github repository. The goal is to integrate the functionality of the Animation module with TLC and the Toolbox, so that animation traces can be generated without impacting model checking performance, and so that animations can be easily viewed directly inside the toolbox. An animation trace would be automatically generated by TLC and opened in a web viewer pane in the Toolbox when a trace violates an invariant, analogous to how the Error Trace Explorer works. Using TLA+ itself as a graphics description language will be easier and more natural for existing users of TLA+. They will not need to learn a new language or framework to create animations of their specifications.

## Design Ideas

We can add a new flag (e.g. `--animationSpec`) to TLC that takes as a parameter a user's "animated spec" expression, call it _AnimSpec_. _AnimSpec_ contains the same variables as an original spec, but adds auxiliary variables that track animation related state. It is not necessary for this animation related state to be tracked during the entire model checking procedure. Currently, when TLC finds a violating error trace, it does not have access to all states of that trace. It only has the fingerprints of each state. For error trace exploration, TLC already re-constructs the full state of each step in an error trace. If a user wants to view the animated error trace, then during this re-construction process, TLC can use _AnimSpec_ instead of the original specification. This will produce the animation for that specific error trace. Since _AnimSpec_ adds auxiliary variables, we will want these variables to be ignored by using a "view", so that the state fingerprints generated during animated trace generation are identical to the original fingerprints. Once TLC generates the animated trace, the generated HTML/SVG string can be copied into a standard HTML template, which can then be opened in a web viewer pane in the toolbox.

Note that If the evaluation of _AnimSpec_ fails during trace re-construction, TLC can always fall back to the standard _Spec_, print an error message, and not produce or open the animation.

**Comment by will62794** [comment]
@lemmy Does the design direction outlined in the above comment still seem reasonable to you? If my understanding is correct, the Trace Explorer feature is not actually something built into TLC, but lives in the [Toolbox code](https://github.com/tlaplus/tlaplus/blob/5b92a0dd12fdcd88dbb1164a8515667dc1594318/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/output/data/TraceExplorerDataProvider.java). In that case, I presume that we would not add any kind of `--animationSpec` command line argument to TLC. Rather, we would just have it run using the animated version of the spec (i.e.`AnimSpec`) instead of the original spec when it generates the error trace. Note that my understanding of how the trace explorer works has been partially influenced by [this bit of documentation](https://github.com/tlaplus/tlaplus/blob/cd417271d9be4dcabd91de8b731f907b7083f457/general/docs/trace-explorer.txt). You can alert me if that is somewhat out of date. 

We could also consider having the "animated" version of the trace explorer evaluate the `View` expression at every state, and print out its value, just as it would if it were evaluating a normal state expression during trace exploration. We could then add some separate parsing code that pulls out the SVG representation of each state and concatenates them into an HTML template, which can then be displayed in a browser window. This would differ slightly from the existing behavior of the Animation module, which appends each new state to a global sequence of all frames up to that state. Conforming to how the Animation module currently works is probably easier. Open to hearing your thoughts on this issue.

**Comment by lemmy** [comment]
- Exactly, the trace explorer is built on-top of TLC and its documentation does not appear to be outdated
- Initially I had a different idea in mind but not adding ```--animationSpec``` and extending the trace explore instead sounds much better (no additional complexity in TLC)
- The trace explorer's Toolbox UI would probably have to change s.t. the explorer has a visualize button that runs trace exploration with the AnimationSpec
  - The Toolbox could also do that automatically if the model defines an AnimationSpec but a user could have several AnimationSpecs
- I do not have a preference with regards to your second paragraph except that -as far as I remember - the global sequence can become quite large and thus degrade performance

**Comment by lemmy** [comment]
Does it make sense to broaden the title/scope to "Animation Support for Traces"? Technically the differences are slim.

**Comment by will62794** [comment]
>Does it make sense to broaden the title/scope to "Animation Support for Traces"? Technically the differences are slim.

Sure, that seems sensible. I probably titled the issue as such since traces are displayed in the toolbox in an "Error-Trace" tab.

**Comment by will62794** [comment]
Hi @lemmy. Eclipse is giving me an error about Java 11 when I try to build and run the most recent version of the Toolbox ([f233b6](https://github.com/tlaplus/tlaplus/commit/f233b6263cafd04e3aceba7a0213e788d2dcfefb)):

```
Cannot locate JRE definition: "JavaSE-11". Launch aborted.
```

I have installed Java 11 JDK on my Mac, which is running High Sierra (10.13.6) i.e.

```
$ java -version                                                                                                                
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```

In the Eclipse preferences window under `Java > Installed JRES` my installation at `/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home` is listed. Any thoughts on how to resolve this?

**Comment by lemmy** [comment]
@will62794 Is it possible your Eclipse launch config for the Toolbox is hard-wired to your old Java 1.8 installation?
![jre](https://user-images.githubusercontent.com/88777/53136341-7be94480-3533-11e9-8216-bdc1b857bf9b.png)

**Comment by will62794** [comment]
Thanks, that fixed it. I made the selected environment ("CDC 1.0, Foundation 1.0" in my case), use the right JRE. I switched it from Java SE 8 to Java SE 11.

**Comment by will62794** [comment]
Hi @lemmy, I have been thinking about the core design goals of the Toolbox animation integration and I have a few thoughts that I would like to run by you. Here a few of the goals I would like to achieve with the animation feature, along with notes/question about how to achieve them:

1. Use TLA+ itself as the graphical description language
2. Allow users to annotate TLA+ actions with specific names in their animation
3.  Keep the original spec and animated spec in the same file directory.
    - This means that users don't have to switch between different specs in the Toolbox just to see their animated trace. For example, switching between `Spec.tla` and `SpecAnimated.tla`
4. Make it possible to keep the animated spec definitions and the original spec file completely separate.
    - This allows users to take existing specs and add animation support without cluttering up the original spec. I am envisioning that the standard procedure within the Toolbox will be to create a `SpecAnimated.tla` file that contains the animation definitions (the `View` expression, helpers, and the animated versions of `Init` and `Next`), where `SpecAnimated.tla` extends the `Spec.tla` module. So, the animated spec will have access to all the definitions in `Spec.tla` but the inverse will not be true. The only question would be whether it is easy for TLC to have access to the definitions in `SpecAnimated.tla` when we run the trace explorer for animation. It seems that the Toolbox has the concept of a "root" module file, but perhaps this is only a concept at the Toolbox layer. For example, it may be trivial to run the TLC trace explorer with the `SpecAnimated.tla` file instead of the `Spec.tla` file. I wanted to get your thoughts on this, though.

I am trying to work out a clean and sensible workflow for someone who wants to use the animation feature to visualize specs. I believe that this will inform the decisions I make about how to implement the feature.

**Comment by lemmy** [comment]
1. Strongly agree, while  TLA+ is not designed to be a domain specific language for visualizations, we are not interested in beauty
2. Not clear to me what you want to do (extend TLA+ language?!) and why it is important for the animator
3. Makes sense
4. Strongly agree, lets not clutter Spec. The Toolbox can create an artificial root module MC that extends Spec and SpecAnimated

**Comment by will62794** [comment]
I have done some more exploration of the codebase and hacked together a crude prototype of the Animation feature. This has helped me shape my current vision for how the feature will work, and how to implement the real version. Here are my current thoughts.

### User Interface

To create an animation for their TLC traces, a user imports the `Animation` module and defines a `View` expression in their spec. The view expression is a TLA+ state expression. In the Toolbox, they will then specify the name of their view expression in some input form (it doesn't necessarily have to be called "View"). Perhaps this would be a new form near the checkbox option for state space visualization. When TLC produces a new error trace, the animated version of the trace will automatically be displayed either in a new tab or in a new split pane, next to the error trace view. We could also have an explicit "Animate" button, but that is a UI detail we can discuss when the time comes. 

### Implementation

I think it will be wise to re-use as much of the existing TraceExplorer logic as possible. There are existing classes, [TraceExplorerJob](https://github.com/tlaplus/tlaplus/blob/01fbb430ec8b4158d7a6dad088d4f81b58436d7f/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/job/TraceExplorerJob.java) and [TraceExplorerDataProvider](https://github.com/tlaplus/tlaplus/blob/01fbb430ec8b4158d7a6dad088d4f81b58436d7f/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/output/data/TraceExplorerDataProvider.java), which I think we can add animation specific versions of. My understanding is that _TraceExplorerJob_ represents a running TLC process (specific for trace exploration), and _TraceExplorerDataProvider_ is the class responsible for consuming the output from a TLC model checker run once it completes. When a trace is being "animated" behind the scenes, we will simply run a new TLC job that runs as a normal trace explorer job would, except that it evaluates the user's given view expression at each state, instead of the given set of trace explorer expressions. Once it completes, we extract the evaluated view expression from each state of the trace and compile it into a suitable HTML template. We can add something like a _TraceAnimationDataProvider_ to do this post-processing and to open the appropriate animation viewer window.  I believe we can create a new Toolbox view _TraceAnimationView_ that roughly follows the structure of other existing views e.g. [ToolboxWelcomeView](https://github.com/tlaplus/tlaplus/blob/01fbb430ec8b4158d7a6dad088d4f81b58436d7f/org.lamport.tla.toolbox/src/org/lamport/tla/toolbox/ui/view/ToolboxWelcomeView.java). It will basically just display some given HTML. 

I would like to start with a basic, minimal implementation, which may consist of just the infrastructure to build an animated HTML trace even before adding any of the UI elements or logic to interact with it. I also have some "stretch goals" which I think would be nice features, but can be added incrementally once the basics are complete.

**Stretch Goals:**
1. Enforce a mapping between the currently selected error trace view state and the animated trace view. When the user clicks on a state in the error trace viewer, the animation will automatically jump to the corresponding state. 
2. Export to HTML feature. Allow users to export the animated trace to a standalone HTML file that they can share around. 
3. Have a way to easily preview a particular state in the animation view. This might be helpful when developing a new animation. A user could define a particular "example" state and see how it appears visually given their view expression. This might help the development experience for building animations. 

**Open Questions/Notes:**

1. The allowable locations of the `View` definition is a small detail to be worked out. As I mentioned above, it would be nice to allow users to have a `Spec.tla` and `SpecAnimated.tla`, if they want to separate their animation definitions and original spec. They can always put their view expression right in the original spec if they want. From my basic testing, definitions placed in a separate, non-root module file do not appear "visible" to TLC. Perhaps, as you said, it is simple to work around this issue by creating a temporary spec file that extends `Spec` and `SpecAnimated`. 

2. For the initial implementation, I am cutting the feature of allowing users to specify custom action annotations, which was something I included in the original Animation module. You can see an example of the action annotations [here](https://github.com/will62794/tlaplus_animation/blob/b480ae9f17062e5f9428aed7a67cb663dcb4f773/examples/LogVisibility/LogVisibilityAnimated.tla#L43-L45). I think that it is acceptable to omit this. We can always consider adding it later. This makes things simpler by not requiring users to define a new, animated version of their spec. Instead, they only need to define a view expression. I think this makes for a better user experience. 

@lemmy It's not imperative that you give a detailed response to all of my points above. I am mostly interested in running the basic implementation plan by you before I dive in. The outline I have written here is as much for your benefit as it is for my own. It is helpful for me to put my design plans in writing. It acts as a reference for myself and a public documentation of my thought process.

**Comment by lemmy** [comment]
@will62794 I agree that it is best to start with what other tend to call "minimum viable product".  For the mvp it would probably be acceptable to directly add the view expression to ```Spec```.  Naming actions sounds more like a dedicate feature which we eventually want to add to TLC.  Repeatedly I have wished to be able to label actions to make it easier to map from a (vanilla) error trace to the spec.

Adding @quaeler - who is doing most of the UI work - to make him aware of this feature.

**Comment by will62794** [comment]
Hi @lemmy, I have been making progress on the Toolbox animation feature, but I have a few questions in regards to testing. Since this is mostly a UI specific feature, for prototyping I have started by working in the animation logic and running the Toolbox manually to test out my changes. This works reasonably well but the feedback loop is slow. I am wondering about better testing strategies. I have worked with the unit tests in the codebase previously, but I am curious about the existing "UI tests" and how to run them. I believe these may be referred to as RCPTT test cases? 

For example, there appear to be a variety of these tests inside the `org.lamport.tla.toolbox.product.uitest` directory. Would you be able to give me some direction on how these tests work and how to run them? I think they might make my development process smoother.

Sorry that the work on the animation feature has been moving somewhat slowly. It is always a bit hard to predict how much time I will have to spend on it week to week when doing it as a side project. Thanks for your patience on this.

**Comment by lemmy** [comment]
@quaeler (please chime in) and I have only recently started to use the RCPTT tests and there is unfortunately no howto or guide yet.   Assuming you initially and recently followed the [ide guide](https://github.com/tlaplus/tlaplus/tree/master/general/ide), your Eclipse IDE should already have the RCPTT tooling installed.  If that's the case, this [screencast](https://vienna.lemmster.de/uploads/rcptt.gif) should get you started.  In short:

* Create a regular Toolbox launch configuration in Eclipse by launching the Toolbox from the .product file
* Create an RCPTT launch config "Eclipse Application under Test" by selecting the previously created launch config
* Start the Toolbox from this new RCPTT launch config
* You can now run existing tests and record snippets
* Amend an existing test or create a new one in ...product.uitests

**Comment by quaeler** [comment]
Ya, as Markus writes, there is a large dearth of guides and only loose documentation. Once you have the RCPTT launch configuration, i found it most useful to examine one of the existing tests to understand how the scripting language works.  RCPTT uses ECL (Eclipse Control Language, i believe), the auto-generated reference API document for which [can be found here.](https://hudson.eclipse.org/rcptt/job/rcptt-all/ws/releng/doc/target/doc/ecl/index.html)

How useful it will to what you're writing depends on the underlying framework; for example, i believe you won't find it practical to test GEF based UI.

If you have any specific questions, please feel free to ask!

**Comment by lemmy** [comment]
@will62794 More and more reports come in from users having issues with the 1.5.7 Toolbox release due to JVM incompatibilities.  This forces us to release a new Toolbox soon.  What is your time frame for a first pull request for animator?  Ideally the next release would include the animator or a preview of it.

**Comment by will62794** [comment]
@lemmy I know this has been quite delayed. I have a patch in progress that is getting close to something that could be put up for an initial PR, but I also don't want to hold up the next Toolbox release if it's urgent. If I had a patch ready for review within the next 2 weeks, even if it presented a "beta" version of the animator feature, would that be acceptable for your release timeline?

**Comment by lemmy** [comment]
A beta in two weeks would be great.  How much risk of breaking existing functionality do you think comes with the patch?

**Comment by will62794** [comment]
From what my current implementation looks like, I think the changes should be relatively isolated, without much risk of breaking any existing functionality. Ideally the changes will have no impact for users if they don't choose to use the feature. I will keep the "blast radius" in mind, though, as I continue to work on this.

**Comment by will62794** [comment]
### WIP Patch
Hi @lemmy. The trace animator patch is not quite ready for review yet, but if you want to take a look at the current progress and try it out, you can check out my dev branch [here](https://github.com/will62794/tlaplus/tree/trace_animation). For now, the `Animation.tla` module must be manually added to a spec that is currently opened in the Toolbox. You can use [this](https://gist.github.com/will62794/69efad335d2c752649ab34f9b41ebffe) version of that module if you want to test locally. Here is an example of how a very simple animation can be defined in a basic spec:
```tla
------------------------------ MODULE animtest ------------------------------
EXTENDS Integers, Animation

VARIABLE x

Init == x = 0
Next == x' = (x + 1) % 8

_View == Circle(10, x * 30 + 5, 5, ("fill" :> "orange"))
View == MakeView(_View)

=============================================================================
```
Currently, the Toolbox is hard coded to consider the TLA+ expression `View` as the thing to evaluate for each frame of the animation. You can see that I have added an "Animate" button right below the "Explore" button in the trace explorer interface. When you click it, it runs the trace animator in the background and then displays the animated trace. You can step forward and backward in the trace with the left and right arrow keys. The UI is very minimal at this point but can always be enhanced in follow up patches. The TLC runs for the animator seem quite slow for some reason, which I think may be due to the fact that it is slow at evaluating the string building expressions inside the animation module. It makes the user experience worse, but I am not worried about these details right now, since I think they aren't too important for a beta version of this feature. Also, I think that can easily be optimized later on. My goal is to put up a complete pull request this weekend for you to take a look at. We can discuss options for making this a "hidden" or experimental feature in the Toolbox in case it still has some issues/bugs when the next Toolbox version is ready for release.

**Comment by lemmy** [comment]
@will62794 This sounds great.  May I ask you to record a quick'n'dirty screencast to demo the functionality (unless the functionality (UI) is self-explanatory)?

**Comment by will62794** [comment]
Sure, I can include a brief screencast. Also, is there a way to run the full suite of Toolbox tests from the command line? I have run the TLA+ tools test but I don't believe I have tried out the Toolbox test suite. Additionally, do the Toolbox tests run in the CI system?

**Comment by quaeler** [comment]
You can do a `mvn clean verify` which will do the whole shebang.

**Comment by lemmy** [comment]
@will62794 As per last week's discussion, I consider this feature done.
