### ISSUE TITLE
macOS: "JVM 1.8" required, but apparently I have Java 8

### ISSUE THREAD

**Issue by anentropic** [tlaplus/tlaplus#194]
Just downloaded TLA Toolbox from https://github.com/tlaplus/tlaplus/releases/download/v1.5.7/TLAToolbox-1.5.7-macosx.cocoa.x86_64.zip

I get this when I try to open it:
![screen shot 2018-09-21 at 23 12 46](https://user-images.githubusercontent.com/147840/45908388-4f9a9200-bdf4-11e8-91c5-7d31ea96b1bf.png)

System Java settings says I'm up to date and shows:
![screen shot 2018-09-21 at 23 12 53](https://user-images.githubusercontent.com/147840/45908392-51fcec00-bdf4-11e8-98f1-30a52db9ac30.png)

What do I need to install to make this work?

**Comment by anentropic** [comment]
Installing JDK8 from here http://www.oracle.com/technetwork/pt/java/javase/downloads/jdk8-downloads-2133151.html seems to have fixed it

**Comment by lemmy** [comment]
Great!
