### ISSUE TITLE
Support deletion of additional modules

### ISSUE THREAD

**Issue by anentropic** [tlaplus/tlaplus#195]
I have ended up with this 'Untitled' module in my specification project

![screen shot 2018-09-21 at 23 42 36](https://user-images.githubusercontent.com/147840/45909167-43183880-bdf8-11e8-921e-abcd329a8ba0.png)

I cannot find any option to delete it though. If I right-click on either of these modules the 'delete' option is greyed out.

I deleted the file on disc, closed the IDE and reopened but it still won't go away.

It seems to be preventing the spec from parsing:
![screen shot 2018-09-21 at 23 45 30](https://user-images.githubusercontent.com/147840/45909210-7ce93f00-bdf8-11e8-9d36-1babdcfd8455.png)
(I'm only guessing, it doesn't say which module, that error could be something else I suppose)

**Comment by anentropic** [comment]
re-creating the file on disk and filling it with an empty module...
```tla
---- MODULE Untitled ----
====
```
...has made the spec parseable

The delete options are still greyed out

**Comment by lemmy** [comment]
Unfortunately, module deletion is currently unsupported.

**Comment by anentropic** [comment]
I was trying to follow the introductory tutorial at

**Comment by lemmy** [comment]
Workaround:

1. Forget spec in Toolbox and close Toolbox
2. Open .project file located in the *.toolbox subdirectory of the specification
3. Remove the XML <link> element, e.g. to remove Foo.tla remove the following:

```
		<link>
			<name>Foo.tla</name>
			<type>1</type>
			<locationURI>PARENT-1-PROJECT_LOC/Foo.tla</locationURI>
		</link>
```

4. Restart Toolbox and re-add specification

**Comment by lemmy** [comment]
org.lamport.tla.toolbox.ui.handler.DeleteSpecHandler and org.lamport.tla.toolbox.tool.tlc.handlers.DeleteModelHandler provide similar functionality and can acts as guidance for a contributor.

**Comment by quaeler** [comment]
Closed with cf4e03821a677114fced1aa9a54d9d090b0e10ed

**Comment by lemmy** [comment]
There appears a regression (see screencast).

1. Add  additional path to library locations (Preferences > TLA+ preferences) with module M
2. Create a spec with name M
3. EXTENDS M in M (leads to error)
3. Delete spec M
4. Restart Toolbox
4. Create new spec with name N (reusing directory of M)
5. Behavior as shown in the screencast

![deletespec](https://user-images.githubusercontent.com/88777/58113835-4b08c200-7bab-11e9-879b-1f81d5a2b2ef.gif)


@quaeler Feel free to open a new issue if preferred

**Comment by quaeler** [comment]
Opened #312
