### ISSUE TITLE
Do not store TLC generated and runtime data in spec's subdirectories

### ISSUE THREAD

**Issue by nomothetis** [tlaplus/tlaplus#196]
Hi,

I'm working with the TLA+ Toolbox, and for complicated reasons cannot ignore files in a subdirectory when checking in code. I would like to redirect the TLA+ output files (snapshots, etc) to a different location, but was unable to find a setting for that. Is this an option?

Thanks.

**Comment by lemmy** [comment]
@nomothetis You can turn snapshots off entirely by setting the numbers to keep in the preferences to zero. You cannot redirect the output though.

Can you elaborate on what you check in and what you want to ignore (related to github issue #157)?

**Comment by nomothetis** [comment]
Thanks for the tip on turning off snapshots.

Honestly, reading issue #157, covers exactly what I would like for production use; I can live with PlusCal translations being in the same file (though since it's in essence the same information twice, it would be nicer not to have that), but the others make working as a team difficult.

**Comment by nomothetis** [comment]
If I used git, it would. :-) Unfortunately, we use...complicated infrastructure at work.

**Comment by lemmy** [comment]
@nomothetis Do you know that you can recreate the MC.out and MC.cfg from the .launch config that resides in their parent directory?

**Comment by nomothetis** [comment]
I did not know that, but I'm not sure how helpful it is.

Our system automatically saves all and any writes as snapshots to make them accessible across machines. Therefore any generated code is stored ~forever. So even if we find a way to ignore files from _commits_, we would still have unnecessary space consumption problems. Of course, I'm just toying with TLA+ for myself right now, but if we were to seriously adopt it, we'd need to be able to separate generated from source code.

**Comment by lemmy** [comment]
Please reopen if this remains an issue (with latest and greatest).
