### ISSUE TITLE
Error : Taking snapshot

### ISSUE THREAD

**Issue by mehuljain53** [tlaplus/tlaplus#198]
An internal error occurred during: "Taking snapshot of Model"
Attempted to beginRule: F/LamportMutex/LamportOrig.toolbox, does not match outer scope rule: P/LamportOrig
[log.txt](https://github.com/tlaplus/tlaplus/files/2447916/log.txt)

**Comment by lemmy** [comment]
@mehuljain53 Can you please attach the complete log file?

**Comment by mehuljain53** [comment]
This is the complete Log File I have. I have accidentally deleted the log file I had before.

**Comment by lemmy** [comment]
Please provide a recursive directory listing of /Users/mehuljain/Desktop/Fall_18/Asynchronous Systems/TLA/Examples-master/specifications/lamport_mutex/

**Comment by mehuljain53** [comment]
[RecursiveDir.txt](https://github.com/tlaplus/tlaplus/files/2448036/RecursiveDir.txt)

**Comment by lemmy** [comment]
You somehow ended up with a nested .toolbox directory inside another .toolbox directory ```LamportMutex.toolbox/LamportOrig.toolbox```. I believe this is the actual culprit.

**Comment by mehuljain53** [comment]
Issue Solved. Thanks Man
