### ISSUE TITLE
Trace Exploration incorrectly puts "Back to State" marker at top/bottom

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#2]
@xxyzzn: "A counterexample to a liveness property must be an infinite trace. A error trace that TLC finds consists of a finite trace that loops back on itself --- indicated by a finite trace followed either by something like <Back to state 7> or <stuttering>.  However, if you run the trace explorer, that looping indication is [incorrectly put at the top/bottom of the error trace].  The workaround is simple: just remember how it loops before running the trace explorer.  If you forget to do that, the Trace Explorer's "Restore" button will put back the original error trace."

Code pointers:
org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/output/data/TLCError.java
org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/output/data/TraceExplorerDataProvider.java

**Comment by xxyzzn** [comment]
Hi Markus,

Why did you cc me on this?  Was it because I reported the bug to you?

Cheers,

Leslie
