### ISSUE TITLE
Issues found during testing [Research] - File >> Spec Properties

### ISSUE THREAD

**Issue by RickGMSR** [tlaplus/tlaplus#202]
- [ ] item 1: File (Spec Properties - UI) - **Cosmetic Issue:** 

Steps: Open Spec Properties
Result: Move Up/Down Buttons are enables before any TLA+ library path location has been added. 
![image](https://user-images.githubusercontent.com/15837908/47804774-e5c6af80-dcf2-11e8-909f-45c3a0b89f42.png)

- [ ] item 2: File (Spec Properties - UI) - **Edge Case  @Issue**
Steps: Open Spec Properties
Add Directory >> Cancel

Result:
Add Null to TLA+ library path location. Also Dialog shows error message (0) is not a valid library path

![image](https://user-images.githubusercontent.com/15837908/47804763-da738400-dcf2-11e8-83be-f62fd770a50c.png)

- [ ] item 3: File (Spec Properties - UI) - **Edge Case Issue**
Steps: Open Spec Properties
Add Directory >> Cancel
Select Null
Click Edit Location
Result: Edit Location fails to work when you have a bad path
![image](https://user-images.githubusercontent.com/15837908/47805070-a2207580-dcf3-11e8-848f-9da182ed6ef0.png)
@lemmy

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/9
