### ISSUE TITLE
PDF generation from .tex file on Mac 

### ISSUE THREAD

**Issue by nieup** [tlaplus/tlaplus#207]
Tex file is not found when generating pdf, I was able to manually generate the pdf with the command `pdflatex SecondSpec.tex` from the toolbox folder but from the toolbox GUI (`File/...`) it doesn't work. 

Tried with different folder layouts, toolbox folder in the project and at the same level as the project.  

<img width="703" alt="screen shot 2018-11-11 at 21 02 34" src="https://user-images.githubusercontent.com/8448600/48317644-617b0300-e5f5-11e8-8e24-875f6606b2be.png">

**Comment by lemmy** [comment]
You have to configure the path to ```pdflatex``` in the Toolbox's preferences under File > Preferences > TLA+ Preferences > PDF Viewer

**Comment by ferantivero** [comment]
had same issue here and been able to troubleshoot this by configuring it from preferences was mentioned by @lemmy.

just as additional reference I installed MiKTeX.

**Comment by nieup** [comment]
The file he is not finding is the .tex from my understanding. 

This is what I have: 
<img width="1242" alt="screen shot 2018-11-12 at 20 47 58" src="https://user-images.githubusercontent.com/8448600/48371536-7078b880-e6bc-11e8-8bcd-6e8714151d2a.png">

What do you suggest I change in the PDF viewer preferences?

**Comment by lemmy** [comment]
Try setting "Specify pdflatex command" to ```/Library/TeX/texbin/pdflatex```.

**Comment by nieup** [comment]
(/)

**Comment by lemmy** [comment]
What do you suggest should be normal behavior?

**Comment by lemmy** [comment]
Please reopen if necessary.

**Comment by nieup** [comment]
> What do you suggest should be normal behavior?

Would suspect that if the command is in the PATH I wouldn't need to give an absolute path again

**Comment by lemmy** [comment]
Can you submit a patch that adds this behavior to the Toolbox?

**Comment by nieup** [comment]
Found a couple of references: 
from `/Users/cedric/Workspace/java/tlaplus/general/bugzilla/index.xml`

>           <bug_id>109</bug_id>
>           
>           <creation_ts>2011-05-11 15:36:00 +0000</creation_ts>
>           <short_desc>Automatically detect pdflatex on the system</short_desc>
>           <delta_ts>2011-05-11 15:36:18 +0000</delta_ts>
...
>     <commentid>277</commentid>
>     <comment_count>0</comment_count>
>     <who name="Markus Alexander Kuppe">bugzilla.tlaplus.net</who>
>     <bug_when>2011-05-11 15:36:18 +0000</bug_when>
>     <thetext>If pdflatex is not on the system path, an incomprehensible dialog pops up complaining that pdflatex cannot be found ("No such file or directory"). To make it easier for the user, either:
> 
> a) Find pdflatex automatically (CDT has facilities to located system binaries)
> b) Generate PDF directly in Java
> c) Improve error dialog with a direct link to the Preferences &gt; TLA+ Prefs &gt; PDF Viewer</thetext>

Should it detect `pdflatex` (a) or point to where to change it (c)?

**Comment by lemmy** [comment]
a) can still fail so I suggest to start with c).

**Comment by keepsimple1** [comment]
Encountered the same problem and found this discussion. It helps. And just wanted to share, if anyone did not have `pdflatex` on their mac (like me),  the following command would install it without installing the full `mactex`: ```brew cask install basictex```.   And note,  you need to restart bash to be able to do `which pdflatex` to verify its path.

**Comment by lemmy** [comment]
@qualer Please see if improving the error with helpful information what to do can be done in less than an hour.

**Comment by lemmy** [comment]
@quaeler Please see if improving the error with helpful information what to do can be done in less than an hour.

**Comment by quaeler** [comment]
With 6d2f1aa we now have improved warning as seen in this screencast (with panel text that contains a typo corrected before the commit.)
![207_ss](https://user-images.githubusercontent.com/22581048/64372048-e301ae80-cfd6-11e9-9e38-a66b6385827f.gif)

**Comment by asdf2014** [comment]
Any requirements about the version of pdflatex? After all, it crashed the latest TLA+ toolbox..

```bash
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.36; using libpng 1.6.36
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

**Comment by quaeler** [comment]
No known version requirements since it is launched in its own process. Which version of the toolbox and when you say "crash" do you mean the Toolbox itself is no longer running? Could you attach the `hs_err_pid.log` to your reply?
