### ISSUE TITLE
SANY command line doesn't return valid exit status

### ISSUE THREAD

**Issue by yanghao** [tlaplus/tlaplus#208]
For example:

`java tla2sany.SANY modeling/test/test.tla`

making test.tla fail to passing, yet the exit status is still 0.
This made it difficult to integrate TLC into a existing build system.

BR, Yanghao

**Comment by lemmy** [comment]
@yanghao Do you have the bandwidth to provide a patch?

**Comment by yanghao** [comment]
@Lemmy, let me try :) not really a java programmer though.

**Comment by lemmy** [comment]
dc19df16e205ed3de3dd6e3bbaf3a51fa6adb95c

**Comment by lemmy** [comment]
This is fixed now with 2de21907a799791aabffe3ba43b3bcc7c4efb177
