### ISSUE TITLE
Clone models from foreign specs

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#211]
Support cloning of models from foreign - not just the current - spec in the Toolbox's workspace.

**Comment by quaeler** [comment]
When you say 'foreign specs' do you mean other specs listed in the Spec Explorer, or do you mean a spec found via a file-open-dialog, or ?

**Comment by lemmy** [comment]
Let's limit it to specs previously added to the Toolbox.

**Comment by lemmy** [comment]
(LL recently wished for this again)

**Comment by quaeler** [comment]
@lemmy give e7e653334baf0a89d8ddc10060c777ebb6e7de05 a shot, via:
![Screen Shot 2019-06-26 at 7 59 00 PM](https://user-images.githubusercontent.com/22581048/60232915-f106b680-9852-11e9-813d-f9ed369e7e71.png)
and lemme know feedback (but note the 'To be done' concerning model-less specs..)

**Comment by quaeler** [comment]
This has been completed, barring changes due to feedback with abcb83f84e1d6807f6bb7338c681f5039b819392

**Comment by quaeler** [comment]
As there's been no further requests for change, and 1.6.0 is upon us, i'm going to close this.
