### ISSUE TITLE
Bug: Rescaling Issue with PDF

### ISSUE THREAD

**Issue by RickGMSR** [tlaplus/tlaplus#219]
Steps:
Create New Spec
"Help/Table of Contents" | click
"Help/Dynamic Help" | click
"Help/Specifying Systems" | click
"Help/The TLA+ Cheat Sheet" | click

"Window/Reset Window Layout" | click

Result: System may become unresponsive and screen display a big x

**Comment by lemmy** [comment]
Thanks @RickGMSR, I believe this has been fixed by https://github.com/lemmy/Pdf4Eclipse/commit/eaabb3e38ab7442e3261bd33aac8913af381754e

**Comment by quaeler** [comment]
I cannot replicate this on Mac, Windows 10, nor Ubuntu 18.04 (using a 1.5.8 build, 1.5.7 release, and 1.5.8 build, respectively)

**Comment by quaeler** [comment]
Hmm - should have refreshed this bug before commenting.

**Comment by lemmy** [comment]
![screencast](https://user-images.githubusercontent.com/88777/54328659-fc97df80-45cb-11e9-9012-f6e1bbdcbb1f.gif)

**Comment by quaeler** [comment]
Does that mean this hasn't been fixed?

**Comment by lemmy** [comment]
It's fixed but I wanted to keep a recording of the broken behavior as reference.
