### ISSUE TITLE
Long-running RSS background jobs blocks prover job

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#226]
[[...] It also likes to check its “news feed” on a regular basis. It can’t seem to do this at the same time as other operations, and if you’re in the middle of a particularly complex proof checking operation, it will sometimes suddenly pop up a box suggesting that you cancel your job, so that it can get back to reading the news.](http://roscidus.com/blog/blog/2019/01/01/using-tla-plus-to-understand-xen-vchan/)

**Comment by quaeler** [comment]
I held up the RSS polling thread (`org.eclipse.recommenders.internal.news.rcp.poll.PollFeedsJob.run(IProgressMonitor)`) while it was polling and was still able to start and finish a model check job. I also held up the thread inside of `TLCProcessJob.run(IProgressMonitor)` and saw the RSS polling job start and end without problem.

I'm closing this as a non-issue.
