### ISSUE TITLE
Operator TLCSet does not work within the INIT predicate

### ISSUE THREAD

**Issue by dohan** [tlaplus/tlaplus#23]
TLC (TLC2 Version 2.08 of 21 December 2015) throws an incomplete error message when the operator TLCSet of the standard module TLC is used within the INIT predicate:

Attempted to apply the operator overridden by the Java method
public static tlc2.value.Value tlc2.module.TLC.TLCSet(tlc2.value.Value,tlc2.value.Value),
but it produced the following error:
%2%

The error occurred when TLC was evaluating the nested
expressions at the following positions:
    The error call stack is empty.

for module:

----- MODULE ModuleTLC -----
EXTENDS Integers, TLC

VARIABLES x

Init == x = 1 /\ TLCSet(1,"TLCSet works.")
Next == x < 10 /\ x' = x + 1 /\ PrintT(TLCGet(1))

=====
[ModuleTLC.zip](https://github.com/tlaplus/tlaplus/files/566133/ModuleTLC.zip)

Using an older version of TLC (TLC2 Version 2.06 of 9 May 2015)  the TLCSet operator works properly within the INIT predicate.

**Comment by lemmy** [comment]
A fresh build containing the fix (among other changes) can be found at http://tla.msr-inria.inria.fr/tlatoolbox/ci/
