### ISSUE TITLE
Produce PDF Version not working on macOS

### ISSUE THREAD

**Issue by rhettinger** [tlaplus/tlaplus#234]
Running the IDE's `Produce PDF Version` on the spec, `/Users/raymondDocuments/try_tlaplus/TCommit.tla` gives an error:

```
PDF Production Error

TLATex unrecoverable error: -- Trying to run the command `pdflatex TCommit.tex' produced the following error
  Cannot run program "pdflatex" (in directory "Users/raymond/Documents/try_tlaplus/TCommit.toolbox"): error=2, No such file of directory
```

I'm running the nightly build: `Feb  5 20:19 TLAToolbox-1.5.8-macosx.cocoa.x86_64.zip` on macOs Mojave Version 10.14.2

The command **does** produce a valid LaTeX file, `TCommit.tex`.  I know that is valid because I can manually (from the command-line) run `pdflatex TCommit.tex` and successfully produce a PDF.

Here is the relevant *tree* output:

```
$ tree
.
├── DieHard.tla
├── TCommit.tla
├── TCommit.toolbox
│   ├── Model_1
│   │   ├── MC.cfg
│   │   ├── MC.out
│   │   ├── MC.tla
│   │   ├── MC_TE.out
│   │   └── TCommit.tla
│   ├── TCommit.tex
│   ├── TCommit___Model_1.launch
├── mydiehard.tla
└── texput.log

```

I believe the cause of the problem is that the filename is not being appended to the path when running the PDF latex command.

**Comment by lemmy** [comment]
@rhettinger Did you configure the (absolute) path to pdflatex in the Toolbox's preferences (TLA+ Toolbox > Preferences > TLA+ Preferences > PDF Viewer > Specify pdflatex command)?

**Comment by lemmy** [comment]
@rhettinger Please reopen if this is still an issue.

**Comment by heidi-ann** [comment]
I encountered the same issue (Toolbox v1.6.0) on macOS Catalina v10.15.1. The toolbox generated a valid tex file but did not compile to pdf. @lemmy's suggested fix worked (copying `which pdflatex` into preferences) but it would be good if this worked out of the box.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/6d2f1aade6b9fb6654f3c8094370c63af9ac66ca changes the wording on the error dialog and can open the preference right away.  It will be included in the next release.

**Comment by josecastro** [comment]
Have this issue in Mojave, not updating to Catalina yet since it apparently has issues with using non-apple store software. Was looking at the videos of the TLA+ Lamport course and it blows up when trying to generate the pdf. Checked that the path to the pdflatex is correct, I have TexShop installed.
[tlaDUMP.txt](https://github.com/tlaplus/tlaplus/files/5309284/tlaDUMP.txt)

**Comment by mattpotts** [comment]
> @rhettinger Did you configure the (absolute) path to pdflatex in the Toolbox's preferences (TLA+ Toolbox > Preferences > TLA+ Preferences > PDF Viewer > Specify pdflatex command)?

The key thing here is _absolute_ path rather than relying on `$PATH`. I installed the tools with `brew install --cask mactex` and ended up with the absolute paths being `/opt/local/bin/pdflatex` and `/opt/local/bin/dot` and Produce PDF Version is working for me.
