### ISSUE TITLE
Bad invariants in model have a very tiny error icon

### ISSUE THREAD

**Issue by fuzz-ai** [tlaplus/tlaplus#235]
If an invariant is mistyped, the error icon that pops up is extremely small and hard to find (and to mouse over in order to see the actual error):

![image](https://user-images.githubusercontent.com/45412395/52969668-beb1ed80-3376-11e9-8d6a-3d6b5c7fa42e.png)

(It's that tiny orange x to the bottom left of the invariant selection box.)

Java version: openjdk 10.0.2 2018-07-17
OS: Ubuntu 18.04.2 LTS

**Comment by lemmy** [comment]
Belongs to #49

**Comment by hwayne** [comment]
I wonder if there's a way to autopopulate the invariants field and/or make "Add" give a dropdown in addition to a text box...

**Comment by fuzz-ai** [comment]
Similar problem if there are errors in the constants section.  If unspecified, or there is an error, the error icon is small, and the error messages are only visible by hovering over it, or hovering over the "N errors detected" at the top of the screen:

![image](https://user-images.githubusercontent.com/45412395/53307113-a94b3080-385a-11e9-83bb-6c0002977dd5.png)

In addition to being hard to notice, this is also a usability problem in that it's impossible to copy/paste the error messages from here (and I can't see where else they appear.)

**Comment by lemmy** [comment]
@quaeler FYI

**Comment by quaeler** [comment]
WRT the icon, we're relying on Eclipse's form's message manager framework (which is there because of the managed forms (which is there because of the form pages which are the model editor pages)) which automatically slaps that icon (`FieldDecorationRegistry.DEC_ERROR`) on there (hardcoded and immutable in `MessageManager`.)

We can add some additional UI hints ourselves.

**Comment by lemmy** [comment]
What's the story with regards to Eclipse's forms framework and HiDPI?

**Comment by quaeler** [comment]
I believe PDE's plugin editor uses the forms framework, and if so - it looks good at least in 2018-12
![screen shot 2019-02-25 at 10 05 34 am](https://user-images.githubusercontent.com/22581048/53358415-1e634800-38e5-11e9-99aa-abc668fe99a2.png)

**Comment by lemmy** [comment]
Do you happen to have a screenshot with an (error) icon similar to the one in the Toolbox?

**Comment by quaeler** [comment]
Nope... anything i could think of which would be an error condition (negative download sizes, invalid URLs,) were caught on focus loss and reverted rather than displaying an error indication.

**Comment by lemmy** [comment]
Those affected, please open an [Eclipse bug](https://bugs.eclipse.org).  There is nothing that *we* can do to fix this.
