### ISSUE TITLE
How to build the TLA+ Toolbox with maven (mvn)?

### ISSUE THREAD

**Issue by philipmw** [tlaplus/tlaplus#237]
As part of making a contribution to TLA+, I built a custom `tla2tools.jar` following your instructions.

As I understand, TLA Toolbox uses TLA tools under the hood, so I want now to test the Toolbox with my changes. Is that possilble?

There is no `tla2tools.jar` in the TLA Toolbox distribution. The closest is a collection of JARs like `./Eclipse/plugins/org.lamport.tla.toolbox.tool.tlc_1.0.0.201807180447.jar`. However, those JARs' namespace is different from my `tla2tools.jar`.

Can I do what I want to do? What's the right way to test my code change (in TLC) in TLA Toolbox?

**Comment by lemmy** [comment]
@philipmw Did you follow the [IDE setup guide](https://github.com/tlaplus/tlaplus/tree/master/general/ide)?  If yes, you can change the tlatools/ project and - once done with your work - build a Toolbox with ```mvn clean verify -Dmaven.test.skip=true``` (remove maven.test.skip to execute test suite) from the repos root directory.  The Toolbox zip files will then reside in ```org.lamport.tla.toolbox.product.product/target/products/```

**Comment by philipmw** [comment]
I disagree with the way you changed the title of my question. I was not asking how to build the TLA+ Toolbox, but how to drop in a custom set of tools, as a JAR, and have my existing toolbox use those.

It sounds like that is not possible, and instead I need to build the toolbox.

**Comment by lemmy** [comment]
Everything is possible but it is not worth the effort (e.g. released code has been signed and can thus not easily be replaced).

**Comment by philipmw** [comment]
That helps, thanks.

Any idea about this error?

    % mvn clean verify -Dmaven.test.skip=true
    ....
    [INFO] Adding repository http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest
    [ERROR] Failed to resolve target definition /Users/pmw/Repos/tlaplus/org.lamport.tla.toolbox.product.product/TLAToolbox.target: Could not find "org.eclipse.e4.tools.spies.feature.feature.group/0.18.0.v20181023-1826" in the repositories of the current location -> [Help 1]

**Comment by lemmy** [comment]
It seem you don't have yesterday's commit f233b6263cafd04e3aceba7a0213e788d2dcfefb
