### ISSUE TITLE
"Can't enumerate the value" errors from TLC are confusing

### ISSUE THREAD

**Issue by mgritter** [tlaplus/tlaplus#241]
I'm trying to reproduce issues which I found confusing writing my first specification (directly in TLA, not using PlusCal.)  The biggest stumbling blocks were errors of this form:

```
Attempted to enumerate a set of the form [l1 : v1, ..., ln : vn],
but can't enumerate the value of the `count' field:
0
While working on the initial state:
thread = (t1 :> [count: 0, state: initState] @@ t2 :> [count: 0, state: initState])
```

which occurs from the following fragment:

```
EXTENDS Integers
CONSTANT states, initState, countValues, threadIds
VARIABLE thread
InitThread == [ count : 0, state : initState ]
Init == 
  /\ thread = [ t \in threadIds |-> InitThread ]
```

I know _now_ that I screwed up InitThread and defined a set rather than an individual record. But if I made that error, then the error message "looks OK"--- it uses the same syntax that I erroneously tried to use.  So I spent a lot of time asking things like "is it a problem using zero here instead of a model variable, or do I need to override Int to make it a finite range?"  Or "why can't it enumerate zero?" or (closer to correct) "why is it trying to enumerate zero?"  I could have used a stronger hint that "count : 0" expects the right hand side to be a set.

A similar error occurs if I neglect to make a singleton set rather than use the value directly:

```
InitStates == [ count : countValues, state : initState ]
Init ==
  thread \in [ threadIds -> InitStates ]
```

Error:

```
Attempted to enumerate a set of the form [l1 : v1, ..., ln : vn],
but can't enumerate the value of the `state' field:
initState
TLC was unable to fingerprint.
```

The message is somewhat more helpful if I leave the { } out when attempting to do a union:
```
AllStates == states \union initState
InitStates == [ count : countValues, state : AllStates ]
Init ==
  thread \in [ threadIds -> InitStates ]
```

Error;
```
Attempted to enumerate S \cup T when S:
{s1, s2, s3}
and T:
initState
are not both enumerable
TLC was unable to fingerprint.
```

Here I can see something that's a set of model variables, and something that's a model variable but not a set, and TLC explicitly tells me I was trying to take the union of both.  But I'm having trouble making a good suggestion for the first couple cases that would have given me enough context to figure it out right away.  Something along the lines of "0 is not a set, and [x : 0] is supposed to define a set" would have put me on the right track.

**Comment by lemmy** [comment]
I hope that these kinds of issues are now alleviated by the existence of the [TLA+ debugger](https://youtu.be/6oMQYHogQek).
