### ISSUE TITLE
Prover related Toolbox command should not call tlapm on unparsed/syntatically broken spec

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#243]
LL: "Certain Toolbox commands involving the proofs can only be performed if the spec is correctly parsed.  These are the two commands that call tlapm: Launch Prover and Prove Step or Module, and these two commands performed by the Toolbox itself: Renumber Proof and Decompose Proof.  It looks like the first two commands are calling tlapm even though they shouldn't, and I don't know what happens then.  The Decompose Proof command seems to throw an exception and the Renumber Proof command seems to do nothing.  [...]" Subject: "more simple bugs" 02/27/2019

**Comment by quaeler** [comment]
Addressed with d9eef94
