### ISSUE TITLE
Sync input files of the Configuration parser with the source code

### ISSUE THREAD

**Issue by Henne** [tlaplus/tlaplus#246]
TLA2SANY uses two parsers which were generated with JavaCC.
The input files are tla+.jj for the grammar of TLA+ and config.jj for the grammar of the built-in operators which I call Configuration parser.
The generated files from tla+.jj reside in tla2sany/parser/ and the files from config.jj in tla2sany/configuration/.

These generated files were modified manually, but the changes were not put back into the jj input files.
So the input and generated files are out of sync, for both TLA+ and the Configuration parser.
That makes it:
- hard to modify these grammars and 
- hard to keep up-to-date with newer JavaCC Versions, which may fix issues in the generated code.

The generated files from config.jj, which are directly used by tla2sany and therefore by tlc2, have been generated with JavaCC 0.7pre6, which is currently not available anymore.
See: [JavaCC Downloads](https://javacc.org/downloads/)
Warning: These files of the old releases aren't classes. They are html files and of no use.

I would like to provide a patchset I have written, which 
- updates the generated files into the form they were generated by JavaCC 4.0 without breaking the build and
- updates the config.jj file, so that the output of it can be just-copied into tla2sany/configuration and works without manual modifications.

One benefit would be that the TLA+ parser, which has already been generated with JavaCC 4.0,
together with the config.jj can be updated with lesser effort to newer versions of JavaCC.
The last release of JavaCC was version 7.0.5.
Version 4.0 is also very old, but luckily available in some current Linux distributions.

Another benefit can be, that the generated code could be shared between both parsers,
since 4 of the 7 generated files are identical, which would remove duplications and code-smell.

There is one design decision, which I want to discuss that with you:

JavaCC supports generating static parsers, which do not need to be instantiated, and non-static parsers, which need to be instantiated.

At the moment the Configuration parser is static and the TLA+ parser is non-static.

The Configuration parser has one noticeable method called Configuration.load(),
with is called in tla2sany/drivers/SANY.java without instantiating a Configuration object.
But this load() method, defined in config.jj and Configuration.java,
instantiates a configuration object which then does the parsing.

So one way would be to make the Configuration parser non-static, since
- it has already been used that way all the last 10 years,
- there is no need to think about a static and a non-static parser in tlatools and
- the ReInit() method added manually by DRJ can be removed and the one and only method
  used by tla2sany is load() which does all the job.

For keeping it static I'm lacking arguments.

**Comment by lemmy** [comment]
@Henne I believe @pron's [pron-unicode](https://github.com/tlaplus/tlaplus/tree/pron-unicode) branch also touches/updates the .jj files.

**Comment by Henne** [comment]
@lemmy: The changes to the jj files you mentioned are in the [fixjavacc](https://github.com/pron/tlaplus/tree/fixjavacc) branch of pron's fork. I'll read it tomorrow.

**Comment by lemmy** [comment]
@ahelwer

**Comment by lemmy** [comment]
Please reopen if somebody wants to move this all the way through.

**Comment by ahelwer** [comment]
I looked into newer versions of JavaCC hoping we might be able to get incremental parsing & error tolerance for free (or cheap, at least) by just upgrading. Unfortunately it looks like this feature was still in the "spitballing solutions on the discussion board" phase for JavaCC in early 2020: https://javacc.com/2020/01/26/fault-tolerant-parsing-is-it-a-pipe-dream-an-answer-to-angelo-zerr/

**Comment by ahelwer** [comment]
A much more extensive download list of past javacc versions is available here: https://mvnrepository.com/artifact/net.java.dev.javacc/javacc

I downloaded the 4.0 release .jar from 2006 and confirmed it has the same sha256 hash as the one saved in our repo.

**Comment by ahelwer** [comment]
Ref https://github.com/javacc/javacc/issues/279

**Comment by revusky** [comment]
> Ref [javacc/javacc#279](https://github.com/javacc/javacc/issues/279)

Andrew, I ran across the above issue and, as a result, I wrote you an email about 4 days ago. I just wanted to know whether you had received it, and more importantly, whether you had a chance to look at the file I attached. As I guess I said before, if you have any questions or comments, it might be best to use https://discuss.congocc.org/ or you can use the Issues at https://github.com/congo-cc/congo-parser-generator

**Comment by lemmy** [comment]
This looks outdated.  Please reopen if not.
