### ISSUE TITLE
Is there a new build for the Mac? Mac OS version doesn't work for Mojave....

### ISSUE THREAD

**Issue by nradonic** [tlaplus/tlaplus#249]
Is there a new build for the Mac? Mac OS version doesn't work for Mojave....

**Comment by lemmy** [comment]
@nradonic You can grab a [nightly build](http://nightly.tlapl.us/products) which works on Mojave.  We have yet to prepare an official release.

**Comment by rw** [comment]
@lemmy The nightly build link isn't loading, and anyway it looks like it wouldn't use HTTPS. Do you have a signed build that works on Mac? Thanks!

**Comment by lemmy** [comment]
@rw Connectivity to our build machine is unfortunately interrupted.  I hope for for the machine to be available again soon but can't give an ETA (the administrators have been notified).

Note that recently a [Homebrew](https://brew.sh/) cask [has been added](https://github.com/Homebrew/homebrew-cask-versions/pull/7203) for Toolbox nightlies (also affected by the outage though):

```bash
$ brew tap homebrew/cask-version
$ brew cask install tla-plus-toolbox-nightly
```

**Comment by rw** [comment]
@lemmy Thanks for the quick help! It looks like those builds aren't signed, though, and the site isn't behind HTTPS. Do you have a more secure option? Thanks!

**Comment by lemmy** [comment]
@rw  Thanks for bringing this up.  The [nightlies](https://nightly.tlapl.us/) can now also be accessed via HTTPS.

With regards to signing the app itself, please note that the individual Toolbox jars are actually signed.  You can verify the signatures under Help > About > Installation Details > Plug-Ins > Show Signing Info.

In the future we also hope to provide an app signed the Apple way, but Apple doesn't make this particularly easy.

**Comment by rw** [comment]
@lemmy These are great, thanks again for your help! Just for completeness' sake, could you point me to the CI build scripts so that I could try building the Mac app for myself? Is it the `.travis.yml`?

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/237#issuecomment-466211422

**Comment by rw** [comment]
@lemmy I saw that before, but maybe I didn't understand the implications -- is that also applicable for running a headless TLA+ build in CI? Thanks for all your help!

**Comment by lemmy** [comment]
Please clarify what a "headless TLA+ build in CI" means but the maven build is what is executed by our Jenkins instance.

**Comment by rw** [comment]
@lemmy Ah I think I figured it out! According to this page, the relevant file is now missing and maven can't find it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545329

**Comment by lemmy** [comment]
I'm working on this problem right now and hope to have a solution soon.

**Comment by rw** [comment]
@lemmy I got much farther in the build process due to your recent commit. Thanks! The next whackamole issue is this:

```
$ mvn verify -Dmaven.test.skip=true -e -X -U

...

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2019-04-20 07:48:45.000
!MESSAGE Connection to http://lemmy.github.com/jclouds2p2/p2.index failed on sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Retry attempt 0 started
!STACK 0
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by lemmy** [comment]
I believe this is caused by an outdated jvm. Please try upgrading to the most recent jvm release if you happen to be on an older one. If that's not the case, please attach the complete maven log.

**Comment by rw** [comment]
@lemmy Got it working with master and JDK 11, thank you for all of your help?
