### ISSUE TITLE
Toolbox failed to launch after update from 1.5.4 to 1.5.7, clean didn't fix

### ISSUE THREAD

**Issue by evelynmitchell** [tlaplus/tlaplus#251]
I just applied the updates, and restarted.
The only unusual item in the updates, was accepting the Eclipse certificate, which I did.
[.log](https://github.com/tlaplus/tlaplus/files/2959121/default.log)

Ubuntu 18.04

**Comment by evelynmitchell** [comment]
Terminal has:
./toolbox --clean

(java:17750): Gtk-WARNING **: 17:30:42.792: Unable to locate theme engine in module_path: "adwaita",

(java:17750): Gtk-WARNING **: 17:30:42.795: Unable to locate theme engine in module_path: "adwaita",
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://472.fwk691779749:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://472.fwk691779749:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]

(toolbox:17715): Gtk-WARNING **: 17:30:44.412: Unable to locate theme engine in module_path: "adwaita",

(toolbox:17715): Gtk-WARNING **: 17:30:44.416: Unable to locate theme engine in module_path: "adwaita",

**Comment by lemmy** [comment]
@evelynmitchell The log indicates that you tried updating a 1.5.4 Toolbox to the current 1.5.7.  That is unfortunately not supported.

Please manually download the [1.5.7 Toolbox release zip](https://github.com/tlaplus/tlaplus/releases/tag/v1.5.7).  Once extracted, starting the 1.5.7 Toolbox should load your existing specifications from the Toolbox workspace in ~/.tlaplus/ 

Let me know if you need more detailed instructions.

**Comment by evelynmitchell** [comment]
Thanks lemmy. I will do that.
