### ISSUE TITLE
p2 updater should reject incompatible updates (skipping releases)

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#252]
see  #251

As a simple workaround we could wire Toolbox 1.5.4 to receive updates from an URL .../1.5.5/.  Toolbox 1.5.5 only checks the URL .../1.5.6 and so on.  The disadvantage is, that we decide on the next version number when we do the previous release (we do we switch to 1.6.0).

Alternatively, each Toolbox version (e.g. x.x.Y) could have a unique URL (.../x.x.Y).  As part of the Toolbox x.x.Z release the x.x.Z content is published at URL .../x.x.Y.

Note: It seems p2 indicates its version as part of the HTTP request:

```
GET /tlatoolbox/branches/1.5.8/toolboxUpdate/p2.index HTTP/1.1" 404 447 "-" "p2/1.2.100.v20180822-1354 (Java 11.0.2+9 AdoptOpenJDK; Linux 4.15.0 x86-64; en_US) org.lamport.tla.toolbox.product.standalone.product/1.5.8 (org.lamport.tla.toolbox.application)
```

@quaeler How does Knime handle this?  Does it even use p2 update?

**Comment by quaeler** [comment]
Ya - they use p2 and have the update sites directory-ed by version (major.minor).

![Screen Shot 2019-03-13 at 3 44 22 PM](https://user-images.githubusercontent.com/22581048/54319545-1410a180-45a7-11e9-83ff-f3e2c382d4e9.png)

**Comment by lemmy** [comment]
Is it possible to update a 3.6.0 Knime to 3.6.9?

Maybe we have to be more "aggressive" with incrementing the Toolbox's minor version.

**Comment by quaeler** [comment]
It is possible to jump dot-versions not sequentially (e.g 3.6.0 to 3.6.2)

**Comment by lemmy** [comment]
Does Knime follow semantic versioning s.t. Micro gets only bumped on bugfix releases that contain no new features?

**Comment by quaeler** [comment]
KNIME does a minor release twice per year; dot-releases contain both bugfixes and features (though larger impact new features sometimes wait for the next minor release.)

**Comment by lemmy** [comment]
@quaeler Please check the reasoning in the commit message of 1a20ddf94585c042dd21e575753c485f10b3f867

**Comment by lemmy** [comment]
Changed https://tla.msr-inria.inria.fr/build/job/M-HEAD-master-Toolbox.product.standalone/ to force nightly builds to by default update to latest and greatest.

```bash
## See commit 1a20ddf94585c042dd21e575753c485f10b3f867 why changing the regular URL toolboxUpdate/ to ci/toolboxUpdate doesn't work anymore.
sed -i.bak 's/enabled="false"/enabled="true"/g' org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product
#sed -i.bak 's/tlatoolbox\/toolboxUpdate/tlatoolbox\/ci\/toolboxUpdate/g' org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product
```

To activate either install today's nightly build or enable "Receive experimental features" in Toolbox preferences:

![Screenshot from 2019-04-04 20-40-56](https://user-images.githubusercontent.com/88777/55602365-0bc90380-571a-11e9-8247-8bdf75130fc0.png)
