### ISSUE TITLE
Show TLC cmd as executed on the command line in model editor

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#257]
Newer Eclipse releases come with a "Show Command Line" button which - for the current launch config - opens a dialog showing the actual command line call.

![Screenshot from 2019-03-15 12-01-00](https://user-images.githubusercontent.com/88777/54455978-3d057380-471a-11e9-95fd-e6cf43e2bfdc.png)

Similar functionality should be added to the Toolbox to reduce friction for users who use both the Toolbox and TLC on the command line.

Technically, the information is already present and logged to the Toolbox's .log file in [TLCProcessJob](https://github.com/tlaplus/tlaplus/blob/49b55d4441cbf81e34e9c6fe9b7da9e2afd26937/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/job/TLCProcessJob.java#L201) once TLC executes.  As a first step, it might thus be easier to print the command the to model editor's "process output" on the result page.  A user then has to start and immediately stop TLC to obtain the command.  If this clutters "process output" it could alternatively go to TLC Console.

@quaeler Do you happen to have comments?

**Comment by quaeler** [comment]
It seems unlikely most people would benefit from actually visually seeing that in the Toolbox itself - so perhaps a menu item and/or model editor button that copies the command to the clipboard?

**Comment by lemmy** [comment]
Seeing - while being able to copy&paste - would e.g. help users understand what Toolbox checkbox does what.

**Comment by lemmy** [comment]
WRT seeing the actual cmd: http://discuss.tlapl.us/msg03101.html
