### ISSUE TITLE
Intermittent Junit Test Failure: GotoDefinitionTest

### ISSUE THREAD

**Issue by Henne** [tlaplus/tlaplus#260]
On my system the GotoDefinitionTest from org.lamport.tla.toolbox.tool.tlc.ui.uitest fails with a NullPointerException. I used Xephyr for the uitests.

I replaced the line
   `queue.add(TokenSpec.findCurrentTokenSpec(r));`
with
  `final TokenSpec TS = TokenSpec.findCurrentTokenSpec(r);
    if (TS != null) queue.add(TS);`

which avoids the NullPointerException and results in a understandable assertion.

The reason for that failure is, that getTLAEditorWithFocus() from the class EditorUtil
returns null, because the TextWidget of the Editor has no focus.

Changing that method, that it returns the Editor in the case it doesn't have the focus,
makes that test work, but does not fix the problem.

**Comment by lemmy** [comment]
@quaeler IIRC you are the original author of this test.

**Comment by lemmy** [comment]
SWTBot tests have been removed from the project's (active) test suite.
