### ISSUE TITLE
Spec Explorer does not annotate (snapshot) model as errored despite an error trace

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#261]
The root cause appears to be that the (error) marker (org.lamport.tla.toolbox.tool.tlc.util.ModelHelper.TLC_MODEL_ERROR_MARKER_TLC) read by org.lamport.tla.toolbox.tool.tlc.model.Model.hasError is only set in org.lamport.tla.toolbox.tool.tlc.output.data.TLCModelLaunchDataProvider.createError(TLCRegion, String) if coverage data reports an incomplete state space exploration.  While this will be the case most of the time but not always.  It also requires at least a single line of coverage data to set the marker.

The root cause appears to be that the TLCModel instance - visualized in the Spec Explorer - lacks a reference to the error which only gets parsed from the MC.out file when the Model Editor is manually opened.

~This bug might only show up in the context of cloud TLC.~

**Comment by quaeler** [comment]
The `Model` is now marked for each warning and error during model checking as the ResultPage gets notifications from the checker; as the snapshot now has these markers saved as part of it, the display in the Spec Explorer should be correctly reflective of erred snapshots.
Please re-open if something is amiss.
