### ISSUE TITLE
Bogus "No property pages for ." on mouse click on tree item's "Properties" context menu for everything except spec

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#263]
![Screenshot from 2019-03-27 14-21-28](https://user-images.githubusercontent.com/88777/55113170-a2068500-509b-11e9-80ae-bf3802e88dee.png)

Menu item defined in /org.lamport.tla.toolbox/plugin.xml. Menu items are ideally disabled.

@quaeler If you happen to come by this...

**Comment by quaeler** [comment]
Fixed with https://github.com/tlaplus/tlaplus/commit/99a9c1b49976b4f99727ef2c369d727746288091
