### ISSUE TITLE
Update the embedded Java runtime to the current version (12)

### ISSUE THREAD

**Issue by pron** [tlaplus/tlaplus#269]
```
Ron Pressler @pressron
Replying to @lemmster

You should bundle JDK 12 now.

lemmster's avatar
lmstr @lemmster
Replying to @pressron

Are there substantial (performance) changes? The plan is to follow LTS releases only.

pressron's avatar
Ron Pressler @pressron
Replying to @lemmster

No, but following LTS releases makes no sense unless you're a big bank with deep software problems. Ordinary Java applications should follow the release train. It's the easiest, cheapest, safest route.

pressron's avatar
Ron Pressler @pressron
Replying to @pressron @lemmster

The feature releases are only a bit bigger than the patches (that you'll have to upgrade to if you're on LTS). So the number and cost of upgrades is the same, but you're following the path of least resistance, and never have to consider major upgrades again.

pressron's avatar
Ron Pressler @pressron
Replying to @pressron @lemmster

Also, CDS is now enabled by default, which makes for a significantly faster startup (good for SANY).

pressron's avatar
Ron Pressler @pressron
Replying to @pressron @lemmster

Also, memory footprint is lower (with the G1 collector; good for the Toolbox)

pressron's avatar
Ron Pressler
@pressron
Replying to @pressron @lemmster

But basivally, unless you have good reason not to, it's best to take the default path.
```
https://twitter.com/pressron/status/1114536612665417728

**Comment by lemmy** [comment]
FWIW: Commits https://github.com/lemmy/eclipse-jdk-bundles/commit/7d2b8dafa3f888f7e959bd943ab7f8fcc83a5843 and dd26d4386a1f5975ebbd7f733567dc8951fa83a1 update the bundled JVM to 11.0.3.  https://github.com/lemmy/eclipse-jdk-bundles/commit/04ea73d34f9b054e007e939cff2d65bb1593c983 prepares the repo for Java 12.

**Comment by lemmy** [comment]
Can somebody quantify the advantages of switching to Java 12?

**Comment by pron** [comment]
It's not "switching" so much as updating (12 is not a major release; 9 was the last major release ever, and Java has now switched to gradual updates). This is the recommended, best-practice, update path to receive bug and security fixes. In addition, there are performance benefits to each feature version. The embedded JDK should ideally be updated every 2-3 months (it's not the end of the world if a version or two are skipped), and the next update in the recommended path after 11.0.2 is 12. Note that we're now at 12.0.2, and the next update is 13, coming in a couple of weeks.

**Comment by alygin** [comment]
There're two parts in "let's switch/upgrade to Java X"

- Bundling Java X with the Toolbox as the JVM runtime.
- Compiling the Toolbox and the TLA+ tools with and for Java X.

And here are my thoughts on both these parts:

**Java X as just a JVM runtime**

Switching from Java 11 to Java 12 is not just a minor upgrade to stay up to date. It's switching from an LTS version (three years of public updates with bug and security fixes, and occasional performance improvements backporting) to a non-LTS version (six months of public updates). And the _"next update is 13, coming in a couple of weeks"_ effectively means _"in a couple of weeks you'll **have to** upgrade to 13 if you want to continue to receive updates"_.

So, keeping Java 11 doesn't mean not following best practices and not receiving bug and security fixing. You'll get all of that. It means not being at the cutting edge of Java features.

I'm not saying that upgrading the JVM runtime to v12 is a bad idea per see, I think it might be worth doing. All I'm saying is that it's not just a one-off upgrade, it's a commitment to upgrade regularly, otherwise we'll quickly get stuck with a totally out-of-date JVM (the one with no updates at all).

**Compiling for Java X**

Another point worth mentioning here (probably even most important) is that not all users work with the TLA+ tools via the Toolbox, they run [command line tools](https://github.com/pmer/tla-bin) or use the [VS Code extension](https://github.com/alygin/vscode-tlaplus) to run the tools for them.

If the requirement of Java version for TLA+ tools changes every several months, all these users will have to upgrade their Java too, which they may see as quite an annoyance, especially if it adds nothing to functionality.

Moreover, those people who work with the TLA+ tools directly often use other JVM implementations. For instance, I use GraalVM, which works faster on my use cases. It's now LTS-versions oriented and doesn't support every single Java update. So, I won't even have an option to keep my dev environment and use the latest TLA+ tools. And that doesn't look good to me.

And I want to emphasize the "for" preposition here, it's not "with". You can still compile the tools *with* Java 12 *for* running in Java 11 environment, which is totally OK. Like TLC now compiles with Java 11 for Java 8 (into Java 8 bytecode).

**Comment by pron** [comment]
I work on OpenJDK at Oracle. I know the changes we made to the update model are confusing, but LTS vs feature releases do not mean what some think they do.

Before we get to what LTS means in practice, let me point out that OpenJDK has no concept of LTS. If you look [here](https://openjdk.java.net/projects/jdk/11/), there is no mention of 11 being LTS in OpenJDK, because it isn't. There is nothing special about it. LTS is a service offered by some companies to arbitrarily selected JDK versions. Most companies follow Oracle's choice of versions in the LTS offering, but not all of them (e.g. Azul). In addition, OpenJDK can have update projects, , that last as long as their maintainers wish. Those project can also be for arbitrarily selected versions, but the most active update projects, 8u and 11u, led by Red Hat, do correspond to Oracle's version choice as well.

Now, what do "current JDK" vs LTS mean? They *do not* mean stable support vs cutting edge at all. We provide two update paths for Java: a gradual one (let's call it "feature releases"), and a non-gradual one (let's call it "LTS"). In the gradual path -- which is the default and the one we recommend unless you have a very good reason not to follow it -- there is perpetual free support and no more major upgrades *ever*. Every three releases, i.e. every six months, the current release gets a new integer number, but it is not a major release. The last major Java release *ever* was 9. It's just that the way we name our versions has changed.

To stay up-to-date with security features you must update your JDK to a new version every 2-3 months (again, ideally) whether you're on the current JDK path or the LTS path. Updating from 11.0.2 to 12 (or 13) does *not* introduce a higher risk of code breakage than updating from 11.0.2 to 11.0.3. It *may* take some more work because it may require changes to the command line or to update dependencies (always a good idea), but in exchange it means there will *never* be a major upgrade ever again. In contrast, sticking to LTS is more costly. Every three years there will be a major upgrade that is potentially significantly bigger than major upgrades in the past, because OpenJDK's development revolves around the "default" path, not the LTS path, and so features could be removed *without warning* between two LTS versions.

Who is the LTS path for? It is for large companies that prefer a large, scheduled upgrade that they plan and budget well in advance, even though it is costlier. It is *not* otherwise recommended, and should be chosen only for a very good reason.

Now, I am not sure how @alygin uses GraalVM, but the Graal JIT is bundled in OpenJDK and can be used in any JDK (12, 13 etc.). Graal Native Image is an experimental feature and does not even really support Java 8. It's work in progress.

**Comment by alygin** [comment]
@pron , thank you for the clarification. I'm sure you're absolutely correct on every single point you made. And I honestly can't find a single contradiction to what I said. It just seems to me a bit Oracle-centered, while the real world is a bit wider and there're facts we have to deal with:

1. _Oracle doesn't have the concept of LTS versions._ Yet the toolbox uses AdoptOpenJDK, not just generic OpenJDK. And AdoptOpenJDK [has concepts of LST- and feature-releases](https://adoptopenjdk.net/support.html#roadmap). Which means that if the Toolbox maintainers decide to upgrade to Java 12.0.x, one month later they will only have one option if they want to stay up-to-date with bug and security fixes -- to upgrade to Java 13, they can't just rebundle Java 12.0.y. That's my only point, it's about an informative decision and commitment to that decision, not about terms that Oracle uses or doesn't use.

2. _As a general rule, people shouldn't make use of global Java runtime_. It sounds totally right, though in the reality, people still use global Java runtime, they either don't know about this general rule or simply don't care about it. We haven't arrived to that perfect world yet.

3. _The recommended practice is that any Java application should bundle its own custom runtime._ It also sounds reasonable. But let's be practical, you can't bundle the whole JRE with every single command line tool. You can do it with the whole "TLA+ Toolbox" application, but if you have a look at any release of this very application ([the latest](https://github.com/tlaplus/tlaplus/releases/tag/v1.6.0), for instance), you'll find a tla2tools.jar, destributed as a separate library for people to use. Just because the world still works this way.

So, again, I'm not against using Java 12 runtime in the toolbox, and I didn't want my comment to sound like that, sorry if I misled you. I just want it to be clear what it means _in practice_ and how it affects future upgrades.

**Comment by pron** [comment]
Just a minor correction: I didn't say *Oracle* doesn't have LTS, I said OpenJDK doesn't. Also, Oracle is the company behind OpenJDK, whether you use Oracle's distribution, Adopt, or any other. Adopt doesn't really have LTS, either, it just uses the name for its OpenJDK udate project (8u/11u) builds, but that doesn't really matter. 

The choice is this: there are two update paths for Java. The default, recommended, one, that is more gradual and cheaper and in practice means no major upgrades, and the other one -- we can call it LTS -- which is more costly and less gradual. All projects should follow the default path unless they have a really good reason not to.

Also, I'm not for using Java 12 specifically in the toolbox. In the default update path, the version name, which is incremented every three releases or six months, doesn't really matter. You use the current mainline JDK, whatever number it has in its name.

Using the current JDK in practice means that there will not be major upgrades required down the line, which is not the case if 11u is used. This is the only implication for TLA+ and its users that I'm currently aware of.

**Comment by lemmy** [comment]
Java 13 is out.

**Comment by pron** [comment]
Yep :) There's a new Java release every ~2 months, and the integer is bumped every three releases.

**Comment by lemmy** [comment]
@quaeler Can you please upgrade the p2 bundle to Java 13?

**Comment by quaeler** [comment]
This has been done with https://github.com/quaeler/eclipse-jdk-bundles/commit/419a722f07ef7cbfbda10d086072b5d50160f665 which is ready to be merged over to your fork.

Things of note:
* the top level POM needs be updated with the new jdk-bundle version
* the POM in `org.lamport.tla.toolbox.product.uitest` needs to be updated due to a change in the way OpenJDK is laying out the dylibs in the macOS version of its deploy.

Once you've merged to your fork, built and deployed, i can update one or both POMs on the Toolbox master.

![Screen Shot 2019-11-08 at 4 10 30 PM](https://user-images.githubusercontent.com/22581048/68520592-a60f9d80-024d-11ea-8746-c82be91aa2bb.png)

**Comment by lemmy** [comment]
https://github.com/quaeler/eclipse-jdk-bundles/commit/419a722f07ef7cbfbda10d086072b5d50160f665 doesn't apply cleanly. :-(

**Comment by quaeler** [comment]
so, so, SO, lame. what's the merge issue? fork that branch?

**Comment by lemmy** [comment]
You based your work on your master branch, which was at Java 11.0.. mine had already moved via  with 11.0.3 to Java 12.0.1.1  Since you are familiar with the actual changes, please cherry-pick your 13.0.1 commit on top of my master and create a PR.

**Comment by quaeler** [comment]
I don't have permission to write or branch your fork, and i can't fork your fork as i have the original.

**Comment by lemmy** [comment]
Will it do if I give you write access to my fork?

**Comment by quaeler** [comment]
Yep - already assumed i had it - so just need to push.

**Comment by quaeler** [comment]
Pushed with https://github.com/lemmy/eclipse-jdk-bundles/commit/393d983f9354b5e442dc7cd27334da56638426a1

**Comment by lemmy** [comment]
https://github.com/lemmy/eclipse-jdk-bundles/commit/d82f5bcca29f5fa4c32983cb8caea51801ed5a69 updates the gp-pages branch meaning it should now be possible to consume Java 13.x.x in the Toolbox repository.

**Comment by quaeler** [comment]
Toolbox changes made with 432d87a3bfc258a6eed4dbf3cf53d979cf7f2a0c

**Comment by lemmy** [comment]
The Jenkins build appears to be broken due to this change.

**Comment by quaeler** [comment]
Curse the green checkmark... "why do we even have a green checkmark?"

**Comment by quaeler** [comment]
Looks like a bunch of RCPTT failing on the Linux.. we could ship macOS only.

(But seriously, how can the the green checkmark says macOS/Win/Linux build successes, and the CI master head is failing.. is this the CI machine hiccup'ing?)

Will check out under an Ubu tomorrow and try running locally.

**Comment by lemmy** [comment]
The checkmark is set by the Azure Pipeline build and not by the Jenkins build (which doesn't integrate with GH beyond pulling code).

**Comment by quaeler** [comment]
Hmm... so in Azure Pipeline, the Linux build is a-ok, and in CI it falls over?

**Comment by lemmy** [comment]
Yes, but the Azure Pipeline doesn't execute the tests (because they tend to time out).

**Comment by quaeler** [comment]
Ah - ok. danke.

**Comment by quaeler** [comment]
The problem is launching the checker from the Toolbox fails with
```
Error launching TLC with command-line (CWD: /home/loki/.tlaplus/Queens/Queens.toolbox/FourQueens): /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java -cp /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/lib/*:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/lib/javax.mail/*:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/class: -XX:MaxDirectMemorySize=394m -Xmx198m -Dtlc2.tool.fp.FPSet.impl=tlc2.tool.fp.OffHeapDiskFPSet -XX:+UseParallelGC tlc2.TLC -deadlock -fp 84 -config MC.cfg -coverage 3 -workers 1 -tool -metadir /home/loki/.tlaplus/Queens/Queens.toolbox/FourQueens MC
Exception occurred executing command line.
Cannot run program "/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java" (in directory "/home/loki/.tlaplus/Queens/Queens.toolbox/FourQueens"): error=13, Permission denied
```
Performing that in a shell window from the same CWD works fine.  Will ponder.

**Comment by lemmy** [comment]
Is the x bit correctly set on the binary?

**Comment by quaeler** [comment]
:- )  yes... and i ran it fine from the shell

**Comment by quaeler** [comment]
```
loki@pere-ubu-1804:~$ ls /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java
-rwxr-xr-x 1 loki loki 8720 Oct 26 03:12 /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java
loki@pere-ubu-1804:~$ /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)
loki@pere-ubu-1804:~$ cd .tlaplus/Queens/Queens.toolbox/
loki@pere-ubu-1804:~/.tlaplus/Queens/Queens.toolbox$ cd FourQueens
loki@pere-ubu-1804:~/.tlaplus/Queens/Queens.toolbox/FourQueens$ /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java -cp /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/lib/*:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/lib/javax.mail/*:/home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.tlatools_1.0.0.201911111835/class: -XX:MaxDirectMemorySize=394m -Xmx198m -Dtlc2.tool.fp.FPSet.impl=tlc2.tool.fp.OffHeapDiskFPSet -XX:+UseParallelGC tlc2.TLC -deadlock -fp 84 -config MC.cfg -coverage 3 -workers 1 -tool -metadir /home/loki/.tlaplus/Queens/Queens.toolbox/FourQueens MC
@!@!@STARTMSG 2262:0 @!@!@
TLC2 Version 2.15 of Day Month 20?? (rev: cf29306)
@!@!@ENDMSG 2262 @!@!@
...
```

**Comment by quaeler** [comment]
```
java.io.IOException: Cannot run program "/bin/ls": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:882)
	at org.eclipse.jdt.launching.AbstractVMRunner.exec(AbstractVMRunner.java:95)
	at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:503)
	at org.lamport.tla.toolbox.tool.tlc.job.TLCProcessJob.run(TLCProcessJob.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 10 more
```

**Comment by lemmy** [comment]
?

**Comment by quaeler** [comment]
It appears there is something broken in the java.lang process related stuff in the JRE, but not the JDK, on Linux.
```
loki@pere-ubu-1804:~/Downloads/jdk-13.0.1+9$ bin/java Bla
process: Process[pid=24119, exitValue=0]
loki@pere-ubu-1804:~/Downloads/jdk-13.0.1+9$ /home/loki/dev/tlaplus/git/tlaplus/org.lamport.tla.toolbox.product.product/target/products/org.lamport.tla.toolbox.product.product/linux/gtk/x86_64/toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.2/jre/bin/java Bla
Exception in thread "main" java.io.IOException: Cannot run program "/bin/ls": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at java.base/java.lang.Runtime.exec(Unknown Source)
	at Bla.main(Bla.java:4)
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 6 more
loki@pere-ubu-1804:~/Downloads/jdk-13.0.1+9$ cat Bla.java
public class Bla {

public static void main (String[] args) throws Exception {
Process p = Runtime.getRuntime().exec("/bin/ls");
System.out.println("process: " + p);
}

}

loki@pere-ubu-1804:~/Downloads/jdk-13.0.1+9$ 
```
Will look more...

**Comment by quaeler** [comment]
... but not if i download the JRE directly and use the one i've downloaded - so something is corrupt in the jdk-bundle somehow... will determine.

**Comment by quaeler** [comment]
Linux bundle now needs `lib/jspawnhelper` to have its execution bit set. With b7a3c968b95c1e84f08fa6fdf067b29e85a4dc24 your fork is ready for a rebuild.

**Comment by lemmy** [comment]
https://github.com/lemmy/eclipse-jdk-bundles/commit/ee8dd77cfb718b09cf5a7c07bc62b1ce946646d9

**Comment by quaeler** [comment]
Builds successfully on Ubu1804 for me; kicked off the CI build.

**Comment by quaeler** [comment]
CI RCPTT still failing - fails locally too. The Linux product it builds has permissions set correctly (i.e downloading the Linux zip from [here](https://tla.msr-inria.inria.fr/build/job/CI-HEAD-master-Toolbox/239/execution/node/5/ws/org.lamport.tla.toolbox.product.product/target/products/) is a functioning Toolbox that can run a checker.
If i look at what it is putting in the unpacked AUT, it's now the same thing that was happening with the macOS build in the past - the execution bit is not being maintained on the unpacked executable.
Will address.

**Comment by quaeler** [comment]
Linux tests finally functioning with 199c6cb and macOS tests running again once we updated the jdk-bundle version number in the top level pom with 116d391

**Comment by lemmy** [comment]
Running the nightly build locally:

```
Error launching TLC with command-line (CWD: /home/markus/src/TLA/_specs/models/GoogleGroup/Neverov/LockTwo.toolbox/Model_1): /opt/TLA+Toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.3/jre/bin/java -cp /opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201911130118:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201911130118/lib/*:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201911130118/lib/javax.mail/*:/opt/TLA+Toolbox/plugins/org.lamport.tlatools_1.0.0.201911130118/class:/usr/local/lib/tlaps//*:/home/markus/src/TLA/_specs/CommunityModules/dist/CommunityModules-201908231109.jar -XX:MaxDirectMemorySize=794m -Xmx398m -Dtlc2.tool.fp.FPSet.impl=tlc2.tool.fp.OffHeapDiskFPSet -XX:+UseParallelGC -DTLA-Library=/usr/local/lib/tlaps/:/home/markus/src/TLA/_specs/CommunityModules/dist/CommunityModules-201908231109.jar tlc2.TLC -fp 15 -config MC.cfg -coverage 3 -workers 2 -tool -metadir /home/markus/src/TLA/_specs/models/GoogleGroup/Neverov/LockTwo.toolbox/Model_1 MC
Exception occurred executing command line.
Cannot run program "/opt/TLA+Toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.3/jre/bin/java" (in directory "/home/markus/src/TLA/_specs/models/GoogleGroup/Neverov/LockTwo.toolbox/Model_1"): error=13, Permission denied
```

**Comment by quaeler** [comment]
Odd.. the one built by the CI machine (last build 247 - here: https://tla.msr-inria.inria.fr/build/job/CI-HEAD-master-Toolbox/247/execution/node/5/ws/org.lamport.tla.toolbox.product.product/target/products/ ) has perms set correctly on jspawnhelper (as does the one at http://nightly.tlapl.us/products/ - which has the same ZIP checksum.)

Does your `jspawnhelper` not have the execution bit set?
```
algebraic:lib loki$ ls jspawnhelper 
-rwxr-xr-x@ 1 loki  staff  18696 Oct 26 04:12 jspawnhelper
algebraic:lib loki$ pwd
/Users/loki/Downloads/toolbox 2/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.3/jre/lib
```

**Comment by lemmy** [comment]
```bash
markus@avocado:~# ls -lah /opt/TLA+Toolbox/plugins/org.lamport.openjdk.linux.x86_64_13.0.1.3/jre/lib/
total 100M
drwxr-xr-x 5 root root 4,0K Nov 13 10:58 .
drwxr-xr-x 6 root root 4,0K Nov 13 10:58 ..
-rw-r--r-- 1 root root  39K Nov 12 17:23 classlist
-rw-r--r-- 1 root root  13K Nov 12 17:23 jexec
drwxr-xr-x 2 root root 4,0K Nov 13 10:58 jfr
-rw-r--r-- 1 root root 104K Nov 12 17:23 jrt-fs.jar
-rw-r--r-- 1 root root  19K Nov 12 17:23 jspawnhelper
-rw-r--r-- 1 root root   29 Nov 12 17:23 jvm.cfg
-rw-r--r-- 1 root root  44K Nov 12 17:23 libawt_headless.so
-rw-r--r-- 1 root root 746K Nov 12 17:23 libawt.so
-rw-r--r-- 1 root root 478K Nov 12 17:23 libawt_xawt.so
-rw-r--r-- 1 root root  29K Nov 12 17:23 libdt_socket.so
-rw-r--r-- 1 root root  13K Nov 12 17:23 libextnet.so
-rw-r--r-- 1 root root 1,5M Nov 12 17:23 libfontmanager.so
-rw-r--r-- 1 root root 778K Nov 12 17:23 libfreetype.so
-rw-r--r-- 1 root root  51K Nov 12 17:23 libinstrument.so
-rw-r--r-- 1 root root  47K Nov 12 17:23 libj2gss.so
-rw-r--r-- 1 root root  18K Nov 12 17:23 libj2pcsc.so
-rw-r--r-- 1 root root  87K Nov 12 17:23 libj2pkcs11.so
-rw-r--r-- 1 root root 8,1K Nov 12 17:23 libjaas.so
-rw-r--r-- 1 root root 256K Nov 12 17:23 libjavajpeg.so
-rw-r--r-- 1 root root 204K Nov 12 17:23 libjava.so
-rw-r--r-- 1 root root 7,9K Nov 12 17:23 libjawt.so
-rw-r--r-- 1 root root 276K Nov 12 17:23 libjdwp.so
-rw-r--r-- 1 root root 138K Nov 12 17:23 libjimage.so
-rw-r--r-- 1 root root  78K Nov 12 17:23 libjli.so
-rw-r--r-- 1 root root  14K Nov 12 17:23 libjsig.so
-rw-r--r-- 1 root root  82K Nov 12 17:23 libjsound.so
-rw-r--r-- 1 root root 559K Nov 12 17:23 liblcms.so
-rw-r--r-- 1 root root 8,1K Nov 12 17:23 libmanagement_agent.so
-rw-r--r-- 1 root root  33K Nov 12 17:23 libmanagement_ext.so
-rw-r--r-- 1 root root  30K Nov 12 17:23 libmanagement.so
-rw-r--r-- 1 root root 578K Nov 12 17:23 libmlib_image.so
-rw-r--r-- 1 root root 105K Nov 12 17:23 libnet.so
-rw-r--r-- 1 root root  91K Nov 12 17:23 libnio.so
-rw-r--r-- 1 root root  13K Nov 12 17:23 libprefs.so
-rw-r--r-- 1 root root 7,8K Nov 12 17:23 librmi.so
-rw-r--r-- 1 root root  29K Nov 12 17:23 libsctp.so
-rw-r--r-- 1 root root 364K Nov 12 17:23 libsplashscreen.so
-rw-r--r-- 1 root root 317K Nov 12 17:23 libsunec.so
-rw-r--r-- 1 root root 220K Nov 12 17:23 libunpack.so
-rw-r--r-- 1 root root  80K Nov 12 17:23 libverify.so
-rw-r--r-- 1 root root  38K Nov 12 17:23 libzip.so
-rw-r--r-- 1 root root  92M Nov 12 17:23 modules
-rw-r--r-- 1 root root  12K Nov 12 17:23 psfontj2d.properties
-rw-r--r-- 1 root root 3,8K Nov 12 17:23 psfont.properties.ja
drwxr-xr-x 2 root root 4,0K Nov 13 10:58 security
drwxr-xr-x 2 root root 4,0K Nov 13 10:58 server
-rw-r--r-- 1 root root 106K Nov 12 17:23 tzdb.dat
```

**Comment by lemmy** [comment]
Never mind, I know what is going on.

**Comment by quaeler** [comment]
Tell me!
