### ISSUE TITLE
TLC trace doesn't address the situation with more than one predecessors

### ISSUE THREAD

**Issue by andrewlee302** [tlaplus/tlaplus#27]
In many cases with concurrency, it occurs that some states can be reached by more than one predecessor states. The trace graph is important in recovering/debugging or analysis. So it's urgent to enhance the trace persistency.

**Comment by lemmy** [comment]
Hi Andrew,

you can (partially) achieve what you suggest by passing _-continue_ to TLC. With it, TLC will continue to explore the state graph even after a property-violating behavior prefix --- a counterexample to a safety property --- is found.

If you additionally pass _-dump dot graph_, the [tlc2.util.IStateWriter](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/util/IStateWriter.java) will dump the state graph in dot format to a file named graph.dot located in the model directory. dot files can be visualized with [GraphViz](http://www.graphviz.org/). TLC's dot output lacks visualization of counterexamples. However, the output combined with the GraphViz tools, it should be able to annotate counterexamples easily. Dumping the state graph with the IStateWriter only scales for tiny state spaces (for larger state spaces one would have to hook it up to e.g. a graph database).

Generally though, consider the following trivial spec with _Inv_ as the (safety) property and _Constraint_ as a state constraint:

```
----------------------------- MODULE GHIssue027 -----------------------------
EXTENDS Naturals
VARIABLES x, y
   
Init == /\ x = 0
        /\ y = 0
           
Next == \/ /\ x' = x + 1
           /\ UNCHANGED <<y>>
        \/ /\ y' = y + 1
           /\ UNCHANGED <<x>>
              
Spec == Init /\ [][Next]_<<x,y>>
   
Constraint == /\ x < 4
              /\ y < 4

Inv == (x+y) < 5
=============================================================================
```

This trivial spec alone already produces almost a dozen counterexamples. How would you handle much larger sets of counterexamples in the TLA<sup>+</sup> Toolbox?

Last, [Michael Leuschel et al.](http://www.cs.hhu.de/lehrstuehle-und-arbeitsgruppen/softwaretechnik-und-programmiersprachen.html) intended to present [Animation, Visualisation and Constraint Solving for TLA<sup>+</sup> Using ProB ](http://tla2016.loria.fr/). Unfortunately, the conference got canceled. Still, you might want to check out [ProB](https://www3.hhu.de/stups/prob/index.php/Main_Page) in the scope of TLA<sup>+</sup>.

**Comment by andrewlee302** [comment]
Hi,
Thanks a lot. I got what I wanted by using *-dump dot graph*. I have thought the *TLATrace* is exactly what the execution trace means. So I'm also curious about the actual function of the trace except for *printing trace for debugging*.
