### ISSUE TITLE
"A label may not appear in a macro" when no macro is present

### ISSUE THREAD

**Issue by fuzz-ai** [tlaplus/tlaplus#270]
I have encountered the issue also reported here: https://groups.google.com/forum/#!topic/tlaplus/ouUGXPV8kRI
in which the PlusCal translator appears to stop working.  I had previously tried to refactor some code into a macro, and started receiving 

"PCal Translator Error

Unrecoverable error:
 -- A label may not appear in a macro"

in a process definition, even though the macro definition has been deleted.  I even introduced a new process and commented out the old one with the same error.  Restarting Toolbox appears to be the only workaround.

**Comment by lemmy** [comment]
@fuzz-ai This happened with the 1.5.7 Toolbox release or one of the nightlies leading to 1.5.8 (the way how the pcal translator is invoked has changed after 1.5.7)?

**Comment by fuzz-ai** [comment]
It was in 1.5.7.

**Comment by lemmy** [comment]
If possible, please check if this bug is still present in the [nightly].

[nightly]: http://nightly.tlapl.us/products

**Comment by mgxm** [comment]
I could not reproduce the bug on 1.5.8. Seems to be fixed

**Comment by quaeler** [comment]
Marking closed as fixed.
