### ISSUE TITLE
Better Toolbox support for model checking different CONSTANT values

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#272]
This idea is about running TLC multiple times/once for each configuration:

LL: "I was doing something by hand that should be mechanized.  I'm writing a spec of an algorithm in which Succ is a CONSTANT parameter.  I wanted to test the algorithm for all values of Succ in some set S.  The only way to do that is to make Succ a variable that is left unchanged by the next-state relation.  It would be nice if I didn't have to do that manually.  It seems like too much work to do it properly.  But I wonder if there is some kludgy way to tell the Toolbox to create a new file with the necessary transformation that will work most of the time."

LL: "The ideal way would be for the user to specify in TLC's cfg file that a constant Succ be turned into a variable initialized to an arbitrary element of S, where S is an identifier defined to equal a constant.  Implementing that is not trivial."

-----

This idea is about running TLC only once for all configurations:

A related scenario frequently occurs in PlusCal specifications where an algorithm should be model checked for different values (sets) of P.  Changing P into a variable only works for safety checking, but does not work with liveness properties because the fairness constraint becomes state level.

```tla
CONSTANT P
ASSUME(IsFiniteSet(P))
...
process (p \in P) {
   ...
}
```

It is unclear how this would work with symmetry sets when properly implemented in TLC.  The proposed Toolbox workaround above wouldn't have this kind of problem.

[Apalache's constant initializer](https://github.com/konnov/apalache#option-2-initialize-constants-with-constinit) is similar.

**Comment by konnov** [comment]
Could you reserve a keyword in the TLC configuration format, e.g., `CINIT` or `CONSTINIT`, so we could use a TLC config as the primary configuration format for Apalache too?

**Comment by lemmy** [comment]
Consider it reserved.

Changing the old parser will be a pain though. @Henne PR's could be useful here: https://github.com/tlaplus/tlaplus/pull/259.

**Comment by lemmy** [comment]
https://github.com/konnov/apalache/issues/79

**Comment by lemmy** [comment]
The kludge proposed by LL above would likely require to run multiple instances of TLC in parallel, which makes https://github.com/tlaplus/tlaplus/issues/378 a prerequisite.

**Comment by lemmy** [comment]
An approach would be to switch from EXTEND in the MC.tla file to INSTANCE with a re-definition of the CONSTANTS.  TLC would then have to traverse the semantic graph to patch the const node with a variable node.

**Comment by pron** [comment]
I've also worked on bringing config.jj up to date: https://github.com/pron/tlaplus/commits/fixjavacc

**Comment by lemmy** [comment]
The various script in the artifact of the [RenamingProof](https://hurault.perso.enseeiht.fr/RenamingProof/) are an example where this would be useful.  However, this feature is probably best implemented at the TLC level to address the CLI use case.

**Comment by lemmy** [comment]
@ahelwer It is not immediately relevant for trace exploration, but please have this feature on the radar.

**Comment by lemmy** [comment]
Related: https://github.com/lemmy/BlockingQueue/issues/5#issuecomment-831626034

**Comment by lemmy** [comment]
Another finding why a more principled approach would be good:  Assuming a plain, high-level `H`, it is impractical to check refinement if a lower-level spec `L` introduces "constant variables" to check various subsets of `H`'s constants:

```tla
---- MODULE H ----
CONSTANT C
...
====

---- MODULE L ----
CONSTANT C
VARIALBES c

Init ==
  c \in SUBSET C

H = INSTANCE H

THEOREM Spec => H!Spec
====
```

**Comment by lemmy** [comment]
Addressed as shown in https://github.com/tlaplus/tlaplus/issues/577#issuecomment-883781778 and https://github.com/tlaplus/tlaplus/issues/577#issuecomment-884510795

**Comment by lemmy** [comment]
https://github.com/lemmy/BlockingQueue/commit/f3075bf4dcda25387b05d7f2d8787b61fb95a48b  shows how sets of constant values can be checked.
