### ISSUE TITLE
Programatic interface for tla

### ISSUE THREAD

**Issue by zstone1** [tlaplus/tlaplus#273]
Hello, I am looking for some docs, or advice on the following matter:

1) Calling TLC/ pluscal translator directly from java. Ideally java 8 or 9.
2) Parsing responses from the command line tools
3) Writing Petri Net specifications in PlusCal

If you need some background on my problem:
I am writing some code (in java/kotlin). It takes a petri net, and some ltl style properties. It verifies those properties, and if they fail reports a counter example in terms of a sequence of transition firings of the petri net. Sounds like classic model checking. However, it needs to be done programmatically from java. Furthermore, I cannot expose any details about the model checker itself. My users are pretty far from mathematicians.

I am not too worried about translating petri net descriptions into PlusCal, and the ltl properties to TLA+. But what I need is a way to actually call tlc/PlusCal translator from my java code. Surely I'm not the first person to try automating calls to tlaplus toolbox functionality?

If I have to call the command line tools from java as an external process, I can live with that. But then I would need to parse the responses. Is there any documentation on the format of the outputs? If I accidentally give it bad input, what the format for the errors?

**Comment by lemmy** [comment]
@zstone1 1. and 2. are both the mechanism how the TLA Toolbox invokes and communicates with TLC.  Please check the Toolbox's source code for instructions.  Note that we have effectively dropped support for < Java 11.

I'm afraid I can't answer question 3.  Are you referring to basic PT nets or a more sophisticated flavor?  What kind of LTL properties do you have in mind (some LTL operators such as Next might be difficult to translate to TLA+).

**Comment by zstone1** [comment]
After some further digging, it turns out ProB2 (https://github.com/bendisposto/prob2) seems to solve my problem. It has a TLA interface, the petri nets are pretty easy to translate into b-machines, and it runs in java 8. Thanks!

**Comment by lemmy** [comment]
Don't you then translate the original petri-net into a b-machine and then again into TLA+?  I wonder how much bloat this creates.  If such a translation turns out to be practicle, it might be a viable approach to participate in the petri-net [model checking contest](https://mcc.lip6.fr/index.php).

Also note that prob2's TLA+ interface can't support Java8 indefinitely unless they decide not to upgrade to newer TLC versions.
