### ISSUE TITLE
Implement filtering of the error-trace in the TLC Error View

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#274]
The Error-Trace list should allow filtering on:
* Variable / Expression
* Value
** by explicit value
** by changed value
* Frame range (e.g states 10 through 15)

**Comment by lemmy** [comment]
I suggest to only implement variable filtering for now for which we have a real use case: Refinement (compare page 9 of "[Hiding, Refinement, and Auxiliary Variables](https://lamport.azurewebsites.net/tla/hiding-and-refinement.pdf)").

-------------

In terms of UI:

* Add a hide/un-hide button (next to the existing collapse & link buttons)
* Clicking the button opens a modal dialog
* For all spec & trace expression¹ variables dialog shows a pair consisting out of a checkbox and the name of the variable (for un-named trace expression it shows the expression)
* Checked state indicates a variable is hidden 

Additionally, hiding a variable from the trace should be possible by left-clicking a var with a modifier key pressed

¹ Should work for evaluated/explored trace expressions too (un-hiding shouldn't require re-exploration)

**Comment by lemmy** [comment]
This is more important than #261

**Comment by quaeler** [comment]
d6886b5 provides the bulleted items, but not left clicking with a modifier key.

**Comment by quaeler** [comment]
32b422d provides ALT-clicking on a variable to omit it.

**Comment by lemmy** [comment]
Can you record a screencast and link it here and in the changelog?

**Comment by quaeler** [comment]
53a673d is the changelog addition, and attaching the GIF here!
![error-trace-filtering](https://user-images.githubusercontent.com/22581048/62180695-d4ecae00-b305-11e9-99aa-c6d78d5f5fa2.gif)
