### ISSUE TITLE
Allow restarting of TLC from a specific state in the TLC Error Trace

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#275]
It would be very nice to allow users to 'right-click' on a specific state in Error-Trace of the TLC Error View and choose a command worded roughly like "Start from this state."

Upon invoking this, TLC will be invoked with a modified spec commencing checking with the selected state as the initial state.

**Comment by lemmy** [comment]
To clarify: There is no need to modify the original spec.  The (generated) TLC config file can simply reference a new initial predicate in the generated MC.tla file.

**Comment by lemmy** [comment]
This enhancement request has received significant positive feedback during TLA+ conf.

**Comment by lemmy** [comment]
@quaeler Wanna take it?

**Comment by lemmy** [comment]
I just realized that the trick outlined in https://github.com/tlaplus/tlaplus/issues/365#issuecomment-531998203 is related to this enhancement; except instead of copying a single state to the init predicate, it copies the complete trace as the state constraint.

**Comment by quaeler** [comment]
shoaley - sounds good.

**Comment by lemmy** [comment]
Looking at the commits and the screencast, it doesn't seem to include the idea outlined in https://github.com/tlaplus/tlaplus/issues/275#issuecomment-532002862.

How much work will it be to generate and copy the sequence of actions to the "Action Constraints" on the "Spec Options" page?  Instead of adding <<A,B,C>>[TLCGet("level")] we could add a 1-arity operator to Toolbox.tla named something along the lines of ActionPrefix(<<A,B,C,>>) which constraints the checked behaviors to those whose action prefix satisfies <<A,B,C>>.

**Comment by quaeler** [comment]
Hmm.. i thought the cited idea states that the trace should be copied as a state constraint. ?

**Comment by lemmy** [comment]
Copying the actual trace as a state constraint is an alternative.  However, I believe it to be more useful to instead follow the action constraint approach under the assumption that a user wants to check all behaviors corresponding to a (prefix) sequence of actions and not just the single behavior which is the error trace.  Especially, if a user modifies the spec to rule out the error trace in which case TLC would deadlock.

**Comment by quaeler** [comment]
Ok - will mull

**Comment by lemmy** [comment]
One way to implement the UI is to allow users to select a sub-sequence of the states shown in the behavior in which case the action constraints uses "wildcards" for the un-selected states.  I.e. let the action prefix be <<A,B,C,A,B,C>> but a user only select the states at trace position 2,3,5.  The action constraint would then be <<TRUE,B,C,TRUE,B,TRUE>>.

**Comment by lemmy** [comment]
Two observations with the current implementation:
- the predicate is copied as a state constraint (Spec Options) but should be the init predicate (Model Overview)
- the predicate includes the trace expressions if any (which are undefined in the spec)

**Comment by quaeler** [comment]
The changes made with 4851e3b now place the predicate (excluding trace expressions, if any) as either the Init condition, or appends it as a conjunction to the currently defined temporal specification, depending on the pre-existing model configuration.

I considered, and played around with an implementation of, the action constraints idea; getting a correct form, though, when an action takes a non-zero number of arguments is a true bugaboo - so i have still not gone this route.

**Comment by lemmy** [comment]
@quaeler Instead of adding a action constraint you can explore if the same can be expressed as a state constraint.  For inspiration, look at what the generated TE.tla looks like.

**Comment by quaeler** [comment]
As discussed last, installs the error trace state conjunction in the Init of an Init-Next and either preserves the Next if the model was originally Init-Next, or put's the temporal spec as the Next definition were it a closed behavior spec. The model is not automatically launched and the user is presented with a dialog telling them the model has been reconfigured and asking that they review it.
Please re-open if warranted.

**Comment by lemmy** [comment]
Action constraint for a PlusCal algorithm:

```tla
ActionConstraint == LET w == CHOOSE w \in Workers: TRUE
                        s == <<A(w), A(w), B(w), B(w), ..., Terminating>>
                    IN IF TLCGet("level") \in DOMAIN s 
                       THEN s[TLCGet("level")]
                       ELSE TRUE
```
