### ISSUE TITLE
TLC should return a non-zero exit status when model fails

### ISSUE THREAD

**Issue by japgolly** [tlaplus/tlaplus#277]
Currently TLC returns 0 when a model check completes with failure.

In my case, a have a few quick models I run in succession and I'd like to have my script stop on the first failure, rather than me being overwhelmed with failure after failure. Without an indicative exit status, callers are unable to determine the model result.

**Comment by lemmy** [comment]
What do you actually mean by "model fails"?

**Comment by japgolly** [comment]
I mean the model checker finds a behaviour that violates an invariant.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/output/EC.java already maps all errors and failures to integers.  It shouldn't be too difficult to set the actual EC integer as TLC's exit value. @japgolly Do you have the bandwidth to work on this?

**Comment by japgolly** [comment]
I'd be happy to do this. I'm a bit busy though so it might take 2 or 3
weeks to get time, but if you don't mind that delay, leave it with me.

**Comment by lemmy** [comment]
@japgolly Looking forward to the pull request.

**Comment by lemmy** [comment]
@japgolly Do you still intend to provide a PR?

**Comment by japgolly** [comment]
Hi @lemmy, sorry for the delay; I've been busier (and sicker) than I expected. I've got some free time today, I'm going to take a look at this now.

**Comment by japgolly** [comment]
@lemmy are you perhaps currently online such that we could have a quick chat? If so would you mind DM'ing me on twitter?

**Comment by lemmy** [comment]
@japgolly What's your twitter handle?

**Comment by japgolly** [comment]
@lemmy It's `@japgolly` :)
