### ISSUE TITLE
Deleting a model results in NullPointerException

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#279]
When there are 2 models (model_1 and model_2), if I delete model_2 it will stay on the spec explorer tree, and when I click on it the toolbox throws a java.lang.NullPointerException exception.

If I exit the toolbox and then run it again, problem is fixed and model_2 is gone.

**Comment by lemmy** [comment]
@AmirHossein-SayyadAbdi What OS are you on and is this a reproducible or an intermittent bug?

**Comment by AmirHossein-SayyadAbdi** [comment]
@lemmy I am using Windows version of the toolbox and the bug is reproducible.
