### ISSUE TITLE
Bogus expression in TraceExplorer after Trace Exploration

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#28]
![bogusvariablenameintraceexplorer](https://cloud.githubusercontent.com/assets/88777/20598622/26612348-b24a-11e6-9112-ab6d8cbd0a62.png)

# **!!!Workaround: Rerun Trace Exploration!!!**

**Comment by 0joshuaolson1** [comment]
If this is wontfix, it's not an open issue and should be documented elsewhere.

**Comment by lemmy** [comment]
Thanks for mentioning this. We used wonfix in the past when we had no plans to work on an issue due to resource constrains but would still accept patches. helpwanted is indeed a much better indicator for this.

**Comment by quaeler** [comment]
Is there a way to reproduce this reliably?

**Comment by lemmy** [comment]
Actually I believe I fixed this bug in the 1.5.4 cycle. Please reopen if it shows up again.
