### ISSUE TITLE
New model shows single page

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#281]
Creating a new model should present a model editor featuring a single page (which is the general content of the current 'Overview' page.)

**Comment by quaeler** [comment]
Running TLC will then display the 'Results' tab. When the run has completed, the profile tab will then also be added (but not brought to the top of the stack.)

**Comment by lemmy** [comment]
* For snapshots the Result Page has to be there when the Model Editor opens up
* The profiler tab will not open up unless coverage and cost statistics are collected

**Comment by quaeler** [comment]
Agreed * 2 - when i write "New Model" i mean either right clicking on "models" in the Spec Explorer, or choosing the item under the "TLC Model Checker" menu bar folder.

**Comment by lemmy** [comment]
Additional requirement: it should be possible to create and configure a "standard" model with the keyboard only where standard means no settings on the advanced pages.

**Comment by lemmy** [comment]
How much of this is still open after 1.6.0?

**Comment by quaeler** [comment]
The part where a results page shows already on a new model.

**Comment by quaeler** [comment]
Addressed with 82c3c81
