### ISSUE TITLE
Move memory slider and worker spinner from How to run to Advanced

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#283]
Move the memory slider and the worker spinner from the Overview page's "How to run?" section to the new Advanced page (see #282). When selecting a choice from the pulldown, text should be supplied which lists what this means in terms of worker and memory count (e.g "4 workers & 8192 MB allocated to TLC")

**Comment by quaeler** [comment]
Implemented with 5eae39e59c287f32f3bc34c1ed0ac1f20a88bfee

**Comment by lemmy** [comment]
Would it be possible to append the actual values such as "3 workers allocated..." to the combo itself?

**Comment by quaeler** [comment]
sure - we have horizontal space to kill on that widget - will do

**Comment by lemmy** [comment]
Please pull the repo because I just committed a potentially conflicting change.

**Comment by quaeler** [comment]
yes - when i get back to doing this, i will sync my fork to master and then branch off my fork to do work.
