### ISSUE TITLE
Condense the General section of the Results page

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#284]
To whit:
* start and end time along with an icon representation of 'currently running', 'not running', etc should be on a single line
* if depth first searching was done, show appropriate verbiage
* if checkpoints exist, show appropriate verbiage
* if execution was done in simulation mode, show appropriate verbiage
* have a problems section encompassing: errors, fingerprint collision, 0 count in coverage, ...

**Comment by quaeler** [comment]
@lemmy please give feedback on the reduced result available with 0e14c2bf208955caed83a357be724ed5b8a92e08

**Comment by lemmy** [comment]
How does a user e.g. learn about the mode (BFS, DFS, SIM) once model-checking completed?

**Comment by quaeler** [comment]
BFS is not mentioned as it's the default mode; either of the other two should be rendered in the top line, running or not (like seen in that GIF i emailed to you concerning sub-tab traversal.)

**Comment by quaeler** [comment]
Are there any requests for change on the current implementation, or is this closeable?

**Comment by lemmy** [comment]
Looks good to me and haven't heard complaints from elsewhere.

**Comment by BinyuHuang-nju** [comment]
Hi.Everytime I want to do model checking with TLC, the results always show "Fingerprint collision probability: calculated: XXX" . How can I avoid the condition?

**Comment by lemmy** [comment]
Please consider providing a PR for https://github.com/tlaplus/tlaplus/issues/285

**Comment by BinyuHuang-nju** [comment]
> Please consider providing a PR for #285

Thanks a lot.
