### ISSUE TITLE
Allow fingerprint collision probability threshold preference

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#285]
Allow the user to define the threshold at which they would like to be warned concerning the probability of fingerprint collision (a warning which will appear on the Results page - see #284)

**Comment by lemmy** [comment]
How do we expect users to come up with a reasonable threshold?  Instead I wonder if the Model Editor should display a warning (somewhere) that gradually increases its visibility (low probably is green, high probability is red).

**Comment by quaeler** [comment]
This is an excellent question (this issue has its genesis in what i guessed to be Leslie's thought in that Model Editor design thread - so i'm just parroting for the description.)
Once we agree on ranges that represent 'low' to 'high,' i think the color mapping is the preferred way to go.
