### ISSUE TITLE
Improve section layout space consumption

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#286]
The sections in the Model Editor pages should consume available space - like the Required dependency section of the Eclipse Manifest Editor.

**Comment by lemmy** [comment]
Can you please be more specific what this issue is about?

**Comment by quaeler** [comment]
Sorry - for example on the current Results page, were one to collapse all sections except for User Output, the text area in the User Output section should grow vertically to, ideally, consume all available space in the viewport.

**Comment by lemmy** [comment]
Is this still an issue?

**Comment by quaeler** [comment]
Nope.
