### ISSUE TITLE
Allow error stack traversal via arrows to be reflected in the spec

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#289]
In the TLC Error View, the user can navigate through the stack trace tree with error keys but this doesn't change the highlighted line in the spec; the line should be updated to reflect the currently selected stack item.

**Comment by lemmy** [comment]
Related/to be addressed with https://github.com/tlaplus/tlaplus/issues/9

**Comment by quaeler** [comment]
Closed with 14ce7a6fcf12b682c72620bf2efc4125700ef76f

**Comment by lemmy** [comment]
Can this be turned on and off?

**Comment by quaeler** [comment]
No - from our talks i didn't understand it to be "it would be nice for some people" but rather "the behavior should be this."
Feel free to re-open to make this a preference-driven function.

**Comment by lemmy** [comment]
It actually just occurred to me. :-)

Instead of a preference, why not simply add a button to the error trace view (next to the expand/collapse button) similar to the Eclipse Package Explorer's *Link with Editor* functionality?

![Screenshot from 2019-05-08 16-41-29](https://user-images.githubusercontent.com/88777/57415205-275b7a00-71b0-11e9-9aaf-2bf11fcd3b33.png)

**Comment by quaeler** [comment]
Sounds good - does the double-click observe this toggle button's state as well? (It would seem hinky to me were it to not...)

**Comment by lemmy** [comment]
Are you asking if double-click becomes a no-op when *link to editor* is off?

**Comment by quaeler** [comment]
Yes.

**Comment by lemmy** [comment]
To me a double-click is an intentional user action indicating the wish to navigate to the source. A selection change on the other hand does not always indicate this wish (unless *link to editor* is on).

**Comment by quaeler** [comment]
Ok - i'll buy that.

**Comment by quaeler** [comment]
This is implemented with 12790ae4c494c09dba8754b227ab48a5a3051697
