### ISSUE TITLE
OpenSpecHandler null pointer exception

### ISSUE THREAD

**Issue by shanemikel** [tlaplus/tlaplus#29]
I've tried a couple releases (1.4.5-linux.gtk.x86_64 and 1.5.2-linux.gtk.x86_64)

Upon trying to create and open a new spec, I hit a null pointer:
```
An internal error occurred during: "OpenSpecHandler is parsing spec...".
java.lang.NullPointerException
```

Using openjdk-8-jre on a recent Ubuntu derivative
I will happily provide more information if somebody can guide me to it

**Comment by lemmy** [comment]
Hi,

can you paste the content (tail) of the Toolbox's .log file? The file is located inside workspace/.metadata/ relative to the Toolbox's installation directory.

>  When reporting a bug, please include all details.  It will be helpful if you can include the relevant part of the Toolbox's log, which is the file named  .log.  On Windows and Linux, the .log file is in the folder  workspace/.metadata . That folder is in the same folder as the executable file with which you run the Toolbox. On the Mac, it is in the folder  toolbox.app/Contents/MacOS/workspace/.metadata, where  toolbox.app is the folder that you execute to run the Toolbox. (The log contains enough timestamped entries for you to figure out what part of it relates to the problem you are reporting.) 


In the meantime, you might want to check out the current "nightly" builds. Much has changed since 1.5.2 and there is a chance the bug is gone. It even comes with an easy to install apt repository:

    echo "deb https://tla.msr-inria.inria.fr/tlatoolbox/ci/toolboxUpdate/ ./" > /etc/apt/sources.list.d/tlaplus.list
    wget -qO - https://tla.msr-inria.inria.fr/jenkins.pub | sudo apt-key add -
    apt update
    apt install tla+toolbox

**Comment by shanemikel** [comment]
!ENTRY org.lamport.tla.toolbox 1 -1 2016-12-04 23:31:23.264
!MESSAGE Spec build invoked on Hello ...

!ENTRY org.eclipse.core.jobs 4 2 2016-12-04 23:31:23.266
!MESSAGE An internal error occurred during: "OpenSpecHandler is parsing spec...".
!STACK 0
java.lang.NullPointerException
        at org.lamport.tla.toolbox.spec.parser.SpecificationParserLauncher.parseSpecification(SpecificationParserLauncher.java:35)
        at org.lamport.tla.toolbox.spec.nature.ParserHelper$2.run(ParserHelper.java:75)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2344)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2326)
        at org.lamport.tla.toolbox.spec.nature.ParserHelper.rebuildSpec(ParserHelper.java:84)
        at org.lamport.tla.toolbox.ui.handler.OpenSpecHandler$1.run(OpenSpecHandler.java:71)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
!SESSION 2016-12-04 23:32:02.915 -----------------------------------------------
eclipse.buildId=1.4.2
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --help
Command-line arguments:  -os linux -ws gtk -arch x86_64 --help

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2016-12-04 23:32:03.684
!MESSAGE TLA+ Toolbox started with 1 arguments.

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2016-12-04 23:32:03.684
!MESSAGE --help

**Comment by shanemikel** [comment]
I have just managed to install the toolbox from the apt repository, and loading the spec didn't cause any exception.
