### ISSUE TITLE
Change coverage table from Results statistics to only uncovered expressions

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#292]
Remove the coverage table from the Statistics section of the Results page; warnings of zero count coverage will be displayed as part of #284 and their association to the spec will be handled via #291

**Comment by lemmy** [comment]
The TLACoverageEditor in commit 881f2e676d9f99c329f621790d2151438448761f annotated uncovered actions with a org.eclipse.jface.text.source.AnnotationPainter.

**Comment by lemmy** [comment]
Instead of removing the table, the count column should be removed and the all elements filtered with non-zero count.

**Comment by quaeler** [comment]
Are you saying filtered so that the table shows only non-zero count, or filtered so that the table shows only zero count?

**Comment by lemmy** [comment]
The latter but I've already taken care of this.

**Comment by lemmy** [comment]
b3dfe4abf2d80c751f0aea01d80c69d036588161
