### ISSUE TITLE
Investigate presenting state statistics in graph form initially

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#293]
On the Results page of the Model Editor, in the Statistics section, consider showing a graph instead of the table, with checkbox widgets to show/hide the graph lines for each attribute, and a button to show the current tabular data in a dialog.

**Comment by lemmy** [comment]
[Eclipse Advanced Visualization Project](https://projects.eclipse.org/projects/science.eavp)
[SWTChart](https://projects.eclipse.org/proposals/eclipse-swtchart)

**Comment by lemmy** [comment]
Please reopen if we will ever have the resources.
