### ISSUE TITLE
Instructions for building release from source?

### ISSUE THREAD

**Issue by asmyers** [tlaplus/tlaplus#31]
I see instructions for setting up a development environment with Eclipse but not
for building a release package from the repository. When I try `mvn install` one of the
tests pops up an eclipse window and then fails when I close it.  At that point the build is failed.

**Comment by lemmy** [comment]
Hi Andrew,

1. You can skip all tests with -Dmaven.test.skip=true
2. You can tell Maven to keep going after test failures with -Dmaven.test.failure.ignore=true
3. You can avoid building yourself and grab the latest CI build at http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/

For 1. and 2., the release packages are located in org.lamport.tla.toolbox.product.product/target/products/

Generally, for the UI tests to succeed, you must not close the Eclipse windows (unless you know the test is stuck). On Linux you can have the tests use a dedicated DISPLAY when its interfering with your other work (see https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.test/pom.xml#L34-L47).

Let us know if a test hangs on your machine.

**Comment by asmyers** [comment]
#3 is perfect, thanks!  Loving all the bug fixes you've put into the toolbox!

**Comment by lemmy** [comment]
Note that the packages at http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/ will automatically prompt to update to the most recent CI build. This feature has been added quite recently, so let me know if it does not work.

**Comment by asmyers** [comment]
Looks like the automatic update feature works.  I just got the Dec. 20th update automatically.

Cheers!
