### ISSUE TITLE
Definition override disappears from advanced page

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#316]
If I select these overrides:

![image007](https://user-images.githubusercontent.com/88777/58495710-fde99a80-812c-11e9-8087-d2abe04ef7e7.png)

and then  click on Next <- TRUE I get this

![image005](https://user-images.githubusercontent.com/88777/58495712-ff1ac780-812c-11e9-877b-4ba1ac26f3e8.png)

At this point, nothing I do can get the window to show the right thing except selecting

the Next <- TRUE and deleting it, which produces:

![image006](https://user-images.githubusercontent.com/88777/58495713-004bf480-812d-11e9-8bf9-ef01251f37db.png)

**Comment by lemmy** [comment]
Not reproducible with v1.5.7

**Comment by lemmy** [comment]
Both elements were likely in the list but the list's height is too small and the scroll indicator easy to miss.

**Comment by lemmy** [comment]
@quaeler Can you please change the advanced model page to use a layout that makes better use of screen estate?

**Comment by quaeler** [comment]
Addressed with 2ea44638a2c80f736a22f3fcee9b784ca1881b27
