### ISSUE TITLE
PCal: Unrecoverable Error with blank info

### ISSUE THREAD

**Issue by Alexhb61** [tlaplus/tlaplus#318]
I think the PCAL translator can't handle a certain type of newline character, but the IDE displays this newline as normal. This error is very confusing. I started writing my tla spec in another editor which might be why the error wasn't detected earlier.

**Comment by lemmy** [comment]
@Alexhb61 Can you attach the spec?

**Comment by Alexhb61** [comment]
I was able to recreate the bug with this code
`---- MODULE error ----
EXTENDS Naturals, TLC

(* --algorithm transfer
variables alice_account = 10, bob_account = 10, money = 5;

begin
A: alice_account := alice_account - money;
B: bob_account := bob_account + money;

end algorithm *)
====
`

**Comment by lemmy** [comment]
@Alexhb61 GitHub seems to screw up whitespaces.  Can you attach a zipped snapshot of the spec?  Also, what error does the PCal transpiler print?

**Comment by lemmy** [comment]
Assumed to be fixed with abd5181ad3a94588998ddb2243e4d3122cd2b8be
