### ISSUE TITLE
Update Help topics

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#319]
The following help topics need to be modified to capture changes present in the 1.6.0 release:
* :white_check_mark: If #288 is included: [Preferences panel change](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/model/executing-tlc.html), [Results page](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/model/results-page.html)
* :white_check_mark: [Font preference for variable stack trace](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/gettingstarted/preferences.html)
* :white_check_mark: [Links to additional options pages, How to run changes](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/model/overview-page.html)
* :white_check_mark: [Name change on the Advanced page, TLC options moved out](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/model/advanced-page.html)
* :white_check_mark: New page for the TLC options section which was on the advanced page
* :white_check_mark: [Reflecting the new two pages, not 3, on a new model](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/model/creating-model.html)
* :white_check_mark: [Updating the Welcome View verbiage concerning the sample spec buttons](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.doc/html/gettingstarted/gettingstarted.html)

**Comment by lemmy** [comment]
- TLCProfiler and coverage+cost related UI
- Load library archives (e.g. [CommunityModules](https://github.com/tlaplus/CommunityModules) in addition to library folders

**Comment by quaeler** [comment]
I believe this issue is done? @lemmy?

**Comment by quaeler** [comment]
@lemmy anything outstanding here still ?

**Comment by lemmy** [comment]
Everything that is no crossed off above in https://github.com/tlaplus/tlaplus/issues/319#issuecomment-499911408
