### ISSUE TITLE
TLA+ Toolbox can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#320]
<img width="1280" alt="Screen Shot 2019-06-09 at 7 07 59 PM" src="https://user-images.githubusercontent.com/88777/59168271-f8576180-8ae9-11e9-9ef7-67bb20c70fc8.png">

1. Locate ```TLA+ Toolbox``` in ```Applications``` folder in ```Finder```
2. ```Control+Right-Click``` > ```Open``` on ```TLA+ Toolbox```
3. The ```TLA+ Toolbox can't be opened because Apple cannot check it for malicious software.``` dialog now has an ```Open``` button which opens the Toolbox
4. From now on the Toolbox can simply be started from the launcher

<img width="1280" alt="Screen Shot 2019-06-09 at 7 09 07 PM" src="https://user-images.githubusercontent.com/88777/59168304-191fb700-8aea-11e9-86f6-b13bee7d2e21.png">

See ["Install an app from an unidentified developer "](https://support.apple.com/en-us/HT202491) section.

**Comment by cartazio** [comment]
same issue here ...

**Comment by lemmy** [comment]
@cartazio Did the steps outlined above solve the issue for you?

**Comment by cartazio** [comment]
ctrl+click then open worked for me

**Comment by bgamari** [comment]
For the record, I have collected some general resources that might be useful for maintainers facing this issue [here](https://gitlab.haskell.org/ghc/ghc/issues/17418).

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/master/general/docs/Notarization_in_macOS.md

**Comment by lemmy** [comment]
```bash
## set password (requested from Apple) to talk to the notarization service
xcrun altool --store-password-in-keychain-item "AC_PASSWORD" -u "apple dev id" -p THEPASSWORDOBTAINEDFROMAPPLE

## Request notarization
xcrun altool --notarize-app --primary-bundle-id "org.lamport.tla.toolbox.product.product" --username "apple dev id" --password "@keychain:AC_PASSWORD" --file TLAToolbox-1.7.0-macosx.cocoa.x86_64.zip

## check status of REQUEST_ID returned by previous step.
xcrun altool --notarization-info REQUEST_ID --username "apple dev id" --password "@keychain:AC_PASSWORD"
```
