### ISSUE TITLE
TLCModelLaunchDataProvider#hasZeroCoverage() provides incorrect results

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#323]
Once a model check has been executed in which zero coverage count was encountered, all subsequent model checks during the Toolbox's lifespan (potentially able to be further restricted to "during the lifespan of the spec being open") will have the instance of `TLCModelLaunchDataProvider` supplied to `modelChanged(...)` methods will continue to return `true` from `hasZeroCoverage().`

**Comment by lemmy** [comment]
Please describe the user visible effect of this.

**Comment by quaeler** [comment]
Per the email yesterday - there is none now.

**Comment by quaeler** [comment]
Addressed with ea18143
