### ISSUE TITLE
Investigate if JNLP web-start of Distributed TLC still works with Java 11

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#330]
https://medium.com/adoptopenjdk/move-over-java-web-start-raise-your-glass-to-icedtea-web-v1-8-1-c0395e9f27

**Comment by quaeler** [comment]
Does not work on macOS.

**Comment by quaeler** [comment]
Attempting with 1.8.3 on macOS with Java 11 runs into a problem seemingly in their code while attempting to display a warning dialog. This issue seems fixable patchable though - will try.

**Comment by quaeler** [comment]
By changing line 56 in the attached class (the class is actually no longer in their GitHub repository so maybe it's on the way out) and adding an export for `java.base/jdk.internal.util.jar` i was able to run a JNLP successfully as this:
```
java --add-exports java.base/jdk.internal.util.jar=ALL-UNNAMED,java.desktop -cp javaws.jar:plugin.jar:jsobject.jar:tagsoup-1.2.1.jar:../../linux-deps-runtime/js.jar net.sourceforge.jnlp.runtime.Boot -Xnofork -nosecurity -jnlp http://localhost:10996/fpset.jnlp
```
[SunMiscLauncher.java.zip](https://github.com/tlaplus/tlaplus/files/3613053/SunMiscLauncher.java.zip)

Do we have usage statistics on how many users use JNLP currently?

**Comment by lemmy** [comment]
No, we don't have stats.  My feeling is that it isn't useful anymore.

What about adding a disclaimer at the top of the jnlp page saying that this is broken and needs a caretaker?

**Comment by quaeler** [comment]
Ok - i'll modify the page - sounds like a good idea.

**Comment by quaeler** [comment]
Master's port 10996 web page content has been updated, as well as help docs and change log, with 8a804af
