### ISSUE TITLE
Toolbox update signed with expired Inria Certificate

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#332]
> Hi,
>
> In the last update of the toolbox the IDE requires me to accept a new certificate for updates (see details below). Is  this certificate trustworthy?
>
> ![pngOc12uTGBdb](https://user-images.githubusercontent.com/88777/60756860-d30a2600-9fb7-11e9-912f-577b86845dab.png)
> ![png0NnvH54vLl](https://user-images.githubusercontent.com/88777/60756864-e6b58c80-9fb7-11e9-8484-22e262fb37af.png)
>
> 
> Best,
> -- raul

see http://discuss.tlapl.us/msg02952.html

**Comment by lemmy** [comment]
@quaeler Do you have time to take a look of what is going on?  If asked Raul for more details but he hasn't responded yet.

**Comment by quaeler** [comment]
I'll look today, though i hope he replies with some useful information.

**Comment by quaeler** [comment]
Aside from the jar signer target, i haven't found where any other assets are being signed. I don't know where the real keystore we use is - if it's the one in the repository, it hasn't been touched in 2 years, which is both later than the expiration date (and so presumably does not contain an already expired certificate, and also therefore hasn't been broken in recent months.)

I see the same thing though if i update to a nightly build (this screen shot as its being done from a 1.5.7 release app).

![Screen Shot 2019-07-06 at 5 16 23 PM](https://user-images.githubusercontent.com/22581048/60762334-3cb71e00-a012-11e9-9a17-151307a6f9fb.png)

**Comment by lemmy** [comment]
https://github.com/lemmy/Pdf4Eclipse/commit/da0e75a3df6edab96204fe535db56f11fcf4bb72

**Comment by lemmy** [comment]
@quaeler Can you check with the newest nightly build again?

**Comment by quaeler** [comment]
I can no longer update at all - after accepting all the licenses and starting the downloads, i eventually receive the following.. (tried deleting the temp directory; tried downloading a new 1.5.7 zip and using that app; ... - no difference.)
![Screen Shot 2019-07-06 at 10 09 50 PM](https://user-images.githubusercontent.com/22581048/60764319-2756e980-a03c-11e9-973c-97d82ada6ff4.png)

**Comment by lemmy** [comment]
Not happening here when I upgrade 1.5.7 to current nightly (Linux).

**Comment by quaeler** [comment]
Still no love this morning on macOS fresh 1.5.7. The file it complains about not being able to delete is 644 owned by me, so i'm not sure what it is really trying to say.
```
An error occurred while uninstalling
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Uninstall, operand=[R]org.eclipse.rcp_root 4.7.3.v20180330-0640 --> null, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction).
Backup of file /private/var/folders/35/ph5gw5n16_162t8yblqd19lw0000gn/T/AppTranslocation/BA6FB6B8-E685-49D3-AC9B-CE97C582F78B/d/TLA+ Toolbox.app/Contents/Eclipse/readme/readme_eclipse.html failed.
File that was copied to backup could not be deleted: /private/var/folders/35/ph5gw5n16_162t8yblqd19lw0000gn/T/AppTranslocation/BA6FB6B8-E685-49D3-AC9B-CE97C582F78B/d/TLA+ Toolbox.app/Contents/Eclipse/readme/readme_eclipse.html
```

```
algebraic:tlaplus loki$ ls "/private/var/folders/35/ph5gw5n16_162t8yblqd19lw0000gn/T/AppTranslocation/BA6FB6B8-E685-49D3-AC9B-CE97C582F78B/d/TLA+ Toolbox.app/Contents/Eclipse/readme/readme_eclipse.html"
-rw-r--r--@ 1 loki  staff  97644 Aug  9  2017 /private/var/folders/35/ph5gw5n16_162t8yblqd19lw0000gn/T/AppTranslocation/BA6FB6B8-E685-49D3-AC9B-CE97C582F78B/d/TLA+ Toolbox.app/Contents/Eclipse/readme/readme_eclipse.html
algebraic:tlaplus loki$ 
```

**Comment by lemmy** [comment]
@quaeler Can you roll-back the install to 1.5.7 or does the update permanently break the Toolbox?

**Comment by quaeler** [comment]
The failed update leaves the 1.5.7 install unaltered.

**Comment by lemmy** [comment]
FWIW: The 1.6.0 build currently hosted as a draft release on Github successfully updates to the latest nightly when the experimental updates flag in the preference is checked.

**Comment by lemmy** [comment]
A 1.5.7 Toolbox update to current 1.6.0 nightly on macOS succeeded for me.  @quaeler Can you try purging ~/.tlaplus/ followed by a fresh 1.5.7 install and 1.6.0 update?

**Comment by quaeler** [comment]
Yes - that works for me.

**Comment by quaeler** [comment]
We should advise people to install anew, though. The update process doesn't seem to do some things like fix the app icon.

**Comment by lemmy** [comment]
Does the app icon alone really warrant a re-install?  The VM e.g. gets correctly switched to the bundled one.

**Comment by quaeler** [comment]
I dunno - you know we differ on thoughts concerning aesthetics :- )   Yes, totally not mission critical - some people will not care, some people will find a generic app icon to be a little schlock-y.

**Comment by lemmy** [comment]
Do you happen to know why it didn't show the new icon?

**Comment by quaeler** [comment]
I don't - it did install the the `.icns` file into the correct place; i am not sure why the app's display in Finder doesn't update.

**Comment by lemmy** [comment]
Might it be possible that it will show the icon after restarting macOS?

**Comment by quaeler** [comment]
Totally plausible that some periodic recaching done by Finder will eventually display the icon - i'll check in with my Finder periodically through the day.

**Comment by lemmy** [comment]
Lets consider the original issue fixed.
