### ISSUE TITLE
Warning to install software from unsigned sources

### ISSUE THREAD

**Issue by raulpardo** [tlaplus/tlaplus#340]
Hi,

In every update the Toolbox requires me to install software from unsigned sources. Below you can find the jars involved when trying to install experimental updates 1.6.0.201907181123 from version 1.6.0.201907102009. I'm running the linux gtk version of the Toolbox on Ubuntu 18.04.

```
Warning: You are installing software that contains unsigned content. The authenticity or validity of this software cannot be established. Do you want to continue with the installation?
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox_1.0.0.201907181123
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.doc_1.6.1.201907181123
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.jclouds_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.jnlp_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.product.standalone_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.rss_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.tool.prover_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.tool.tla2tex_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.tool.tlc_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tla.toolbox.tool.tlc.ui_1.0.0.201907181123.jar
  xxx/tla/toolbox/plugins/org.lamport.tlatools_1.0.0.201907181123
```

**Comment by lemmy** [comment]
The warning seems bogus:

![Screenshot from 2019-07-19 10-26-53](https://user-images.githubusercontent.com/88777/61553664-c18d3900-aa0f-11e9-9923-553ebe9c787b.png)

@raulpardo Can you check that ```Help > About > Installation Details > Plug-ins``` shows similar singing infos for your Toolbox installation?

**Comment by raulpardo** [comment]
It shows exactly the same (just for an older version). Perhaps it is a problem related on my configuration of the Toolbox? Even though I simply unpacked it from the zip file.

![image](https://user-images.githubusercontent.com/8382285/61568603-2bdfc100-aa84-11e9-9dd1-30c1d1505ece.png)

**Comment by lemmy** [comment]
@raulpardo Please clarify what you mean by "unpacked it from a zip".  I thought you would get the error when you update one Toolbox to a newer version with the built-in ```Help > Check for updates```.

**Comment by raulpardo** [comment]
Yes, I get the error when I click on `Help > Check for updates`. What I meant is that, in order to install the Toolbox, I downloaded [this zip file](https://github.com/tlaplus/tlaplus/releases/download/v1.6.0/TLAToolbox-1.6.0-linux.gtk.x86_64.zip) and unpacked it.

**Comment by quaeler** [comment]
I just verified this as well on Ubu1604, downloading the 1.6.0 zip linked above, enabling experimental updates in preferences, doing `Help → Check for Updates`, and selecting the Toolbox update, continuing along i see this:
![Screen Shot 2019-10-25 at 4 23 33 PM](https://user-images.githubusercontent.com/22581048/67609905-201b2f00-f744-11e9-9b65-5c80eba3ce3a.png)
After a restart, indeed none of them are signed:
![160_updates_certs_check](https://user-images.githubusercontent.com/22581048/67610016-d0893300-f744-11e9-9cc0-d9eda11e383b.gif)

**Comment by lemmy** [comment]
@quaeler wrote in an email:

hmm.. so i looked at this.  i think what is most likely happening is that p2 is grabbing the pack’d jar, and that jar is not signed (or is at least no longer signed after being unpacked.) unpacking from command line produces a not-exactly-but-similarly sized jar file in comparison to the jar downloaded into the toolbox plugins directory - i’m not sure what explains the non-exact-ness..

thoughts?

the below starts from the toolbox’s plugins directory after p2 has downloaded the updated toolbox plugins but not yet ‘installed’ them (done while the signed content dialog is being displayed in Toolbox)

loki@pere-ubu:~/Downloads/toolbox/plugins$ jarsigner -verify org.lamport.tla.toolbox.editor.basic_1.0.0.201907102009.jar 

jar verified.
loki@pere-ubu:~/Downloads/toolbox/plugins$ jarsigner -verify org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar 

jar is unsigned.
loki@pere-ubu:~/Downloads/toolbox/plugins$ cksum org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
3194040047 355195 org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
loki@pere-ubu:~/Downloads/toolbox/plugins$ pushd /tmp
/tmp ~/Downloads/toolbox/plugins
loki@pere-ubu:/tmp$ wget http://lamport.org/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
--2020-01-29 13:14:34--  http://lamport.org/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
Resolving lamport.org (lamport.org)... 205.233.73.65
Connecting to lamport.org (lamport.org)|205.233.73.65|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://tla.msr-inria.inria.fr/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar [following]
--2020-01-29 13:14:35--  http://tla.msr-inria.inria.fr/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
Resolving tla.msr-inria.inria.fr (tla.msr-inria.inria.fr)... 193.55.250.165
Connecting to tla.msr-inria.inria.fr (tla.msr-inria.inria.fr)|193.55.250.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 382852 (374K) [application/java-archive]
Saving to: ‘org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar’

org.lamport.tla.toolbox.editor.basic_1.0. 100%[====================================================================================>] 373.88K   476KB/s    in 0.8s    

2020-01-29 13:14:36 (476 KB/s) - ‘org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar’ saved [382852/382852]

loki@pere-ubu:/tmp$ jarsigner -verify org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar 

jar verified.
loki@pere-ubu:/tmp$ cksum org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
1569664483 382852 org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
loki@pere-ubu:/tmp$ mkdir tmp2
loki@pere-ubu:/tmp$ cd tmp2
loki@pere-ubu:/tmp/tmp2$ wget http://lamport.org/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz
--2020-01-29 13:15:02--  http://lamport.org/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz
Resolving lamport.org (lamport.org)... 205.233.73.65
Connecting to lamport.org (lamport.org)|205.233.73.65|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://tla.msr-inria.inria.fr/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz [following]
--2020-01-29 13:15:02--  http://tla.msr-inria.inria.fr/tlatoolbox/ci/toolboxUpdate/plugins/org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz
Resolving tla.msr-inria.inria.fr (tla.msr-inria.inria.fr)... 193.55.250.165
Connecting to tla.msr-inria.inria.fr (tla.msr-inria.inria.fr)|193.55.250.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 120020 (117K) [application/x-gzip]
Saving to: ‘org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz’

org.lamport.tla.toolbox.editor.basic_1.0. 100%[====================================================================================>] 117.21K   246KB/s    in 0.5s    

2020-01-29 13:15:03 (246 KB/s) - ‘org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz’ saved [120020/120020]

loki@pere-ubu:/tmp/tmp2$ unpack200 org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar.pack.gz org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
loki@pere-ubu:/tmp/tmp2$ jarsigner -verify org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar 

jar is unsigned.
loki@pere-ubu:/tmp/tmp2$ cksum org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
2265373241 354860 org.lamport.tla.toolbox.editor.basic_1.0.0.202001291810.jar
loki@pere-ubu:/tmp/tmp2$

**Comment by lemmy** [comment]
Fix confirmed by updated to latest nightly.
