### ISSUE TITLE
1.6.0 Known Issues

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#341]
- [x] Table column & cell highlighting on ```Model Checking Results``` page does not work on Windows 10 (see upstream bug [Eclipse 536621](https://bugs.eclipse.org/536621))
   - ```State space progress``` no longer highlights (red) a non-zero ```Queue Size``` to warn about incomplete state space exploration
   - Action statistics for an action with zero states and zero distinct states are not highlighted yellow
- [x] ```Never Share Executions Statistics``` button is initially disabled
  In order to permanently silence the dialog that asks users to opt-in to execution statistics, a user has to opt-in once followed by an opt-out (Help > Opt In/Out Execution Statistics). No statistics are shared unless TLC is run between opt-in and opt-out. (https://github.com/tlaplus/tlaplus/commit/7ce413c801ac92d230c38e17bf449be857bbb96d)

- [x] Double-clicking a row in the Action statistics table does not jump to the Location shown in the table if an action consists of two or more disjuncts. Instead the Toolbox jumps to the left-hand side/the name of the action. (https://github.com/tlaplus/tlaplus/commit/4d96ff086f43dae29420fd4c8119ee8163e99a9c)

- [x] Existing model no longer opens after spec rename. #339

- [x] The License file at the root of the released tla2tools.jar is outdated and should be replaced with an MIT license file.

- [x] Improve the locating of, and setting of custom locations for, `tlapm` - [covered by 345](https://github.com/tlaplus/tlaplus/issues/345)

**Comment by lemmy** [comment]
@quaeler FYI

**Comment by lemmy** [comment]
@quaeler I checked on Windows and the Toolbox gets a Color instance for SWT.Color_Yellow.  However, the background on the sub-actions table on the result page doesn't get highlighted. Any ideas?

**Comment by quaeler** [comment]
Historically i've run afoul of some quirks with Windows' SWT table implementation - and a quick google of this situation turns up some tenuously themed bugs filed at eclipse.org - but i don't know of and strategy without some more digging.

**Comment by lemmy** [comment]
IIRC it worked correctly in 1.5.7

**Comment by quaeler** [comment]
I have that feeling too... maybe something about the layout changes.. ? Seems weird that layout would impact that, but it is SWT after all.

**Comment by lemmy** [comment]
https://bugs.eclipse.org/536621 is addressed by bumping the target platform to:

```
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
<unit id="org.eclipse.help.feature.group" version="2.2.600.v20190605-1800"/>
<unit id="org.eclipse.equinox.core.sdk.feature.group" version="3.18.0.v20190517-1309"/>
<unit id="org.eclipse.platform.feature.group" version="4.12.0.v20190605-1801"/>
<unit id="org.eclipse.rcp.configuration.feature.group" version="1.1.500.v20190605-1800"/>
<unit id="org.eclipse.emf.ecore.feature.group" version="2.18.0.v20190528-0845"/>
<unit id="org.eclipse.equinox.executable" version="3.8.400.v20190515-0925"/>
<unit id="org.eclipse.ecf.core.feature.feature.group" version="1.5.3.v20190423-0625"/>
<unit id="org.eclipse.e4.rcp.feature.group" version="1.6.500.v20190605-1801"/>
<unit id="org.eclipse.emf.common.feature.group" version="2.16.0.v20190528-0845"/>
<unit id="org.eclipse.equinox.sdk.feature.group" version="3.18.0.v20190528-1257"/>
<unit id="org.eclipse.core.runtime.feature.feature.group" version="1.2.500.v20190518-1240"/>
<unit id="org.eclipse.jdt.feature.group" version="3.18.0.v20190605-1800"/>
<unit id="org.eclipse.pde.source.feature.group" version="3.14.0.v20190605-1800"/>
<repository id="eclipse" location="http://download.eclipse.org/eclipse/updates/4.12/R-4.12-201906051800/"/>
</location>
```

**Comment by quaeler** [comment]
@lemmy assigning an icon to a cell still renders in win10 - perhaps we could use an icon instead of background coloring?

**Comment by lemmy** [comment]
@quaeler Good idea, that should work.  However, lets wait if we run into more reasons to upgrade to a newer Eclipse foundation first.

**Comment by lemmy** [comment]
Upstream fix has just been deferred until Eclipse Platform SWT 4.14.
