### ISSUE TITLE
Deleting a model snapshot results in NullPointerException

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#343]
I am using Version 1.6.0 of 10 July 2019 of Toolbox on Windows 10, and when I deleted a model snapshot it was deleted successfully but the corresponding GUI item remained (with no text) and clicking on it resulted in NullPointerException.

**Comment by lemmy** [comment]
Thanks for the report. Can you please attach the corresponding stacktrace that is found in ~/.tlaplus/. metadata/.log?

**Comment by AmirHossein-SayyadAbdi** [comment]
Sure, but sorry I cannot find this log file! As I mentioned before I am using the toolbox on Windows.

**Comment by lemmy** [comment]
The ``` .log```  file is in the ```.tlaplus/.metadata/``` folder in your home directory.  On Windows, you can find out where your home directory is located, by entering the command echo ```%SYSTEMDRIVE%%HOMEPATH%``` in Command Prompt. (The log contains enough timestamped entries for you to figure out what part of it relates to the problem you are reporting.)  

From https://tla.msr-inria.inria.fr/tlatoolbox/doc/trouble/trouble.html#reporting

**Comment by AmirHossein-SayyadAbdi** [comment]
Thanks for the instructions on finding the log file.

This is the major error:
!MESSAGE Launch configuration SpecName___Model_1_SnapShot_1558107284052 at file:/TLA_SPECS_PAH/SpecName.toolbox/SpecName___Model_1_SnapShot_1558107284052.launch does not exist.

It is obvious that when I delete a model snapshot it will be deleted successfully, but its GUI element does not get deleted. And this is why clicking on it will result in Null exception.

**Comment by quaeler** [comment]
I cannot replicate this on either macOS or Win10, with 1.6.0 release, deleting either successful or erred snapshots.
Could you give some more guidance as to how to replicate this?

**Comment by AmirHossein-SayyadAbdi** [comment]
I was able to reproduce the issue this way:
1- Created a new spec and let its content be the same spec as TCommit [1].
2- Created a model and set the initial state as TCInit and set the next state as TCNext.
3- I Ran TLC.
4- Deleted the currently generated model snapshot.

Then there was a GUI element that is empty and when I click on it the result is NullPointerException.

[1] https://github.com/tlaplus/Examples/blob/master/specifications/transaction_commit/TCommit.tla

**Comment by quaeler** [comment]
Hmm... i'm at a loss. This works correctly on both platforms for me. In your step 4, are you using the context menu like this: (the dialog pane occurs out of capture view)
![343_delete_context](https://user-images.githubusercontent.com/22581048/62837923-2fe9a380-bc2a-11e9-9c3c-e995af491c7d.gif)

... and are you saying that the "Model_1" in your tree view still has an expansion chevron next to it (the 'v') but there is no text below that?

**Comment by AmirHossein-SayyadAbdi** [comment]
It is possible that the error is not producible in all specs, because I remember deleting a model snapshot correctly as well.

It my step 4 when I right click on the snapshot and select "delete" and I confirm, the GUI element (that has Aug 11 2019 text in your GIF) will remain but its text will be cleared. And clicking on it will result in NullPointerException.

**Comment by quaeler** [comment]
When you say that 'the GUI element remains' - do you mean that you still see the icon on the left side (but no longer the accompanying date-time text)?

**Comment by AmirHossein-SayyadAbdi** [comment]
This is strange, because yesterday I was able to reproduce the error and today I am not.

But what I meant is that after I deleted the snapshot, the icon ![1](https://user-images.githubusercontent.com/24325657/62848073-f9c22780-bcee-11e9-890f-77fa037ca248.png) still remained with no text.
It was empty and clicking on it resulted in NullPointerException.

**Comment by quaeler** [comment]
Are you saving to a network mounted drive (or is this happening when your machine is under heavy load from a parallel running process?)

**Comment by AmirHossein-SayyadAbdi** [comment]
No I am saving it on my own hard drive locally, and the system was not under such a heavy load either.

**Comment by lemmy** [comment]
@quaeler Check the git history of IIRC ToolboxExplorer.  I attempted to fix a race condition related to deletion in the past.

**Comment by lemmy** [comment]
Please reopen if this remains an issue.
