### ISSUE TITLE
Improve TLAPS integration in the Toolbox

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#345]
The toolbox relies on `tlapm` existing either in `/usr/local/bin` on the default PATH as understood by the Toolbox at launch time. This is inconvenient for users who do not want to install it in a specific location, and who's system default PATH does not incorporate the install directory.
To address this we should:
* Create a preference pane item allowing the user to specify the location of the `tlapm` executable
* Create unit tests for the preference pane, launching it, and the enabled states of the context menu items dependent on its presence

**Comment by quaeler** [comment]
Last touches in with fdf663a

**Comment by lemmy** [comment]
My Toolbox (Linux) no longer detects TLAPS installed to ```/usr/local/lib/tlapls``` automatically.

![image](https://user-images.githubusercontent.com/88777/64291848-eedd6a00-cf1d-11e9-9b36-f55a30f95f22.png)

**Comment by quaeler** [comment]
It never looked in `lib` though... https://github.com/tlaplus/tlaplus/commit/3bb3aeb840cc25929e2d62926705b01ee6041809#diff-c8b4173ac254955f19a58c7618a5c5d6L56

**Comment by lemmy** [comment]
It seems I managed to mess up my TLAPS installation.
