### ISSUE TITLE
Deleting Two Specs Simultaneously

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#346]
I am using Version 1.6.0 of 10 July 2019 of Toolbox on Windows 10.

I selected two specs in the Spec Explorer, one of which was open. I then right-clicked on one of the two specs and then I selected Delete. This resulted in the open spec to be deleted, but the closed spec prompted a confirm dialog to be "forgotten" instead of deletion.

There was no errors or exceptions.

**Comment by quaeler** [comment]
I attempted to replicate this on both Win10 and macOS and on both platforms i received a dialog for each specification as i would expect. ("Forgotten" is indeed the dialog verbiage intended to be shown during the delete action. The Toolbox-specific content (model files including snapshots) is deleted from the file system, the `.tla` files are not.)

Could you provide more specific reproduction steps? For example, in my attempt to replicate, i:
1. Launched the Toolbox
2. Added a new spec named "SpecEins"
3. Added another new spec named "SpecZwei"
4. In Spec Explorer i clicked on SpecEins, then on SpecZwei while holding down the SHIFT key.
5. I right clicked on SpecZwei and chose Delete in the context menu.
6. I clicked Yes on the dialog i received concerning SpecEins.
7. I clicked Yes on the dialog i next received concerning SpecZwei.
8. I noted both specifications were no longer listed in the Spec Explorer.

**Comment by AmirHossein-SayyadAbdi** [comment]
I agree.
The issue is resolved.
Thanks.
