### ISSUE TITLE
print module in ASCII from TLA+ Toolbox

### ISSUE THREAD

**Issue by keepsimple1** [tlaplus/tlaplus#347]
This is an enhancement feature request to:

- support printing a module (as to a printer) in ASCII (i.e. not the pretty-printer) from TLA+ Toolbox. 

It was brought up in https://groups.google.com/forum/#!topic/tlaplus/DNmoXn3HWO0 . Thanks.

**Comment by lemmy** [comment]
FWIW: With the spec editor having focus, pressing Ctrl+P opens the OS's print dialog on Linux.

**Comment by keepsimple1** [comment]
Thanks.  Adding a menu item for Print will be nice,  otherwise I will use Ctrl+P workaround or a different editor.

**Comment by lemmy** [comment]
Workaround appears good enough.
