### ISSUE TITLE
Cannot open a tla file

### ISSUE THREAD

**Issue by introom** [tlaplus/tlaplus#350]
The window rendering is weird.

I am using i3wm.

The screenshots are:
![image](https://user-images.githubusercontent.com/669045/62871190-99ae9e00-bd4d-11e9-9c60-923eb2d655b4.png)

and then click the browse button,  we then get this:
![image](https://user-images.githubusercontent.com/669045/62871222-ac28d780-bd4d-11e9-808f-3a8ec9bd97bb.png)
Just a blank white popup, i can choose the file from nowhere.

**Comment by lemmy** [comment]
@introom This looks like an SWT deficiency to me.  Have you checked [Bugzilla](https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse&component=SWT&list_id=18890152&product=Platform&query_format=advanced) at eclipse.org?

**Comment by introom** [comment]
https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse&component=SWT&list_id=18890152&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&product=Platform&query_format=advanced

Too many issues, not sure which one is pertinent.

**Comment by decanus** [comment]
I am experiencing this issue on mac too, @introom did you find a workaround?

**Comment by decanus** [comment]
@introom I have found the way to open a file, its pretty nontrivial. What you do is you select your root module, type the file name a prompt will show. Click on replace and it will just open the file.

**Comment by lemmy** [comment]
@decanus Are you on i3wm?

**Comment by decanus** [comment]
@lemmy nope, OS X

**Comment by lemmy** [comment]
@quaeler Can you please check if things have changed since I last looked into it?

**Comment by quaeler** [comment]
Have tried with last night's nightly build on both Mojave and Catalina, but it operates as expected.

What version of the Toolbox and what version of OS X, @decanus ?

**Comment by decanus** [comment]
Mac OS X: 10.15.1
TLA Toolbox: 1.6.0

So opening a file works, its just awfully unintuitive because I need to go through the process like I would create a new file, a prompt then asks me if I would like to replace the existing files and when I hit replace it opens @quaeler.

**Comment by quaeler** [comment]
I'm confused - so you're not experiencing this issue at all?

**Comment by decanus** [comment]
No, @quaeler. I am not. I previously thought I was.

**Comment by quaeler** [comment]
@decanus it sounds like it is related to this https://github.com/tlaplus/tlaplus/issues/114 maybe.

**Comment by lemmy** [comment]
Please reopen if this remains an issue (with latest and greatest).

**Comment by keepsimple1** [comment]
Can I propose to re-open this issue? I am using the latest version 1.7.1 on macOS and have the same problem:

The steps of opening an existing ".tla" file is very, very confusing.

**Comment by lemmy** [comment]
@keepsimple1 Can you provide a patch/PR?
