### ISSUE TITLE
Feature Request: PlusCal macros shouldn't need to be assignments

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#353]
Sometimes we have to write something like 

```tla
define
  LeftFork(p) == p
  RightFork(p) == IF p = NP THEN 1 ELSE p + 1

  HeldForks(p) ==
    { x \in {LeftFork(p), RightFork(p)}: forks[x] = p}
end define;
\* ...

process philosopher \in 1..NP
variables hungry = TRUE;
begin P:
  while hungry do
    either
      with fork \in AvailableForks(self) do
        forks[fork] := self;
      end with;
```

It would be nice if we could instead write

```tla
macro left_fork() {self}

macro right_fork() {IF self = NP THEN 1 ELSE self + 1}

macro held_forks() {
   { x \in {left_fork(), right_fork()}: forks[x] = self}
}
\* ...
      with fork \in available_forks() do
        forks[fork] := self;
      end with;
```

This currently doesn't work because all PlusCal macros must be an assignment, so we can't use them as fragments of expressions.

**Comment by dricketts** [comment]
I believe this feature would also allow one to sidestep the issue with definitions described in this issue: https://github.com/tlaplus/tlaplus/issues/338. One could use macros instead of definitions, and since macros are expanded, PlusCal would put primes on variables hidden behind macros.

**Comment by lemmy** [comment]
@hwayne Has anybody checked what the rational was to restrict macros to assignments?

**Comment by hwayne** [comment]
I've searched and can't find anything written down about this. Lamport might know why the restriction

**Comment by lemmy** [comment]
PCal lang spec: https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/pcal/Pcal.tla

**Comment by lemmy** [comment]
Please reopen once the proposed language change has received its blessing.
