### ISSUE TITLE
Disjunct of negated eventually predicates blows up liveness tableau

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#354]
**Setup:** Given spec

```tla
EXTENDS Integers, TLC, Sequences
VARIABLES x

Init == x = 0
Next == x' = (x + 1) % 2
Spec == Init /\ [][Next]_x

LivenessA == \E y \in 0..4: ~<>(x=1)
LivenessB == \E y \in 0..8: ~<>(x=1)
```
Model check both liveness properties in separate model runs.

**Expected:** Runtime checking should be similar (within an order of magnitude) timeframe.

**Actual:** Runtime blowup is exponential.

**Comment by lemmy** [comment]
@hwayne Has this blowup originally occurred in a real-world spec?  If yes, can you share it too?

**Comment by lemmy** [comment]
```\E y \in 0..4: ~<>(x=1)``` can be rewritten as ```~<>(x=1) \/ ~<>(x=1) \/ ~<>(x=1) \/ ~<>(x=1) \/ ~<>(x=1)```
