### ISSUE TITLE
PlusCal transpiler hangs on parsing an incorrect label

### ISSUE THREAD

**Issue by alygin** [tlaplus/tlaplus#358]
PlusCal transpiler hangs (with 100% CPU utilisation) when parsing an algorithm with two colons after a label. The simplest file to reproduce:

```
---- MODULE hang ----
(*--algorithm hang
begin
    A::
        skip;
end algorithm; *)
====
```

It doesn't hang if `skip;` is on the same line as the label.

Setup: Toolbox 1.6.0, PlusCal 1.9, MacOS Mojave 10.14.5.
Can also be reproduced when running pcal from the command line.

**Comment by lemmy** [comment]
Already present in v1.4.8 (likely even older versions).

**Comment by lemmy** [comment]
A whitespace after `A::` no longer hangs the translator.
