### ISSUE TITLE
Using MacOS Preview for state graph visualization

### ISSUE THREAD

**Issue by mmxmb** [tlaplus/tlaplus#359]
I am having problems using MacOS preview for state graph visualization. 

When running TLC on a model with state graph visualization enabled, I see the message `AdobePDFViewer cannot find a compatible Adobe Acrobat or Adobe Reader to view this PDF. Please select one.`

Is it possible to use Preview or at least save state graphs as PDFs? I really don't want to use Adobe.

I also found [this mention](https://github.com/tlaplus/tlaplus/blob/e7e678c5d3f7b8dbf239d18363a0f3432836793f/general/docs/microsoft-release.txt#L215) of Preview, but it doesn't make much sense to me since the explanation is very limited.

**Comment by lemmy** [comment]
Sounds similar to https://github.com/tlaplus/tlaplus/issues/357#issuecomment-527543219

**Comment by quaeler** [comment]
Addressed with 71f9048
