### ISSUE TITLE
Show/hide unmodified variables in error trace

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#360]
Akin to #274 implement the ability to hide variables which are unmodified. There's actually two permutations of this i could imagine; given a variable X which is changed in frame 2 and 3, but not in frame 4 and 5, then hide could:
* not show X in frames 1, 4, and 5, but do show it in frames 2 and 3
* show X in all frames

**Comment by quaeler** [comment]
Addressed with 9291f2e - please re-open if insufficient.

**Comment by lemmy** [comment]
Please capture a screencast.

**Comment by quaeler** [comment]
Screencast added with e6fbe01
