### ISSUE TITLE
Add the ability to run a single, specified unit test from the command line for tlatools

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#363]
For some TLA+ Tools development workflows (e.g. working on TLC itself), it can be useful to have the ability to run a single unit test from the command line as opposed to running it from inside the Eclipse IDE interface. Currently the custom Ant buildfile only supports running an entire suite of tests. 

This should be possible by modifying the `test` target inside the existing `customBuild.xml`. Or we could consider adding a new, dedicated target i.e. `test-single`. Right now you can run a single test by manually modifying this [line](https://github.com/tlaplus/tlaplus/blob/eb42f9ed462782c1577ec7433a993b770959437e/tlatools/customBuild.xml#L372) (see related [comment](https://github.com/tlaplus/tlaplus/issues/147#issuecomment-407468541)). For example, you could change it to something like

```
<include name="**/BitVectorTest.java" />
```
to run `tlc2.util.BitVectorTest`. Presumably this include statement could be parameterized on a property passed to Ant. For example:

```
<include name="**/${test.test}.java" />
```

So you could then run a specific unit test (or a set of tests that match a regex) with a command like:

```
ant -Dtest.test="BakeryTest" -f customBuild.xml compile-test test
```

**Comment by lemmy** [comment]
@will62794 http://ekstazi.org/ might be worth looking at to reduce testing time.
