### ISSUE TITLE
Can tlc track a specified error trace?

### ISSUE THREAD

**Issue by Starydark** [tlaplus/tlaplus#365]
While checking a specification using tlc, I can deduce an error trace manually, but the trace is so long that tlc need too much time to explore. So can tlc choose the next step manually to get the specified error trace?

**Comment by lemmy** [comment]
Lets consider the following spec whose state space has 100 distinct states:

```tla
EXTENDS Naturals
VARIABLES x, y

Init == x = 1 /\ y = 1 

A == x' \in 1..10 /\ UNCHANGED y

B == y' \in 1..10 /\ UNCHANGED x

Next == A \/ B

============
```

You can force TLC to explore a subset of the state space by specifying a "State Constraint" on the ```Spec Options``` page of the Model:

```tla
\/ /\ x = 1
   /\ y = 1
\/ /\ x = 2
   /\ y = 1
\/ /\ x = 3
   /\ y = 1
\/ /\ x = 4
   /\ y = 1
\/ /\ x = 4
   /\ y = 1
\/ /\ x = 5
   /\ y = 1
\/ /\ x = 6
   /\ y = 1
\/ /\ x = 7
   /\ y = 1
\/ /\ x = 8
   /\ y = 1
\/ /\ x = 9
   /\ y = 1
\/ /\ x = 10
   /\ y = 1
```

**Comment by Starydark** [comment]
Thanks for your reply. Specifying a "State Constraint" may reduce states, but sometimes it's hard to specify it, such as the executing of A A A B B A B B B...
If I want to develop a function  of tracking a specified error trace by meaning of selecting the next action one by one, is this very hard to implement? And I'm not very familiar with the structure of this project at present, could you please give me some help?

**Comment by lemmy** [comment]
Use the following "Action Constraint":

```tla
<<A,A,A,B,B,A,B,B,B>>[TLCGet("level")]
```
