### ISSUE TITLE
Opening a new spec while the current spec has unsaved changes

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#366]
I am using version "1.6.0 of 10 July 2019" of the toolbox on Windows 10.
When I have unsaved changes in a currently open module of a spec, if I double-click on another spec a dialog prompts and says if I want to save the changes to my current module or not. If I click "cancel" then the changes will not be saved and yet the other spec I double-clicked on gets opened while the unsaved old spec is still open in the editor too.
This should not happen because when I choose "cancel" the operation of opening a new spec should be canceled.

**Comment by quaeler** [comment]
Addressed with 5be659a
