### ISSUE TITLE
Document possible TLCGet parameters

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#368]
The github wiki is one possible place to document this, or the TLC module itself.

**Comment by lemmy** [comment]
Lets not use the wiki because it will be lost should we migrate away from Github.

**Comment by lemmy** [comment]
@ahelwer Can you take this?

**Comment by ahelwer** [comment]
Where should I document them, and where is the existing list of parameters which are supported?

**Comment by lemmy** [comment]
I would say it is best documented as part of the operators documentation in the standard module: https://github.com/tlaplus/tlaplus/blob/3014894545c54dee787d575c3070021801183eed/tlatools/src/tla2sany/StandardModules/TLC.tla#L28-L60

The existing list of parameters can be found at: https://github.com/tlaplus/tlaplus/blob/3014894545c54dee787d575c3070021801183eed/tlatools/src/tlc2/module/TLC.java#L169-L227

**Comment by ahelwer** [comment]
Is it correct to say that "level" is the depth from the starting state of the state from which TLCGet is called? And "diameter" is the maximum depth reached? Does depth start counting from 0 or 1?

**Comment by lemmy** [comment]
* "level" is the distance (number of transitions) from the current state (in which TLCGet is evaluated) to the behavior's initial state (local property) => initial states have level 0
* "diameter" is the longest behavior found so far by model checking (global property of the state space exploration) => initial states have diameter 1

**Comment by lemmy** [comment]
This discussion revealed a bug in the impl of "level": https://github.com/tlaplus/tlaplus/blob/c70ce6a6d2f1a5e90062707ae87ab8e5b5218275/tlatools/src/tlc2/module/TLC.java#L222-L224  and https://github.com/tlaplus/tlaplus/blob/c70ce6a6d2f1a5e90062707ae87ab8e5b5218275/tlatools/src/tlc2/tool/TLCState.java#L26

I will fix the bug.
