### ISSUE TITLE
Error-Trace shows bogus values

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#372]
Commit d6886b5fa0789a9b0b66fdc07cedf244de9d4e0f (identified with git bisect) introduced a regression:  Depending on which variable in the tree gets expanded the first, the same variable in the other states will show identical values (see screenshot).

![Screenshot from 2019-10-04 21-01-18](https://user-images.githubusercontent.com/88777/66249658-b29f5400-e6eb-11e9-9f49-7a2835bf3412.png)

**Comment by quaeler** [comment]
Addressed with a3c4329

**Comment by lemmy** [comment]
@quaeler Given the importance of the trace explorer, I feel this should be covered by a test.  Can you please add an RCPTT or Plug-in test (whatever makes sense)  that would detect such a regression in the future?

**Comment by quaeler** [comment]
Yes - this seems like a sane thing to introduce.

**Comment by quaeler** [comment]
RCPTT introduced with d80cf98
