### ISSUE TITLE
Creating a new spec

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#373]
I am using toolbox version 1.6.0 of 10 July 2019 on Linux Mint 19. There are two issues.

First, I could not create a new spec using the toolbox, because the prompted dialog for choosing a new file requires the file to preexist. So I had to create a new tla file and choose it in the "Open root file" dialog.

Second issue is that while a dialog is open (for example for choosing the root module file), then if the dialog for sharing TLC execution stats appears, then no button on the TLC execution stats actually works.

**Comment by lemmy** [comment]
Can you attach a screenshot of the second issue?

**Comment by AmirHossein-SayyadAbdi** [comment]
Here is the screenshot
![Screenshot from 2019-10-05 18-22-30](https://user-images.githubusercontent.com/24325657/66256676-36fddf80-e79d-11e9-8c3b-41ac861a0fbb.png)

In order to reproduce it, simply click on help->Opt In/Out Execution Statistics. Then try to create a new spec and the issue rises.

**Comment by AmirHossein-SayyadAbdi** [comment]
There is a third issue as well, and I remember having the same issue on windows as well.

When we scroll down in the "Model Overview" page then the configurations get tampered with without our intention.

For example, I mean a simple scroll down causes the "System resources dedicated to TLC" to change to "Minimal".

**Comment by lemmy** [comment]
About the buttons on the execution statistics dialog: from the screenshot it appears as if the left two buttons are enabled (rightmost is disabled to indicate that you are currently opt-out).  Is it possible that the new spec wizard blocks input for the execution statistics dialog?

**Comment by AmirHossein-SayyadAbdi** [comment]
No, in fact the two enabled buttons are actually clickable too.

I clicked on them (also on the close x button) but none worked.

**Comment by lemmy** [comment]
And this behavior persists when the new spec dialog is *not* simultaneously open?

**Comment by AmirHossein-SayyadAbdi** [comment]
Sorry, I edited my last comment.

**Comment by AmirHossein-SayyadAbdi** [comment]
> And this behavior persists when the new spec dialog is _not_ simultaneously open?

It was fine when the new spec dialog was not simultaneously open.

**Comment by lemmy** [comment]
May I assume that https://github.com/tlaplus/tlaplus/issues/135 captures the main issue of this ticket?

**Comment by AmirHossein-SayyadAbdi** [comment]
> May I assume that #135 captures the main issue of this ticket?

True, it does.
I feel that the new spec dialog should be able to create a file, just as it does on Windows. I mean from a user experience point of view, it is important. Because last time I had to create a new .tla file manually and then I selected that file.

Suggestion: perhaps it would be nice to opt for a "home directory" on toolbox startup? Just like Eclipse asks for the first time to specify a home directory.

**Comment by lemmy** [comment]
@AmirHossein-SayyadAbdi Please note that you can simply type the path and name of the new spec into the new spec dialog and the (spec) file will be automatically created.  It is just a limitation of the (native) OS file chooser dialog that one cannot create a file there.

**Comment by AmirHossein-SayyadAbdi** [comment]
True.
Perhaps there is some way to enable the new spec dialog to create the spec file too. It is unlikely that Java GUI on Linux would not permit the file chooser to create a new file!

There is also a third issue that I have ran into on both Linux Mint 19 and Windows 10. When I scroll down on the "Model Overview" page, the TLC configurations change without any intention.
For example, the ComboBox that chooses the resources assigned to TLC which includes "minimal" or "custom" changes unnecessarily.

**Comment by lemmy** [comment]
I'm pretty sure I looked into this before and it wasn't a five minute thing (I'm a Linux user myself and would very much like this fixed).

About the scroll issue:. I assume the combo has focus by default.  I don't know how SWT determines focus or if the toolbox focuses the combo by default. In case of the latter, we can probably just not select the combo.

**Comment by AmirHossein-SayyadAbdi** [comment]
I understand, thank you.
Shall I close the issue, or leave it open for perhaps future consideration?

**Comment by lemmy** [comment]
@quaeler Can you have a quick look WRT the scroll issue?

**Comment by quaeler** [comment]
By default the "How to run?" section is collapsed, so the TLC resources combobox within it could not have focus.
The first item to take focus on the "Model Overview" tab is the error/warning hyperlink (on macOS and Windows - does not seem to happen on Ubu1804,) if one exists, followed by the Model description text box, and thereafter elements in a top-to-bottom, left-to-right, progression.

Expanding the "How to run?" section, the combobox does not retain focus on either Windows or macOS; on Ubu1804, it is rendered as though it has focus, though scrolling with my scroll wheel does not affect its selection (perhaps this a VMWare issue though?)
If anything, i would say that the Windows and macOS versions **should** capture focus and all platforms should change value with scroll wheel input, in the name of 'accessibility.'

**Comment by AmirHossein-SayyadAbdi** [comment]
@lemmy @quaeler I think the scroll issue was a transient error that happened, because today I was not able to reproduce it.
