### ISSUE TITLE
tlc command-line option to specify library paths

### ISSUE THREAD

**Issue by ajdavis** [tlaplus/tlaplus#374]
Hello, the TLA+ Toolbox GUI offers configurable library search paths:

![image](https://user-images.githubusercontent.com/84101/66680658-00addd80-ec3f-11e9-85cd-898024c477fa.png)

It would be nice if I could specify library paths to the tlc command-line tool.

My current workaround is to copy all the modules that my spec needs into the current directory before running tlc.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/2796d934402090edb4be18bd860c90e66b468a20/tlatools/src/util/SimpleFilenameToStream.java#L33

**Comment by ajdavis** [comment]
Thanks, how would I use that? I'm guessing `java -DTLA-Library=/path/to/libraries ...`?

**Comment by dvc94ch** [comment]
This would be really useful. An environment variable could also work.

**Comment by dvc94ch** [comment]
This works for me: `TLA_JAVA_OPTS="-DTLA-Library=../utils" tlc Example.tla`, it should probably be documented somewhere.

**Comment by dvc94ch** [comment]
Interestingly this does not: `TLA_JAVA_OPTS="-DTLA-Library=utils" tlc examples/Example.tla`

**Comment by dvc94ch** [comment]
So added a script that may be of some use to people, this currently fits my requirements
```python
#!/usr/bin/env python3

import argparse
import pathlib
import os
import sys

parser = argparse.ArgumentParser(description='tlc wrapper')
parser.add_argument('module', type=str, help='the module to check')
args = parser.parse_args()

root = os.getcwd()
libraries = []
modules = {}
tla_java_opts = '-DTLA-Library='

for file in pathlib.Path(root).rglob('*.tla'):
    lib = os.path.dirname(file)
    if not lib in libraries:
        libraries.append(lib)
        tla_java_opts += lib + ':'

for file in pathlib.Path(root).rglob('*.cfg'):
    mod = os.path.basename(file)[:-4]
    modules[mod] = os.path.dirname(file)

if not args.module in modules:
    print('module not found')
    print(list(modules.keys()))
    sys.exit()
    
wdir = modules[args.module]
cmd = 'tlc ' + args.module + '.tla'

os.environ['TLA_JAVA_OPTS'] = tla_java_opts
os.chdir(wdir)
os.system(cmd)
```

**Comment by lemmy** [comment]
I'm all in favor of [adding a proper "-help" command](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/TLC.java) to document command-line parameters and environment variables (the latter of which still have to be added).  Any takers?  However, we don't have the bandwidth to maintain wrapper scripts.  Please lets push the functionality into the Java code-base.
