### ISSUE TITLE
Deleting a spec that has unsaved changes

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#375]
Hi,
I am using Toolbox version 1.6.0 of 10 July 2019 on Linux Mint, and I just happened to experience this error.
I created an entirely new spec (by using "Add New Spec") and I typed a few letters in the newly opened .tla file.
I then deleted the entire spec, and when Toolbox prompted to "save the changes or not", I clicked "cancel" button and the spec was deleted successfully, then I opened an already existing spec. I finally closed the Toolbox.

I then deleted the deleted spec's .tla file using Linux cmd line. After that when I opened the Toolbox, the following error was shown: "Failed to create part's controls".

A screenshot of the error:
![Screenshot from 2019-10-12 11-26-16](https://user-images.githubusercontent.com/24325657/66697586-d6622b80-ece3-11e9-8b44-86a7e28f092c.png)
And its error trace:
[error trace.txt](https://github.com/tlaplus/tlaplus/files/3720353/error.trace.txt)

**Comment by quaeler** [comment]
Clicking on cancel should have halted the deletion process; i'll address that.

Deleting filesystem assets from 'behind Eclipse/Toolbox's back' is "expected" to cause problems like the part creation exception seen.

**Comment by quaeler** [comment]
Addressed with 02b54be
