### ISSUE TITLE
Race condition because modules extracted to system's temp directory

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#378]
```
markus@avocado:~/src/TLA/_specs/models/ConfluentAlgorithm/MCC-test$ java -cp /tmp/tla/tlatools/dist/tla2tools.jar tlc2.TLC MC
TLC2 Version 2.03 of 20 July 2011
Running in Model-Checking mode.
Parsing file MC.tla
Parsing file ConfluentAlgorithm.tla
Parsing file /tmp/TLC.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
Semantic processing of module ConfluentAlgorithm
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module TLC
Semantic processing of module MC
Starting... (2019-10-17 08:45:16)
Computing initial states...
...
```

When TLC is executed from the jar file, it transparently extracts the standard modules to the system's temp location (/tmp/ dir above).  This is racy if multiple instances of TLC run simultaneously.  Instead, TLC could extract the files to the directory it creates for the state queue, fingerprint set, and trace whose name is a timestamp (and thus has very low probability of a name clash).  It might look strange though, if the standard modules are read from ```states/1580319301/...```.

**Comment by lemmy** [comment]
Since it is an uphill battle to convince TLC to work with InputStreams instead of Files and Strings (representing absolute, relative, or names of Files), it seems best to instead use an in-memory filesystem such as https://github.com/google/jimfs.

**Comment by lemmy** [comment]
Related: http://discuss.tlapl.us/msg03690.html

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/8cb8698f46a8c4737ca3f94b33827816c1db52d0

**Comment by kyanha** [comment]
java.nio.file.Files.createTempDirectory() seems appropriate to mention here, available since Java 7.

**Comment by lemmy** [comment]
@kyanha Agreed, see https://github.com/tlaplus/tlaplus/commit/8cb8698f46a8c4737ca3f94b33827816c1db52d0
