### ISSUE TITLE
TLA Toolbox does not launch on Java 9

### ISSUE THREAD

**Issue by SpaceMacGyver** [tlaplus/tlaplus#38]
I've unpacked [TLAToolbox-1.5.2-linux.gtk.x86_64.zip](https://tla.msr-inria.inria.fr/tlatoolbox/products/TLAToolbox-1.5.2-linux.gtk.x86_64.zip) on my computer and attempted to launch it, but I am presented with an error shortly after the splash screen that directs me to a log file.  The contents of this file are [here](https://github.com/tlaplus/tlaplus/files/844429/1489579418058.log.txt), and seem to indicate missing dependencies.

Have I missed some installation instructions?  It was my impression that this toolbox should have worked out-of-the-box...

I should note that this is a fairly recent Ubuntu desktop install, and in addition to out-of-the-box configuration I have installed openjdk and other assorted modules in attempts to get an unrelated IcedTea application installed.  Attached is [a file](https://github.com/tlaplus/tlaplus/files/844439/details.txt) containing output from `lsb_release`, `lscpu`, and `java -version`.

**Comment by lemmy** [comment]
You are trying to launch the Toolbox on an (unreleased) Java 1.9 VM. Try running it with a current Java 1.8. I will update the title to better reflect the underlying problem.

**Comment by SpaceMacGyver** [comment]
@lemmy You have correctly identified my issue; changing out for JRE8 gets me into the application.  Thanks for the assistance.

**Comment by lemmy** [comment]
Lets keep it open as a reminder.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/08c40ffb5f04a8f735b1d41c852e1242860381f8
https://github.com/tlaplus/tlaplus/commit/82d4735b022fea7d6e3e9a98f920b10b71e36b8e
