### ISSUE TITLE
Cannot start Toolbox with Eclipse Oomph: Missing Constraint: Require-Bundle: org.eclipse.ui.themes; bundle-version="1.2.200"

### ISSUE THREAD

**Issue by ajdavis** [tlaplus/tlaplus#382]
I followed the excellent instructions here:

https://github.com/tlaplus/tlaplus/tree/5927c2fe8/general/ide/README.md

When I tried to launch TLA+ Toolbox from Eclipse I get an error:
```
Missing Constraint: Require-Bundle: org.eclipse.ui.themes; bundle-version="1.2.200"
```
See this video: https://www.youtube.com/watch?v=CB-EIpms96o

I can fix the problem by adding org.eclipse.ui.themes to the list of plugins. Perhaps the dependencies are incomplete on master in org.lamport.tla.toolbox.feature.standalone/feature.xml?

**Comment by lemmy** [comment]
Please checkout git revision 6d300e24771db3bb46c5c8c592800ad90f8629bd from two days ago until we fix the bug.

@quaeler The same bug seems to break the CI build.

**Comment by ajdavis** [comment]
Thank you!

**Comment by quaeler** [comment]
I get too mollified by that nice green check mark GH provides on commits... :- /
Will suss.

**Comment by lemmy** [comment]
@ajdavis By the way, I assume you want to work on a TLC module override?  In this case, it might be easier to close all ```org.lamport.*``` Eclipse projects. You will only need the ```tlatools``` project.

**Comment by quaeler** [comment]
Commit 66a5bd14da8a48fed9cdcad42ef840baa1c86130 has the CI machine building correctly (doing something unintelligible with RCPTT, but the unresolved bundle issue is gone.)

**Comment by ajdavis** [comment]
Thanks for the bugfix @quaeler! And @lemmy, thanks for the instructions. You're correct I'm working with TLC as a command-line program right now, exploring the techniques we're discussing in #367.

**Comment by lemmy** [comment]
@ajdavis Feel free to reach out to me if you need help with the code base.
