### ISSUE TITLE
Improvements to the usability of Dark theme

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#384]
Now that we have enabled Dark mode, some readability & rendering issues have cropped up. A presumably growing list of them, with descriptions, features:
* Prover colors do not work well with the editor's text coloration (and the non-dark editor's text coloration did not work well with the dark background.) These colors are unfortunately defined in a [plugin.xml file.](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.prover/plugin.xml#L216) Previously it was done in [ProverUIActivator](https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.prover/src/org/lamport/tla/toolbox/tool/prover/ui/ProverUIActivator.java#L72) which, while maybe not the best spot, is at least in Java.
* A brand new specification opened has a spec editor which does not inherit the correct background color (though it does get the write text coloring affectation.) Reopening and closing the spec editor doesn't seem to effect it - only going to the Preference panel for the theme and clicking `Apply` again does, weirdly / lamely.
* Some model editor tabs, randomly, do not show an entire dark background but will start if another model editor tab is brought to the front. Examples would be "white space at the bottom of the Spec Options page, or a header section.

**Comment by lemmy** [comment]
![Screenshot from 2019-10-25 13-30-03](https://user-images.githubusercontent.com/88777/67602513-a119fc80-f72b-11e9-8d76-2b2ad91f9982.png)
![Screenshot from 2019-10-25 13-30-26](https://user-images.githubusercontent.com/88777/67602517-a24b2980-f72b-11e9-8b1c-c6400b9507eb.png)

**Comment by lemmy** [comment]
A lot of work for very little gain
