### ISSUE TITLE
Flickering of module text editor in TLA+ Toolbox

### ISSUE THREAD

**Issue by mwshinn** [tlaplus/tlaplus#390]
The module text editor flickers to gray frequently (apparently a redraw?).  The frequency and duration of flickering makes the editor borderline unusable.  The flickering occurs most often when the mouse is moved into the text editor or when text is modified.
Here is an example video (zipped because github doesn't seem to support ogv videos): [out.ogv.zip](https://github.com/tlaplus/tlaplus/files/3827423/out.ogv.zip)

TLA+ Toolbox: 1.6.0 (official GNU/Linux x64 binary)
Platform: Ubuntu 18.04.2 LTS
System: Linux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
GTK2: 2.24.32-1ubuntu1
GTK3: 3.22.30-1ubuntu1
Java: java-11-openjdk-amd64

Thanks!  Happy to provide any more info.

**Comment by lemmy** [comment]
I'm at a loss. I have almost the same environment but never observed similar behavior.  Can you please check with the most recent [nightly build](https://nightly.tlapl.us/products)?

**Comment by mwshinn** [comment]
The same thing happens with the nightly.

A few things that might be helpful in tracking it down:

- It is reliably triggered when I start or stop moving my mouse.
- There is sometimes a less-strong baseline level of flicker (not captured on the video) with a semi-constant frequency of about .5hz.  This flicker doesn't last as long as the big long flickers you see on the video.  I get a similar type of flicker when scrolling with the scroll bar.

**Comment by lemmy** [comment]
Do you observe the same behavior when you download the [Eclipse SDK](https://download.eclipse.org/eclipse/downloads/drops4/R-4.12-201906051800/download.php?dropFile=eclipse-SDK-4.12-linux-gtk-x86_64.tar.gz), which is the foundation of the Toolbox?

**Comment by mwshinn** [comment]
I looked into similar bugs in eclipse, and it seems that this is due to the use of the environment variable GTK_IM_MODULE=xim.  Setting GTK_IM_MODULE=ibus eliminates the flicker for me so I can use this as a workaround.  Thanks for your help!

**Comment by lemmy** [comment]
Can you link the relevant Eclipse bug?

**Comment by mwshinn** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=517671
