### ISSUE TITLE
TLC does not correctly compare integers or integer intervals due to overflow

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#391]
The assertion in this spec should trivially pass:
```
---- MODULE Overflow ----

EXTENDS Integers

x == {1157660672, -989822976}
y == {-989822976, 1157660672}

ASSUME x = y

=========================
```

However, TLC reports that it fails:
```
$ tlc2 Overflow
[...]
Error: Assumption line 18, col 8 to line 18, col 12 of module Overflow is false.
Finished in 00s at (2019-11-12 15:58:54)
```

The root cause is that TLC uses simple subtraction to compare integers, which can overflow when those integers are very far apart. As a result, the two binary sets in the specification do not normalize to an identical internal representation.

I am aware of at least two places where TLC incorrectly uses subtraction to compare integer values:

 - https://github.com/tlaplus/tlaplus/blob/56740fd57b089eb8f85ef722dd0ee60a961b391f/tlatools/src/tlc2/value/impl/IntValue.java#L73
 - https://github.com/tlaplus/tlaplus/blob/56740fd57b089eb8f85ef722dd0ee60a961b391f/tlatools/src/tlc2/value/impl/IntervalValue.java#L40

There may be other locations as well.

A simple fix would be to use the library function [Integer.compare(int, int)](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#compare(int,%20int)), instead of subtraction. The library function correctly handles this case.

**Comment by lemmy** [comment]
Has this bug shown up in a real-world spec?

**Comment by Calvin-L** [comment]
Not to my knowledge. I noticed the problem while reading through the TLC source code, and constructed the artificial spec above to exhibit it.

**Comment by Calvin-L** [comment]
@lemmy Sorry to bug you again, but the fix is not quite right.

1. The computation `size = this.high - this.low + 1` returns zero when `high` = `Integer.MAX_VALUE` and `low` = `Integer.MIN_VALUE`. Therefore the subsequent test `size < 0` does not actually detect overflow.
2. The new `compareTo` method for intervals might not return zero ("equal") when the two intervals have different `low` values but are both empty because `high < low`.

Here's an spec that demonstrates the two problems:

```
---- MODULE Overflow2 ----

EXTENDS Integers, FiniteSets

MaxInt == 2147483647
MinInt == -MaxInt - 1

ASSUME Cardinality(MinInt .. MaxInt) > 0      \* FAILS due to (1)
ASSUME (10..5) = (20..15)                     \* OK, as expected
ASSUME Cardinality({(10..5), (20..15)}) = 1   \* FAILS due to (2)

=========================
```

**Comment by Calvin-L** [comment]
(Regarding the `size` computation: it might be good to use the `tlc2.module.Naturals.Plus(...)` function that is already built-in to detect overflow when adding. If you are willing to depend on Java 8+, you can also use [`Math.addExact`](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#addExact-int-int-).)

**Comment by lemmy** [comment]
Care to provide a PR (Java 8+ has been the de facto minimum dependency for a while)?

**Comment by Calvin-L** [comment]
Sure, I should be able to put one together this evening.
