### ISSUE TITLE
Writing tests for a spec

### ISSUE THREAD

**Issue by dvc94ch** [tlaplus/tlaplus#392]
Sometimes you'll have a spec that tlc doesn't find any issues with, but you know that the spec is wrong. In these cases you'd like to write tests for the spec that assert that a sequence of state transitions is valid, or a sequence of state transitions is invalid. This doesn't seem to be possible to express in TLA, but it would be possible to write a tool that searches the state dump file to figure out if A -> B -> C is a valid state transition. Below is what I tried:

```tla
---- MODULE Tests ----
EXTENDS Naturals, Sequences, TLC

VARIABLES a, t

vars == <<a, t>>
view == <<a>>

Init ==
    /\ a = 0
    /\ t = 0

Next ==
    /\ a' = (a + 1) % 2
    /\ t' = t + 1

ValidStates(s, t0, values) ==
    t \in t0..(t0 + Len(values) - 1) => s = values[t - t0 + 1]

TestsInner ==
    /\ ValidStates(a, 0, <<0, 1, 2, 0>>)
    /\ ValidStates(a, 1, <<1, 2>>)
    \*/\ ~ValidStates(a, 0, <<0, 2>>)

Tests == <>[][TestsInner]_vars

Spec == Init /\ [][Next]_vars
====
```
```
SPECIFICATION Spec
VIEW view
PROPERTY Tests
```

**Comment by lemmy** [comment]
Try ```<<A,A,C,B,A>>[TLCGet("level")]``` as an action constraint ("Additional spec options" page of the Toolbox) to force TLC to explore only behaviors whose action sequence is A,A,C,B,A where A,C,B are actions.

Please clarify your first sentence.  Are you saying that TLC fails to search the state graph exhaustivelyg?

**Comment by dvc94ch** [comment]
Nope, I say that my expectation and what is written is not the same, and I'm not smart enough to figure out why without extra help

**Comment by dvc94ch** [comment]
That's awesome! Thanks
