### ISSUE TITLE
Single clicking on an action in the trace explorer opens the spec, even if closed

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#397]
According to the tooltip, double clicking on an action will jump to the location in the spec:

![image](https://user-images.githubusercontent.com/2660212/69273428-f7992000-0b9d-11ea-9b5d-40d785ee70cb.png)

However, it will automatically jump when single-clicking, or moving over the action with the keyboard buttons. This causes the spec view, if minimized, to open again,

This is all on Windows 10 with the 1.6.0 Toolbox.

**Comment by lemmy** [comment]
This has changed in the [nightly build](https://nightly.tlapl.us/).  Please check if this is still an issue.

**Comment by hwayne** [comment]
Still getting the same issue, unfortunately

**Comment by lemmy** [comment]
@quaeler Can you please take a look?

**Comment by quaeler** [comment]
I can't replicate this on macOS; will try with Win10 next.

**Comment by quaeler** [comment]
... and i cannot replicate this on Win10 with the 1.6.0 release. :- /

@hwayne does this happen all the time, or sporadically?

**Comment by hwayne** [comment]
It was happening consistently, so it's probably just something weird with my setup

**Comment by lemmy** [comment]
Close?

**Comment by quaeler** [comment]
Do you mean it was, but it is no longer, happening, or that it is still happening consistently?

**Comment by hwayne** [comment]
It's still happening consistently

**Comment by quaeler** [comment]
Hmm.. vexing! Is there anything "not usual" about your setup? (Are there assistive input devices which you use? Are you running Win10 inside a guest VM? Are you connecting to it via RDP/VNC/... ? )

oohhhh!
Wait - do you have the sync button turned on?
![Screen Shot 2019-11-22 at 7 50 11 AM](https://user-images.githubusercontent.com/22581048/69439917-bc613300-0cfc-11ea-9210-12f7a9dd69cb.png)

**Comment by quaeler** [comment]
@hwayne  ?

**Comment by hwayne** [comment]
Not doing anything unusual, just running it straight on windows 10. Let me
know if there's anything you want me to try

**Comment by quaeler** [comment]
Is your sync button clicked?

**Comment by hwayne** [comment]
Yup, that was it! Didn't realize that that was even an option until now, must have accidentally clicked it at some point.
