### ISSUE TITLE
Action expression evaluation with primed and unprimed variables can produce bogus error trace

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#4]
xxyzz: 

"If you run Model_1 of SendSetUndoPP, it will report an

```
Invariant TypeOKP is violated.
```

error and produces an error trace.  Go to the end of the trace and double click on the last action (the one that produced the last state).  You’ll see that it’s the SendP action on line 14 of SendSetUndoPP.tla.  Now open the Error-Trace Exploration area and add the following two expressions:

```
SendP     Send
```

These are action expressions, so they depend on variables and primed variables.  The values of those expressions that apply to the final two states of the trace are reported with the next-to last state.  Observe that SendP = FALSE.  In other words, the trace explorer says that the final two states don’t satisfy SendP.  However the error-trace also tells us that the last state was produced from the next-to last state by a SendP action.

```
-----------------------------------------------------------------------------
SendP2 == /\ Send
          /\ ProphCondSend(p)
          /\ p' \in NewProphs(p, Dom', DomInjSend, PredSetSend)

UndoP2 == /\ Undo
          /\ ProphCondUndo(p)
          /\ p' \in NewProphs(p, Dom', DomInjUndo, PredSetUndo)

NextP2 == (\E v \in Value: ChooseP(v)) \/ SendP2 \/ RcvP \/ UndoP2
SpecP2 == InitP /\ [][NextP2]_varsP
-----------------------------------------------------------------------------
```

I’ve defined SendP2 and UndoP2 by manually expanding the definition of NewProphecyAction in the definitions of SendP and Undo, and defined SpecP2 by replacing SendP and UndoP in SpecP with SendP2 and UndoP2.  So SpecP and SpecP2 are obviously equivalent.  Now clone Model_1 and in the resulting model, replace the specification SpecP with SpecP2.  This time TLC runs correctly and finds no error.  From the bogus error trace that SpecP produces, it looks like TLC is evaluating NewProphs incorrectly when it expands the definition of NewProphecyAction.  Note that the ChooseP and RcvP actions are also defined in terms of NewProphecyAction, but they seem to work fine.  The arguments with which NewProphecyAction is being called are defined starting on line 24 of SendSetUndo.  The only significant difference between whether or not TLC is correctly evaluating NewProphecyAction and the others seems to be that it works incorrectly when a couple of the arguments have primes.  However, all of them have the same argument Dom’."

---

> YY: I would try to log as much as possible when getNextStates() is called on the preceding state that generates the bad state. I would use the fingerprint of that preceding state to do conditional logging.

**Comment by craft095** [comment]
Is this bug still to be fixed? From the description it is not clear what exactly the problem is and how to reproduce it

**Comment by craft095** [comment]
Thanks @lemmy ! This bug is not reproduced on 1.7.1 - both SpecP and SpecP2 produce the same result: no violations. I suggest closing this issue.

**Comment by lemmy** [comment]
Thanks for checking!
