### ISSUE TITLE
Options to output state graph dot file

### ISSUE THREAD

**Issue by LordGordonQ** [tlaplus/tlaplus#403]
TLA+ Toolbox has the option to generate a Graphviz's dot file. Unfortunately I was unable to find the equivalent CLI option nor the cfg setting (there is a cfg documentation somewhere?).

Is it possible to have a configuration for this in case I want to run my model from a different tool than Toolbox (ie: VS Code)?

**Comment by lemmy** [comment]
TLC outputs the state graph in dot format with: "... -dump dot /path/to/output.dot ...". Optionally, you may add "actionlabels" and "colorize" to add labels and colorize the dot graph: "... -dump dot,actionlabels,colorize /path/to/output.dot ..."

https://github.com/tlaplus/tlaplus/blob/354d0e11f2e52f64eaf4e59c93a2935a9f71ccc2/tlatools/src/tlc2/TLC.java#L404-L423

**Comment by LordGordonQ** [comment]
Is it possible to update https://lamport.azurewebsites.net/tla/tlc-options.html?back-link=tools.html ? In this page the extra options are not written. Or there is a up-to-date page with all the command line options?

Thanks

**Comment by lemmy** [comment]
The source code I linked to above is the most up-to-date documentation.  Instead of trying to keep an html file in sync, I'd rather like to see work on a command-line help or even proper man page for TLC.  A PR would be highly appreciated.
