### ISSUE TITLE
Specifying symmetry set in cfg file manually

### ISSUE THREAD

**Issue by arssher** [tlaplus/tlaplus#404]
In short: setting 
`SYMMETRY <expression>`
in model conf file doesn't work; apparently `<expression>` must be single identifier.

I'm running TLC from command line (because this is remote machine, and that's easier than setup the toolbox in distributed mode). For that, I need to manually specify the model file. Following MC.tla and MC.cfg files generated by the toolbox, I've put to my conf file the following lines:
```
CONSTANTS
n1 = n1
n2 = n2
n3 = n3
\* MV CONSTANT definitions
CONSTANT
nodes = {n1, n2, n3}
\* SYMMETRY definition
SYMMETRY Permutations({n1, n2, n3})
```

However then
`java -cp tla2tools.jar tlc2.TLC tmp.tla`
fails with 
```
The exception was a tlc2.tool.ConfigFileException
: TLC found an error in the configuration file at line 10
It was expecting a keyword, but did not find it.
```

where line 10 is 
`SYMMETRY Permutations({n1, n2, n3})`

The fix is to declare 
`perms == Permutations(nodes)`
in `tmp.tla` and change the offending line in `tmp.cfg` to
`SYMMETRY perms`
Then it works, but this is unobvious.

You can find full tmp.tla and tmp.cfg files in the attachment (postfixed with .txt to workaround github guards). 
Most probably this is a known behaviour, but I've stumbled on it and after failing to google up the subject decided to make this note.

[tmp.cfg.txt](https://github.com/tlaplus/tlaplus/files/3933377/tmp.cfg.txt)
[tmp.tla.txt](https://github.com/tlaplus/tlaplus/files/3933378/tmp.tla.txt)

**Comment by lemmy** [comment]
Note that you can always copy the generated MC.cfg/MC.tla file from the Toolbox.

**Comment by lemmy** [comment]
Closing as this ultimate boils down to what has been discussed in https://github.com/alygin/vscode-tlaplus/issues/159
