### ISSUE TITLE
Please fix TLA.setup to remove bogus XML content

### ISSUE THREAD

**Issue by merks** [tlaplus/tlaplus#409]
The TLA.etup was contributed to Oomph's github project catalog via:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=489276

As part of improving the behavior of producing an archive of all the Oomph setups, I analyzed more carefully the contents of all the resources going into the archive, so I noticed problems with this:

https://raw.githubusercontent.com/tlaplus/tlaplus/master/general/ide/TLA.setup

Specifically the very last element with name setup:PreferenceTask is bogus.  If you want a proper preference task, please create a new one that will be serialized properly.  So specifically these 3 lines should be deleted:

  <setup:PreferenceTask
      key="/instance/org.eclipse.ui/defaultPerspectiveId"
      value="org.eclipse.jdt.ui.JavaPerspective"/>

Once I update setup archiver application (probably later today) the following job will **stop** updating your setup until the unrecognized XML content is removed from your setup:

https://ci.eclipse.org/oomph/job/setup-archiver/lastStableBuild/console

**Comment by lemmy** [comment]
Last setup task has been removed.
