### ISSUE TITLE
Workbench crash running "File / Produce PDF Version" on macOS 10.14.6

### ISSUE THREAD

**Issue by awwx** [tlaplus/tlaplus#411]
TLA Workbench version 1.6.0

pdflatex installed via `brew cask install basictex`

Running pdflatex on the command line against a .tex file created by the TLA Workbench works.

Location of pdflatex (`/usr/local/texlive/2019basic/bin/x86_64-darwin/pdflatex`) set in TLA+ Workbench preferences "Specify pdflatex command".

Running "File / Produce PDF Version" crashes the Workbench.  Crash report: https://gist.github.com/awwx/050ad58e5a7e67ed38dbb9d8ab4e99e0

TLA+ Workbench configuration ("About TLA+ Toolbox / Installation Details / TLA+ Toolbox Installation Details / Configuration"): https://gist.github.com/awwx/3b83a584f47e650bcf7899333c5995ca

**Comment by awwx** [comment]
Here's the hs_err_pid log file (in case it contains anything useful not in the crash report...): 
[hs_err_pid23839.log](https://github.com/tlaplus/tlaplus/files/4007239/hs_err_pid23839.log)

**Comment by lemmy** [comment]
Thanks for the report. Do you agree that this is related to #357?

**Comment by awwx** [comment]
@lemmy  Yes, thank you, I was able to confirm that this is a duplicate of #357 by removing the `/Library/Internet\ Plug-Ins\AdobePDFViewer*` files.
