### ISSUE TITLE
/usr/local/bin is not in $PATH

### ISSUE THREAD

**Issue by introom** [tlaplus/tlaplus#412]
Tlaplus searches in $PATH to find the =dot= executable.

However, the $PATH it searches lacks /usr/local/bin  (probably read from macOS default settings).

While we can manually set the =dot= location, It is better to include /usr/local/bin by default.

**Comment by quaeler** [comment]
We currently rely upon the GraphViz library code to find `dot` if a full path is not specified in the preference panel by invoking [this](https://github.com/abstratt/eclipsegraphviz/blob/master/plugins/com.abstratt.graphviz/src/com/abstratt/graphviz/GraphVizActivator.java#L195) with `DotMethod.AUTO`

I can amend this to first look explicitly in `/usr/local/bin` and if found there set the path for GraphViz.

**Comment by lemmy** [comment]
Is this something that should rather be addressed at the GraphViz level?

**Comment by quaeler** [comment]
GraphViz suffers from the general Eclipse problem, at least under macOS, that the custom PATH isn't available ([for example](https://stackoverflow.com/questions/829749/launch-mac-eclipse-with-environment-variables-set/36282543)) - GraphViz [does do an attempt to search the path](https://github.com/abstratt/eclipsegraphviz/blob/master/plugins/com.abstratt.graphviz/src/com/abstratt/graphviz/GraphVizActivator.java#L116) already.

It's a minor addition to `TLA2TeXActivator` probably.

**Comment by quaeler** [comment]
Addressed with dd7ff0b

**Comment by lemmy** [comment]
In the long run, we should switch to a no-installation GraphViz renderer  (e.g. JavaScript based) that can be packaged with the Toolbox.

**Comment by quaeler** [comment]
Agreed.
