### ISSUE TITLE
Add clearer link to nightly builds in Github repo

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#417]
I believe [this](https://nightly.tlapl.us/dist/) is the right place to download nightly TLC builds, but I always forget the link. Perhaps this could be added more clearly to the README or the CONTRIBUTING pages. Nightly Toolbox download links would also be helpful.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/master/CONTRIBUTING.md#nightly-builds
