### ISSUE TITLE
How to check whether something is function or not

### ISSUE THREAD

**Issue by troublescooter** [tlaplus/tlaplus#419]
What is the right way of checking whether something is a function or not?

Based on suggestions I found in Lamport's 'Specifying Systems' on p140-141, I tried
```
IsFcnOn(f,S) == f = [x \in S |-> f[x]]
IsFcnOn(f,{"first","second"})
```
and
`f = [first |-> f.first, second |-> f.second]`
for the less generic case where I'm just interested whether
f is a record of that form or not.
Unfortunately this doesn't work if f is not a function,
with runtime exceptions in tlc.

Was this once possible with tlc and later removed?

**Comment by lemmy** [comment]
This works if you know f's co-domain.

```tla
IsFcnOn(f, D, C) == f \in [ D -> C ]
```

I checked with ```TLC2 Version 2.03 of 10 March 2011``` and it already refuses to evaluate f[x] for x \notin DOMAIN f.
