### ISSUE TITLE
What license governs the code in this repository?

### ISSUE THREAD

**Issue by dpp** [tlaplus/tlaplus#42]
Howdy... I've very interested in using TLA+ and the code in this repository for a project I'm working on (https://funcatron.org). However, I'm unclear as to the license that governs the code. Some files seem to be MIT licensed. There's a license file (https://github.com/tlaplus/tlaplus/blob/master/tlatools/doc/License.txt) that is 14 years old. And there's a reference to the Microsoft Research License in some files.

Clarification of license terms would be greatly appreciated.

Thanks!!

**Comment by lemmy** [comment]
http://lamport.azurewebsites.net/tla/tools.html and http://lamport.azurewebsites.net/tla/toolbox.html both link to the MIT license at http://lamport.azurewebsites.net/tla/license.html.

**Comment by lemmy** [comment]
Amended the README.

**Comment by dpp** [comment]
Thank you very much! Looking forward to building some cool things on top of TLA+.
