### ISSUE TITLE
ArrayIndexOutOfBoundsException when specifying symmetry set

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#432]
Some symmetry sets can cause TLC to throw an unhelpful `ArrayIndexOutOfBoundsException`. This appears to have been introduced in the fix for #218, although I don't understand the code well enough to know what to do about it.

My debugger says the exception is thrown by this line:
https://github.com/tlaplus/tlaplus/commit/5544517ed04b934c69f3048bcaa736fe7b12d027#diff-a399541e8221269460ee19b7cdda0b2fR3224

(I believe this bug is not in a released version of TLC; I am running the master branch of TLC so that I can have the fix in d5b5a7fa9f).

SingletonSymmetry.tla:
```
---- MODULE SingletonSymmetry ----

EXTENDS TLC

CONSTANT Humans, Others

symmetry == Permutations(Humans) \union Permutations(Others)

VARIABLES set

TypeOK ==
    /\ set \subseteq Humans

Init ==
    /\ set = {}

Next ==
    \E h \in Humans:
        set' = set \union {h}

==================================
```

SingletonSymmetry.cfg:
```
CONSTANT Humans = {Alice}
CONSTANT Others = {Cat, Dog}

INIT Init
NEXT Next
SYMMETRY symmetry
INVARIANT TypeOK
```

Invocation:
```
$ tlc2 SingletonSymmetry
TLC2 Version 2.15 of Day Month 20?? (rev: ${git.shortRevision})
[...]
Starting... (2020-02-24 14:26:32)
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.ArrayIndexOutOfBoundsException
: Index 2 out of bounds for length 2
Finished in 00s at (2020-02-24 14:26:32)
```

**Comment by lemmy** [comment]
@quaeler Please have a look.

**Comment by quaeler** [comment]
Yes, this is interesting as its not a checking configuration that can be specified by the Toolbox (the symmetry constraint not being a on single constant, but rather on the result of an operation on N>1 constants.) My previous approach is ill-suited to this; will address.

**Comment by Calvin-L** [comment]
I believe this can indeed be specified in the toolbox by checking the "Symmetry set" option for multiple model values:

![Screen Shot 2020-02-24 at 4 10 00 PM](https://user-images.githubusercontent.com/1393639/75202464-2d5f1f00-5720-11ea-948c-56f831d09fd0.png)

```
$ cat Symmetry.toolbox/Model_1_SnapShot_1582589297324/MC.tla 
[...]
\* SYMMETRY definition
symm_158258929522014000 == 
Permutations(const_158258929522012000) \union Permutations(const_158258929522013000)
[...]

$ cat Symmetry.toolbox/Model_1_SnapShot_1582589297324/MC.cfg 
[...]
\* SYMMETRY definition
SYMMETRY symm_158258929522014000
[...]

$ tlc2 Symmetry.toolbox/Model_1_SnapShot_1582589297324/MC
[...]
Starting... (2020-02-24 16:09:37)
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.ArrayIndexOutOfBoundsException
: Index 2 out of bounds for length 2
Finished in 01s at (2020-02-24 16:09:37)
```

**Comment by quaeler** [comment]
You're right (presumably this is why I provided the concatenation of CONSTANT naming in the warning message.)

**Comment by quaeler** [comment]
@Calvin-L please give 58fdada a shot - it will now correctly warn on the Humans set being declared symmetric although having cardinality one. (Whether you want this checking-halting-warning is potentially a different issue.)

**Comment by Calvin-L** [comment]
Yes, that commit fixes the example in the description. :)

However, there are other cases to consider as well.

--------

Empty sets cause an exception:
```
CONSTANT Humans = {}
CONSTANT Others = {}
[...]
```
```
[...]
Starting... (2020-02-25 15:11:37)
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at util.Set.<init>(Set.java:86)
	at util.Set.<init>(Set.java:100)
	at tlc2.value.impl.MVPerms.permutationSubgroup(MVPerms.java:21)
	at tlc2.tool.impl.Tool.getSymmetryPerms(Tool.java:3235)
	at tlc2.tool.TLCStateMut.setTool(TLCStateMut.java:74)
	at tlc2.tool.impl.Tool.<init>(Tool.java:134)
	at tlc2.tool.impl.Tool.<init>(Tool.java:126)
	at tlc2.tool.impl.Tool.<init>(Tool.java:121)
	at tlc2.tool.impl.FastTool.<init>(FastTool.java:47)
	at tlc2.TLC.process(TLC.java:1064)
	at tlc2.TLC.main(TLC.java:289)
```

--------

Empty-set/singleton-set produces an error message that is only partially-correct:
```
CONSTANT Humans = {}
CONSTANT Others = {Cat}
[...]
```
```
[...]
Starting... (2020-02-25 15:13:05)
Error: The sets Humans, and Others have been defined to be a symmetry set but only contain a single element.
Finished in 00s at (2020-02-25 15:13:05)
```

--------

Empty-set/binary-set produces an error message that is clearly wrong:
```
CONSTANT Humans = {}
CONSTANT Others = {Cat, Dog}
[...]
```
```
[...]
Starting... (2020-02-25 15:14:01)
Error: The set Humans has been defined to be a symmetry set but only contains a single element.
Finished in 00s at (2020-02-25 15:14:01)
```

**Comment by Calvin-L** [comment]
> Whether you want this checking-halting-warning is potentially a different issue.

Agreed, that's outside the scope of this issue.

(But, to get the discussion started anyway: I believe empty and singleton symmetry sets---while redundant---are perfectly well-defined. The fact that TLC aborts when it encounters a singleton or empty symmetry set will interfere with some scripts I plan to write. The scripts generate several different configuration files for the same specification. With the abort behavior, some configuration files will necessitate a change to the specification itself to "fix" the defined symmetry set. I can think of two workarounds: defining a different symmetry set for each possible subset of the CONSTANT declarations, or waiting for #404 to be addressed. Neither workaround is very palatable to me.)

**Comment by quaeler** [comment]
Allowing empty sets should accompany a change to the toolbox which considers it illegal; if we all agree that empty sets should be supported then i'll address the above use cases as well. Thoughts @lemmy  ?

**Comment by lemmy** [comment]
Let's emit a warning if a symmetry set is empty or has cardinality one.

By the way, there are no plans to address #404. Maybe #272 would be useful?

**Comment by quaeler** [comment]
The commit cee3bfc enables zero-element symmetry sets and changes from halt-on-error model checking for cardinalities 0 and 1 to only emitting a warning:
```
Warning: The sets Others, and Humans have been defined to be a symmetry set but contain less than two elements.
```

**Comment by Calvin-L** [comment]
@lemmy Yes, #272 does look like it would save me the trouble of writing these scripts. :) It escaped my notice earlier.

@quaeler Thanks for the quick resolution! I haven't done a whole lot of testing, but cee3bfc seems to fully resolve the issue.

**Comment by quaeler** [comment]
Good news - i will close the issue after i check in a few unit tests.

**Comment by quaeler** [comment]
4 unit tests testing 0,1,N(N>1) cardinality symmetry sets provided via 1c920e1 - closing this now. Thanks @Calvin-L for filing this and sticking with it.
