### ISSUE TITLE
Difficulty adding a new module to existing spec in Toolbox

### ISSUE THREAD

**Issue by houseofwealth** [tlaplus/tlaplus#437]
Trying to add a new module to a spec produces an error message saying that the file will be created in read-only mode because the current spec is not open, even though it is.

Workaround I have found is to create the module in a separate editor, add it to the EXTENDS or INCLUDES list of the importing module, and hit save. The module then appears in the list of modules in the tree in the module browser on the left

**Comment by lemmy** [comment]
Please provide more info, i.e. your environment and maybe a screenshot.

**Comment by lemmy** [comment]
Please reopen with more information if this remains a problem.
