### ISSUE TITLE
glib and gtk issues running toolbox on ubuntu 18.04.3

### ISSUE THREAD

**Issue by ToddG** [tlaplus/tlaplus#444]
**SUMMARY**
Running toolbox on Ubuntu 18.04.3 consistently produces these errors in the console where I launch it from. This is not blocking me, but I thought I'd create a ticket to track this in this project as a quick search did not turn anything up in this repo. This seems to be an issue with eclipse per these links:

* https://stackoverflow.com/questions/48467865/glib-critical-g-base64-encode-step-assertion-in-null-failed-problems-i
* https://www.eclipse.org/forums/index.php/t/1081230/

**SYSTEM**
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**REPRO1**
```toolbox```

**REPRO2**
Tried these various combinations as suggested in links above.
```
env SWT_GTK3=0 SWT_WEBKIT2=0 toolbox
env SWT_GTK3=1 SWT_WEBKIT2=0 toolbox
env SWT_GTK3=0 SWT_WEBKIT2=1 toolbox
env SWT_GTK3=1 SWT_WEBKIT2=1 toolbox
```

**ERRORS**
(same for all repros)

(TLA+ Toolbox:1124): GLib-CRITICAL **: 07:43:52.651: g_base64_encode_step: assertion 'in != NULL' failed

(TLA+ Toolbox:1124): Gtk-WARNING **: 07:43:58.935: Negative content width -4 (allocation 2, extents 3x3) while allocating gadget (node progressbar, owner GtkProgressBar)

**FILES**
* [toolbox-error-log.txt](https://github.com/tlaplus/tlaplus/files/4523337/toolbox-error-log.txt)
* [toolbox-configuration.txt](https://github.com/tlaplus/tlaplus/files/4523347/toolbox-configuration.txt)

**Comment by lemmy** [comment]
Thanks for reporting it.  I've observed these errors for many years but they don't appear to have any effect on the Toolbox.  Do the errors cause Toolbox issues on your end?
By the way, the [nightly build](https://nightly.tlapl.us) of the Toolbox comes with a newer Eclipse foundation.  It is possible that some of the errors have been addressed.

**Comment by ToddG** [comment]
Thanks Markus. No, this error/warning doesn't cause any issues in the toolbox (that I can see, anyway). I'm seeing other issues, but I'll log those separately.

**Comment by lemmy** [comment]
Closing because it's an Eclipse issue.
