### ISSUE TITLE
Deleting the toolbox directory causes CoreExeception on toolbox startup

### ISSUE THREAD

**Issue by ToddG** [tlaplus/tlaplus#445]
**SUMMARY**
Deleting the {{name}}.toolbox directory causes the toolbox to throw CoreException on startup.

**SYSTEM**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
**REPRO**
* start the toolbox
* create or import a spec for foo.tla 
* create and run a model
* exit the toolbox
* delete the foo.toolbox directory (and the states directory, but this one is created by the tlc command line I think)
* start the toolbox (the toolbox will load the project foo.tla on startup)

**ERROR1**

Dialog displays: Failed to create the part's controls

Top lines of error snippet:
```
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1078)
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:621)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:355)
...
```
**ERROR2**

The console output shows:

```
org.eclipse.ui.PartInitException: Cannot determine URI for '/logical_clock/logical_clock.tla'.
...
```

**FILES**
* ![tla-logical-clock-error-on-startup](https://user-images.githubusercontent.com/104545/80130569-a8d92300-854d-11ea-8a97-2b24a2bf7254.png)
* [tla-console-error.txt](https://github.com/tlaplus/tlaplus/files/4524201/tla-console-error.txt)
* [tla-display-error.txt](https://github.com/tlaplus/tlaplus/files/4524202/tla-display-error.txt)

**Comment by lemmy** [comment]
This is expected; please delete specs via the Toolbox.

**Comment by ToddG** [comment]
Ok, I'll refrain from trying to help fine tune the user experience.

**Comment by lemmy** [comment]
We appreciate your help, please continue to report issues. However, we simply don't have the resources to address all issues and this one doesn't strike me as a show stopper.

**Comment by ToddG** [comment]
Ok. Thanks for the clarification. I'm happy to help. I'll report critical things if/when I bump into them.

**Comment by lemmy** [comment]
(I created the label "cantfix" to indicate that we don't have the resources but accept pull requests.)

**Comment by ToddG** [comment]
Ah, even better. Ok, I'll roll up my sleeves and alloc some time for this.
