### ISSUE TITLE
Importing .dot files on Gephi or Cytoscape

### ISSUE THREAD

**Issue by josedusol** [tlaplus/tlaplus#449]
Hello,
Im currently trying to visualize the generated state space with external tools. Unfortunately,
when trying to open the .dot file in Cytoscape i get "unable to parse" (had also installed the dot-app extension). Similarly, with Gephi i get a lot of "Unable to parse edge" messages.
Should i try another tool?,  Or maybe is better to convert to other format?.
Thanks

**Comment by lemmy** [comment]
Does it open with GraphViz's xdot or render to e.g. SVG with dot?

**Comment by josedusol** [comment]
I tried using dot converting to svg and the browser says "error on line 1 at column 1: Document is empty". 
Then i tried converting to png, but the resulting file is broken according to the OS.
The .dot file is just 3KB.

**Comment by lemmy** [comment]
Please share the .dot file and TLC's output.

**Comment by josedusol** [comment]
> Please share the .dot file and TLC's output.
Ok, here is the dot file (as .txt) and the pdf produced by the toolbox. The pdf is fine.

[example.pdf](https://github.com/tlaplus/tlaplus/files/4533967/example.pdf)
[example.txt](https://github.com/tlaplus/tlaplus/files/4533960/example.txt)

**Comment by lemmy** [comment]
No problems here (converted to png instead of svg because can't attach svg to issues).

```bash
markus@avocado:/tmp$ dot -Tpng example.txt > example.png
markus@avocado:/tmp$ eog example.png 
```

![example](https://user-images.githubusercontent.com/88777/80291172-2775c200-8700-11ea-9589-93f9fe10cb75.png)

**Comment by josedusol** [comment]
> No problems here (converted to png instead of svg because can't attach svg to issues).
> 
> ```shell
> markus@avocado:/tmp$ dot -Tpng example.txt > example.png
> markus@avocado:/tmp$ eog example.png 
> ```
> 
> ![example](https://user-images.githubusercontent.com/88777/80291172-2775c200-8700-11ea-9589-93f9fe10cb75.png)

Well... don't know what to say to that. But maybe if you give me the dot version you are using could be useful to compare.

**Comment by lemmy** [comment]
```bash
markus@avocado:~$ dpkg -l|grep graphviz
ii  graphviz                                                         2.40.1-2                                            amd64        rich set of graph drawing tools
ii  libgraphviz-dev                                                  2.40.1-2                                            amd64        graphviz libs and headers against which to build applications
ii  python3-graphviz                                                 0.5.2-1ubuntu1                                      all          Simple Python 3 interface for Graphviz
markus@avocado:~$ dot -v
dot - graphviz version 2.40.1 (20161225.0304)
libdir = "/usr/lib/x86_64-linux-gnu/graphviz"
Activated plugin library: libgvplugin_dot_layout.so.6
Using layout: dot:dot_layout
Activated plugin library: libgvplugin_core.so.6
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
	/usr/lib/x86_64-linux-gnu/graphviz/config6a
		was successfully loaded.
    render	:  cairo dot dot_json fig gd json json0 map mp pic pov ps svg tk vml vrml xdot xdot_json
    layout	:  circo dot fdp neato nop nop1 nop2 osage patchwork sfdp twopi
    textlayout	:  textlayout
    device	:  bmp canon cmap cmapx cmapx_np dot dot_json eps fig gd gd2 gif gtk gv ico imap imap_np ismap jpe jpeg jpg json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp x11 xdot xdot1.2 xdot1.4 xdot_json xlib
    loadimage	:  (lib) bmp eps gd gd2 gif ico jpe jpeg jpg png ps svg xbm

```
