### ISSUE TITLE
Customize syntax color on dark theme

### ISSUE THREAD

**Issue by josedusol** [tlaplus/tlaplus#450]
Hello

First of all, thanks for the new release. Im trying the dark theme. Unfortunately,
when doing proofs, the "color predicates" over the syntax colors are a bit unreadable. This was already
noticed [here](https://github.com/tlaplus/tlaplus/issues/384).

As a possible workaround, the color predicates can be changed. But, is possible to also change keywords colors (THEOREM, BY, DEF, QED, etc)?

Thanks.

**Comment by lemmy** [comment]
To be honest, I don't know because I'm not a user of the dark theme.  Generally, the dark theme has been added in hopes that the community will pick up the effort and move it forward.
