### ISSUE TITLE
Opening menu item "Interesting Obligations"

### ISSUE THREAD

**Issue by AmirHossein-SayyadAbdi** [tlaplus/tlaplus#451]
Hi,
I use the latest version of the toolbox 1.7.0 and when I click on the menu item "Interesting Obligations" under the "TLA Proof Manager", I get a blank page on the right side of the screen.
![Picture 2020-04-28 14_08_57](https://user-images.githubusercontent.com/24325657/80473015-c695f600-895a-11ea-9796-ea02dbe58910.png)

**Comment by lemmy** [comment]
@AmirHossein-SayyadAbdi Can you check that failed obligations show up when you try to prove something, e.g. `THEOREM FALSE OBVIOUS`?  If does here:
![Screenshot from 2020-04-28 08-15-26](https://user-images.githubusercontent.com/88777/80509405-393cac80-892e-11ea-9476-046e7bb12a51.png)

**Comment by AmirHossein-SayyadAbdi** [comment]
Dear @lemmy, I wrote only "THEOREM FALSE OBVIOUS" in my spec and saved it, then I clicked on "Interesting Obligations" and nothing showed up in the right hand side panel. However, I have not installed TLA Proof Manager independently, perhaps that is the reason behind it? When I click "TLAPM Console" an empty console opens.

**Comment by lemmy** [comment]
@AmirHossein-SayyadAbdi The view remains empty/grey as long as there are no failed proof obligations.

**Comment by lemmy** [comment]
To avoid confusion, the console would ideally not be visible until a user installed TLAPS.
