### ISSUE TITLE
When an instance is imported, dot visualization fails due to invalid character `!`

### ISSUE THREAD

**Issue by hatch-carl** [tlaplus/tlaplus#452]
Given `FlipSpec.tla` and `FlopSpec.tla`
```
---- MODULE FlipSpec ----
VARIABLES flip
Init == flip = TRUE
Next == flip' = ~flip
Spec == Init /\ [][Next]_<<flip>>
====
---- MODULE FlopSpec ----
VARIABLES flip
A == INSTANCE FlipSpec WITH flip <- flip
Next == flip' = FALSE
Spec == A!Init /\ [][A!Next \/ Next]_<<flip>>
====
```

If we run a default model from `FlopSpec.tla`'s toolbox with Spec as the temporal formula, and select the option to visualize the state after running, the visualization will not appear. When run manually on the console, `dot,actionlabels,colorize` will report:
```
Error: <stdin>: syntax error in line 137 near '!'
```

As a workaround: 
```
cat Model_1.dot | tr '!' ':' | dot -Tpdf -o out.pdf && open out.pdf
```

**Comment by lemmy** [comment]
Is it possible to escape the `!` character in dot?
