### ISSUE TITLE
Importing Existing TLA Specs

### ISSUE THREAD

**Issue by abakst** [tlaplus/tlaplus#454]
OS: macOS 10.15.4
TLA Toolbox Version: 1.7.0

If I have an existing spec (a *.tla file) and want to import it into the toolbox, the file chooser dialog does not make it clear that this is possible.

This is the current behavior:
1. Create `/path/to/Foo.tla`
2. File > Open Spec... > Add New Spec
3. Click "Browse" to select the root module file
4. Navigate to `/path/to` and double click `Foo.tla` to select it (it will appear greyed out)
5. Click "Save"
6. At this point, a dialog appears with the text "`PModel.tla` already exists. Do you want to replace it?" Click "Replace"
7. Click "Finish" 
8. The model appears imported in the Spec Explorer

This is confusing in a few ways:
- In step 2, "Add New Spec" does not sound like it will permit you to "Import" an existing spec. Perhaps rewording OR adding a new "Import" option would help
- In step 4, greying out the existing file indicates that the file should not be selectable, even though it is. If the file is selectable, it would be clearer if it were not greyed out.
- In step 6, the dialog text is confusing because it indicates that file will be overwritten, even though it won't. Simply updating the text to indicate the actual behavior (the module will be imported) would be helpful.

Thanks!

**Comment by lemmy** [comment]
Workaround: With the Toolbox up an running and `.tla` linked to the Toolbox, double-clicking a spec in Finder directly opens the Toolbox's add-new-spec/import dialog.

1. https://github.com/tlaplus/tlaplus/issues/299
2. & 4. The behavior is dictated by the macOS file chooser and keeps changing with every? new macOS release.

Related: https://github.com/tlaplus/tlaplus/issues/437

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/4fb3d8da7a7f47e664f88ad841831c3bcae6ad92/toolbox/org.lamport.tla.toolbox/src/org/lamport/tla/toolbox/util/UIHelper.java#L679-L690

**Comment by lemmy** [comment]
Please reopen with new insights.
