### ISSUE TITLE
More intuitive error message for out of bounds TupleValue access

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#456]
When TLC tries to access a value at a tuple index that is out of bounds, it print an error message like the following:

```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: Attempted to apply tuple
<<2>>
to integer 2 which is out of domain.
TLC was unable to fingerprint.

Fingerprint Stack Trace:
0) line 170, col 16 to line 182, col 24 of module AtomicTerms

Reason:
Attempted to apply tuple
<<2>>
to integer 2 which is out of domain.
```

I don't think this error message is particularly intuitive, since it doesn't seem natural to say we are "applying a tuple to an integer...". While this technically makes sense when you view tuples as as functions over an integral domain, I think this error message could be improved, especially since we appear to have the necessary type information to know that it is a TupleValue (and not just a plain function) where the error message is [produced](https://github.com/tlaplus/tlaplus/blob/4fb3d8da7a7f47e664f88ad841831c3bcae6ad92/tlatools/org.lamport.tlatools/src/tlc2/value/impl/TupleValue.java#L133-L134). Having the error message say something like:

```
Attempted to access index 2 of tuple <<2>> which is out of domain.
```
would seem clearer.

**Comment by lemmy** [comment]
@will62794 Is this the only instance of non-intuitive error message (I don't assume it is)?  Are you going to open a PR?

**Comment by lemmy** [comment]
Thanks!
