### ISSUE TITLE
Operator Tracing

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/tlaplus#460]
Hi,

I know that it's possible to trace/dump TLC states for all possible "timelines", is there any way to also  trace operators inputs/outputs? I mean, I'd like to see both the states and the input/output of the operators in the dump file.

If there is not, would a PR be welcomed (if it's possible at all to do it)?

Thanks

**Comment by lemmy** [comment]
No, this is not possible.  When would this be useful?

(It's easy to write an AspectJ pointcut to log the parameter when they are passed back and forth Tool.java)

**Comment by pfeodrippe** [comment]
I want to create a dump file where I could see not only the state of the variables, but, between these states, what operators were called (in sequence) and their input and output.

With this file I could create a custom visualizer or replay them in another environment.

I'll check what I can do with your AspectJ alternative, thank you!

**Comment by lemmy** [comment]
In TLA+, a system execution is (fully) represented by a sequence of states. The dump file (additionally) includes action names. I don't understand why you need intermediate values to replay an execution in other environments.

What I think would be generally useful, with regards to intermediate values, if you rename "custom visualizer" to "debugger". That's a feature that users will find useful.

By the way, you can use `Print` to log intermediate values to stdout or create auxiliary variables in your TLA+ spec to record intermediate values.

**Comment by pfeodrippe** [comment]
Debugger is really a better name. Thank you, I will try to follow on one of the alternatives you've said o/

**Comment by lemmy** [comment]
Happy to discuss in-depth if you want to commit to building a real debugger.

**Comment by pfeodrippe** [comment]
> Happy to discuss in-depth if you want to commit to building a real debugger.

Thank you o/ I'll try to have some thoughts about this month (it's hard to think sanely in this quarantine) and give you a shout out. If you have something in mind (a link, a post, a ideia etc), please, let me know.

Obrigado
