### ISSUE TITLE
Regressions: TLC shows no error trace on EvalException thrown by module overrides such as violated TLC!Assert

### ISSUE THREAD

**Issue by rluiten** [tlaplus/tlaplus#461]
I am new to TLA+.
I was trying out the example here. https://www.learntla.com/introduction/example/

On v1.7.0 and the linked nighty v.1.7.1 in another issue I get no values in the Error-Trace field in TLC-Errors panel.
The error-trace is displayed correctly in v1.6.0.
The code I was running in just a simple model with no Invariants or anything extra from the linked example page. I pasted code below to make it reproducible I hope.

Just translate the PlusCAL algorithm and run model, it will report errors but no stack trace, I did notice that the TLC Console is a lot less in v1.7.0. and 1.7.1 than in v1.6.0

I am on windows 10 having tested out v1.6.0, v1.7.0 and v1.7.1.

```
---- MODULE transfer1 ----
EXTENDS Naturals, TLC

(* --algorithm transfer1
variables alice_accountX = 10, bob_account = 10,
          account_total = alice_accountX + bob_account;

process Transfer \in 1..2
  variable  money \in 1..20;
begin
Transfer:
  if alice_accountX >= money then
    A: alice_accountX := alice_accountX - money;
       bob_account := bob_account + money;
end if;
C: assert alice_accountX >= 0;
end process

end algorithm *)

\* BEGIN TRANSLATION


\* END TRANSLATION
====

```

**Comment by lemmy** [comment]
Breaking commits either one of: e183eec864f2612a6e5000dde5dd75b157c67d3f f904e4bccb8104c0e32ca07a17714a83bcbc83b3 fa260e850544a3404dc1cbe74435d53ab9e23521

```bash
markus@avocado:/tmp/tla((no branch, bisect started on master))$ git bisect good
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
e183eec864f2612a6e5000dde5dd75b157c67d3f
f904e4bccb8104c0e32ca07a17714a83bcbc83b3
fa260e850544a3404dc1cbe74435d53ab9e23521
We cannot bisect more!
```

**Comment by lemmy** [comment]
66569d03ca1be31ae1cf3cef0a23b005cbc6ecc3 regresses with regards to error handling of module overrides.

**Comment by lemmy** [comment]
@rluiten Please confirm that the most recent build at https://nightly.tlapl.us/products/ fixes the issue for you.

**Comment by rluiten** [comment]
Looks fine to me, thanks.

**Comment by jeremyh** [comment]
This is quite a frustrating bug for people new to TLA -- it breaks the very first example on a beginners overview. 

I assumed it was my fault for not understanding the interface, and fought with it for a while. Eventually, I found this issue after giving up.

I hope another stable release is planned soon so others don't have to go through this.

**Comment by lemmy** [comment]
@jeremyh What is the beginners overview you are referring to?

**Comment by jeremyh** [comment]
> @jeremyh What is the beginners overview you are referring to?

The one that rluiten mentions above: https://www.learntla.com/introduction/example/

**Comment by lemmy** [comment]
@hwayne @jeremyh I suggest creating regression tests [(see e.g. Github179bTest.java)](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/Github179bTest.java) based on the material of learntla.com and the book Practical TLA+ to prevent similar regressions in the future.
