### ISSUE TITLE
New Java 11 dependency, Java 8 causes "NoSuchMethodError: String.strip()"

### ISSUE THREAD

**Issue by ajdavis** [tlaplus/tlaplus#462]
Running a recent tla2tools.jar on the command line yields an error for me:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.strip()Ljava/lang/String;
  at tlc2.TLC.handleParameters(TLC.java:750)
  at tlc2.TLC.main(TLC.java:245)
```
It appears that https://github.com/tlaplus/tlaplus/commit/4111431a169b96d0b2eb850fd6fb4416cf5af4ff introduced a call to String.strip(), which requires Java 11. Does TLC officially require Java 11 now?

(Low-priority for me: Java 8 was the default on my test machine but I can use Java 11 instead.)

**Comment by lemmy** [comment]
@ajdavis We don't have the bandwidth to guarantee compatibility with old Java VM.  The Toolbox even ships with a VM to make sure users have the right version.

However, I have been conservative WRT > 1.8 features, but this one slipped my attention.
