### ISSUE TITLE
(Question) Stable download links for TLC releases

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#463]
Are the links on the Github releases page (i.e. https://github.com/tlaplus/tlaplus/releases/download/v1.7.0/tla2tools.jar) the proper, stable links to use for an external tool that wants to download a pinned version of the TLC tools to use for model checking? I know there are nightly builds as well but I'm wondering if these are the recommended links to use for downloading version pinned TLC releases.

**Comment by visualzhou** [comment]
To give a little background, we at MongoDB attempted to include model checking in our continuous integration tool - [Evergreen](https://github.com/evergreen-ci), so it's preferred to pin the TLC version. Here's [a successful run](https://evergreen.mongodb.com/task/mongodb_mongo_master_tla_plus_tla_plus_0a5ff5f074b671308c843b4ba6d7195b2591e7d4_20_04_22_00_27_44).

**Comment by lemmy** [comment]
http://dl.tlapl.us/tlatoolbox/dist/tla2tools.jar  (http://tla.msr-inria.inria.fr/tlatoolbox/dist/tla2tools.jar)
http://nightly.tlapl.us/dist/tla2tools.jar

**Comment by ajdavis** [comment]
Thanks - and if we want a long-lived link for 1.7.0 specifically, should we use the GitHub link?

**Comment by lemmy** [comment]
Depends if you want to depend on Github or INRIA. By the way, `dl.tlapl.us` redirects to `tla.msr-inria.inria.fr` so you might use `tla...` directly to remove `tlapl.us` as a source of failure.

**Comment by lemmy** [comment]
Given that tla2tools.jar is 2mb, you might also go 0-depedencies and add it to your repository.
