### ISSUE TITLE
P-style PlusCal templates for content assist

### ISSUE THREAD

**Issue by lcao0319** [tlaplus/tlaplus#464]
While on module editor, the current template does not set up user for a start right away. the current template is:
(***************************************************************************
--algorithm AlgorithmName {
}
***************************************************************************)

A more sensible template could be: 
(*--algorithm AlgorithmName
end algorithm;*)

I have a patch in my fork. Please let me know how to contribute.

**Comment by lemmy** [comment]
"The additional wordiness of the p-syntax makes the meaning of the code clearer, and its use of explicit ends instead of “}”s makes it easier to find syntax errors. However, the c-syntax version is shorter, and sensible formatting makes the meaning of the code clear enough. You may prefer the
c-syntax version if you’re used to programming in a language derived from C, such as C++, C#, or Java." (https://lamport.azurewebsites.net/tla/c-manual.pdf)

**Comment by lcao0319** [comment]
Maybe we should give the user the choices of selecting a p-syntax or c-syntax when she presses Control-space (the default key combination for invoking content assist). The popup menu should contain two entries: one for p- and one for c-style.

**Comment by lemmy** [comment]
That would be overly verbose and likely lead to an unintended mixture of P and C syntax.  A Toolbox-wide or per-spec preference should work better, but would only make sense if the completion supports the same set of proposals for the P syntax than it does for the C-syntax.

**Comment by lcao0319** [comment]
I am glad we are talking about the usability of the toolbox :-) A preference will be very nice. Or something gives IDE directions on what set of templates to use. Maybe the New Spec wizard can have a radio button for this choice. Then the IDE consistently use one set of completion proposals for that spec.

I see now that my pull request is premature without considering the two-style complexity. Should we close this and write another issue/feature request?

**Comment by lemmy** [comment]
Since here is where the discussion started, let's just continue to use this issue.

**Comment by lemmy** [comment]
Please reopen if you want to work on this.
