### ISSUE TITLE
Generating State Graph Visualization - java heap space - does JVM arguments apply?

### ISSUE THREAD

**Issue by CThuleHansen** [tlaplus/tlaplus#466]
Hi.

So I am trying to generate a rather big state graph visualization, and I run into 
```
An internal error occurred during: "Generating State Graph Visualization...". Java heap space.
```

My question is - does the JVM arguments in TLC Options also apply to the generating state graph visualization action?

Here, I have set `Xmx15g` to increase the jvm heap size

**Comment by lemmy** [comment]
The Toolbox's state graph visualization isn't meant for large graphs.   Instead, uncheck the Toolbox's visualization and have TLC write the `.dot` file by passing `-dump dot foo.dot` as a `TLC command line parameter`on the `TLC options` page of the model editor (iff `foo` matches the model name, the Toolbox will attempt to render it).

https://github.com/mryndzionek/tlaplus_specs shows how to beautifully render dot files on the command line, but you might also want to try [Gephi](https://gephi.org/), [Cytoscape](https://cytoscape.org/), ...

Let me know how it goes.
