### ISSUE TITLE
"self" operator not defined when only one process is declared

### ISSUE THREAD

**Issue by cwagner2046** [tlaplus/tlaplus#468]
Minor problem I would think: When only one process is declared (in a PlusCal program), the "self" operator is reported as being unknown by the TLA+ Parser.

Example of program:
```tla
EXTENDS TLC, Naturals
(* --algorithm conccurency_0 { \* C-style PlusCal program
  variable a=1;
  process (p1 = 1)
  {
      A: print self;
  }
}
```

I'm currently learning TLA+ using H. Dwayne's Learn TLA+ website and L. Lamport's c-manual.pdf. So I often try out code snippet inspired by these resources - like the program above (see also the second example at https://www.learntla.com/concurrency/processes/). In none of these 2 resources did I see a mention that "self" should be defined only in the case of multiple processes.

The parser's error message reads "unknown operator: 'self'".

**Comment by cwagner2046** [comment]
I forgot to mention: I'm using the Toolbox Version 1.7.0 on a Macbook running Yosemite (Mac OS/X 10.10.5)

**Comment by lemmy** [comment]
`self` is not an operator in the TLA+ translation of a *multi-process* PlusCal algorithm, but a bound variable in the next-state relation and an argument/parameter of the TLA+ action:

```tla
(***************************************************************************
--algorithm AlgorithmName {
  process (A \in {"a"}) {
      label: print self;
  };
}
***************************************************************************)
\* BEGIN TRANSLATION 
...
A(self) == /\ pc[self] = "label"
           /\ PrintT(self)
           /\ pc' = [pc EXCEPT ![self] = "Done"]

Next == (\E self \in {"a"}: A(self))
...
```
For a uni-process algorithm, the TLA+ next-state relation simply is:

```tla
(***************************************************************************
--algorithm AlgorithmName {
  process (A = "a") {
      label: print "self";
  };
}
***************************************************************************)
\* BEGIN TRANSLATION
...
A == /\ pc["a"] = "label"
     /\ PrintT("self")
     /\ pc' = [pc EXCEPT !["a"] = "Done"]

Next == A
...
```

Thus, if you want the translator to generate `self`, simply write `process (A \in {"a"})` in the PlusCal algorithm.  The meaning of the two specs is the same.
