### ISSUE TITLE
The toolbox doesn't see my checkpoint

### ISSUE THREAD

**Issue by kbr-** [tlaplus/tlaplus#469]
Hi,

I'm running TLA+ Toolbox 1.7.0 downloaded from the [releases](https://github.com/tlaplus/tlaplus/releases) page.
My system is Ubuntu 19.10 with kernel 5.3.0-51-generic, if that helps.

I've been model checking my spec a few days ago on my laptop. I wanted to pause the model checking and resume it later, so I closed the Toolbox "forcibly" with an interrupt. I did this on an older version (1.5.3) and it worked, leaving behind a checkpoint which I could then resume my model checking from (simply cancelling model checking doesn't leave a checkpoint; not the best UX, but not the point of this issue). 

Now the problem is that the Checkpoint ID field is empty, as if no checkpoint existed:
![image](https://user-images.githubusercontent.com/6516501/83944941-83eff500-a807-11ea-9f28-009b701f265c.png)
And, of course, selecting "Recover from checkpoint" complains that no checkpoint data was found.

However, the Model Checking Results page proves that indeed there was a checkpoint taken:
![image](https://user-images.githubusercontent.com/6516501/83944948-9833f200-a807-11ea-8612-b4e4855ecb26.png)

The same is suggested by "Storage:"
![image](https://user-images.githubusercontent.com/6516501/83944959-a97cfe80-a807-11ea-993b-4a51debd28c4.png)

And an appropriate directory indeed does exist in my Model directory and takes up the expected amount of space:
![image](https://user-images.githubusercontent.com/6516501/83944997-e21cd800-a807-11ea-9eee-617605f41938.png)

**Comment by lemmy** [comment]
IIRC sending an interrupt to the Toolbox (or the forked TLC process) does not trigger a checkpoint.  Instead, TLC takes checkpoints periodically (every 15 minutes by default).  You can, however, trigger a checkpoint and gracefully terminate model-checking through JMX.

This said, it sounds as if recovering from checkpoints is generally broken in recent Toolbox version.
