### ISSUE TITLE
Trace Explorer does not show trace

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#47]
@ahelwer: "I installed 1.5.3, and on a fairly complicated spec it does not display the error trace in the GUI:

Double-clicking those states does nothing and provides no further details. Weirdly, if I look inside MC.out I see the state trace just fine:

@!@!@STARTMSG 2110:1 @!@!@
Invariant inv_149384363400123000 is violated.
@!@!@ENDMSG 2110 @!@!@
@!@!@STARTMSG 2121:1 @!@!@
The behavior up to this point is:
@!@!@ENDMSG 2121 @!@!@
@!@!@STARTMSG 2217:4 @!@!@
1: <Initial predicate>
/\ IsNodeUp = (n1 :> TRUE @@ n2 :> TRUE @@ n3 :> TRUE)
/\ NetworkPath = ( <<n1, n1>> :> TRUE @@
  <<n1, n2>> :> TRUE @@
  <<n1, n3>> :> TRUE @@
  <<n2, n1>> :> TRUE @@
  <<n2, n2>> :> TRUE @@
  <<n2, n3>> :> TRUE @@
  <<n3, n1>> :> TRUE @@
  <<n3, n2>> :> TRUE @@
  <<n3, n3>> :> TRUE )
/\ LockTimeout = FALSE
/\ BackupLock = None
/\ IsTakingBackup = (n1 :> FALSE @@ n2 :> FALSE @@ n3 :> FALSE)
/\ Leader = None

@!@!@ENDMSG 2217 @!@!@
@!@!@STARTMSG 2217:4 @!@!@
2: <Action line 138, col 24 to line 138, col 37 of module NodeBackup>
/\ IsNodeUp = (n1 :> TRUE @@ n2 :> TRUE @@ n3 :> TRUE)
/\ NetworkPath = ( <<n1, n1>> :> TRUE @@
  <<n1, n2>> :> TRUE @@
  <<n1, n3>> :> TRUE @@
  <<n2, n1>> :> TRUE @@
  <<n2, n2>> :> TRUE @@
  <<n2, n3>> :> TRUE @@
  <<n3, n1>> :> TRUE @@
  <<n3, n2>> :> TRUE @@
  <<n3, n3>> :> TRUE )
/\ LockTimeout = FALSE
/\ BackupLock = None
/\ IsTakingBackup = (n1 :> FALSE @@ n2 :> FALSE @@ n3 :> FALSE)
/\ Leader = n1

@!@!@ENDMSG 2217 @!@!@
(and so on)

It just doesn't appear to make its way into the error trace in the GUI.
![traceexplorer](https://cloud.githubusercontent.com/assets/88777/25694774/7ced3ac8-30b0-11e7-9dde-271ad16bdec0.png)"

**Comment by lemmy** [comment]
@ahelwer This is fixed in the most recent [nightly build](http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/). In the meantime, rename "NodeBackup" to something without "Back", e.g. "Nodebackup".

**Comment by ahelwer** [comment]
Thanks for the quick response!
