### ISSUE TITLE
How to generate a unique name per thread

### ISSUE THREAD

**Issue by lvanengelen** [tlaplus/tlaplus#474]
I have been using TLA+ to generate traces that I export to a file, as described here: https://github.com/tlaplus/CommunityModules/issues/5#issuecomment-584429753. Currently I use `IOExec` with a small shell script that uses the PID (Process Identifier) to make the output filename unique:

```sh
echo "$1" > "./generated-states/state_$$.json
```

This depends on PIDs being unique during the whole simulation, which I would like to avoid. To that end I think I can use `TLCSet/TLCGet` to have an increasing unique number for each export. However, I would like to be able to make use of multiple worker threads. Is there already a way to get a value unique to each thread that I can use in the filename?

If not, I see two ways of adding this functionality:
1. Add another string value for `TLCGet`, e.g. 'thread' returning the thread ID and return the thread id from here: https://github.com/tlaplus/tlaplus/blob/d62b289/tlatools/org.lamport.tlatools/src/tlc2/module/TLC.java#L178
2. Add an operator to a community module like `TLCExt` returning the value of `Thread.getId()`.
What would be the preferred approach? I could try to implement it if necessary. As it is multithreaded code, is there any gotcha I might be overlooking?

**Comment by lemmy** [comment]
I'm afraid I don't understand your scenario because the term "simulation" makes it sound as if you are running TLC in simulation mode.   Also, what's the process of which you use the PID?


That said, adding a "named register" to TLCGet that equals the value of `IdThread.getId` is probably fine (let's call it "worker" and not something related to "thread").  However, I suggest that you check if this feature actually addresses your scenario (the set of TLC workers that generate the states of a single behavior is non-deterministic).

**Comment by lemmy** [comment]
Btw. with regards to the `Trace` operator: 31f66d03ce46822b711e4d94132e1518080f2777

**Comment by lvanengelen** [comment]
> I'm afraid I don't understand your scenario because the term "simulation" makes it sound as if you are running TLC in simulation mode. Also, what's the process of which you use the PID?
Sorry, I meant model checking.

Trying to explain myself a bit more clearly.

I have a model similar to something like this (think of it as some database system with objects that can be committed, etc.)

```
CONSTANT MaxSteps
VARIABLES initialState, state, steps

InitialStates == \* some big set with allowed initial states

Init == /\ state \in InitialStates
        /\ initialState = state
        /\ steps = <<>>

Next == UNCHANGED <<initialState>> /\ IF Len(steps) < MaxSteps
        THEN
          /\ \/ \E obj \in ObjectIds: /\ Commit(obj)
                                      /\ steps' = Append(steps, [step |-> "Commit",
                                                                 obj  |-> obj])
             \/ \* ... a bunch of similar action transitions

        ELSE
          UNCHANGED <<state, steps>>

Invariant == LET
  Run == [startState |-> initialState,
          endState |-> state,
          steps |-> steps]

  Json == ToJsonObject(Run)

  Result == IOExec(<<"./export.sh", Json>>)
IN
  Result.exitValue = 0
```

Each state represents a possible execution scenario with start and end states and the steps that were taken to get there. The invariant is used to export each of these to a file using `ToJsonObject` and `IOExec`. These files are later loaded in a unit testing framework to execute tests against a real system: for each entry the start state is setup, the steps are run and the system state is compared to the end state.

For export I need a unique filename to avoid overwriting any previously written file. I use `IOExec` to run a shell script which stores its argument to a file named after the PID of the shell process running the script:
```sh
#!/bin/sh

# export.sh
echo "$1" > "./generated-states/state_$$.json
```
where `$$` is a special variable containing the PID. The PID is only unique for the runtime of the script (i.e. very short) and I want to avoid files overwriting earlier ones.

The alternative approach I had in mind is using `TLCGet`/`TLCSet` to keep track of an increasing counter, incremented for each evaluation of the invariant. That would work when using a single worker, but not if using multiple ones, because each worker has its own copy of the counter, i.e. the counter would not be unique. If I would have some unique worker identifier, I could use the pair `<<worker, counter>>` to uniquely name a file. Having a unique identifier `stateid`, for each (unique) state would also work I think. Then I could use `stateid` to name the file.

Today I came up with another approach: calculating a checksum (SHA1 or whatever) in the script and use that as the filename, which seems to work ok-ish, but it still seems useful to have some unique identifier available for each state or thread.

I hope I explained myself clearer now.

What do you mean with 
> the set of TLC workers that generate the states of a single behavior is non-deterministic

Do you mean that the states of a single behavior can be generated by different threads? That should be ok as just having a unique identifier for each state seems good enough for my scenario.

**Comment by lemmy** [comment]
If all you need are unique values, have you looked at `TLC!JavaTime` or `TLC!RandomElement` `TLC!RandomElement(0..9999999)`?

**Comment by lemmy** [comment]
Please reopen if https://github.com/tlaplus/tlaplus/issues/474#issuecomment-648261279 does not address the issue.

**Comment by lemmy** [comment]
Related: https://github.com/lemmy/formal-methods-playground/commit/d556d6e62fa59d18b07a38d4d8de87b9f33d387c
