### ISSUE TITLE
Unify behavior of command-line and Toolbox trace exploration

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#475]
`Untitled.tla`
```tla
------------------------------ MODULE Untitled ------------------------------
EXTENDS TLC, Naturals

VARIABLE x

Init == 
  x = 0

Next == 
  \/ x' = 1 \/ x' = 2 \/ x' = 3 \/ x' = 4 
  \/ x' = 5 \/ x' = 6 \/ x' = 7 \/ x' = 8

Spec ==
  /\ Init
  /\ [][Next]_x
\*  /\ WF_x(Next) 

Inv == TLCGet("level") >= 0

Prop == <>(x = 8)
====
```

`TE.tla`
```tla
---- MODULE TE ----
EXTENDS Untitled, Toolbox, TLC
...
\* TRACE Sub-Action definition 0
next_sa_0 ==
     /\ x = 0
     /\ x' = 5

\* TRACE Sub-Action definition 1
next_sa_1 ==
     /\ x = 5
     /\ x' = 5

init_159353580269542000 ==
    /\ x = 0

next_159353580269543000 ==
    \/ next_sa_0
    \/ next_sa_1

\* PROPERTY definition
prop_159353582168246000 ==
~<>[](x = (5))
=============================================================================
```

`TE.cfg`
```
...
INIT init_159353580269542000
NEXT next_159353580269543000
PROPERTY prop_159353582168246000 \* Defined in TE.tla and specific to the error trace.
```

`SpecTE.tla`
```tla
---- MODULE SpecTE ----
...
Inv == TLCGet("level") >= 0

Prop == <>(x = 8)

\* TRACE Sub-Action definition 0
Spec_sa_0 ==
        /\ x = 0
        /\ x' = 5

\* TRACE Sub-Action definition 1
Spec_sa_1 ==
        /\ x = 5
        /\ x' = 5

\* TRACE INIT definition traceExploreInit
_SpecTEInit ==
    /\ x = 0

\* TRACE NEXT definition traceExploreNext
_SpecTENext ==
/\  \/ Spec_sa_0
    \/ Spec_sa_1
============================================================================
```

`SpecTE.cfg`
```
INVARIANT Inv    \* Defined in Untitled.tla and not relevant for this error trace.
PROPERTY Prop \* Defined in Untitled.tla
INIT _SpecTEInit
NEXT _SpecTENext
...
```

The old `TE.tla` checks property `prop_159353582168246000` whereas `SpecTE.tla` checks the original property `Prop` defined in spec `Untitled.tla`.  I don't have time to come up with a spec where this causes TLC trace exploration on the command-line to fail in producing an error trace, but the code should be unified anyway.

Additionally, with https://github.com/tlaplus/tlaplus/commit/7a3201242b187668226ae8525bfaeeba320dddde, `SpecTE.tla` still expects the behavior to deadlock for TLC to produce the same error trace.  However, it should generate an invariant like in `TE.tla`.

**Comment by lemmy** [comment]
@quaeler Is the different behavior of trace exploration on the command-line just an oversight?

**Comment by quaeler** [comment]
ooph - i have no recollection. i can try and look at the commits and the code this weekend to see if it jogs my memory.

**Comment by lemmy** [comment]
Thanks that would be appreciated!

**Comment by lemmy** [comment]
FWIW: The Toolbox already has functionality to generate an invariant (only safety) that is violated by the final/terminal state.  Another variant could be defined in terms of `_TETrace`:

```tla
_SpecTEInv ==
\* For each of the spec's vars gen...
/\ v1 # _TETrace[Len(_TETrace)].v1
/\ v2 # _TETrace[Len(_TETrace)].v2
...
```

**Comment by quaeler** [comment]
on initial blush, and excusing everything i've forgotten in the past few months, `TraceExplorerDelegate` relies upon [TraceExpressionModelWriter](https://github.com/tlaplus/tlaplus/blob/7a3201242b187668226ae8525bfaeeba320dddde/toolbox/org.lamport.tla.toolbox.tool.tlc/src/org/lamport/tla/toolbox/tool/tlc/model/TraceExpressionModelWriter.java) which trivially subclasses the thing command line is using.. so i'm not sure where the non-unification is stumbling.

**Comment by quaeler** [comment]
after wandering around the historical commits, nothing has jogged my memory as to why this non-unification exists - so it must be an oversight (though, to be honest, i can't assemble a completely coherent picture in my mind of the re-architecture based on the commit messages, and the working part of my brain assigned to codebases has been largely overwritten at this point.. so this conclusion is equal parts deduction, and capitulation!)
