### ISSUE TITLE
Evaluate alias expression on pair of states s and t in error-trace and printed in place of s

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#485]
```tla
---- CONFIG Alias ----
SPECIFICATION FairSpec
INVARIANT Inv
PROPERTY Prop
ALIAS Alias
======================

---- MODULE Alias ----
EXTENDS Integers, TLC, Sequences

VARIABLES x, y
vars == <<x,y>>

Next == /\ y' = ~y
        /\ \/ /\ x < 4
              /\ x' = x + 1
           \/ /\ x = 4
              /\ x' = 1

Spec == x = 1 /\ y = FALSE /\ [][Next]_vars

FairSpec == Spec /\ WF_vars(Next)

Inv == x < 4

Prop == <>(x > 4)

Animation(e1,e2) == "e1: " \o ToString(e1) \o " e2: " \o ToString(e2)

\* An expression that is evaluated on the pair of states
\* s and t and printed in place of s in an error trace.
\* Useful to:
\* - filter out variables (not shown below)
\* - rename variables
\* - map variables (e.g. animation)
\* - additional trace expressions
\* TLC ignores the original state if the evaluation of
\* Alias fails.
Alias == [y |-> y, \* x and y reordered.
          x |-> x, 
          a |-> x' - x, 
          b |-> x' = x,
          anim |-> Animation(x, y), \* Animation
          te |-> ENABLED Next]      \* Trace Expression

AliasEq ==
     "y" :> y @@
     "x" :> x @@
     "a" :> x' - x @@
     "b" :> x' = x @@
     "anim" :> Animation(x, y) @@
     "te" :> ENABLED Next
=======================
\* FairSpec => []Inv
Error: Invariant Inv is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
/\ y = FALSE
/\ x = 1
/\ a = 1
/\ b = FALSE

State 2: <Action line 11, col 34 to line 11, col 46 of module Alias>
/\ y = TRUE
/\ x = 2
/\ a = 1
/\ b = FALSE

State 3: <Action line 11, col 34 to line 11, col 46 of module Alias>
/\ y = FALSE
/\ x = 3
/\ a = 1
/\ b = FALSE

State 4: <Action line 11, col 34 to line 11, col 46 of module Alias>
/\ y = TRUE
/\ x = 4
/\ a = 0     \* Stuttering
/\ b = TRUE  \* Stuttering

-------------------------------
\* Spec => Prop
Error: Temporal properties were violated.
Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ y = FALSE
/\ x = 1
/\ a = 0     \* Stuttering
/\ b = TRUE  \* Stuttering

State 2: Stuttering

-------------------------------
\* FairSpec => Prop
Error: Temporal properties were violated.
Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ y = FALSE
/\ x = 1
/\ a = 1
/\ b = FALSE

State 2: <Next line 17, col 9 to line 21, col 23 of module Alias>
/\ y = TRUE
/\ x = 2
/\ a = 1
/\ b = FALSE

State 3: <Next line 17, col 9 to line 21, col 23 of module Alias>
/\ y = FALSE
/\ x = 3
/\ a = 1
/\ b = FALSE

State 4: <Next line 17, col 9 to line 21, col 23 of module Alias>
/\ y = TRUE
/\ x = 4
/\ a = -3      \* State 1 is successor
/\ b = FALSE   \* State 1 is successor

Back to state 1: <Next line 17, col 9 to line 21, col 23 of module Alias>

-------------------------------

```

(The `Alias` feature would perhaps have helped with https://github.com/dgpv/bip32_template_parse_tplaplus_spec/issues/1)

**Comment by lemmy** [comment]
Makes the following (complex) Toolbox code obsolete:

org.lamport.tla.toolbox.tool.tlc.output.data.TraceExplorerDataProvider.processTraceForTraceExplorer()
org.lamport.tla.toolbox.tool.tlc.output.data.TLCError.applyFrom(TLCError, Map<String, Formula>, Hashtable<String, TraceExpressionInformationHolder>, String)
org.lamport.tla.toolbox.tool.tlc.output.data.TLCError.applyFrom(Map<String, Formula>, Hashtable<String, TraceExpressionInformationHolder>, TLCState, TLCVariable[], TLCVariable[])

**Comment by lemmy** [comment]
@will62794 Change is related to animations, please comment.

**Comment by lemmy** [comment]
Issues:

* `_TEPosition` and `TLCGet(..)` behave funny
* Not implemented for DFID and simulation mode

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/f5306c601a2133ebffad6224db93c16663fe5ff5

**Comment by lemmy** [comment]
Quickly generate animations:

`java -cp /opt/toolbox/tla2tools.jar:CommunityModules.jar tlc2.TLC -simulate num=1 -depth 32001 -config AsyncGameOfLife.cfg AsyncGameOfLifeAnim.tla | grep anim | sed 's;anim = ;anim |-> ;g' | xclip`

![Peek 2020-07-09 17-55](https://user-images.githubusercontent.com/88777/87104773-c6915c80-c20d-11ea-90ca-d34cba478088.gif)

**Comment by lemmy** [comment]
Simplified creation of animations without the [bottleneck of a browser](https://github.com/will62794/tlaplus_animation/issues/3):

https://github.com/lemmy/tlaplus_specs/blob/master/AsyncGameOfLifeAnimGlider.tla

**Comment by lemmy** [comment]
@ahelwer This Alias feature is perhaps even better suited for https://github.com/alygin/vscode-tlaplus/issues/119 than https://github.com/tlaplus/tlaplus/issues/393.

**Comment by lemmy** [comment]
```java
		final String aliasHelp = "TLC allows the cfg file to contain the statement ALIAS R\n" + 
				"where R is the definition of a record in the spec or the model.  R's\n" + 
				"component expressions can be formed from constant-, state-, and\n" + 
				"action-level expressions.\n" + 
				"When printing an error-trace, TLC evaluates the record R on every step\n" + 
				"(pair or states s -> t) of the behavior that violated the property.\n" + 
				"TLC prints the result r of the evaluation of R in place of s by formatting\n" +
				"each component h_i of r as a conjunct s.t. (\"h_i\" = r[\"h_i\"]).\n" +
				"If the evaluation of R fails for a step, TLC falls back to printing s.\n\n"
				+ "Consider  ALIAS R  with\n" + 
				"\n" + 
				"   R == [x |-> x+1, sum |-> x + y', te |-> ENABLED A]\n" + 
				"\n" + 
				"for a state s with x = 42 and y = 24, a (successor) state t with\n" +
			    "x = 23 and y = -42, and action A defined as x' \\in Nat /\\ y' \\in Nat\n" +
				"will print s as\n" + 
				"   \n" + 
				"    /\\ x = 43\n" + 
		        "    /\\ sum = 0\n" + 
		        "    /\\ te = TRUE";
```

https://github.com/tlaplus/tlaplus/commit/d3cfde5a37d943b95a354d40ad60b8bef07411b2#diff-bca27abf950d8004d8807798d7fc3a4f31f932ba0ad5c480dd3140662db9637eR407-R426

**Comment by ajdavis** [comment]
What's the purpose of the `AliasEq` operator in the example at the top of this issue?

**Comment by lemmy** [comment]
`AliasEq` is just a syntactic variant of `Alias.

**Comment by lemmy** [comment]
@JoshuaRowePhantom suggested renaming the `ALIAS` keyword for clarity (`VIEW` was unfortunately taken).  While I believe it is too late to rename `ALIAS`, we could introduce a synonym in TLC's config file.  What would be a more descriptive keyword?

/cc @frankshearar

**Comment by lemmy** [comment]
You can get this and more with a feature described in https://github.com/tlaplus/tlaplus/commit/1327ddb5c281128d8d69eaaf97d71b7ae20856a5 which was part of https://github.com/tlaplus/tlaplus/issues/640.

**Comment by kuujo** [comment]
FYI this feature is wonderful for debugging refinement mappings.

**Comment by lemmy** [comment]
The record syntax does not support referencing other keys of a record such as `diff` by `changes` in

```tla
Alias ==
  [ x |-> x, diff |-> x' # x, changes |-> diff # diff' ]
```

However, we can work around it with a LET/IN:

```tla
Alias ==
  LET v == [ x |-> x, diff |-> x' # x ]
      derived == [ changes |-> v.diff # v.diff' ]
  IN v @@ derived
```

**Comment by lemmy** [comment]
Examples of what Alias and a few minor changes enable: https://github.com/microsoft/CCF/pull/5904#issuecomment-1885182087
