### ISSUE TITLE
Model does not find variables in Module.

### ISSUE THREAD

**Issue by danwt** [tlaplus/tlaplus#486]
For a spec, no variables are found despite them being there

![Screenshot 2020-07-09 at 09 46 44](https://user-images.githubusercontent.com/30197399/87018445-26b1df80-c1c9-11ea-9dbc-af4e6bac2ff6.png)

where the spec is

```
EXTENDS TLC
CONSTANTS Nodes, NULL
INSTANCE LinkedLists

(*--fair algorithm tortoise_and_hare
variables
  ll \in LinkedLists(Nodes),
  tortoise = First(ll),
  hare = tortoise;
  
macro advance(pointer) begin
  pointer := ll[pointer];
  if pointer = NULL then
    assert ~Cyclic(ll);
    goto Done;
  end if;
end macro;

begin
  while TRUE do
    advance(tortoise);
    advance(hare);
    advance(hare);
    if tortoise = hare then
      assert Cyclic(ll);
      goto Done;
    end if;
  end while;
end algorithm; *)
```

**Comment by lemmy** [comment]
Your spec doesn't have a module header and footer (https://www.reddit.com/r/tlaplus/comments/hl4bpt/stuck_on_no_behavior_spec/) nor does it appears as if you translated the PlusCal to TLA+ with the Toolbox's PlusCal translator.

**Comment by lemmy** [comment]
Please reopen should https://github.com/tlaplus/tlaplus/issues/486#issuecomment-656157479 not address the issue.
