### ISSUE TITLE
Model Checker can't display sets containing both strings and numbers

### ISSUE THREAD

**Issue by tangentstorm** [tlaplus/tlaplus#488]
Attempting to evaluate the expression: `{0, "1"}` in the model checker gives:

> The `Evaluate Constant Expression� section�s evaluation failed.
> 
> Attempted to apply the operator overridden by the Java method
> public static tlc2.value.impl.Value tlc2.module.TLC.PrintT(tlc2.value.impl.Value),
> but it produced the following error:
> Attempted to compare string "1" with non-string:
> 0

Given that it's coming from a function called PrintT, it makes me think TLC has correctly constructed the set, but simply doesn't know how to display it.

**Comment by lemmy** [comment]
Forget about `PrintT` and the technical details like lazy evaluation and instead, notice that `0 = "1"` is undefined.

**Comment by lemmy** [comment]
Please re-open if questions remain.
