### ISSUE TITLE
Error trace not shown for assertion in fair process

### ISSUE THREAD

**Issue by fabric-and-ink** [tlaplus/tlaplus#492]
I have defined a simple pluscal spec with a fair process that contains an assertion. This assertion is violated, however no error trace is shown in the toolbox 1.7.0, whereas I get an error trace in 1.6.0. Below is a simple example where no error trace is shown for me. I have a more complex spec, where I found an assertion error during model checking but have no way in understanding the individual steps to reach the violation with the current version.

```
EXTENDS TLC

(*--algorithm test

fair process bla = "bla"
variable
    x = 1;
begin
Go: assert x = 0;
end process;
end algorithm;*)
```

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/461

**Comment by fabric-and-ink** [comment]
Ok. I won't verify additionally that this works on master.

**Comment by lemmy** [comment]
"won't" or "will"?

**Comment by fabric-and-ink** [comment]
Sorry, I hope I didn't sound harsh. I meant that it seems to be fixed and that is fine for me.
