### ISSUE TITLE
Where is the "Checkpoint ID"?

### ISSUE THREAD

**Issue by josedusol** [tlaplus/tlaplus#495]
Hello,

After doing model checking for a few hours, i want to start it again from last checkpoint. I know there is a checkpoint because every 30min one is created, and it has an associated folder.
I suppose to start from checkpoint, i just need to select "Recover from checkpoint" option in the toolbox. But i also need to set "Checkpoint ID", which i don't know. 
The doc says "Toolbox will fill in the Checkpoint id for you", but apparently it didn't.

So, my question is, where is the "Checkpoint ID" or how to instruct TLC to run from checkpoint?.

**Comment by lemmy** [comment]
Do you have the fix for https://github.com/tlaplus/tlaplus/issues/469?

**Comment by josedusol** [comment]
> Do you have the fix for #469?


Thanks, i had not seen that. But it was fixed on 1.7.1?, because i am on that version.

**Comment by lemmy** [comment]
There is no 1.7.1 release yet but every nightly since https://github.com/tlaplus/tlaplus/commit/a754d8d1d045416e33f2e750a70d43a5fcc1974a has the fix.

Can you list the output of your Model_1 directory (or whatever name your model has)?

**Comment by josedusol** [comment]
It is called "mc":
```
drwxr-xr-x 1 josedu 197610     0 Aug  5 23:24 ./
drwxr-xr-x 1 josedu 197610     0 Aug  6 17:17 ../
drwxr-xr-x 1 josedu 197610     0 Aug  6 02:58 20-08-05-23-24-34/
-rw-r--r-- 1 josedu 197610  2884 Aug  5 20:25 boot1.tla
-rw-r--r-- 1 josedu 197610  7284 Aug  5 22:56 boot2.tla
-rw-r--r-- 1 josedu 197610   364 Jul 31 16:38 Main.tla
-rw-r--r-- 1 josedu 197610   712 Aug  5 23:24 MC.cfg
-rw-r--r-- 1 josedu 197610 43941 Aug  6 03:01 MC.out
-rw-r--r-- 1 josedu 197610  1520 Aug  5 23:24 MC.tla
-rw-r--r-- 1 josedu 197610 43941 Aug  6 03:01 MC_TE.out
-rw-r--r-- 1 josedu 197610  1245 Aug  3 02:13 pcr_base.tla
-rw-r--r-- 1 josedu 197610  3015 Aug  3 02:14 pcr_cl.tla
-rw-r--r-- 1 josedu 197610  3214 Aug  3 02:15 pcr_cw1.tla
-rw-r--r-- 1 josedu 197610  4339 Aug  5 18:07 pcr_cw2.tla
```

**Comment by lemmy** [comment]
Can you run the Toolbox in debug mode and check what happens in `org.lamport.tla.toolbox.tool.tlc.model.Model.getCheckpoints(boolean)`?

**Comment by lemmy** [comment]
@josedusol Have you been able to pinpoint the issue?

**Comment by josedusol** [comment]
> Can you run the Toolbox in debug mode and check what happens in `org.lamport.tla.toolbox.tool.tlc.model.Model.getCheckpoints(boolean)`?

Sorry the delay. Is debug mode supposed to start with `-debug` argument?

**Comment by lemmy** [comment]
Sorry for the confusion.  What I meant was to run the Toolbox in Eclipse with Eclipse's debug mode.

**Comment by josedusol** [comment]
> Sorry for the confusion. What I meant was to run the Toolbox in Eclipse with Eclipse's debug mode.

Ok. I can launch the toolbox from Eclipse. But i can do anything in package explorer because of:

![image](https://user-images.githubusercontent.com/17714269/90061013-ed82f880-dcbb-11ea-9f5c-b176226f8ff4.png)

Another "problem" is:

![image](https://user-images.githubusercontent.com/17714269/90061257-46529100-dcbc-11ea-869f-58575a3d5ddb.png)

**Comment by lemmy** [comment]
What's your Java version? You want Java 11.

**Comment by josedusol** [comment]
> What's your Java version? You want Java 11.

Yes, but i forgot Eclipse doesn't read JAVA_HOME, and was initially installed with Java 14. 

Well, im testing a spec with checkpoint folder. When i open the model in toolbox, `getCheckpoints(boolean)` returns an empty array of checkpoint directories. I will try to go more in depth to figure out why.

BTW, i have the fix for #469.

**Comment by lemmy** [comment]
@josedusol Are you still on it?

**Comment by josedusol** [comment]
> @josedusol Are you still on it?

No. Unfortunately i couldn't reproduce it anymore. I'm closing this for now.
