### ISSUE TITLE
Add ability to export raw TeX from the Toolbox instead of just PDF. 

### ISSUE THREAD

**Issue by Tombert** [tlaplus/tlaplus#499]
As it stands, within the Toolbox, you can only produce a PDF version of the specification you're working on. 

Since the PDF version is using pdflatex behind the scenes anyway, I think there should be an option under File to export out the raw TeX, so that it may be more-easily used within a research paper without having to finagle with using command-line tools or grab it out of the `.toolbox` folder.

**Comment by Tombert** [comment]
I would do it myself but the company I work for (who shall remain nameless) has a really strict non-compete, so I cannot contribute without putting myself (or the project) into legal trouble.

**Comment by lemmy** [comment]
To confirm:  What you propose already exists except that it creates a PDF as the byproduct?  In other words, you can  already export to PDF and grab the `.tex` file from the `Model.toolbox` folder.

**Comment by Tombert** [comment]
Yes, obviously the PDF is useful, but I want to grab the TeX to be included with a separate paper that I'm writing. 

The `Model.toolbox` folder thing works, but it's not 100% intuitive; I had to ask on the TLA+ google group to find out about that fact, and I had initially assumed that the TeX file would be right next to the PDF file in the folder. 

I imagine that I'm not the only person to have this problem, so I think having an option to export the TeX, by either allowing the user to provide a path or just having a button to plop it next to the PDF file would be useful.
