### ISSUE TITLE
TLC command line help missing build date value

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#500]
Very minor issue: when I run `java tlc2.TLC -help` on Windows 10 I get the following output:

```
NAME

        TLC - provides model checking and simulation of TLA+ specifications - Version 2.15 of Day Month 20??
```

I suppose this should either print the correct build date or be removed. I hear that reproducible builds are the new hotness, so we should probably avoid unnecessary timestamps.

**Comment by lemmy** [comment]
With the nightly version, this is expected.  If this happens with the latest release, it is known: https://github.com/tlaplus/tlaplus/issues/453
