### ISSUE TITLE
GitHub action for TLA+ to use in CI for projects depending on TLA+

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#501]
It would be extremely nice to have a GitHub action such that a simple incantation like this one

```yaml
- name: Set up TLA+
  uses: actions/setup-tlaplus@v1
```

would let the user to call SANY, TLC in their CI.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/306
https://github.com/lemmy/BlockingQueue/blob/3a66f46f6f5703f2863f71baaf0aedaaee58836f/.github/workflows/main.yml#L30-L33

**Comment by anton-trunov** [comment]
Thanks a lot for the pointer -- really helpful!

**Comment by lemmy** [comment]
Feel free to reopen if https://github.com/tlaplus/tlaplus/issues/501#issuecomment-686560353 is insufficient.
