### ISSUE TITLE
Instantiate another module with same name but in different path

### ISSUE THREAD

**Issue by josedusol** [tlaplus/tlaplus#502]
Hello!

Suppose i have two projects in different paths, say `dir1 `and `dir2`. Both projects have a `main.tla` as root module. Is it possible to `INSTANCE `one `main `module from the other without getting a `Circular dependency` error between them?. 

Obviously the problem is that they have the same name, just using a different module name will do it. But as they are in different locations, maybe there is a way to "differentiate" them by path or something.

Thanks.

**Comment by lemmy** [comment]
You have to rename one of the modules/files.

**Comment by josedusol** [comment]
> No, you have to rename one of the modules/files.

Ok Markus, thanks. Could this be considered as a "feature"?.

**Comment by josedusol** [comment]
> Sounds to me as if you want to add namespaces to TLA+, which is obviously a major effort. Perhaps, something could be hacked for your particular case, but that's probably not a good use of our time.

Yes, you are right. Thanks.
