### ISSUE TITLE
Lightweight way to run model checking on remote machine from the Toolbox via SSH

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#504]
I often develop a spec in the Toolbox on my laptop but when I'm ready to run model checking I'd prefer to run TLC on a more powerful remote server that I have access to. This helps prevent overloading my local machine and allows me to use a more powerful machine for model checking. Distributed and/or Cloud TLC seems overkill for this scenario, especially since the remote machine is not necessarily an Azure/EC2 instance. Ideally, it would be possible to have something like a "run on remote server" feature in the Toolbox model interface that was parameterized by an SSH user and hostname. I imagine the Toolbox could copy over the necessary spec and model files to the remote machine, run the appropriate TLC command, and stream the TLC output back to the local machine i.e. everything in the Toolbox would appear the same as if it were running locally, but model checking would occur on the remote machine.

**Comment by lemmy** [comment]
It would have to make a lot of assumptions about the remote host (correct Java version, TLC installation, ...).  This is precisely what Cloud TLC takes care of by provisioning a full environment (including OS optimizations).  Once Cloud TLC has provisioned the environment, it is pretty lightweight (copy spec/tlc.jar to remote host & launch), which usually takes 5-10 seconds.

That said, I, too, frequently wish to have a mechanism to run TLC on my more powerful desktop machine on the push of a button.  JClouds -a multi-cloud library with which the Toolbox talks to Azure, AWS, ...-  used to have a docker feature, which would have been the best match to implement this feature within Cloud TLC.  Unfortunately, jclouds is in maintenance mode (aka dead). This is why I've been using the following on the CLI (which could probably be built into the Toolbox):

`tar cf - *.{tla,cfg} | ssh serverroom 'tar xf - && java -jar /path/to/TLA\+Toolbox/tla2tools.jar -workers auth MC`

or 

`cat tla2tools.jar | ssh serverroom 'cat - > /tmp/tlc && chmod +x /tmp/tlc && /tmp/tlc -workers auto'`

**Comment by lemmy** [comment]
@will62794 Note, I added one more paragraph after your reaction.

**Comment by will62794** [comment]
Got it, thanks for the info. I too recall doing some similar command line incantation in the past to copy over spec and model generated by the Toolbox to run on a remote machine.

**Comment by lemmy** [comment]
I believe this issue can be closed.
