### ISSUE TITLE
CLI: return non-zero exit codes if there are errors

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#510]
This would simplify interacting with the tool using the command line interface which is very useful for testing.

E.g. SANY gives me something like this as its output 
```
Semantic errors:

*** Errors: 1

line 130, col 54 to line 130, col 54 of module Foo

...
```
but `echo $?` returns `0`.

**Comment by lemmy** [comment]
@anton-trunov Is this with the latest release?  I remember working in this area a while ago.

**Comment by anton-trunov** [comment]
Looks like this is the latest release. The Toolbox says
```
This is Version 1.7.0 of 20 April 2020 and includes:
  - SANY Version 2.2 of 20 April 2020
  - TLC Version 2.15 of 20 April 2020
  - PlusCal Version 1.10 of 20 April 2020
  - TLATeX Version 1.0 of 20 September 2017
```

**Comment by lemmy** [comment]
Please try a recent nightly.

**Comment by anton-trunov** [comment]
Looks like a recent version didn't work. Here are the steps to reproduce:

1. The code snippet to test with
```
---- MODULE Foo ----

bar == undefined_operator(42)

====================
```

2. Download `tla2tools.jar` and run SANY on the code snippet above:
```shell
wget https://tla.msr-inria.inria.fr/tlatoolbox/ci/dist/tla2tools.jar
java -cp tla2tools.jar tla2sany.SANY Foo.tla
```

3. Here is the output
```
****** SANY2 Version 2.2 created 08 July 2020

Parsing file /Users/anton/zilliqa/scilla-tla/Foo.tla
Semantic processing of module Foo
Semantic errors:

*** Errors: 1

line 3, col 8 to line 3, col 25 of module Foo

Unknown operator: `undefined_operator'.


```

4. `echo $?` returns `0`

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/pull/483

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/blob/d5654d93bc5787026382201fda7aa3fbb55222c6/tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java#L425-L426

**Comment by anton-trunov** [comment]
Thanks, that works for me! (btw, it would be nice if SANY supported `-help` CLI flag)

**Comment by lemmy** [comment]
Agreed, can you provide a PR?

**Comment by anton-trunov** [comment]
Sure, I'll try doing that after some deadlines... Let me just open an issue to track it.
