### ISSUE TITLE
CLI: SANY should support -help flag

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#511]
As of now the only way to discover SANY's CLI options is looking in the source code here: https://github.com/tlaplus/tlaplus/blob/d5654d93bc5787026382201fda7aa3fbb55222c6/tlatools/org.lamport.tlatools/src/tla2sany/drivers/SANY.java#L417-L425

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/eff4e9b31354c6b661229205af3f6e2716a4a231
