### ISSUE TITLE
Invalid code signature on MacOS installation of tla-plus-toolbox-nightly

### ISSUE THREAD

**Issue by diracdeltas** [tlaplus/tlaplus#516]
Update: I get the same result when installing from https://nightly.tlapl.us/products/TLAToolbox-1.7.1-macosx.cocoa.x86_64.zip instead of homebrew

After running `brew install tla-plus-toolbox-nightly` and opening the installed application, I see this error on MacOS 10.14.6:

<img width="418" alt="Screen Shot 2020-10-16 at 10 49 14 PM" src="https://user-images.githubusercontent.com/549654/96329495-53fcfd80-1002-11eb-8801-6074fb79922d.png">

**Comment by lemmy** [comment]
FWIW: This is orthogonal to Homebrew and also happens on 10.15.7 with the download from https://nightly.tlapl.us (that is successfully notarized according to Apple).

**Comment by lemmy** [comment]
@diracdeltas The Toolbox 1.7.0 zip file works fine.  Do you happen to know a *good* 1.7.1 nightly on macOS (I'm no mac user myself) to make it easier to manually bisect?

**Comment by diracdeltas** [comment]
@lemmy 1.7.0 works fine for me too. Latest nightly and the one I tried yesterday both failed. Is there a way I can get older nightly builds to test?

**Comment by lemmy** [comment]
We don't keep older nightlies unless Github Actions keep them somewhere. Our INRIA machine (nightly.tlapl.us) doesn't have sufficient storage to keep old nightlies, which is why the Github Action replaces the previous one when it uploads to nightly.tlapl.us.

**Comment by lemmy** [comment]
For the current nightly (installed from zip or Homebrew), `xattr -rc /Applications/TLA+\ Toolbox.app` makes the Toolbox start up correctly.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/765dccc2a43fb0bce3b158558f603a1826236004
https://github.com/tlaplus/tlaplus/commit/eedd4df56ee77277af02088346adc5188a46bff9
https://github.com/tlaplus/tlaplus/commit/c5182bcc4c752cdf4d11ca6fb93f621ff59f86d3
https://github.com/tlaplus/tlaplus/commit/0e33c5122c6c6097f2082bd946aa5b77dfd0140f

**Comment by diracdeltas** [comment]
Thanks for the quick fix!
