### ISSUE TITLE
"NewSpecWizard job has encountered a problem"

### ISSUE THREAD

**Issue by drewhk** [tlaplus/tlaplus#52]
I simply cannot create any new Specs with `Add new Spec` menu because it fails always with the following error:

![image](https://cloud.githubusercontent.com/assets/932285/26342884/1edf4996-3f9a-11e7-859c-e6d68393407a.png)

```
An internal error occurred during: "NewSpecWizard job".
assertion failed: E:\temp\tla-test-spec\testspec.toolbox is *not* a subdirectory of e:\temp\tla-test-spec\testspec.tla. This is commonly caused by a symlink contained in the latter path.
```

Please note that there are no symlinks involved anywhere.

**Comment by lemmy** [comment]
Hi,

thanks for your bug report. The root cause is a bogus case-sensitive comparison of the the drive letter. Please try changing your input path to "E:\temp\tla-test-spec\testspec.tla" until we get the bug fixed.

Thanks
M.

**Comment by drewhk** [comment]
Ah, that was it, thanks.

**Comment by lemmy** [comment]
For the record, I explored the alternative to relax ResourceHelper.isProjectParent to compare the device (drive latter) case insensitive:

    public static boolean isProjectParent(final IPath aFileName, final IProject project) {
		return arePathEqual((Path) aFileName, (Path) project.getLocation().removeLastSegments(1));
	}

	public static boolean arePathEqual(final IPath first, final IPath second) {
		// Be more forgiving with regards to the casing of drive letters on
		// windows. IPath#equals is case sensitive with regards to the device,
		// see https://bugs.eclipse.org/49516. Thus, we compare the segments
		// and the device separately. If the device is not null (e.g. if it's
		// a drive letter, a case insensitive comparison is done. I didn't bother
		// to check this behavior with UNC path though).
		if (first.matchingFirstSegments(second) == first.segmentCount()) {
			if (first.getDevice() != null) {
				// Compare devices - which we expect to be a drive letter - 
				// case-insensitive.
				return first.getDevice().equalsIgnoreCase(second.getDevice());
			} else {
				// Except both path to have no device.
				return second.getDevice() == null;
			}
		}
		return false;
	}

I decided against it, because it might cause problems later when paths are compared in other places.

**Comment by drewhk** [comment]
Can't you normalize instead while reading form the form field? Also, why not just use `java.nio.Path#startsWith` (https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#startsWith(java.nio.file.Path))?

**Comment by lemmy** [comment]
@drewhk What's the advantage over normalization in NewSpecWizardPage.dialogChanged(), which is called when the input field is modified?

**Comment by drewhk** [comment]
You mean the advantage of using `java.nio.file.Path`? It handles all kinds of edge cases for you. But I see now that you use some eclipse specific type (IPath) and I am not sure how that works. I have to admit I have not looked in the toolbox IDE code.

**Comment by lemmy** [comment]
A build with the fix is available [at the usual location](http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/).
