### ISSUE TITLE
comment in preamble is treated as module start 

### ISSUE THREAD

**Issue by PratikDeoghare** [tlaplus/tlaplus#527]
```
---- What is this 

\* A comment 
\* ---- MODULE foo ----
And more preamble there is.

------------------------------- MODULE Foo -------------------------------


=============================================================================

```  

![](https://user-images.githubusercontent.com/1302569/97904366-a8adb180-1d40-11eb-9262-34ba803d0daf.png)

I expected `\* ---- MODULE foo ----` to be treated as a comment. 

If I change the to 3 dashes instead of 4 dashes before MODULE in the comment, parsing works fine. 

```
---- What is this 

\* A comment 
\* --- MODULE foo ----
And more preamble there is.

------------------------------- MODULE Foo -------------------------------


=============================================================================
```

**Comment by lemmy** [comment]
On what do you base the assumption that `\*` has the same meaning outside a TLA+ module that it has inside a module?

**Comment by PratikDeoghare** [comment]
> On what do you base the assumption that \* has the same meaning outside a TLA+ module that it has inside a module?

Ha! No basis to assume that.  It is highlighted like a comment in the toolbox so I thought it was a comment. 

Looks like there is a bug in my understanding.

Now reading this [1]. 

1. A .tla file is not a module. 
2. A module starts at `---- MODULE Name ----` and ends at `====`. 
3. Any text is allowed beyond module start and module end. 

Have I understood this correctly? 

Thanks for the comment. It is clarifying the bug I am working on. 

[1]  https://lamport.azurewebsites.net/tla/TLAPlus2Grammar.tla 
```
TLAPlusGrammar ==
 LET P(G) ==
   /\ G.Module ::=     AtLeast4("-") 
                   & tok("MODULE") & Name & AtLeast4("-")
                   &   (Nil | (tok("EXTENDS") & CommaList(Name)))
                   &   (G.Unit)^* 
                   &   AtLeast4("=") 
```

**Comment by lemmy** [comment]
If in doubt, SANY is (probably) right.
