### ISSUE TITLE
invariant is not a state predicate

### ISSUE THREAD

**Issue by magicsupery** [tlaplus/tlaplus#528]
i got a error
The invariant Liveness  is not a state predicate (one with no primes or temporal operators).
i'm very confused why my liveness is not
**Liveness == 
 <>(\A p \in People: wants[p] = {})**

here is my all tla code 

\* BEGIN TRANSLATION - the hash of the PCal code: PCal-06efd894049035205739e02959289542
VARIABLES library, pc

(* define statement *)
AvaliableBooks == {book \in Books: library[book] > 0}

VARIABLES books, wants

vars == << library, pc, books, wants >>

ProcSet == (People)

Init == (* Global variables *)
        /\ library \in [Books -> NumCopies]
        (* Process person *)
        /\ books = [self \in People |-> {}]
        /\ wants \in [People -> SUBSET Books]
        /\ pc = [self \in ProcSet |-> "Person"]

Person(self) == /\ pc[self] = "Person"
                /\ \/ /\ \E book \in AvaliableBooks \ books[self]:
                           /\ library' = [library EXCEPT ![book] = library[book] - 1]
                           /\ books' = [books EXCEPT ![self] = books[self] \union {book}]
                           /\ wants' = [wants EXCEPT ![self] = wants[self] \ {book}]
                   \/ /\ \E book \in books[self]:
                           /\ library' = [library EXCEPT ![book] = library[book] + 1]
                           /\ books' = [books EXCEPT ![self] = books[self] \ {book}]
                           /\ wants' = [wants EXCEPT ![self] = wants[self] \union {book}]
                /\ pc' = [pc EXCEPT ![self] = "Person"]

person(self) == Person(self)

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == /\ \A self \in ProcSet: pc[self] = "Done"
               /\ UNCHANGED vars

Next == (\E self \in People: person(self))
           \/ Terminating

Spec == /\ Init /\ [][Next]_vars
        /\ \A self \in People : WF_vars(person(self))

Termination == <>(\A self \in ProcSet: pc[self] = "Done")

\* END TRANSLATION - the hash of the generated TLA code (remove to silence divergence warnings): TLA-72002854448896217113bffdf0c265b9
TypeInvariant ==
/\ library \in [Books -> NumCopies \union {0}]
/\ books \in [People -> SUBSET Books]
/\ wants \in [People -> SUBSET Books]

Liveness == 
 <>(\A p \in People: wants[p] = {})

**Comment by lemmy** [comment]
`<>` is a temporal operator and, therefore, `Liveness` is not a state predicate but a temporal formula--a property.

**Comment by magicsupery** [comment]
> `<>` is a temporal operator and, therefore, `Liveness` is not a state predicate but a temporal formula--a property.

3ks
