### ISSUE TITLE
macro cross modules

### ISSUE THREAD

**Issue by magicsupery** [tlaplus/tlaplus#536]
macro ChannelSend(from, to, msg) begin
    either
        to.queues := Append(to.queues, msg);
    or
        from.queues := Append(from.queues, CHANNEL_TIMEOUT);
    end either;
end macro;

I defined a macro in module Channel， when i write a new module "Test", i want to use that macro(sth like a c++ class functions)

how can i do this in pluscal or tla+?

**Comment by magicsupery** [comment]
ChannelSend(from, to, msg) == 
        /\ \/ /\ to' = [to EXCEPT !.queues = Append(to.queues, msg)]
              /\ from' = from
           \/ /\ from' = [from EXCEPT !.queues = Append(from.queues, CHANNEL_TIMEOUT)]
              /\ to' = to
        /\ msg' = msg

I write this in the module "Channel", but in my "Test" module

when i write sth like:
Channel!ChannelSend(from, to, "apply")
the compiler tell me this is wrong!

**Comment by lemmy** [comment]
Please attach the complete spec or a minimal spec that reproduces the problem.

**Comment by magicsupery** [comment]
------------------------------- MODULE Channel ------------------------------- 

LOCAL INSTANCE Sequences
LOCAL INSTANCE TLC

CHANNEL_TIMEOUT == "TIMEOUT"


ChannelNew == [queues |-> <<>>]
ChannelSend(from, to, msg) == 
        /\ \/ /\ to' = [to EXCEPT !.queues = Append(to.queues, msg)]
              /\ from' = from
           \/ /\ from' = [from EXCEPT !.queues = Append(from.queues, CHANNEL_TIMEOUT)]
              /\ to' = to
        /\ msg' = msg
========================================


-------------------------------- MODULE test --------------------------------




LOCAL INSTANCE TLC
LOCAL INSTANCE Integers
LOCAL INSTANCE Sequences
Channel == INSTANCE Channel

(*--algorithm message_queue
variables
     from = Channel!ChannelNew;
	 to = Channel!ChannelNew;
	 
process writer = "writer"
begin Write:
    while TRUE do
        to.queues := Append(to.queues, "msg");
        Channel!ChannelSend(from, to, "msg");  \*--Expected ":=" but found ";"
    end while;
end process;
end algorithm;*)
==============================================
Pcal Translator Error

**Comment by lemmy** [comment]
`ChannelSend` is not a macro but a TLA+ action that cannot appear in a PlusCal algorithm.

(Related: https://github.com/tlaplus/tlaplus/pull/455)
