### ISSUE TITLE
complex system need a union version

### ISSUE THREAD

**Issue by magicsupery** [tlaplus/tlaplus#542]
when we compile c++， we can use the IncrediBuild tool to make use of all computers in my office.

so is there a pattern toolbox support this? my complex system check will run almost one day...

**Comment by lemmy** [comment]
I don't know what IncrediBuild is, but it seems you want [distributed TLC](https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/distributed-mode.html).

Please use the [mailing list](https://groups.google.com/g/tlaplus) for questions.
