### ISSUE TITLE
Enhancement: Log the full TLA+ invocation in toolbox console

### ISSUE THREAD

**Issue by rodgarrison** [tlaplus/tlaplus#546]
The toolbox is a powerful tool. For those interested in command line work, however, it'd be nice to see what the toolbox runs during model evaluation because it is necessarily comprehensive in its support. This way it'd be easier to carry over its power into Makefiles or scripts.

**Comment by lemmy** [comment]
FWIW: The Toolbox logs the command-line to `~/.tlaplus/.metadata/.log` prior to model-checking.

/cc @arnaudbos

**Comment by rodgarrison** [comment]
@leemy Indeed. Good enough for me. Much appreciated.

**Comment by arnaudbos** [comment]
Nice! I've been asking the same question to @lemmy litterally three days ago.
Thanks for the mention!
