### ISSUE TITLE
Using primed variable in invariant causes unhelpful error message

### ISSUE THREAD

**Issue by agacek** [tlaplus/tlaplus#55]
I accidently used a primed variable in an invariant. The resulting error message was misleading and not helpful.

In my case, I was doing the DieHard example and used the invariant `big' \in 0..5` which led to the error message:

```
In evaluation, the identifier big is either undefined or not an operator.
big
While working on the initial state:
/\ big = 0
/\ small = 0
```

**Comment by inieves** [comment]
A build with the fix is available at the usual location: [http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/](url)

**Comment by lemmy** [comment]
0c9613fefac1da7c7d88eda4cb07cc2db00513dc reveals that the change in 8d57c8aa421e7b532e4ceac93614722756108819 caused a regression.

**Comment by lemmy** [comment]
We found that the regression is caused by another bug in TLC. This change can thus remain as is. See e63534412e88096d453db65b0bb8ad671dbc82ca for background.
