### ISSUE TITLE
TLA labels/actions in dot file

### ISSUE THREAD

**Issue by yashFrost97** [tlaplus/tlaplus#557]
Hello all! 
Is there an option to have TLA+ labels in the dot file through the toolbox? I currently only see the colour in my dot file graph. 
For eg: `-8631748407493987020 -> -2028111506862562585 [label="",color="2",fontcolor="2"];` 
Is there a way to know what label this edge is inside the square brackets? 

Help appreciated!

**Comment by lemmy** [comment]
For model `Model_1`, pass `-dump dot,colorize,actionlabels Model_1` on the `TLC Options` page.  Uncheck `Visualize state graph after...` on the same page.

**Comment by yashFrost97** [comment]
Awesome! Thanks for the help!

**Comment by yashFrost97** [comment]
Awesome! Thanks for the help

**Comment by lemmy** [comment]
Feel free to re-open
