### ISSUE TITLE
input ended before beginning of module.

### ISSUE THREAD

**Issue by ppLorins** [tlaplus/tlaplus#559]
hi , I'm new to tla+ and today I try to product the pdf version of the tla+ specification from lamport's [this tutorial ](http://lamport.azurewebsites.net/video/video5.html), but it gave me this error:
![image](https://user-images.githubusercontent.com/5534049/103436008-06338100-4c52-11eb-8438-5bfb324b3c82.png)

I've installed pdflatex in my mac and config the right path to tla toolbox. Any one could help ? Thanks.

OS: macOS Catalina 10.15.1
tla toolbox: 
>This is Version 1.7.0 of 20 April 2020 and includes:
>  - SANY Version 2.2 of 20 April 2020
>  - TLC Version 2.15 of 20 April 2020
> - PlusCal Version 1.10 of 20 April 2020
> - TLATeX Version 1.0 of 20 September 2017

source tla+ code can be found [here](https://gist.github.com/ppLorins/0745f3a4551f575bd8c050a82259552b)

**Comment by lemmy** [comment]
Your spec is missing the module start and end markers:

```tla
---- MODULE tcommit ----

... \* here comes the content of your tcommit.tla


====
```

**Comment by lemmy** [comment]
Feel free to reopen if this doesn't address the problem.

**Comment by ppLorins** [comment]
thanks. it's solved.
