### ISSUE TITLE
tla+ toolbox quit unexpectly when producing pdf document

### ISSUE THREAD

**Issue by ppLorins** [tlaplus/tlaplus#560]
when click "Produce PDF Version", the toolbox quit unexpectly:
![image](https://user-images.githubusercontent.com/5534049/103454748-00a56c00-4d22-11eb-97bf-458383b02a98.png)

OS: macOS Catalina 10.15.1
tla toolbox:

>This is Version 1.7.0 of 20 April 2020 and includes:

>SANY Version 2.2 of 20 April 2020
>TLC Version 2.15 of 20 April 2020
>PlusCal Version 1.10 of 20 April 2020
>TLATeX Version 1.0 of 20 September 2017

source tla+ code can be found [here](https://gist.github.com/ppLorins/0745f3a4551f575bd8c050a82259552b), which is Lamport's tla+ video lecture5.

the error details can be found [here](https://gist.github.com/ppLorins/fbebd954e6beed51add7cd19886e8be9)

configured pdfLatex :
![image](https://user-images.githubusercontent.com/5534049/103462096-ec7f6000-4d5d-11eb-9536-0ed1ad224347.png)

**Comment by lemmy** [comment]
Please check if the instructions around https://github.com/tlaplus/tlaplus/issues/357#issuecomment-535770396 fix your problem.

**Comment by ppLorins** [comment]
> Please check if the instructions around [#357 (comment)](https://github.com/tlaplus/tlaplus/issues/357#issuecomment-535770396) fix your problem.

Solved ! Thanks a lot.
