### ISSUE TITLE
no responding when click "Edit" to init value of declared constants.

### ISSUE THREAD

**Issue by ppLorins** [tlaplus/tlaplus#561]
![image](https://user-images.githubusercontent.com/5534049/103661414-b0403f80-4fa9-11eb-82d2-5a19cfe80ad2.png)

OS: macOS High Sierra 10.13.6
tla toolbox: 
>This is Version 1.7.1 of 31 December 2020 and includes:
>  - SANY Version 2.2 of 20 April 2020
>  - TLC Version 2.16 of 31 December 2020
>  - PlusCal Version 1.11 of 31 December 2020
>  - TLATeX Version 1.0 of 20 September 2017

the code is [here](https://gist.github.com/ppLorins/be88ef5bd196fd10641227c9d1383571)

**Comment by lemmy** [comment]
@ppLorins Does it work when you select `RM <-` first and then click the `Edit` button?

**Comment by ppLorins** [comment]
> @ppLorins Does it work when you select `RM <-` first and then click the `Edit` button?

OMG, this is a dumb report..............  sorry for this.
