### ISSUE TITLE
Debugger crashes when checking liveness: Exception 'util.WrongInvocationException: TLCStateFun.deepCopy'

### ISSUE THREAD

**Issue by vitorenesduarte** [tlaplus/tlaplus#565]
While using the debugger (model and .cfg file below), I got the following error:

```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a util.WrongInvocationException: TLCStateFun.deepCopy: This is a TLC bug.
```

Happy to provide more details as needed.

-----------------

- [model](https://github.com/informalsystems/ibc-rs/tree/master/docs/spec/tla/fungible-token-transfer)
- `IBCTokenTransfer.cfg`:

```
CONSTANTS MaxHeight = 2
          MaxPacketSeq = 2
          MaxBalance = 2
          NativeDenominationChainA = "samoleansA"
          NativeDenominationChainB = "samoleansB"

SPECIFICATION Spec

PROPERTY ICS20Prop
INVARIANT ICS20Inv
```

**Comment by lemmy** [comment]
Thanks, I have it reproduced.

**Comment by lemmy** [comment]
Please disable liveness checking for now, i.e. remove `PROPERTY ICS20Prop` from your config

**Comment by lemmy** [comment]
Fixed in 7a5326d

**Comment by lemmy** [comment]
Fix included in most recent http://tla.msr-inria.inria.fr/kuppe/vscode/vscode-tlaplus-1.5.4.vsix

**Comment by vitorenesduarte** [comment]
Awesome, thanks!
