### ISSUE TITLE
Undo stops working properly

### ISSUE THREAD

**Issue by mqvist** [tlaplus/tlaplus#568]
I currently experience a frustrating issue with the TLA+ Toolbox version 1.7.1 on Windows:

If two TLA+ modules are open in separate editor tabs in the Toolbox, switching between the tabs causes undo (ctrl-z) to stop working in one of them. From this point on undo only affects only of the editors no matter which one is active. The only resolution seems to be to reopen the Toolbox. I tried this with a fresh copy of the Toolbox and got the same behavior.

**Comment by mqvist** [comment]
Tested with Toolbox version 1.7.0: undo works properly with multiple editors.

**Comment by lemmy** [comment]
Thanks for the report.  I've noticed the same on Linux even with the Eclipse IDE.

**Comment by lemmy** [comment]
Nothing related on Bugzilla: https://bugs.eclipse.org/bugs/buglist.cgi?classification=Eclipse%20Project&list_id=20308591&query_format=advanced&short_desc=undo&short_desc_type=allwordssubstr

**Comment by lemmy** [comment]
@houseofwealth @mqvist Please try the most recent [nightly build](https://nightly.tlapl.us/products/) that upgrade Eclipse in hopes of fixing this intermittentd undo issue.

**Comment by houseofwealth** [comment]
Unfortunately, I spoke too soon. The problem persists even in 1.8

**Comment by lemmy** [comment]
@houseofwealth Do you have steps that reliably reproduce the issue?

**Comment by houseofwealth** [comment]
I'm not yet seeing a pattern. It just happened for the first time since I downloaded this build a few days ago. I restarted toolbox and it seems ok now. I will keep observing it.

**Comment by houseofwealth** [comment]
OK I believe I can replicate the problem:

Create a spec with 2 modules. 
Edit one of the modules. Test that Ctl-Z is working correctly.
Open the other module. Test Ctl-Z is working correctly there too.
Return to the original module. Ctl-Z no longer works

**Comment by houseofwealth** [comment]
hello, any updates on this? I recently made the mistake of selecting a line and choosing "Box comment" thinking it would box comment that line but instead it placed the entire file contents inside boxed comments (is this a bug or a feature?), with currently no way to recover.

**Comment by lemmy** [comment]
Sorry, I haven't had the chance to look into this.

**Comment by lemmy** [comment]
This must be an upstream/Eclipse issue.  It just happened to me in the Eclipse IDE (I20201202-1800).

**Comment by lemmy** [comment]
Upstream bug https://bugs.eclipse.org/571395

**Comment by houseofwealth** [comment]
ok thanks. Lets hope someone familiar with that bit of code is able to get to it. I'm surprised its not been escalated, its a real showstopper

**Comment by lemmy** [comment]
@houseofwealth Can you help to answer the questions by upstream in https://bugs.eclipse.org/571513#c3 ?

**Comment by lemmy** [comment]
@houseofwealth Please try the [most recent build](https://nightly.tlapl.us/products/) that contains commit be76942.

**Comment by houseofwealth** [comment]
I tried it briefly and it seems to be behaving ok. I will test it further and let you know. Thanks!

**Comment by lemmy** [comment]
Please reopen if this remains an issue.
