### ISSUE TITLE
Support overriding constant parameters of model on command line

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#577]
Often, when verifying a specification `Spec.tla` with a TLC configuration `Spec.cfg` that instantiates some constant parameters of the spec, I want to do model checking runs with different values for the parameters e.g. increasing the set of nodes in a system or tuning parameters of a state constraint bound. I find myself creating multiple copies of the config files that are identical except for a change to one constant parameter e.g.

```
Spec-3Node.cfg
Spec-4Node.cfg
Spec-5Node.cfg
```
It would be helpful if I could create one config file to act as a "template", and just override constant parameters of my choosing from the command line. For example, for a config file like

```
SPECIFICATION Spec
CONSTANT N = 3
```

It would be possible to run the following commands for different values of `N`:

```
java tlc2.TLC -config Spec.cfg -constant N=4  Spec.tla
java tlc2.TLC -config Spec.cfg -constant N=5  Spec.tla
java tlc2.TLC -config Spec.cfg -constant N=6  Spec.tla
``` 

I believe this is similar to a feature of @hwayne's [tlacli](https://github.com/hwayne/tlacli) tool.

**Comment by lemmy** [comment]
Please see if #272 covers your use case.

**Comment by will62794** [comment]
It seems #272 is about "running TLC multiple times/once for each configuration", which is a slightly different, albeit related, feature. I don't think #272 would necessarily cover my use case, though it may depend on how it is eventually implemented. I'm just interested in running a single configuration with a CONSTANT instantiation (or multiple) that can be specified from the command line.

**Comment by lemmy** [comment]
That's probably a nice feature for atomic values but what about more involved expressions such as operator definitions?  Would you want to write those on the command-line too?

**Comment by lemmy** [comment]
At any rate, back then I suggested implementing Hillel's cmd-line wrapper in Java by creating a new class with a main method that cleverly delegates to `TLC.java`.  This class gets added to tla2tools.jar and will work without any additional dependencies such as a Python runtime.  From my perspective, that's still the best implementation approach for the feature proposed here.

**Comment by lemmy** [comment]
Yet another way would be to amend `SpecProcessor.java` and have it read environment variables that take precedence over the values found in the config.

**Comment by will62794** [comment]
> ...what about more involved expressions such as operator definitions? Would you want to write those on the command-line too

I doubt it. For my use case I'm mostly interested in overriding simple constant expressions.

> back then I suggested implementing Hillel's cmd-line wrapper in Java by creating a new class

Do you think this feature is an unreasonable addition to TLC itself (i.e. `tlc2.TLC`) for some reason? Of course it could always be implemented as a separate tool/class, but the simplest thing seems to be just adding a command line flag to the existing tool.

**Comment by lemmy** [comment]
I would suggest taking a more principled approach and rely on a command-line parsing library for this feature.  Since this would be a lot of work for the existing command-line processing, a new class provides a clear cut.

**Comment by lemmy** [comment]
With the new [IOUtils!IOEnv operator](https://github.com/tlaplus/CommunityModules/blob/77a5cf20ffe6eef005278d81c4dde1743ed1cbfe/modules/IOUtils.tla#L53-L57) this becomes:

```MC.cfg
SPECIFICATION Spec
CONSTANT N <- NFromEnv
```

```MC.tla
---- MODULE MC ----
EXTENDS Spec, IOUtils

s2i(str) ==
    \* TODO s2i should be defined in IOUtils with an unbound choose from NAT
    \*      and overridden with a module override that converts the string
    \*      to an IntValue and returns
    \*         Attempted to compute the value of an expression of form CHOOSE x \in S: P, but no element of S satisfied P.
    \*      otherwise. Perhaps, the name atoi is more meaningful.
    CHOOSE n \in 0..2^16: ToString(n) = str

NFromEnv ==
    s2i(IOEnv.N)
```

```shell
for n in $(seq 3); do N=$n java tlc2.TLC MC; done
```

**Comment by lemmy** [comment]
As of today, assuming some spec `Spec.tla`, one can combine `IOEnvExec` and REPL to run model-checking for various configurations:

```tla
---- MODULE MC ----
EXTENDS Spec, IOUtils, TLC, TLCExt

s2n(str) ==
    CHOOSE n \in 0..2^16: ToString(n) = str

B ==
    s2n(IOEnv.B)

SetOfNModelValues(lbl, N) ==
   { TLCModelValue(lbl \o ToString(i)) : i \in 1..N }

P ==
   SetOfNModelValues("p", s2n(IOEnv.P))

C ==
   SetOfNModelValues("c", s2n(IOEnv.C))

====
```

```shell
$ alias tlcrepl
alias tlcrepl='java -cp /opt/toolbox/CommunityModules-deps.jar:/opt/toolbox/tla2tools.jar tlc2.REPL'

$ tlcrepl '\A Env \in [ {"P","C","B"} -> 1..2]: PrintT(<<Env, IOEnvExec(Env, <<"java", "-jar", "/opt/toolbox/tla2tools.jar", "MC">>).exitValue>>)'
<<[B |-> 1, P |-> 1, C |-> 1], 0>>
<<[B |-> 1, P |-> 1, C |-> 2], 0>>
<<[B |-> 1, P |-> 2, C |-> 1], 0>>
<<[B |-> 1, P |-> 2, C |-> 2], 0>>
<<[B |-> 2, P |-> 1, C |-> 1], 0>>
<<[B |-> 2, P |-> 1, C |-> 2], 0>>
<<[B |-> 2, P |-> 2, C |-> 1], 0>>
<<[B |-> 2, P |-> 2, C |-> 2], 0>>
TRUE
```

-----

If it is desirable to have more control over what happens when a configuration fails, one can write a "TLA+ script":

```tla
--------------------- MODULE TLAScript ---------------------
EXTENDS TLC, IOUtils, Naturals

Cmd == <<"java", "-jar", "/opt/toolbox/tla2tools.jar", "MC">>

ASSUME \A Env \in [ {"P","C","B"} -> 1..3 ]:
    /\ PrintT(Env)
    /\ LET ret == IOEnvExec(Env, Cmd).exitValue
       IN CASE ret =  0 -> TRUE
            [] ret = 10 -> PrintT("Assumption violation")
            [] ret = 12 -> PrintT("Safety violation")
            [] ret = 13 -> PrintT("Liveness violation")
            [] OTHER -> FALSE

=============================================================================
---- CONFIG TLAScript ----
\* TLC always expects a configuration file, but an empty one will do in this case.
====
```

**Comment by lemmy** [comment]
> Often, when verifying a specification `Spec.tla` with a TLC configuration `Spec.cfg` that instantiates some constant parameters of the spec, I want to do model checking runs with different values for the parameters e.g. increasing the set of nodes in a system or tuning parameters of a state constraint bound. I find myself creating multiple copies of the config files that are identical except for a change to one constant parameter e.g.
> 
> ```
> Spec-3Node.cfg
> Spec-4Node.cfg
> Spec-5Node.cfg
> ```
> 
> It would be helpful if I could create one config file to act as a "template", and just override constant parameters of my choosing from the command line. For example, for a config file like
> 
> ```
> SPECIFICATION Spec
> CONSTANT N = 3
> ```
> 
> It would be possible to run the following commands for different values of `N`:
> 
> ```
> java tlc2.TLC -config Spec.cfg -constant N=4  Spec.tla
> java tlc2.TLC -config Spec.cfg -constant N=5  Spec.tla
> java tlc2.TLC -config Spec.cfg -constant N=6  Spec.tla
> ```
> 
> I believe this is similar to a feature of @hwayne's [tlacli](https://github.com/hwayne/tlacli) tool.

The new `ParameterziedSpecObj.java` supports passing CLI parameters to the SpecProcessor. Example: https://github.com/tlaplus/tlaplus/commit/48cb41c59b4ccf280ad289d290281485591a633f   https://github.com/tlaplus/tlaplus/commit/386eaa19f4d610781a79c95730638ba193cec614
