### ISSUE TITLE
self describing options for command line tolls

### ISSUE THREAD

**Issue by zsfre** [tlaplus/tlaplus#580]
most command line tools these days have a comprehensive output from `cmd --help` or equivalent that tells the user what all the options are. At present, the published documentation is out of date and the command line output is no help. The only authoritative source is the code. 

Suggest adopting a command line option parsing library to support this.

**Comment by lemmy** [comment]
If you are referring to https://lamport.azurewebsites.net/tla/tlc-options.html, it will soon be removed.  There shouldn't be anything missing in https://lamport.azurewebsites.net/tla/current-tools.pdf? 

Btw, the newest TLC release has a "-help"/"-h" command.

**Comment by zsfre** [comment]
Ah, that's better. I suggest including a `--help` alias as that's pretty common nowadays. Also, change the usage message which is currently `Usage: java tlc2.TLC [-option] inputfile` to include the `-help` option

**Comment by lemmy** [comment]
```bash
TLC2 Version 2.15 of Day Month 20??
Error: Error: Missing input TLA+ module.
Usage: java tlc2.TLC [-help] [-option] inputfile
```
