### ISSUE TITLE
How to generate JNI header file?

### ISSUE THREAD

**Issue by yagehu** [tlaplus/tlaplus#583]
I'm interested in using SANY from Rust via FFI. AFAIK, I have to generate a header file from the Java source files first. For a simple Java file I can generate the header with `javac -h . MyClass.java`. How can I generate a header file for SANY?

**Comment by lemmy** [comment]
There is no support whatsoever for JNI.  Instead, use SANY's command line interface.

**Comment by yagehu** [comment]
Thanks for the answer. Closing. Just want to leave a note that you folks have built a wonderful suite of tools, and it would be super nice if other language/runtimes can make use of them :)

**Comment by lemmy** [comment]
Please feel free to open an enhancement request, if your use-case is not supported by SANY's command line.
