### ISSUE TITLE
Error messages and definitions in REPL

### ISSUE THREAD

**Issue by Alexander-N** [tlaplus/tlaplus#586]
The thing I'm missing most in the current prototype is informative error messages, currently it seems to always be `Error evaluating expression: ...`. With that I think the REPL could be used to speed up evaluations in [tlaplus_jupyter](https://github.com/kelvich/tlaplus_jupyter).

Also it would be nice to be able to add definitions which can be used later in the REPL session. I'm thinking of things like
```TLA
Range(T) == { T[x] : x \in DOMAIN T }
```

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/ad5b5a823b9e7b44871fccf71c65f7c940987399#diff-19f9731fa76dc2c1c065ff879239932067dda8d22e29177709af403164ba3e1f

**Comment by lemmy** [comment]
Error-reporting has been improved in ddec154234afb0b8587f590a4d1c4dd357831bc5.


Definitions can be stated with LET/IN:

```tla
LET Range(T) == { T[x] : x \in DOMAIN T }
IN Range([ a |-> 42])
```

Alternatively, push definitions such as `Range` into a module `Foo` in a file `Foo.tla` in `$CWD`, and "load" `Foo` via:

```tla
LET F == INSTANCE Foo IN F!Range([ a |-> 42])
```
