### ISSUE TITLE
Parse Error: Encountered "<EOF>" at line 0, column 0 and token - Regression in InJarFilenameToStream

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#593]
@pfeodrippe  Commit 00cd5641d5d07b79818a7096fc1cbcc02388070c introduces a regression with `model.InJarFilenameToStream`

```shell
markus@avocado:~/src/TLA/tla((no branch, bisect started on master))$ java -jar tlatools/org.lamport.tlatools/dist/tla2tools.jar 
@!@!@STARTMSG 2262:0 @!@!@
TLC2 Version 2.15 of Day Month 20?? (rev: ${git.shortRevision})
@!@!@ENDMSG 2262 @!@!@
@!@!@STARTMSG 2187:0 @!@!@
Running breadth-first search Model-Checking with fp 80 and seed -5197081046360030598 with 1 worker on 4 cores with 5952MB heap and 64MB offheap memory [pid: 104041] (Linux 5.4.0-66-generic amd64, Ubuntu 11.0.10 x86_64, MSBDiskFPSet, DiskStateQueue).
@!@!@ENDMSG 2187 @!@!@
@!@!@STARTMSG 2220:0 @!@!@
Starting SANY...
@!@!@ENDMSG 2220 @!@!@
Parsing file /tmp/MC.tla
Parsing file /tmp/EWD840.tla (/tmp/MC.tla)
***Parse Error***
Was expecting "---- MODULE (beginning of module)"
Encountered "<EOF>" at line 0, column 0 and token "" 

Residual stack trace follows:
Begin module starting at line 0, column 0.
Module definition starting at line 0, column 0.

a
Fatal errors while parsing TLA+ spec in file MC

tla2sany.semantic.AbortException
@!@!@STARTMSG 2219:0 @!@!@
SANY finished.
@!@!@ENDMSG 2219 @!@!@
@!@!@STARTMSG 2185:0 @!@!@
Starting... (2021-03-14 20:22:16)
@!@!@ENDMSG 2185 @!@!@
@!@!@STARTMSG 3002:1 @!@!@
Parsing or semantic analysis failed.
@!@!@ENDMSG 3002 @!@!@
@!@!@STARTMSG 2186:0 @!@!@
Finished in 355ms at (2021-03-14 20:22:16)
@!@!@ENDMSG 2186 @!@!@
```

Reproduce by copying a spec and model to `src/model`, followed by `ant -f customBuild.xml clean compile dist`, and running `java -jar dist/tla2tools.jar`.

**Comment by pfeodrippe** [comment]
😮 I will check it today, thanks for the report, Markus.

**Comment by lemmy** [comment]
Please make sure to add a test case.

**Comment by pfeodrippe** [comment]
@lemmy I've been able to reproduce the error and was checking how to test it. So this occurs when using the Toolbox (which creates `MC` files) and the spec is in a jar? What were you using to find this bug?

Do you know if there is some test like this already which test things inside a jar? I also can try to mock something or add a test which builds `tla2tools.jar` and run just like you did (like a smoke test).

About finding the jar, I guess it's doable to find it, just need to check the classpath.

**Comment by pfeodrippe** [comment]
> About finding the jar, I guess it's doable to find it, just need to check the classpath.

Yeah, that's solved.

**Comment by pfeodrippe** [comment]
I have fixed locally (didn't write a test yet though), how could I test RMI and RCP? I guess they are not as straightforward, right?

**Comment by pfeodrippe** [comment]
> I have fixed locally (didn't write a test yet though), how could I manually test RMI and RCP? I guess they are not as straightforward, right?

If I learn how to setup the other two locally, then we will at least minimize these kind of regressions.

**Comment by lemmy** [comment]
What's the fix?

IIRC the `test-dist` target in `customBuild.xml` runs all unit-tests on the packaged `tla2tools.jar`.  Can you reuse this infrastructure to implement this test?  Alternatively, you can create a dedicated jar file with a spec/model in the `model` package, add it to the git repo, and write a new unit-test that expects the jar to be on the classpath.  `tlc2.tool.UserModuleOverrideFromJarTest` should provide inspiration.

**Comment by pfeodrippe** [comment]
At least I think it's a fix for this case https://github.com/tlaplus/tlaplus/pull/594.

**Comment by pfeodrippe** [comment]
>> IIRC the test-dist target in customBuild.xml runs all unit-tests on the packaged tla2tools.jar. Can you reuse this infrastructure to implement this test? Alternatively, you can create a dedicated jar file with a spec/model in the model package, add it to the git repo, and write a new unit-test that expects the jar to be on the classpath. tlc2.tool.UserModuleOverrideFromJarTest should provide inspiration.

Great, thanks!

**Comment by pfeodrippe** [comment]
Thanks! I will try to add tests for it following the files you mentioned. For RMI and RPC, is it straightforward to test manually?

**Comment by lemmy** [comment]
`RCPFilenameToStream` is what the Toolbox uses and is, thus, way more important than `RMI...`.
