### ISSUE TITLE
Collapse Macros, Procedures, Processes...

### ISSUE THREAD

**Issue by felix-seifert** [tlaplus/tlaplus#598]
**Currently**, you cannot collapse code blocks (e.g. macros or procedures) in your PlusCal code. If you want to look up some variables at the start of your file while you work on something in the mid of the file, you will always have to jump in between those sections.

**Suggestion**: Similar as in other IDEs, it should be possible to collapse PlusCal code blocks (e.g. macros and procedures). This should be possible with a *minus*/*plus* besides the line numbers. This collapsing option should ideally be suggested automatically for your code blocks, i.e. you would not have to pre- and postfix the code block with specific comments.

An **example** of how this suggestion looks like can be found if you generate a translation of some PlusCal code. The automatically generated translation can be collapsed. However, the comments seem to be integral for this functionality.

**Comment by lemmy** [comment]
Hierarchical TLA+ proof steps/obligations, TLA+ comments, the TLA+ translation, as well as comments in PlusCal algorithms can already be folded.  It should, thus, be straightforward to fold what you refer to as (PlusCal) "code blocks".  

However, the current implementation ([TLAReconcilingStrategy](https://github.com/tlaplus/tlaplus/blob/master/toolbox/org.lamport.tla.toolbox.editor.basic/src/org/lamport/tla/toolbox/editor/basic/TLAReconcilingStrategy.java)) for the last three foldable syntax constructs does not work at the level of the AST but uses basic regular expressions to find comments or the TLA+ translation instead.  The infrastructure that folds TLA+ proof steps ([TLAProofFoldingStructureProvider](https://github.com/tlaplus/tlaplus/blob/master/toolbox/org.lamport.tla.toolbox.editor.basic/src/org/lamport/tla/toolbox/editor/basic/proof/TLAProofFoldingStructureProvider.java)) on the contrary takes SANY's AST into account.  Folding for PlusCal algorithms would have to take a similar approach, except that it would have to work on the PlusCal translator's AST (`pcal.trans`).

Can you provide a patch?

**Comment by lemmy** [comment]
Since the [TLA+ VSCode extension](https://github.com/alygin/vscode-tlaplus/) has (rudimentary*) folding, it might provide inspiration on how to implement support for the "low hanging fruits".

* Folding of a process e.g. doesn't collapse the whole process

**Comment by felix-seifert** [comment]
> Can you provide a patch?

Can you please help me briefly with what you mean with "patch"?

**Comment by lemmy** [comment]
Patch = Pull Request
