### ISSUE TITLE
Module override (module overwrite, operator/definition override/overwrite) making use of nested Java class 

### ISSUE THREAD

**Issue by danwt** [tlaplus/tlaplus#599]
Hi,

I'm trying to implement an Operator override and by following the instructions [here](https://stackoverflow.com/a/54757162/8346628) things work perfectly. I would like to use nested classes to assist the implementation but when running TLC (via the toolbox) the main class is detected and an error is thrown

```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.NoClassDefFoundError
: ModuleOverwriteLinearizability$History
```
where `History` is the name of the nested class. Should I just implement the operator without extra classes or is there a simple way to get this done?

Thanks very much

**Comment by lemmy** [comment]
I don't see why nested classes would cause trouble.  Is it possible that the nested classes has not been compiled?

By the way, https://github.com/tlaplus/CommunityModules/blob/dfa1b93855c683ecadc8f7aaf0990560fd823464/modules/tlc2/overrides/SequencesExt.java#L47-L54 shows how to use the newer annotation-based module override approach.  Entry point for TLC is https://github.com/tlaplus/CommunityModules/blob/master/modules/tlc2/overrides/TLCOverrides.java.

**Comment by lemmy** [comment]
This works fine:

```java
package tlc2.overrides;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;

import tlc2.value.impl.BoolValue;
import tlc2.value.impl.StringValue;
import tlc2.value.impl.TupleValue;
import tlc2.value.impl.Value;

public class CSV {

	private static class CSVInner {
		public static Value write(final StringValue template, final TupleValue parameter, final StringValue absolutePath)
				throws IOException {
			final Object[] params = Arrays.asList(parameter.getElems()).stream().map(v -> v.toString())
					.toArray(size -> new Object[size]);
			Files.write(Paths.get(absolutePath.val.toString()),
					(String.format(template.val.toString(), params) + System.lineSeparator()).getBytes("UTF-8"),
					StandardOpenOption.CREATE, StandardOpenOption.APPEND);
			return BoolValue.ValTrue;
		}
	}
	
	@TLAPlusOperator(identifier = "CSVWrite", module = "CSV", minLevel = 1, warn = false)
	public static Value write(final StringValue template, final TupleValue parameter, final StringValue absolutePath)
			throws IOException {
		return CSVInner.write(template, parameter, absolutePath);
	}
}
```

**Comment by danwt** [comment]
Hi lemmy,

Thanks for this. Could my problem be the way that I am running TLC? I am sure that I've compiled the inner class - the way I'm running TLC is through the toolbox. The directory structure looks like
```
├── ModuleOverwriteLinearizability$1.class
├── ModuleOverwriteLinearizability$History.class
├── ModuleOverwriteLinearizability.cfg
├── ModuleOverwriteLinearizability.class
├── ModuleOverwriteLinearizability.java
├── ModuleOverwriteLinearizability.tla
```
I think this uses TLCs feature to automatically search for class matching the module name - whereas I'm not sure by what method the code you posted is loaded.

**Comment by lemmy** [comment]
1) What version of TLC are you working with?
2) Can you (privately) share a zip file with your spec and Java overrides?
3) Without the `@TLAPlusOperator` annotation, TLC expects module overrides in the default namespace.   What happens if you annotate the operator override method in `ModuleOverwriteLinearizability` with `@TLAPlusOperator`?

**Comment by danwt** [comment]
1. It's TLC version 2.15 (which does include the `@TLAPlusOperator` and Toolbox version 1.80
2. Sure!
3.


Without annotation I see 
 ```
Loading IsLinearizable operator override from .../tla/models/module_overwrite_linearizability/ModuleOverwriteLinearizability.toolbox/Model_1/ModuleOverwriteLinearizability.class with signature: <Java Method: public static tlc2.value.impl.Value ModuleOverwriteLinearizability.IsLinearizable(tlc2.value.impl.Value)>.
```
So it loads and then crashes later when it can't find the nested class.


**With** the annotation TLC no longer finds the overwrite and just uses the definition in the .tla file.

**Comment by lemmy** [comment]
TLC looks for a class `TLCOverrides.java` that implements `tlc2.overrides.ITLCOverrides`.  See https://github.com/tlaplus/CommunityModules/blob/master/modules/tlc2/overrides/TLCOverrides.java as an example.

**Comment by danwt** [comment]
I've added you to a private repo. I'll get back to you soon re the above, as it's the end of the day here. Cheers

**Comment by lemmy** [comment]
Your overrides work fine here when run from my Eclipse IDE (sans a `ClassCastException` on line 70 of `ModuleOverwriteLinearizabilityWithNestedClasses`).  Is it possible that this is an IntelliJ problem?

A guide on how to set up Eclipse for TLC development can be found at: https://github.com/tlaplus/tlaplus/tree/master/general/ide

**Comment by danwt** [comment]
Thanks, I got it working. My problem was misunderstanding the loading system. Previously I was just keeping the Module and .java/.class files in the directory next to the spec. Now I am building a jar in a separate project, using the exact same file structure layout the Community Modules project, and adding that jar to the TLA+ toolbox library path.

**Comment by lemmy** [comment]
What speed-up do you get from the module override?

**Comment by danwt** [comment]
I haven't implemented the operator in pure TLA+ for comparison - but may do so at some point. I'll let you know if if I get some relevant perf results.

**Comment by lemmy** [comment]
I believe this is fixed.
