### ISSUE TITLE
"In evaluation, the identifier v is either undefined or not an operator" when temporal properties involve operators with Java module overrides

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/tlaplus#605]
Hi,

I have a spec like below

**spec.tla**
```tla
-------------------------------- MODULE spec --------------------------------

EXTENDS Integers, TLC, Sequences, Json

VARIABLES mainVar

vars == << mainVar >>

Init == mainVar = << 1 >>

Next == mainVar' = << 3 >>

prop ==
  <>(JsonSerialize("eiei.json", mainVar) /\ Head(mainVar) >= 1)

Spec == Init /\ [][Next]_vars

=============================================================================

-------------------------------- CONFIG spec --------------------------------

INIT
   Init

NEXT
   Next

PROPERTY
  prop

=============================================================================

```

---
When I run it with TLC, it gives me
```shell
...
Semantic processing of module TLC
Semantic processing of module Json
Semantic processing of module spec
Starting... (2021-04-14 23:29:09)
Error: In evaluation, the identifier mainVar is either undefined or not an operator.
line 14, col 20 to line 14, col 26 of module spec
Finished in 00s at (2021-04-14 23:29:09)
```

---
Originally I have been using a custom overridden operator with `TLAPlusOperator` (which just returns `TRUE` and it works fine when not in use by a temporal property) and it was giving me the same error, I'm just using `JsonSerialize` because it's already embedded. Removing the `JsonSerialize` and letting `Head` alone works (although `Head` also is an overridden operator, but it uses a different mechanism other that `TLAPlusOperator).

---
Use the toolbox or run the spec from the CLI with
```shell
$ java -cp $SOME_FOLDER/tla2tools.jar tlc2.TLC spec.tla -config spec.tla
```

**Comment by pfeodrippe** [comment]
I know there are other types of interfaces other than `TLAPlusOperator`, maybe some of them would work?

**Comment by pfeodrippe** [comment]
Hunnn `TLCNoOp(mainVar) = mainVar` works, let me check a little bit more here.

**Comment by lemmy** [comment]
Please try loading your module override that fails with `@TLAPlusOperator` through the old mechanism:  Place it in the default package, align the Java class file name with the module name, and the operator name with the (static) method name.  E.g for a constant-level operator defined in module M with name `Op(a,b,c)`:

```java
// no package => default package
public class M
public static Value  Op(Value a, Value b, Value c) {
   return BoolValue.ValTrue;
}

**Comment by pfeodrippe** [comment]
Same thing :(

```shell
...
Semantic processing of module spec
Starting... (2021-04-15 00:48:49)
Loading xxx operator override from file:/Users/paulo.feodrippe/dev/recife/classes/spec.class with signature: <Java Method: public static tlc2.value.impl.Value spec.xxx(tlc2.value.impl.Value)>.
Error: In evaluation, the identifier mainVar is either undefined or not an operator.
line 16, col 10 to line 16, col 16 of module spec
Finished in 00s at (2021-04-15 00:48:49)
```

**Comment by pfeodrippe** [comment]
For the `JsonSerialize` example, if I change that line to be 

```tla
prop ==
  <>(JsonSerialize("eiei.json", << 5, 4 >>) /\ Head(mainVar) >= 1)
```

Then it works again and the json is generated 🤔

**Comment by lemmy** [comment]
Bug: `JsonSerialize("eiei.json", mainVar)` is level-checked as constant-level.

**Comment by pfeodrippe** [comment]
> Bug: JsonSerialize("eiei.json", mainVar) is level-checked to be constant-level by the liveness code. The hack below fixes it for this particular case:

Thanks, `JsonSerialize` works now o/ 

> Big question: Why does it work for Sequences!Head?

Yeah, I guess we will figure out eventually o/

**Comment by lemmy** [comment]
Root cause:

For a non-zero arity operator with *constant-level* right-hand side, whose (left-hand side) arguments do not appear on the RHS, is constant-level.  Consider the operator `Op`:

```tla
VARIABLE v

Op(a,b) == TRUE

...
Next == v = Op(v, 42)
```
`Op` is clearly constant-level even if `Op` is evaluated with some or all of its arguments equal to variables.

**Comment by pfeodrippe** [comment]
Nice, thank you, Markus! So TLC does not take into consideration that the operator is overloaded while parsing it, it makes sense. For now I can just put some bogus operation on the right side, right? Will check it tonight.

Thanks for finding the cause o/

**Comment by lemmy** [comment]
https://github.com/lemmy/tlaplus/commit/4f7c351ba22d477801d4d227c580f56abf4a6d3c lacks tests.

**Comment by pfeodrippe** [comment]
> [lemmy@4f7c351](https://github.com/lemmy/tlaplus/commit/4f7c351ba22d477801d4d227c580f56abf4a6d3c) lacks tests.

Ok, thanks o/
