### ISSUE TITLE
Support `KSubsetValue` appearing as variable values

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#611]
`FiniteSetsExt!kSubset` was originally created to efficiently calculate statistics when simulating specs.  Now, [there is interest](http://discuss.tlapl.us/msg04313.html) in using it as part of the behavior spec (as values of variables).  To support this, `KSubsetValue` has to handle the cases where it is fingerprinted.

With `N` > 30 in the excerpt below, fingerprinting (`KSubsetValue#fingerprint`) fails with:

```
Overflow when computing the number of elements in:
SUBSET { 1, 2, 3, ..., 30, 31 } 

The error occurred when TLC was evaluating the nested
expressions at the following positions:
0. Line 13, column 9 to line 13, column 28 in CMkSubset
```

```tla
N == 31

kSubset(N, 1..N)
```

The cause is that `KSubsetValue` does not override `SubsetValue#size`.  Additionally, `SubsetValue#convertAndCache` instantiates `SubsetValue#pset`, which is not needed for `KSubsetValue`.

**Comment by alfranio** [comment]
After trying to use the kSubset in a specification I found the following possible issues that are described in five different scenarios. Note though I was not able to reproduce error I, II and III in the "Evaluate Constant Expression" section, only while running a concrete specification stripped down to the bare minimum.

**Scenario I:**

The error presented in this scenario starts happening when the cardinality increases: 28 <= cardinality <= 30. The same error message is printed out if the Print TLC operator is removed.

```
GenerateKSets == kSubset(2, 1..28)
Init ==
 /\ KSet = GenerateKSets
 /\ Print(Cardinality(KSet), TRUE)
```

**Error I:**

```
Out Of Memory. There are probably too many initial states.
```

**Scenario II:**

The error presented in this scenario starts happening when the cardinality increases beyond 30:

```
GenerateKSets == kSubset(2, 1..31)
Init ==
 /\ KSet = GenerateKSets
 /\ Print(Cardinality(KSet), TRUE)
```

**Error II:**

```
Attempted to apply the operator overridden by the Java method
public static tlc2.value.impl.IntValue tlc2.module.FiniteSets.Cardinality(tlc2.value.impl.Value),
but it produced the following error:

Overflow when computing the number of elements in:
SUBSET {1, ...}
```

**Scenario III:**

The error presented in this scenario starts happening when the cardinality increases beyond 30. Note that the difference between scenario II and III is the Print TLC operator.

```
GenerateKSets == kSubset(2, 1..31)
Init ==
 /\ KSet = GenerateKSets
```

**Error III:**

```
Overflow when computing the number of elements in:
SUBSET {1,...

While working on the initial state:
KSet = SUBSET {1, ...}

The error occurred when TLC was evaluating the nested
expressions at the following positions:
...
```

**Scenario IV:**
If the KSubset operator is embedded into other operators where there is a filter, the limit increases to 63 and the error message is slightly different.

```
GenerateKSets == kSubset(2, 1..63)

GenerateFilteredKSets ==
   {s \in GenerateKSets : Cardinality(s) = 2}

Init ==
 /\ KSet = GenerateFilteredKSets
 /\ Outcomes = None
 /\ SetOfClusterConfigurations = Non
```

**Error IV:**

```
k=2 and n=63
While working on the initial state:
KSet = {s \in SUBSET {1, ...} : <expression line 'l', col 'c' to line 'l', col 'c' of module XYZ> }

The error occurred when TLC was evaluating the nested
expressions at the following positions:
    The error call stack is empty.
```

**Scenario V:**
It is the same as scenario IV but now calling GenerateFilteredKSets or KSet directly from the Evaluate Constant Expression section.

**Error V:**

```
The `Evaluate Constant Expression� section�s evaluation failed.

Attempted to apply the operator overridden by the Java method
public static tlc2.value.impl.Value tlc2.module.TLC.PrintT(tlc2.value.impl.Value),
but it produced the following error:
k=2 and n=63
```

**Comment by lemmy** [comment]
`kSubset(k, S)` should now work for `Cardinality(S) < 64` and for sensible values of `k` (otherwise, TLC will go OOM).  For larger (input) sets, more work has to happen (e.g. support for [more bits](https://github.com/tlaplus/tlaplus/blob/623c6067c3b05ad007eadb979ea7e096107c576d/tlatools/org.lamport.tlatools/src/tlc2/value/impl/SubsetValue.java#L664-L683)).  However, I would like to better understand your overall use case first.

**Comment by alfranio** [comment]
Hi Markus,

We have some (internal) tools that are used to check and report whether instances in a MySQL Innodb Cluster are healthy: memory and disk consumption are below predefined thresholds, etc, etc. During this checking we also collect information on the instance's view of the cluster and were wondering if could derive the state of the cluster based on we what we call a non- consistent global snapshot.

We would like to find out whether a cluster:

- Has a  majority of members online.
- Has automatically reconfigured itself
- Has an inconsistent configuration after a manual intervention or bug
- etc, etc

Our specification:

- Generates the initial states from:

```
GenerateInstancesViews(instances) ==
  [
    timestamp : 1..Cardinality(instances),
    id : instances,
    online : SUBSET instances,
    unreachable : SUBSET instances
  ]
```

- Filters out invalid views:

```
GenerateValidInstancesViews(instances) ==
  {
    configuration \in GenerateInstancesViews(instances) :
      IsValidInstanceView(instances, configuration)
  }
```

- Generates a set of clusters:

```
GenerateClusters(instances) ==
  kSubset(Cardinality(instances),
          RandomSubset(62, GenerateValidInstancesViews(instances)))
```

- Filters out invalid clusters:

```
GenerateValidClusters(instances) ==
  {
    cluster \in GenerateClusters(instances) :
      IsValidClusterConfiguration(instances, cluster)
  }
```

- Classifies the different clusters: Majority, Majority Loss, etc

Apart from using the generated data in the specification, we also use it to feed test cases that validate the implementation.

I had watched the Apalache Talks from 2018 and 2020 Community Events but to be honest I did not try to use it yet.

Cheers

**Comment by lemmy** [comment]
@alfranio To check if the overall idea works, I'd suggest trying this approach with a smaller cluster that doesn't run into the current limit of `kSubset`.  The occurrence of `RandomSubset` in your example suggests other bottlenecks caused by combinatorial explosion.  The [TLC profiler](https://tla.msr-inria.inria.fr/tlatoolbox/doc/model/profiling.html#modes) and the [Apalache heatmap](https://apalache.informal.systems/docs/apalache/profiling.html) would then help identify bottlenecks.

Generally, what you describe sounds like (online) conformance monitoring to me (https://docs.onosproject.org/tlaplus-monitor/docs/).  However, it is not clear to me if you care about the behavior over time or individual/independent states of the cluster ("snapshot").

**Comment by lemmy** [comment]
@alfranio, I'm going to close this issue.  Please feel free to create follow-up issues.
