### ISSUE TITLE
Not building on OpenBSD, request for cross platform JAR

### ISSUE THREAD

**Issue by samebchase** [tlaplus/tlaplus#612]
Tried building this on OpenBSD using `mvn build`, but I got an error as it was unable to download Eclipse.

I could try building this on another machine. Could someone please share the instructions I can use to create a cross platform JAR file that I can copy over to the OpenBSD machine and run it there?

```
Apr 26, 2021 11:31:04 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://download.eclipse.org:80: The target server failed to respond
Apr 26, 2021 11:31:04 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://download.eclipse.org:80
[INFO] Fetching p2.index from http://download.eclipse.org/mylyn/releases/3.24/ (126B)
[INFO] Fetching p2.index from http://download.eclipse.org/mylyn/releases/3.24/ (126B)
[INFO] Adding repository http://download.eclipse.org/mylyn/releases/3.24
[INFO] Fetching p2.index from http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/ (172B)
[INFO] Fetching p2.index from http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/ (172B)
[INFO] Adding repository http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest
[INFO] Resolving dependencies of MavenProject: tlatoolbox:org.lamport.tlatools:1.0.0-SNAPSHOT @ /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/pom.xml
Apr 26, 2021 11:31:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://download.eclipse.org:80: The target server failed to respond
Apr 26, 2021 11:31:10 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://download.eclipse.org:80
```
Eclipse was removed from the packages in 2016 from OpenBSD, and it seems that the ports (user-maintained builds something like AUR) hasn't been updated in a while. Is having Eclipse a hard requirement to build/run TLA+ Toolbox from source?

**Comment by lemmy** [comment]
If "this" is the Toolbox, you are out of luck: https://github.com/tlaplus/tlaplus/issues/141

On the other hand, TLC itself should be buildable on OpenBSD with `ant -f tlatools/org.lamport.tlatools/customBuild.xml clean compile compile-test dist`.  As an editor, consider VSCode (assuming it runs on OpenBSD) with the [TLA+ VSCode extension](https://github.com/alygin/vscode-tlaplus).

**Comment by samebchase** [comment]
@lemmy: Building TLC and using it with VSCode should is fine by me!

I understand that maintaining another set of builds for a new OS is a big task. Maybe someday, someone from the community who knows what they're doing and steps up.

Thanks for all your efforts in building and maintaining TLA+. It's a great tool!

**Comment by lemmy** [comment]
The TLA+ VSCode extension bundles TLC; you don't have to build TLC yourself.

**Comment by samebchase** [comment]
Hmm... It seems that VS Code (and Electron Apps in general) haven't been ported to OpenBSD.

I tried building TLC with the command given. I'm getting the following errors.

```
    [javac]                ^
    [javac] /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/src/tlc2/tool/management/StateMonitor.java:43: error: package com.sun.tools.attach does not exist
    [javac] import com.sun.tools.attach.AttachNotSupportedException;
    [javac]                            ^
    [javac] /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/src/tlc2/tool/management/StateMonitor.java:44: error: package com.sun.tools.attach does not exist
    [javac] import com.sun.tools.attach.VirtualMachine;
    [javac]                            ^
    [javac] /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/src/tlc2/tool/management/StateMonitor.java:45: error: package com.sun.tools.attach does not exist
    [javac] import com.sun.tools.attach.VirtualMachineDescriptor;
    [javac]                            ^
    [javac] /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/src/tlc2/tool/management/StateMonitor.java:59: error: cannot find symbol
    [javac]     public static void main(String[] args) throws IOException, MalformedObjectNameException, InterruptedException, AttachNotSupportedException {
    [javac]                                                                                                                    ^
    [javac]   symbol:   class AttachNotSupportedException
    [javac]   location: class StateMonitor
    [javac] /home/samuel/src/tlaplus/tlatools/org.lamport.tlatools/src/util/TLAFlightRecorder.java:34: error: package jdk.jfr does not exist
    [javac]     private static class ProgressEvent extends jdk.jfr.Event {
    [javac]                                                       ^
```

Java Version:

```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

**Comment by lemmy** [comment]
The build needs Java >= 11.

**Comment by samebchase** [comment]
Cool, thanks a lot for the assistance @lemmy! 

I might have to figure out some kinda CLI workflow on OpenBSD (if it even is possible). Thankfully, I have another machine where the TLA+ toolbox is working fine, so there's no hard requirement as such. Just was wondering if it would work on OpenBSD.

**Comment by lemmy** [comment]
The Toolbox and the VSCode extension have a few advanced features, such as a debugger, profile, TLAPS integration, ... that don't exist on the CLI.
