### ISSUE TITLE
SANY fails to parse certain higher-order operator arguments

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#625]
Using SANY 1.8.0. One spec reproducing issue:
```tla
---- MODULE MySpec ----
EXTENDS Naturals
F(Op(_,_)) == Op(1,2)
Foo == F(+)
====
```
SANY generates the following error:
```
Encountered "====" at line 5, column 1 and token "(+)"

Residual stack trace follows:
ExtendableExpr starting at line 5, column 1.
ExtendableExpr starting at line 4, column 8.
Expression starting at line 4, column 8.
Definition starting at line 4, column 1.
Module body starting at line 3, column 1.
```
This also occurs with the `-` and `/` operators. I couldn't find any other binary operators triggering this issue during a non-exhaustive random sample.

**Comment by ahelwer** [comment]
Update to this: SANY successfully parses the following:
```
f( + )
f( - )
f( * )
f( / )
```
but not these:
```
f(+)
f(-)
f(*)
f(/)
```

**Comment by ahelwer** [comment]
I believe this is due to (undocumented?) alternative symbols for `\oplus`, `\ominus`, `\oslash`, `\otimes`, and `\odot` with `(+)`, `(-)`, `(/)`, `(\X)`, and `(.)` respectively. The following snippet passes syntactic & semantic validation, supporting the hypothesis:
```
a (/) b == a + b
f == 1 \oslash 2
```
We can also see these symbols defined in the TLA+.jj file [here](https://github.com/tlaplus/tlaplus/blob/5682c4a04610467762d01ce48c1a8a0ae714e68f/tlatools/org.lamport.tlatools/javacc/tla%2B.jj#L1381), confirming this.

**Comment by lemmy** [comment]
If 2. the behavior should be documented in https://lamport.azurewebsites.net/tla/current-tools.pdf

**Comment by ahelwer** [comment]
Closing as wontfix; users can insert spaces if they want to resolve the ambiguity.
