### ISSUE TITLE
SANY does not correctly parse lor/land operators in nonfix form

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#637]
The following specs produce parse errors of `Encountered "," at line X, column Y etc.`:
```tla
---- MODULE MySpec ----
op == \/(TRUE, FALSE)
====
```
```tla
---- MODULE MySpec ----
op == /\(TRUE, FALSE)
====
```
The most-likely root cause is the parser code for conjunction/disjunction lists does not lookahead to see whether a given land/lor token is followed by nonfix function application, so immediately identifies the land/lor tokens as the start of a conjunction or disjunction list. SANY then tries to parse (TRUE, FALSE) as an expression by itself.

Probably not worth fixing but good to document somewhere.

**Comment by hwayne** [comment]
You also can't do `<(1, 2)`.

Do we have a measure of how many "real world" specs use nonfix operators?

**Comment by lemmy** [comment]
The only thing I can think of is to look at the [TLA+ examples.](https://examples.tlapl.us)  The TLC/Apalache usage statistics do not collect information about specs.

**Comment by ahelwer** [comment]
@hwayne this parses for me with SANY:
```tla
---- MODULE MySpec ----
EXTENDS Naturals
op == <(1, 2)
====
```
TLC also evaluates it.

**Comment by hwayne** [comment]
Ah, found the issue internally, my mistake. Issue withdrawn.

**Comment by ahelwer** [comment]
Related to this (and also not worth fixing) SANY will fail to parse this:
```tla
---- MODULE Test ----
USE \/
USE /\
====
```
Although it correctly parses `/\` and `\/` as higher-order operator parameters in other contexts, presumably because it looks ahead and finds the `,` or `)`:
```tla
---- MODULE Test ----
op(_ + _) == TRUE
op2 == op(/\)
op3 == op(\/)
====
```
Ref https://github.com/tlaplus-community/tree-sitter-tlaplus/issues/96
