### ISSUE TITLE
After translating PlusCal, the toolbox resets the position to the top of the file

### ISSUE THREAD

**Issue by shuhaowu** [tlaplus/tlaplus#638]
It seems that when I work with a large enough file, every time I translate the PlusCal, the view of the file will jump from wherever I am in the toolbox to the top of the file.

This makes it a bit cumbersome to work on large pluscal files.

**Comment by lemmy** [comment]
Yes, this is indeed an annoyance.

Btw., the TLA+ VSCode extension handles this more gracefully.

**Comment by shuhaowu** [comment]
Is that plugin supposed to replace the eclipse-based toolbox? Should I be switching to it?

**Comment by lemmy** [comment]
Iff the community votes with its feet and moves to the VScode plugin, it is still going to be a long way to feature parity with the Toolbox. If you are invested in the toolbox and can live with its glitches, I'd suggest staying with the Toolbox for now. :-)

**Comment by lemmy** [comment]
@shuhaowu Please check if the newest [nightly build](https://nightly.tlapl.us/products) fixes the issue.

**Comment by shuhaowu** [comment]
Thanks! This is now much better. It still causes a minor jump in the screen position when translating such that the cursor is at about the 30% position from the top of the screen. I can't reliably reproduces it, it seems to happen when I made more than a few lines of changes. But at least the cursor remain visible within the view, which is really all that matters for now.
