### ISSUE TITLE
Inconsistent SANY behavior when parsing higher-order recursive operators

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#646]
Looking at the recursive operator declaration rules in the [tla+.jj](https://github.com/tlaplus/tlaplus/blob/17cb6d5404e55b40aab2df6a8a0928ed16b86d8a/tlatools/org.lamport.tlatools/javacc/tla%2B.jj#L1832) and [TLAPlus2Grammar.tla](https://github.com/tlaplus-community/tlaplus-standard/blob/de3741d81482ef307594850f34e7e915e672627a/grammar/TLAPlus2Grammar.tla#L107) files, you get the impression that higher-order recursive operators are declared as follows:
```tla
---- MODULE Test ----
RECURSIVE f(_, _, op(_, _))
f(a, b, op(_, _)) == TRUE
====
```
However, SANY doesn't agree - it gives the parse error:
> Was expecting "_"
> Encountered "op" at line 2, column 19 in module Test and token ","

So you can try swapping out `op(_, _)` for a `_` placeholder in the `RECURSIVE` declaration:
```tla
---- MODULE Test ----
RECURSIVE f(_, _, _)
f(a, b, op(_, _)) == TRUE
====
```
but then SANY outputs a different error:
> Definition of f has different arity than its RECURSIVE declaration.

So it's unclear how to actually define a higher-order recursive operator. Mysteriously, there's a (probable) bug that provides a workaround: the arity error goes away when the `op(_, _)` parameter isn't the last parameter in the declaration of `f`:
```tla
---- MODULE Test ----
RECURSIVE f(_, _, _)
f(a, op(_, _), b) == TRUE
====
```
and TLC evaluation works as you'd expect.

It's unclear what the actual behavior *should be* here. Higher-order recursive operators are clearly useful, for example to define `fold` operators over sets or sequences. So they should be allowed. And it doesn't make a large difference whether they are declared with `RECURSIVE f(_, _, op(_, _))` or `RECURSIVE f(_, _, _)`, although the former enables more precise arity checking. But as-is it seems like an arity checking bug and operator declarations like `f(a, b, op(_, _))` where the operator is at the end should be allowed.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/57#issuecomment-844318109

**Comment by ahelwer** [comment]
Hah, there I am merrily commenting in an old thread forever lost to memory. Well like Hillel said, such a thing certainly is useful... making this a low priority bug.
