### ISSUE TITLE
ClassCastException in profiler's CostModel when top-level expression of action, init-predicate, invariant, constraints ... is declared RECURSIVE

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#649]
Example one-bit-clock spec:
```tla
---- MODULE OneBitClock ----
VARIABLE clock
RECURSIVE Check(_)
Check(c) == c \in BOOLEAN
TypeOK == Check(clock)
Init == clock = FALSE
Next == clock' = ~clock
====
```
When asked to check `TypeOK`, TLC emits the following error:
>TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.ClassCastException
: class tlc2.tool.coverage.ActionWrapper cannot be cast to class tlc2.tool.coverage.OpApplNodeWrapper (tlc2.tool.coverage.ActionWrapper and tlc2.tool.coverage.OpApplNodeWrapper are in unnamed module of loader 'app')

Encountered during [this](https://groups.google.com/g/tlaplus/c/_U-3QZ0Ya_w/m/ijY-hXzYAwAJ) thread on the google group.

**Comment by lemmy** [comment]
### Workaround: Run TLC *without* the `-coverage` parameter.

Related: #314 #415 https://github.com/tlaplus/tlaplus/pull/588#issuecomment-817371371

**Comment by ahelwer** [comment]
@lemmy is there any way to run TLC without the `-coverage` parameter from within the toolbox, or does it have to be from the command line?

**Comment by lemmy** [comment]
Turn off `profiling` on the model's `TLC options` page:

![Screenshot from 2021-07-27 08-56-14](https://user-images.githubusercontent.com/88777/127187047-69dc354f-3fb7-446f-84e2-6f342372c9fd.png)
