### ISSUE TITLE
Spurious (?) error: `No next state actions defined to generate successor states from`

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#651]
NoNextState.tla:
```tla
---- MODULE NoNextState ----

CONSTANT Procs
VARIABLE pc

Init ==
    /\ pc = [p \in Procs |-> "INIT"]

Step(p) ==
    /\ pc[p] = "INIT"
    /\ pc' = [pc EXCEPT ![p] = "DONE"]

Next ==
    \/ \E p \in Procs: Step(p)

====
```

NoNextState.cfg:
```text
CONSTANT Procs = {}
INIT Init
NEXT Next
CHECK_DEADLOCK FALSE
```

Results in:
```text
$ tlc2 NoNextState.tla
[...]
Finished computing initial states: 1 distinct state generated at 2021-07-27 11:51:45.
Error: No next state actions defined to generate successor states from.
Finished in 00s at (2021-07-27 11:51:45)

$ echo $?
75
```

Two points here:
 1. The error message is confusing. I have absolutely defined a next-relation (and it's even satisfiable when `Procs /= {}`).
 2. Actually, I don't think this should be an error at all.

----

A bit of discussion about point 2 above:

Deadlock checking should already cover this scenario.

TLC does not complain in other circumstances when `Next` is unsatisfiable. Consider:
```tla
FalseTheHardWay ==
    pc /= pc

Next_v2 ==
    \/ FalseTheHardWay
```

Even though there are no next-states, TLC happily reports
```text
1 states generated, 1 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 1.
The average outdegree of the complete state graph is 0 (minimum is 0, the maximum 0 and the 95th percentile is 0).
Finished in 00s at (2021-07-27 11:58:43)
```

TLC will rightfully report an error if deadlock checking is enabled.

There isn't much difference in my mind between `Next` and `Next_v2`. The "No next state actions defined" error is not useful to me, and I would expect deadlock checking to detect such cases instead.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/79297f07740147fa9aaeec532d9449b539604b23

**Comment by Calvin-L** [comment]
79297f0 fixes the issue for the spec I was working on. Thanks for the quick turnaround!
