### ISSUE TITLE
Potential Feature: Drop Comparability Conditions

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#653]
I think it could sometimes be helpful to drop TLC's comparability conditions by assuming that all the different classes of TLC values have pairwise empty intersections, thereby making any inter-class comparisons equal to false.

I understand that there are no atoms in ZF and thus numbers, functions, etc have to be represented as pure sets, their encodings are unspecified and thus could overlap. But can't I choose the encodings in a non-overlaping way? At least for some of the classes.

Cheers!

**Comment by lemmy** [comment]
At this point, there are no plans to fundamentally change TLC's behavior.
