### ISSUE TITLE
TLC can not override higher-order operators

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#654]
When trying to override the operator `A(a(_)) == 1` the override `A(a(_)) -> a(1)` gives `A parameter name a(_) may not be used, since it is not a valid identifier`
Other things I tried:
- `A(a) -> a(1)` gives `The operator a requires 0 arguments.`
- `A(a) -> a` gives no complaints, but is nonsensical. On use it requires an operator with arity 1. Results were:
1. `A(LAMBDA x : x)` gives `In evaluation, the identifier x is either undefined or not an operator. [newline] x`
2. `A(LAMBDA x : 1)` evaluates to 1
- `A(a) -> B(a)` with `B(b(_)) == b(1)` gives `Expected arity 1 but found operator of arity 0`

I have not tried TLC outside the toolbox (yet).

**Comment by lemmy** [comment]
It would be good to see real-world specs where this bug shows up in practice to determine this issue's priority.

**Comment by zwergziege** [comment]
I use a lot of inductive definitions like this definition of arbitrarily nested lists
```tla
RecF(s0, next(_))   == LET f[n \in Nat] == IF n = 0 THEN s0 ELSE next(f[n-1]) IN  f
RecDef(s0, next(_)) == UNION {RecF(s0, next)[n] : n \in Nat}
...
BaseList      == { List(<<>>) }
NextList(p)   == p \cup { List(v) : v \in Seq(p \cup Naturals \cup Bools) }
Lists         == RecDef(BaseList, NextList)
```
When model checking I need to make the state space finite. In most cases the number of inductive steps should be chosen individually for each inductive definition, but I tried overriding `RecDef` directly and it failed. Even if that was absolutely necessary I could just replace `Nat` in `RecDef` with `NatRecDef == Nat` and override that. I think that in most cases there will be a similar workaround. So there is no real need (at least for me).

**Comment by lemmy** [comment]
Complex constant-level specs are a very niche use case and, thus, not well supported by TLC.  It seems to me that a functional programming language might better fit your task.

**Comment by zwergziege** [comment]
I'm not entirely sure how this relates to the issue at hand, but I appreciate the advice. In hindsight, I would probably have focused on the proofing part and used coq. The thing is that I want to do both model-checking and theorem proving and I also plan to extend to concurrent behavior.

**Comment by lemmy** [comment]
Workaround:  Declare `A` to be a CONSTANT operator:

```tla
---- MODULE Github654 ----
EXTENDS TLC

CONSTANT A(_)
a(n) == n

ASSUME PrintT(A(a(42)))    

====

---- MODULE MC ----
EXTENDS Github654
 
B(b) == "b"

====
```

```
CONSTANT
A <- B
```
