### ISSUE TITLE
tab characters in file `Randomization.tla`

### ISSUE THREAD

**Issue by johnyf** [tlaplus/tlaplus#655]
It appears that tab characters are present in the file https://github.com/tlaplus/tlaplus/blob/dbe63419108b63ff23f80fa653665e64fd54f7b7/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/Randomization.tla and in other TLA+ files. The presence of tabs causes `tlapm` to fail parsing. This was first reported at: https://github.com/tlaplus/tlapm/issues/28. Removing the tab characters from the file `Randomization.tla` results in a successful run of `tlapm`.

The tab characters in the file `Randomization.tla` are in the line:

https://github.com/tlaplus/tlaplus/blob/dbe63419108b63ff23f80fa653665e64fd54f7b7/tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/Randomization.tla#L49

The output from `tlapm` when tab characters are present is the following (the "..." below resulted from editing the output of `tlapm`):

```
File ".../tla2sany/StandardModules/Randomization.tla", line 49, character 1
Unexpected TAB character. TLAPS does not handle TAB characters in source files.
File ".../tla2sany/StandardModules/Randomization.tla", line 48, character 31
Unexpected EOF
File "<unknown>":
Error: Could not parse ".../tla2sany/StandardModules/Randomization.tla" successfully.
 tlapm ending abnormally with Failure("Module.Parser.parse_file")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from M_save.clocking in file "m_save.ml", line 25, characters 16-20
Called from Tlapm.read_new_modules.(fun) in file "tlapm.ml", line 466, characters 8-112
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Tlapm.main in file "tlapm.ml", line 510, characters 20-43
Called from Tlapm.init in file "tlapm.ml", line 537, characters 8-33
```

The other TLA+ files in commit dbe63419108b63ff23f80fa653665e64fd54f7b7 that appear to contain tab characters are the following:

general/tests/bug1.tla
tlatools/org.lamport.tlatools/src/pcal/Pcal.tla
tlatools/org.lamport.tlatools/src/tla2sany/StandardModules/Randomization.tla
tlatools/org.lamport.tlatools/test-model/BagsTest.tla
tlatools/org.lamport.tlatools/test-model/coverage/Github649.tla
tlatools/org.lamport.tlatools/test-model/EvalOrder/InitEvalOrder.tla
tlatools/org.lamport.tlatools/test-model/EWD840/Error02.tla
tlatools/org.lamport.tlatools/test-model/EWD840/Error03.tla
tlatools/org.lamport.tlatools/test-model/EWD840/MC02.tla
tlatools/org.lamport.tlatools/test-model/EWD840/MC02Sim.tla
tlatools/org.lamport.tlatools/test-model/EWD998/EWD998.tla
tlatools/org.lamport.tlatools/test-model/EWD998/EWD998Chan.tla
tlatools/org.lamport.tlatools/test-model/pcal/Bakery.tla
tlatools/org.lamport.tlatools/test-model/pcal/bug_05_10_03.tla
tlatools/org.lamport.tlatools/test-model/pcal/bug_05_12_31.tla
tlatools/org.lamport.tlatools/test-model/pcal/CallReturn2.tla
tlatools/org.lamport.tlatools/test-model/pcal/CCallReturn1.tla
tlatools/org.lamport.tlatools/test-model/pcal/CMultiprocDefine.tla
tlatools/org.lamport.tlatools/test-model/pcal/Euclid.tla
tlatools/org.lamport.tlatools/test-model/pcal/InnerLabeledIf.tla
tlatools/org.lamport.tlatools/test-model/pcal/MacroRealQuicksort.tla
tlatools/org.lamport.tlatools/test-model/pcal/MacroQuicksort.tla
tlatools/org.lamport.tlatools/test-model/pcal/MergeSort.tla
tlatools/org.lamport.tlatools/test-model/pcal/MPNoParams.tla
tlatools/org.lamport.tlatools/test-model/pcal/MultiAssignment.tla
tlatools/org.lamport.tlatools/test-model/pcal/MultiprocDefine.tla
tlatools/org.lamport.tlatools/test-model/pcal/MultiProc2.tla
tlatools/org.lamport.tlatools/test-model/pcal/NoLoop.tla
tlatools/org.lamport.tlatools/test-model/pcal/NoLoop2.tla
tlatools/org.lamport.tlatools/test-model/pcal/NoParams.tla
tlatools/org.lamport.tlatools/test-model/pcal/NotSoSimpleLoop.tla
tlatools/org.lamport.tlatools/test-model/pcal/Quicksort.tla
tlatools/org.lamport.tlatools/test-model/pcal/QuicksortMacro.tla
tlatools/org.lamport.tlatools/test-model/pcal/Quicksort2Procs.tla
tlatools/org.lamport.tlatools/test-model/pcal/ReallySimpleMultiProc.tla
tlatools/org.lamport.tlatools/test-model/pcal/RAB.tla
tlatools/org.lamport.tlatools/test-model/pcal/RealQuicksort.tla
tlatools/org.lamport.tlatools/test-model/pcal/RealQuicksort2.tla
tlatools/org.lamport.tlatools/test-model/pcal/SBB.tla
tlatools/org.lamport.tlatools/test-model/pcal/SimpleLoop.tla
tlatools/org.lamport.tlatools/test-model/pcal/SimpleLoopWithProcedure.tla
tlatools/org.lamport.tlatools/test-model/pcal/SimpleMultiProc.tla
tlatools/org.lamport.tlatools/test-model/pcal/SyncCons.tla
tlatools/org.lamport.tlatools/test-model/pcal/TestTabs.tla
tlatools/org.lamport.tlatools/test-model/pcal/ULCallReturn1.tla
tlatools/org.lamport.tlatools/test-model/pcal/ULEuclid.tla
tlatools/org.lamport.tlatools/test-model/pcal/ULQuicksortMacro.tla
tlatools/org.lamport.tlatools/test-model/pcal/UniprocDefine.tla
tlatools/org.lamport.tlatools/test-model/symmetry/ChooseTableauSymmetry.tla
tlatools/org.lamport.tlatools/test-model/symmetry/ErrorTraceConstruction.tla
tlatools/org.lamport.tlatools/test-model/symmetry/OneBitMutex/OneBitMutex.tla
tlatools/org.lamport.tlatools/test-model/symmetry/TableauSymmetry.tla
tlatools/org.lamport.tlatools/test-model/TLCSet.tla
tlatools/org.lamport.tlatools/test-model/TLCSetSim.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/AdditionalSequenceOperators.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/CertificateModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ClientKnowledgePredicatesModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ClientLogModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/FileModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ModeModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/PhysicalComponentsModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/Sequences.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerFileProtectionModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerFileOwnershipModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerLeasePartialActionsModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerLeaseManagerModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerMessageModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerReviewPredicatesModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ServerOperationProcessorModule.tla
toolbox/org.lamport.tla.toolbox.uitest/farsite/ThreadModule.tla

**Comment by lemmy** [comment]
@johnyf What about replacing tabs with spaces in `Randomzation.tla`, but ignoring the specs that are used for tests.  However, I would suggest checking the [TLA+ examples](https://examples.tlapl.us/).

**Comment by johnyf** [comment]
Thank you for addressing this issue. Yes, changing the file `Randomization.tla` and leaving the test files unchanged seems good to me.

In the `Examples` repository, the following files contain tab characters:

specifications/tower_of_hanoi/Hanoi.tla
specifications/TLC/TLCMC.tla
specifications/tower_of_hanoi/Hanoi.toolbox/Model_1/Hanoi.tla

and in the `CommunityModules` repository, the following files contain tab characters:

modules/Combinatorics.tla
tests/CombinatoricsTests.tla
tests/CSVTests.tla
tests/FunctionsTests.tla
tests/FiniteSetsExtTests.tla
tests/IOUtilsTests.tla
tests/SequencesExtTests.tla

A sidenote is that in the `Examples` repository it appears that the `.gitignore` file makes the `*.tla` files listed above to be ignored (these files do not show up in the search without passing an option to include patterns from `.gitignore`, or alternatively without temporarily renaming the file `.gitignore`).

**Comment by lemmy** [comment]
Converted everything you listed above (including TLC tests).

**Comment by johnyf** [comment]
Thank you for converting the tabs to spaces.

**Comment by lemmy** [comment]
What seems to remain open is to make the TLA+ VSCode extension always insert spaces instead of tabs.  @johnyf Can you open an issue explaining that TLAPM doesn't handle tabs?

**Comment by johnyf** [comment]
Yes, I will open an issue about this at the TLA+ VSCode extension repository.
