### ISSUE TITLE
Using package from Github (or Central) maven repository 

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/tlaplus#656]
I'm trying to use the Github maven package from https://github.com/tlaplus/tlaplus/packages/163463, but I'm having 

```
Could not transfer artifact org.lamport:tlatools:pom:1.7.0-SNAPSHOT from/to github-maven (https://maven.pkg.github.com/tlaplus/*): status code: 401, reason phrase: Unauthorized (401)
```

Should I be using some other url? Also the last published snapshot appears to be from 2020 April, but in the CI it's being published to the repository automatically (https://github.com/tlaplus/tlaplus/runs/3246785659), though I cannot use it.

Related, do we have tlatools in maven central? I've read about it in https://github.com/tlaplus/tlaplus/blob/d977051118f63b9c97d7d4c4d6af27183971ada3/tlatools/org.lamport.tlatools/ossrh.xml.README, but couldn't find it by searching there.

**Comment by lemmy** [comment]
IIRC, the Github maven repository has restrictions that made it effectively useless (please verify, though).  Deploying to maven central has not been automated yet, but the basic pieces should be there.

**Comment by pfeodrippe** [comment]
Yeah GitHub maven repository only works with credentials AFAIK. I have read somewhere that the owner could create a read only credential and then we can use these embedded in the url, but this appears to be a hack and not very user friendly.

**Comment by lemmy** [comment]
Seems you've made some progress. Is this still an issue?

**Comment by pfeodrippe** [comment]
Hi Markus,

Do you know if the instructions at  https://github.com/tlaplus/tlaplus/blob/d977051118f63b9c97d7d4c4d6af27183971ada3/tlatools/org.lamport.tlatools/ossrh.xml.README are working? You have the credentials, right? If you are able to deploy it manually, then we can close this issue o/

And if it works manually, later I can check how to deploy it with GitHub Actions automatically after each build and open a PR with it o/

**Comment by lemmy** [comment]
Does `tladeps` need a maven repository?  If not, I don't think it's worth automating.

**Comment by pfeodrippe** [comment]
> Does `tladeps` need a maven repository? If not, I don't think it's worth automating.

No, it does not. It's just that tladeps is using a tlatools version built locally by me from the master source. 

But you are right, we don't need it in Maven Central to make it work and TLC does not change a lot in such a way that the users really need the last feature, it's very stable from where I can see :)

So I will close this issue, it's not really blocking anything o/

Thanks
