### ISSUE TITLE
Assertion failed after TLAPS run, file change and save

### ISSUE THREAD

**Issue by quicquid** [tlaplus/tlaplus#66]
Hello,

When I execute the following steps, I can reproduce the error message: "Save Failed
assertion failed: " in a popup box:

* Load [switcheroo.tla](https://github.com/tlaplus/tlaplus/files/1299486/switcheroo.tla.txt)
* Run TLAPS such that the lemma obligation is colored (red in this case)
* Change a line (e.g. remove / add a newline somewhere)
* Save

Then the error message appears and the coloration is lost (this seems to always happen after a save). Repeating the procedure reproduces the failed assertion. I received a 
[backtrace](https://github.com/tlaplus/tlaplus/files/1299506/backtrace.txt) once, but I can not reproduce it and it might be unrelated.

This bug occurs in git commit 9d38970362a00cbddd5f7d542b5569b7efb36071 

thanks for having a look into this,
Martin

**Comment by lemmy** [comment]
Is Unicode support turned on?

**Comment by quicquid** [comment]
Oh yes, it's with unicode support on. Turning it off makes the error message vanish.

**Comment by quicquid** [comment]
It works for me, thanks!
