### ISSUE TITLE
Feature request: printing strings and special characters

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#662]
`PrintT("escape \" quote")` results in `"escape \" quote"`. This is a sensible choice when printing arbitrary objects, but it would be nice to have some print operator that prints strings as they are (in this case `escape " quote`). Especially the new-line character would be beneficial when pretty-printing complex structures. I know that most things can be accomplished by using `PrintT` but using strings instead allows much easier manipulation and is advocated in the "current tools" document.

**Comment by lemmy** [comment]
I suggest adding dedicated operators with the desired behavior to, e.g., the [IOUtils module of the CommunityModules](https://github.com/tlaplus/CommunityModules/blob/master/modules/IOUtils.tla).

**Comment by zwergziege** [comment]
That's a fair point.
I'm currently modeling structural operational semantics of toy languages and debugging is no fun without pretty formatting.
I have a few utils that could be useful to others and am happy to contribute. It might take me a while though to get them to shape.

**Comment by lemmy** [comment]
Why don't you use the Toolbox's trace explorer and trace expressions when debugging?

**Comment by zwergziege** [comment]
1. At the moment my specs are not really dependent on the temporal capabilities of TLA since I don't use concurrency (yet). Since many of my specs exhibit the behavior mentioned in #661, I tend to evaluate programs using the constant expression section (which is not too pleasant since it doesn't report the exact error location, but that's another topic). This kind of defeats the purpose of using TLA in the first place, but I'm committed :D
2. I'd still prefer trace expressions that pretty print ASTs if needed to trace expressions that don't
Thanks for the link. I'll take a look at that.

**Comment by lemmy** [comment]
That's not what constant expressions are meant for, which is why the tooling is not up to the task.  Instead, I suggest modeling your program as a behavior, which will unlock the debugging support you find lacking. Whether or not there is concurrent (non-determinism) involved doesn't matter; a behavior spec might as well model a (deterministic) sequence of transitions.

**Comment by zwergziege** [comment]
Thanks for the advice! I actually started this way and resorted to const expressions due to the aforementioned startup times of model checker runs. I still think that the TLCs debugging capabilities including trace exploration will benefit from advanced printing methods since large structures tend to become difficult to read in the trace explorer.
I like the idea of exposing Java's `printf` in a community module and would like to implement it. However, I can't promise that I'll find the time soon since it is more of a nice to have than a necessity.

**Comment by lemmy** [comment]
I actually can't think of a representation more suitable for reading large structures than the trace explorer or the debugger view; it comes with highlighting, folding, filtering, ...  Anyway, no reason not to add a `printf` operator.

**Comment by lemmy** [comment]
When you model your spec as a state machine, why do you still have to re-define operators to the point that it affects startup time?  Users have been re-defining operators since the beginning, and none ran into this issue.

**Comment by zwergziege** [comment]
> I actually can't think of a representation more suitable for reading large structures than the trace explorer or the debugger view; it comes with highlighting, folding, filtering, ... Anyway, no reason not to add a `printf` operator.

Then I might have missed a few features... Silly me.

> When you model your spec as a state machine, why do you still have to re-define operators to the point that it affects startup time? Users have been re-defining operators since the beginning, and none ran into this issue.

I will try to pinpoint it and report back in case I find anything.

**Comment by lemmy** [comment]
Instead of evaluating a constant expression `C`, the following spec should let you inspect the value of `C` in the trace explorer (note that the TLA+ debugger also steps through `ASSUMES`):

```tla
---- MODULE Foo ----

C == ...

-------
VARIABLE x

Init == x = C

Next == FALSE
====
```
