### ISSUE TITLE
Outdated repository link on Oomph installer

### ISSUE THREAD

**Issue by edaena** [tlaplus/tlaplus#664]
One of the repositories from installing with Oomph has an outdated version.
I got this error with the suggested JDK 14 and version 2020-03.
Platform: macOS

Looks like it's on this step from the TLA.setup file:
```
 <repository
        url="http://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/"/>
```

<img width="1317" alt="Screen Shot 2021-08-16 at 7 33 29 PM" src="https://user-images.githubusercontent.com/1280985/129654936-cae397aa-db6e-460d-915e-c6ca3f1e33a8.png">

**Comment by lemmy** [comment]
Thanks, the readme has been updated to say Eclipse `2020-12`.

**Comment by jeffmeyerson** [comment]
@edaena Just wanted to confirm everything is OK, with the Oomph installer and otherwise. Please confirm via email if you have time.
