### ISSUE TITLE
Run TLC in cmd

### ISSUE THREAD

**Issue by tangruize** [tlaplus/tlaplus#665]
There is a need to use TLC on a server without GUI. [tlacli](https://github.com/hwayne/tlacli) is a cool tool. But it can't fully meet my needs. I write a simple script to do this job.

It supports:

- almost all options in TLA+ toolbox model checking panel
- batch models
- show model checking progress like TLA+ toolbox
- save batch result to a csv file
- replace the Init state with a specific state from a trace file
- read trace file to python object or dump json

Here is the repo link: [tlc-cmd](https://github.com/tangruize/tlc-cmd). The usage is simple, just write a config ini file.

Hope this tool can be useful!

**Comment by lemmy** [comment]
@tangruize https://github.com/tlaplus-community/tree-sitter-tlaplus might be relevant for your work.

**Comment by lemmy** [comment]
https://www.reddit.com/r/tlaplus/comments/pekzgf/github_tangruizetlccmd_run_tlc_in_cmd/ has a wider audience and is, thus, a better place to announce tlc-cmd.
