### ISSUE TITLE
Simulation mode trace dumps lack action names

### ISSUE THREAD

**Issue by tangruize** [tlaplus/tlaplus#666]
In the traces dumped in simulation mode, action's name is lost. Here is an example:

```
STATE_1 == 
/\ big = 5
/\ small = 0


STATE_2 == 
/\ big = 5
/\ small = 0
```

However, traces in TLC output log (MC.out) preserves the action name:

```
State 2: <FillSmall line 13, col 14 to line 14, col 28 of module DieHard>
/\ big = 5
/\ small = 3
```

Is it possible to provide an option to save the action name like `actionlabel` in model checking mode `-dump` option?

**Comment by lemmy** [comment]
The simulation dump is a syntactically correct TLA+ spec, while MC.out is just plaintext.  Are you interested in dumping large numbers of traces or just a single one?

**Comment by tangruize** [comment]
I am interested in dumping large numbers of traces. I think the action that leads to the state is valuable information. Is it possible to add a comment above the state to indicate which action leads to that state?

**Comment by lemmy** [comment]
This would be straightforward: Adding `pw.println("\* stateTrace.elementAt(idx).getAction() + "\n");`  to the for loop below should do the trick: https://github.com/tlaplus/tlaplus/blob/2ded5d0ba87efaa8f3d4a2e7cdcd5cbe5130fe0d/tlatools/org.lamport.tlatools/src/tlc2/tool/SimulationWorker.java#L540-L543

@tangruize Can you provide a patch?
