### ISSUE TITLE
TLA+ Toolbox Plugin develop

### ISSUE THREAD

**Issue by niuzhi** [tlaplus/tlaplus#669]
Hello。
I am currently working on the development environment of the toolbox, which is convenient for improving some of the functions of the toolbox on the original basis, such as code auto-completion, code format checking, etc. Now encounter the following questions, please help answer!

1.Reference documents，https://github.com/tlaplus/tlaplus/tree/master/general/ide ，Refer to the document, but the tlaplus project has not been refreshed in the 13th step。why？
 
![image](https://user-images.githubusercontent.com/33443724/132511906-1e9d041e-937b-4362-9eeb-d4b1859c4638.png)

2.After I imported the local tlaplus project through the import function of the eclipse platform, there was an error. Why?

![image](https://user-images.githubusercontent.com/33443724/132512724-d350e2a9-496f-43f6-a5ce-3d3600fbf3e4.png)

3.when I run  org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product，Produces the following error,why？
![image](https://user-images.githubusercontent.com/33443724/132513210-a7c7d347-b368-4cad-bf55-c3ef715de499.png)

4.Is there a detailed deployment document for toolbox plug-in development for reference? Thank you very much.

**Comment by lemmy** [comment]
Something went wrong *before* step 13. because you ended up *manually* importing plug-ins, which should be automatic.  Do you see the "executing startup tasks" message and spinning-arrow icon in step 12.?  If step 12. errors out, click the icon to see the error message.

By the way, do you want to elaborate on what functionality you wish to add?  We are grateful for any contributions, but there could be a reason why something hasn't been done yet.

**Comment by lemmy** [comment]
Is it possible that you missed checking the "TLA+" tree item in step 7.?

**Comment by niuzhi** [comment]
@lemmy step 13 produces the following error
![image](https://user-images.githubusercontent.com/33443724/132636353-6e834300-2b7e-4ad6-89d7-15f6ad34e3ac.png)

**Comment by lemmy** [comment]
This could be a transient issue (network).  Please retry and also make sure that you selected "2020-12" as "Product version" at the beginning of the installer.

**Comment by lemmy** [comment]
Please re-open if this is still an issue.
