### ISSUE TITLE
Toolbox error-trace parser problem when TLA+ string contains equals sign

### ISSUE THREAD

**Issue by timimin** [tlaplus/tlaplus#670]
After updating to version 1.7.1 the error-trace parser cannot handle strings containing equality sign "=".
Model checker itself works fine.

**Comment by lemmy** [comment]
@timimin Can you please provide a spec/model that reproduces the bug?

**Comment by timimin** [comment]
The main spec is ConferenceProcFS_final.tla. The Model_1 conf is inside but it seems the model is not imported automatically.
The current configuration induces the invariant violation. In the respective error-trace see the variable named Trace.
[plif.zip](https://github.com/tlaplus/tlaplus/files/7152067/plif.zip)

**Comment by timimin** [comment]
The main spec is ConferenceProcFS_final.tla. The Model_1 check results in the
 invariant violation. In the respective error-trace see the variable named Trace.
[plif.zip](https://github.com/tlaplus/tlaplus/files/7152793/plif.zip)

**Comment by timimin** [comment]
in the prev version it worked fine

**Comment by lemmy** [comment]
Fixed in most recent [nightly](https://nightly.tlapl.us/products/).

----

For reference, basic test spec:

```tla
----------------------------- MODULE Github670 -----------------------------
VARIABLE v

Init == v = ""

Next == v' = "foo = bar"

Inv == v = ""
=============================================================================
```
