### ISSUE TITLE
Multiline Action Property in conjunction not always parseable 

### ISSUE THREAD

**Issue by hwayne** [tlaplus/tlaplus#678]
Given `VARIABLES x`, the following *does not* parse:

```
Refinement ==
  /\ [][x' # x
  ]_x
```

The follow *does* parse:

```
Refinement ==
  /\ [][x' # x
   ]_x
```

The difference is a single space before `]_x`. The following also parses:

```
Refinement ==
  [][x' # x
]_x
```

The difference is no `/\` on the first line.

**Comment by xxyzzn** [comment]
First of all, remember that

   /\ ...

is the conjunction of a bulleted list of expressions containing one expression.  It is syntactically correct if and only if

   /\ TRUE
   /\ ...

is syntactically correct.  In your example,

   /\ [][x' # x
   ]_x
   
is parsed as (/\ [][x' # x) ]_x while

   /\ [][x' # x
    ]_x
   
is parsed as /\ ([][x' # x) ]_x)

A single space changes the whether the expression is syntactically correct, as it has to.  You would expect

   /\ [][x' # x
                      ]
to be syntactically correct and

   /\ [][x' # x
 ]

not to be syntactically correct.  So there has to be someplace where moving the  ] one space to the left makes the expression unparseable.  The precise spec of the grammar tells you where that place is.  I don't remember what the precise spec says, but I have no reason to doubt that your example is consistent with that spec.

**Comment by lemmy** [comment]
(I allowed myself to escape the TLA+ examples as markdown code blocks to preserve whitespace)
