### ISSUE TITLE
TOOLBOX Optimized development

### ISSUE THREAD

**Issue by niuzhi** [tlaplus/tlaplus#684]
Hello, I am optimizing the toolbox. The optimized functions include code auto-completion, code auto-prompting, and code formatting checking and repairing. It is used to serve people who are not familiar with TLA syntax for rapid development. Currently. The environment has been set up. How should I implement these functions? Are there relevant development documents? These functions should be added under the editor package? Because I don't know much about the TOOLBOX source code. Hope to get your help, thank you very much! Looking forward to the reply from the community!

![image](https://user-images.githubusercontent.com/33443724/140020945-60860889-62d0-47c9-b211-edd05d64a3b8.png)

**Comment by lemmy** [comment]
Hi, for us to help you, you will have to give a detailed description of what these features are going to look like from the user's perspective.  It is probably best to start with a TLA+ spec and discuss what the proposed features do.

**Comment by niuzhi** [comment]
@lemmy 
Hello, because Toolbox does not have code hints and code completion functions, it makes it difficult for people who are not familiar with TLA+ syntax to develop spec. So I plan to add this feature. For example, if I enter the letter 'U' in vscode, vscode will prompt me as shown in the figure1 below for developers to choose, but there is no under toolbox. In addition, we need to always pay attention to the alignment of /\ or \/ when writing the spec. For inattentive developers, we always do not pay attention to alignment, which leads to parsing errors. Therefore, we plan to implement the format of the spec and implement the TLA+ spec format. Inspection of. Regarding code hints and code completion, it should be implemented through the **computeContextInformation** method of the **IContentAssistProcessor** interface. I found that there are related functions in the TLACompletionProcessor class under the toolbox, but I entered the print hint **（System.out.print("======================")**） and found that the code did not reach this part, so I want to ask this How should the block function be realized?


![image](https://user-images.githubusercontent.com/33443724/140239544-6cfadb58-a940-48b7-b079-2d40fdcb2d40.png)

![image](https://user-images.githubusercontent.com/33443724/140239596-f5d12a1a-d8bc-4b06-8aed-65ee42a9bc6a.png)

**Comment by lemmy** [comment]
In the Toolbox, `Ctlr+Space` triggers the completions.

Formatting should best include the AST to guarantee semantic-preserving syntax transformations.

**Comment by niuzhi** [comment]
@lemmy ,Ctlr+Space  NOT triggers the completions. Where do I need to configure it?

**Comment by lemmy** [comment]
@niuzhi The spec has to be parsed (green indicator at the bottom) and then it should work fine.

https://user-images.githubusercontent.com/88777/140597734-b1701a48-1c52-4a4d-8d62-476d8ed0db46.mov

**Comment by niuzhi** [comment]
@lemmy 
hi，
1. I modified some ToolBox functions, but when I used the Exclipse Product export wizard to export the product, the following error was reported. How should I fix it? thank you very much.
![image](https://user-images.githubusercontent.com/33443724/141287528-3009a0f8-b50f-41aa-ac13-52202d6dae6e.png)

Error：
![image](https://user-images.githubusercontent.com/33443724/141287655-241dc299-79cc-4dca-b840-68b834a9a532.png)



2. How to publish ToolBox product into executable file for other personnel to use, look forward to your reply.

**Comment by niuzhi** [comment]
@lemmy  I tried to use maven to build and found that the repository http://archive.eclipse.org/egit/updates-5.9/content.xml could not be read. How can I solve it, thank you very much?

![image](https://user-images.githubusercontent.com/33443724/141306724-de00be23-5273-4707-9c30-d752e5e50bda.png)

**Comment by lemmy** [comment]
You cannot use the export wizard but have to use maven.  

The error is likely an intermittent problem because our Github action works fine.  Try finding a local Eclipse mirror and set it up via maven settinsg.xml file (see example below).  Relevant documentation is on the web.

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>
  </localRepository>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline/>
  <pluginGroups/>
  <servers/>
  <mirrors>
   <mirror>
      <id>osuosl-ajdt</id>
      <mirrorOf>eclipse-ajdt</mirrorOf>
      <url>ftp://ftp.osuosl.org/pub/eclipse/tools/ajdt/48/dev/update/ajdt-e48-2.2.4.201805281636/</url>
      <layout>p2</layout>
      <mirrorOfLayouts>p2</mirrorOfLayouts>
   </mirror>
<!--
   <mirror>
      <id>osuosl-orbit</id>
      <mirrorOf>eclipse-orbit</mirrorOf>
      <url>ftp://ftp.osuosl.org/pub/eclipse/tools/orbit/downloads/drops/R20180829150157/repository</url>
      <layout>p2</layout>
      <mirrorOfLayouts>p2</mirrorOfLayouts>
   </mirror>
-->
   <mirror>
      <id>osuosl-swtbot</id>
      <mirrorOf>eclipse-swtbot</mirrorOf>
      <url>ftp://ftp.osuosl.org/pub/eclipse/technology/swtbot/releases/2.7.0</url>
      <layout>p2</layout>
      <mirrorOfLayouts>p2</mirrorOfLayouts>
   </mirror>
   <mirror>
      <id>osuosl-eclipse</id>
      <mirrorOf>eclipse</mirrorOf>
      <url>ftp://ftp.osuosl.org/pub/eclipse/eclipse/updates/4.9/R-4.9-201809060745</url>
      <layout>p2</layout>
      <mirrorOfLayouts>p2</mirrorOfLayouts>
   </mirror>
  </mirrors>

  <proxies/>
  <profiles/>
  <activeProfiles/>
</settings>
```

**Comment by niuzhi** [comment]
@lemmy  thanks，But I reported the following error when using mvn install? I don't know how to solve it, please help me. In addition, can you write a detailed article published by toolbox, which will help many interested developers to join in, thank you very much, and look forward to your reply

![image](https://user-images.githubusercontent.com/33443724/141453842-e09248b6-b849-4ae3-a1a7-1f6b521ef7a8.png)
![image](https://user-images.githubusercontent.com/33443724/141453904-a3346316-50bb-46a1-bbe8-bd779dd01de8.png)

**Comment by lemmy** [comment]
You have to run maven from the top-level/root directory and not from any of the module (sub) directories.

Unfortunately, I don't have time to write developer documentation. :-(

**Comment by niuzhi** [comment]
@lemmy thanks，
When I compile the project, I always encounter the following jar package cannot be downloaded. I have tried many times but never succeeded. I would like to ask you how to import this jar package into the project offline to avoid this The error occurred? Looking forward to your reply
org.lamport.openjdk.linux.x86_64_14.0.1.7.jar


![image](https://user-images.githubusercontent.com/33443724/141664944-5f9c5f5f-00e1-4dc4-8ce1-6c889b303a5b.png)

**Comment by lemmy** [comment]
You can download the zip file from https://github.com/lemmy/eclipse-jdk-bundles/ and host its content on your own webserver.  You can change the URL from `lemmster.de` to yours in `toolbox/org.lamport.tla.toolbox.product.product/TLAToolbox.target`.

Note that `http://lemmster.de/eclipse-jdk-bundles` is actually hosted by Github.

**Comment by niuzhi** [comment]
@lemmy Thank you very much. At present, my compile has the following problems. The command I use is “mvn clean verify -T 6”, please help me. Thank you very much. How should I configure this?

![image](https://user-images.githubusercontent.com/33443724/141683635-c8cb2549-6810-477b-96ca-1c8b1aa62e77.png)

![image](https://user-images.githubusercontent.com/33443724/141683640-c827c2cb-85ca-4d1f-9fef-30e930f74135.png)

**Comment by lemmy** [comment]
Please try without the `T` parameter.

**Comment by niuzhi** [comment]
@lemmy This error still exists。

![image](https://user-images.githubusercontent.com/33443724/141705539-b0b96613-0b29-4845-9745-8626dd7ef66c.png)


![image](https://user-images.githubusercontent.com/33443724/141705553-edd4262b-bbda-4ca9-86bd-8c47fbcc162c.png)

**Comment by niuzhi** [comment]
@lemmy hello lemmy,
The following error is reported when compile org.lamport.tla.toolbox.product.product. Please tell me how to solve these files. There are these files in my local repository directory. How can I formulate the use of my local package when compiling org.lamport.tla.toolbox.product.product, thank you!

![image](https://user-images.githubusercontent.com/33443724/141783815-2e77ff6b-3766-4350-bd1c-2677461c3c7f.png)


![image](https://user-images.githubusercontent.com/33443724/141784094-197abf54-8a54-455d-ac0a-aea73bfb3d94.png)

**Comment by lemmy** [comment]
Please check the log file that is mentioned in the screenshot: `D:\...\git\tlaplus\workspace\metadata\.log`.

**Comment by niuzhi** [comment]
@lemmy  log file:
![image](https://user-images.githubusercontent.com/33443724/141874588-5834334e-b188-4f40-be07-f7978adc87fe.png)
