### ISSUE TITLE
Feature request: refinement checking for INSTANCEs with arguments

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#687]
Sometimes I have the following problem:
 - I have a spec for some abstract state machine `A`.
 - I have an implementation where there are many instances of `A`. Correctness for the implementation means that each instance behaves like the spec for `A` says it should.

A good example from the literature is Multi-Paxos, where there is a shared log and each slot in the log behaves like a consensus system:

Consensus.tla
```TLA
---- MODULE Consensus ----

CONSTANT Values
VARIABLE chosen_values

Init == chosen_values = {}
Next == chosen_values = {} /\ \E v \in Values: chosen_values' = {v}
Spec == Init /\ [][Next]_<<chosen_values>>

====
```

ReplicatedStateMachine.tla
```TLA
---- MODULE ReplicatedStateMachine ----

CONSTANTS Commands, Slots
VARIABLES log

Init == log = [s \in Slots |-> {}]
Next == \E s \in Slots: log[s] = {} /\ \E v \in Commands: log' = [log EXCEPT ![s] = {v}]
Spec == Init /\ [][Next]_<<log>>

ConsensusOnSlot(s) == INSTANCE Consensus WITH Values <- Commands, chosen_values <- log[s]
Correct == \A s \in Slots: ConsensusOnSlot(s)!Spec

====
```

ReplicatedStateMachine.cfg
```text
SPECIFICATION Spec
CONSTANT Commands = {Read, Write}
CONSTANT Slots = {Slot1, Slot2}
PROPERTY Correct
CHECK_DEADLOCK FALSE
```

Unfortunately, TLC cannot check `Correct` for this system, reporting instead
 > Error: Temporal formulas containing actions must be of forms <>[]A or []<>A.

However, I see no fundamental limitation here. After a puff of inlining, `Correct` is equivalent to a form that certainly looks checkable:
```TLA
/\ ConsensusOnSlot(Slot1)!Init /\ [][ConsensusOnSlot(Slot1)!Next]_<<log[Slot1]>>
/\ ConsensusOnSlot(Slot2)!Init /\ [][ConsensusOnSlot(Slot2)!Next]_<<log[Slot2]>>
```

----

There seem to be two limitations:
 1. TLC will not check properties of the form `\A x \in S: ...`, even when S is a finite set. I imagine such properties could be desugared into a conjunction so they can be handled normally.
 2. TLC will not check properties of the form `Instance(args...)!Spec`. I suspect this is simply an oversight.

**Comment by lemmy** [comment]
Potentially relevant: https://github.com/tlaplus/tlaplus/pull/441

**Comment by JoshuaRowePhantom** [comment]
> Potentially relevant: #441

#441 does not fix this issue.

**Comment by JoshuaRowePhantom** [comment]
The following demonstrates a workaround enabled by #441:

```
    \* Have to comment this out until this is resolved:
    \* https://github.com/tlaplus/tlaplus/issues/687
    \*  /\  \A thread \in ListeningThreads :
    \*    /\  AbstractListener(thread)!Spec
    /\  [][
            \A thread \in ListeningThreads :
                \/  AbstractListener(thread)!Next
                \/  AbstractListener(thread)!vars = AbstractListener(thread)!vars'
        ]_vars
```

**Comment by ahelwer** [comment]
Possibly related to #720

**Comment by craft095** [comment]
Another example I came across involves a bi-directional communication channel, which consists of two queues operating in opposite directions. Both queues must behave like FIFO. Absence of parametric instantiation forced me to use CHOOSE, preventing the use of symmetry optimization.

Abstract FIFO specification:

```tla
---- MODULE FIFO ----
EXTENDS Sequences

CONSTANT Messages
VARIABLE queue
Init == queue = <<>>
Put(message) == queue' = Append(queue, message)
Get ==
    /\ queue /= <<>>
    /\ queue' = Tail(queue)
Next ==
    \/ \E message \in Messages: Put(message)
    \/ Get
Spec == Init /\ [][Next]_queue
====
```

Channel specification:

```tla
---- MODULE Channel ----

EXTENDS Naturals, Sequences
CONSTANT Endpoints, Messages, MaxSize

VARIABLE channel

Init ==  channel \in [Endpoints -> {<<>>}]

Write(endpoint, message) ==
    /\ Len(channel[endpoint]) /= MaxSize
    /\ channel' = [channel EXCEPT ![endpoint] = Append(@, message)]

Read(endpoint) ==
    /\ channel[endpoint] /= <<>>
    /\ channel' = [channel EXCEPT ![endpoint] = Tail(@)]

Next == \E endpoint \in Endpoints:
    \/ Read(endpoint)
    \/ \E message \in Messages:
        Write(endpoint, message)

Spec == Init /\ [][Next]_channel

RefinedQueue(endpoint) == INSTANCE FIFO WITH
    queue <- channel[endpoint]
\* This doesn't work because of parametric instantiation
Refinement == \A endpoint \in Endpoints : RefinedQueue(endpoint)!Spec
====
```

CFG file

```
SPECIFICATION Spec
CONSTANT
    Endpoints = { E0, E1 }
    Messages = { M0, M1}
    MaxSize = 2
PROPERTY Refinement
```

**Comment by lemmy** [comment]
@craft095 PR #1014 also handles your spec. :-)

**Comment by lemmy** [comment]
Done: https://github.com/tlaplus/tlaplus/pull/1014
