### ISSUE TITLE
Enhancement: Relax TLC comparability rules for functions

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#697]
The comparability rules for functions are unnecessarily strict. For an inconclusive and rather one-sided discussion see [1], but I think this belongs here. There is not much to add except for another (small) case for relaxing the comparability rules. The following excerpt from "Specifying Systems" suggests a solution to the typing problem that doesn't work with the comparability rules of TLC:
> If the system can send a message that is either a string or a number, represent the message as a record with a _type_ and _value_ field - for example,
> `[type |-> "String", value |-> "a"]` or `[type |-> "Nat", value |-> 1]`
> We know that these two values are different because they have different _type_ fields.

[1] https://groups.google.com/g/tlaplus/c/wVhZ0G5xyKg

**Comment by ahelwer** [comment]
@zwergziege if you are interested in seeing this through I think it would be helpful for you to join the monthly TLA+ community meeting to talk about why you want this and convince people it is worthwhile: https://groups.google.com/g/tlaplus/c/CpAEnrf-DHQ/m/YrORpIfSBwAJ

Unfortunately if you don't have time to see this through I think we can close this issue.

**Comment by zwergziege** [comment]
Thanks for the invite! I still think that relaxing comparability rules has some merit. Unfortunately, my current use of TLA is effectively zero which does not warrant spending much time on it. Maybe I'll come back to this at a later point in time.
