### ISSUE TITLE
Prepare 1.7.2 TLC bugfix release

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#701]
No, it is not a hard deadline. The hard deadline may be late January/early February.
If 1.8.0 is not released by this time, would it be an acceptable solution to cherry-pick issues for critical fixes (#439, #362 - see below, why they are critical) to create 1.7.2?

Context:

Critical bugs are those which have following properties:
1. It is possible that TLC reports no violation, while there is violation
2. It is hard to propose recommendations/guidelines to work around the issue

I.e. critical bugs may introduce errors, which are left undetected.

I thought there was only #439, but after some tests I realized that #362 is also critical.

_Originally posted by @craft095 in https://github.com/tlaplus/tlaplus/issues/439#issuecomment-993864837_

**Comment by lemmy** [comment]
@craft095 Can you check if https://github.com/tlaplus/tlaplus/issues/570?

**Comment by lemmy** [comment]
@craft095  For certification, do you need a binary release or would a source release (a git tag) be enough?

**Comment by craft095** [comment]
@lemmy Binary release is more preferable (if possible)

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/c40c0351ebcfd3c989f35ed94a59887879747214 should also be critical (unless distributed TLC and simulation mode are not relevant).

**Comment by craft095** [comment]
@lemmy That's right - distributed TLC and simulation mode are out of scope at the moment.

**Comment by lemmy** [comment]
@craft095 Backporting all commits related to #439 would be too much work.  I propose to remove `FcnRcdValue#indexTbl` in the backport to branch v1.7.2:  https://github.com/lemmy/tlaplus/tree/v1.7.2

**Comment by craft095** [comment]
@lemmy That is good, thank you!

**Comment by lemmy** [comment]
Release 1.7.2 contains the two requested changes: https://github.com/tlaplus/tlaplus/releases/tag/v1.7.2

**Comment by munyari** [comment]
Hi @lemmy, is there a way to include the OS specific packages with this release, like you did for v1.8.0 and v1.7.1? I'm currently trying to update the homebrew package on macos here https://github.com/Homebrew/homebrew-cask/pull/120117

**Comment by lemmy** [comment]
@munyari Thanks for maintaining the homebrew package.  In this case, it is not worth it for the vast, vast majority of users to update to 1.7.2.  Users can either stay on 1.7.1 or go to 1.8.0.

**Comment by munyari** [comment]
👍 I appreciate the confirmation that 1.7.1 is the right version to use.
