### ISSUE TITLE
No clear difference between stats=basic and stats=full when generating action graphs

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus/tlaplus#704]
Although the position of actions may change, there is no difference in information.

**Comment by jonesmartins** [comment]
Ok, there is a slight difference. I only saw empty square brackets. Now I understand they appear above clusters of actions. Anyway, is there a way to improve the readability of both graphs?

**Comment by lemmy** [comment]
The graph will be identical regardless of `stats=basic` and `stats=full` if the subactions of the next-state relation have no parameters.  For example, the action graph for https://github.com/tlaplus/Examples/blob/master/specifications/DieHard/DieHard.tla is the same with `stats=basic` and `stats=full`.  However, let's change the spec to:

```diff
diff --git a/specifications/DieHard/DieHard.tla b/specifications/DieHard/DieHard.tla
index 2359139..6d1a932 100644
--- a/specifications/DieHard/DieHard.tla
+++ b/specifications/DieHard/DieHard.tla
@@ -62,16 +62,16 @@ Init == /\ big = 0
 (* So, the first two possibilities yield the following four possible       *)
 (* actions.                                                                *)
 (***************************************************************************)
-FillSmallJug  == /\ small' = 3
+FillSmallJug(i)  == /\ small' = 3
                  /\ big' = big

-FillBigJug    == /\ big' = 5
+FillBigJug(i)    == /\ big' = 5
                  /\ small' = small

-EmptySmallJug == /\ small' = 0
+EmptySmallJug(i) == /\ small' = 0
                  /\ big' = big

-EmptyBigJug   == /\ big' = 0
+EmptyBigJug(i)   == /\ big' = 0
                  /\ small' = small

 (***************************************************************************)
@@ -91,10 +91,10 @@ Min(m,n) == IF m < n THEN m ELSE n
 (* Now we define the last two pouring actions.  From the observation       *)
 (* above, these definitions should be clear.                               *)
 (***************************************************************************)
-SmallToBig == /\ big'   = Min(big + small, 5)
+SmallToBig(i) == /\ big'   = Min(big + small, 5)
               /\ small' = small - (big' - big)

-BigToSmall == /\ small' = Min(big + small, 3)
+BigToSmall(i) == /\ small' = Min(big + small, 3)
               /\ big'   = big - (small' - small)

 (***************************************************************************)
@@ -102,12 +102,13 @@ BigToSmall == /\ small' = Min(big + small, 3)
 (* step is a step of one of the six actions defined above.  Hence, Next is *)
 (* the disjunction of those actions.                                       *)
 (***************************************************************************)
-Next ==  \/ FillSmallJug
-         \/ FillBigJug
-         \/ EmptySmallJug
-         \/ EmptyBigJug
-         \/ SmallToBig
-         \/ BigToSmall
+Next == \E i \in 1..2:
+         \/ FillSmallJug(i)
+         \/ FillBigJug(i)
+         \/ EmptySmallJug(i)
+         \/ EmptyBigJug(i)
+         \/ SmallToBig(i)
+         \/ BigToSmall(i) 

 (***************************************************************************)
 (* We define the formula Spec to be the complete specification, asserting  *)
```

With `stats=full`, the action graph clusters the actions by the `i` parameter:

![DieHard_actions](https://user-images.githubusercontent.com/88777/147189678-3609b788-6bc5-47e0-aec4-35e28a7260c8.png)

**Comment by jonesmartins** [comment]
Indeed. I tested the `stats=basic` and `stats=full` on `TwoPhase.tla` with similar results. I understand that `[i -> 1, i -> 1]` means the value of `i` is 1, but why `i -> 1` twice? 

Also, what do you think about removing unseen action transitions from the action graph to improve readability?

**Comment by lemmy** [comment]
The `i -> 1` appears twice because `i` appears in two contexts (1) in an existential quantification in `Next` and 2) as a parameter of subactions).  Unless you look at it from the perspective of structural equality, the two are not the same. 

I deliberately added unseen actions to the graph.  It should be the *seen* actions if we hide anything; otherwise, it is too easy to miss unseen actions.  However, the thickness of (seen) actions indicates coverage of that action.

**Comment by jonesmartins** [comment]
>  Unless you look at it from the perspective of structural equality, the two are not the same.

I agree.

> It should be the seen actions if we hide anything; otherwise, it is too easy to miss unseen actions.

I see what you mean. 

After reading about generating TLA+ specs (and traces) in HTML, I wonder: it might be useful to analyze graphs online as well, right? Do you think that generating graphs in JSON format to be read online would make some useful tool in this regard?

> However, the thickness of (seen) actions indicates coverage of that action.

Maybe that explains why I saw arrows without a body in a few tests...?
The thickness of seen actions becomes clearer when reading `Spec_action.dot` files -- although it'd be hard to discern between `penwidth=0.58`, `penwidth=0.51` and `penwidth=0.44`.

**Comment by lemmy** [comment]
Given the number of graphical (web) interfaces for GraphViz (https://graphviz.org/resources/#graphical-interfaces) and dot's json output (https://graphviz.org/docs/outputs/json/), I don't think it is worth adding a json export to TLC.


Yes, thickness is hard to discern for small values and useless for large values (thick arrows cover thin ones).  Better ideas?

**Comment by jonesmartins** [comment]
> I don't think it is worth adding a json export to TLC.

Thanks. I forgot `dot` could export to JSON.

>  Better ideas?

Not for static files. Interactive graphs online (or on some desktop application) might be helpful, though? For example, force-directed graphs such as [this](https://observablehq.com/@d3/force-directed-graph), with dragging and zooming-in capabilities plus hovering over state (or action) transitions for more info? 

[Another example](https://observablehq.com/@xianwu/clickable-force-directed-graph-network-graph).
