### ISSUE TITLE
"TLC found an error in the configuration file at line... It was expecting = or <-, but did not find it."

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus/tlaplus#705]
Is this a bug? Am I making a mistake? Don't configuration files accept sequences as constants?

Complete exception message:
```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a tlc2.tool.ConfigFileException:

TLC found an error in the configuration file at line 5
It was expecting = or <-, but did not find it.
```

Specification file: HanoiSeq.tla (available [here](https://github.com/tlaplus/Examples/blob/master/specifications/tower_of_hanoi/HanoiSeq.tla) at tlaplus/examples)

Configuration file:

```tla
INIT Init
NEXT Next

CONSTANTS 
    A = <<1,2,3>>
    B = <<>>
    C = <<>>

INVARIANTS TypeOK NoNewElements TotalConstant NotSolved
```
Line 5 would be `A = <<1, 2, 3>>`.

**Comment by lemmy** [comment]
The config file parser supports only basic TLA+ expressions; sequences are not part of it.  You will have to define the sequences in a file such as `MC.tla` that extends `HanoiSeq` the way the Toolbox does it: https://github.com/tlaplus/Examples/blob/master/specifications/tower_of_hanoi/Hanoi.toolbox/Model_1/MC.tla and https://github.com/tlaplus/Examples/blob/master/specifications/tower_of_hanoi/Hanoi.toolbox/Model_1/MC.cfg

**Comment by jonesmartins** [comment]
Out of curiosity, what is the reason the configuration file parser doesn't support sequences? I understand sequences are translated as functions with domain `1..length_of_sequence`, and I assume the parser doesn't accept functions either. Is that it? 

Also, I couldn't find anything about the parser not allowing sequences (and other things) elsewhere. What I did find was about BNF Grammars at 11.1.4 and the config file parser at 14.7.1 of Specifying Systems. Would you have a link for future reference (i.e., anyone that may find this "issue" in the future)?

**Comment by lemmy** [comment]
There is no BNF for the config file format, just the source: https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/tool/impl/ModelConfig.java
