### ISSUE TITLE
Suggestion: Add dump with more information

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus/tlaplus#706]
My motivation with this suggestion is to create an “agnostic” format to generate graphs in different platforms. 

Currently, the `.dump` file only includes all generated states. I don't know how a change to `dump` files would affect other TLA⁺ tools, so I suggest a new format by adding edges and actions to this file. I'm biased toward JSON because it's widely used.

An example of the json_dump file would be:

```js
nodes: {
 0: "/\ a = 1 /\ b = 1",
 1: "/\ a = 2 /\ b = 1",
 2: "/\ a = 1 /\ b = 2",
 3: "/\ a = 2 /\ b = 2"
},
edges: {
  "IncreaseOne": [ (0, 1), (0, 2) ],
  "IncreaseBoth": [ (0, 3) ]
}
```

**Comment by lemmy** [comment]
Duplicates of:
https://github.com/tlaplus/tlaplus/issues/640
https://github.com/tlaplus/tlaplus/issues/639
