### ISSUE TITLE
TLC runtime CMD

### ISSUE THREAD

**Issue by niuzhi** [tlaplus/tlaplus#709]
Hello, we are currently integrating TLC into the CI environment, by running TLC from the command line, we are implementing model validation for the design layer. Please, is there any good tool for running TLC in CMD, or does the community have any good suggestions and guidance to help me accomplish this feature. thanks

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/501#issuecomment-686560353
