### ISSUE TITLE
(beginner) Trying to write a new module override

### ISSUE THREAD

**Issue by jackmalkovick** [tlaplus/tlaplus#713]
Hello. This is a beginner question, the module override using Java seems a very cool stuff with the annotations. Unfortunately, after a long struggle, I'm not able to make it work, and I don't know how to debug it...

Everything is very simple. I have packed everything in a new JAR with a simple structure:

```
mymodule
|_ MyOperators.class
|_ MyTLCOverrides.class
MyOperators.tla
```

The classes are very simple

```
package mymodule;
public class MyOperators {
	@TLAPlusOperator(identifier = "TestOp", module = "MyOperators", minLevel = 1, warn = false)
	public static Value TestOp(StringValue input) {
		return new StringValue("123");
	}
}
```
and

```
package mymodule;
public class MyTLCOverrides implements ITLCOverrides {
	public Class[] get() {
		return new Class[] { MyOperators.class };
	}
}
```
The TLA file is equally simple

```
------------------------------ MODULE MyOperators ------------------------------

TestOp(input) ==
	CHOOSE val \in STRING : TRUE
  
================================================================================
```

The resulting jar is added in TLA+ Toolbox / File / Preferences / TLA+ Preferences, along with the community one that is visible and usable.

Also, I've updated `start.sh` adding a new property to make `MyTLCOverrides` visible

`-Dtlc2.overrides.TLCOverrides=mymodule.MyTLCOverrides`

If I try to use the operator, like `TestOp("abc")` I get

```
The exception was a java.lang.RuntimeException
: Attempted to compute the value of an expression of
form CHOOSE x \in S: P, but S was not enumerable.
```
I don't think override works in this case :( Please, if you are able give me o hint... Thank you

**Comment by lemmy** [comment]
@jackmalkovick What is the content of `start.sh` because a file called `start.sh` is not part of the Toolbox distribution.

**Comment by jackmalkovick** [comment]
Hmmm strage, I found it there. It works, because if I `ps` the java process after tool box starts, the argument seems to be appended where it should.

`~/toolbox-1.8-night/toolbox --launcher.appendVmargs -vmargs -Dtlc2.overrides.TLCOverrides=mymodule.MyTLCOverrides`

**Comment by lemmy** [comment]
Where did you get the Toolbox from?

**Comment by lemmy** [comment]
At any rate, the property `-Dtlc2.overrides.TLCOverrides=mymodule.MyTLCOverrides` has to be a property of the TLC process, not of the Toolbox process -- enter the property as "JVM arguments" on the "TLC Options" page of a Toolbox model.

**Comment by jackmalkovick** [comment]
Wow! Thank you so much. That was sooo simple! Worked! Thank you!

**Comment by jackmalkovick** [comment]
Regarding the module need, I wanted to do custom file reading and processing for reading some non json inputs.

**Comment by lemmy** [comment]
The CommunityModules have a generic serialization "framework":

https://github.com/tlaplus/CommunityModules/blob/b961f70ef7725b9e30a5457cffe16f90015c0e31/modules/IOUtils.tla#L13-L30

**Comment by jackmalkovick** [comment]
> The CommunityModules have a generic serialization "framework":
> 
> https://github.com/tlaplus/CommunityModules/blob/b961f70ef7725b9e30a5457cffe16f90015c0e31/modules/IOUtils.tla#L13-L30

I'll take a look at that too also. Mostly I wanted to parse in java the complicated lines and get some simple token values available in the  TLA spec.

**Comment by lemmy** [comment]
https://github.com/lemmy/BlockingQueue/blob/f4923167f0402fcda894266f4caffa3ff0fc995d/BlockingQueuePoisonApple_stats.tla#L114-L135 could be relevant too.

**Comment by jackmalkovick** [comment]
> https://github.com/lemmy/BlockingQueue/blob/f4923167f0402fcda894266f4caffa3ff0fc995d/BlockingQueuePoisonApple_stats.tla#L114-L135 could be relevant too.

Indeed! Thank you!
