### ISSUE TITLE
Library modules in jar files are not passed to TLAPM

### ISSUE THREAD

**Issue by zwergziege** [tlaplus/tlaplus#714]
Running TLAPM from the Toolbox on specs that rely on library files in jar form results in a crash with the following error message: 
`Unknown module <name of some lib module>`

I'm aware this could be considered a bug of TLAPM instead, in which case I will reopen the issue there.

Workaround: 
1) Extract the modules from the jar.
2) Add the folder to the lib paths of the toolbox.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlapm/issues/3

https://github.com/lemmy/BlockingQueue/blob/f4923167f0402fcda894266f4caffa3ff0fc995d/.github/workflows/main.yml#L18-L29
