### ISSUE TITLE
TLA+ custom operator problem

### ISSUE THREAD

**Issue by niuzhi** [tlaplus/tlaplus#717]
@lemmy  Hello, I am using TLA+ to implement trace verification, and found the following problems, what is the reason?

background：
Ideally, the trace log collection is as follows`（<<[myId |-> 3, sid |-> 2], [myId |-> 3, sid |-> 1], [myId |-> 2, sid |-> 1]>>)`, but there is a problem with the interface I implemented, please help to solve it, thank you very much.

1.my trace log as follows：
```
myId:3,sid:2
myId:3,sid:1
myId:2,sid:1
```

2.ExternalSeqRecordParser.tla
```tla
---- MODULE ExternalSeqRecordParser ----

EXTENDS Integers, Sequences, TLC

\* parses the log to a TLA+ sequence of TLA+ records
ExSeqRcdParser(path) ==  CHOOSE r \in Seq([myId:Int,sid:Int]):TRUE

========================================
```
3.ExternalSeqRecordParser.java

```java
package tlc2.overrides;
import tlc2.value.impl.*;
import util.UniqueString;
import java.io.*;
import java.util.*;


public class ExternalSeqRecordParser {
	// @TLAPlusOperator(identifier = "ExSeqRcdParser", module =
	// "ExternalSeqRecordParser")

	public static Value ExSeqRcdParser(final StringValue absolutePath) throws IOException {
		// read the log file at [absolutePath]
		BufferedReader br = new BufferedReader(new FileReader(absolutePath.val.toString()));
		// initialize array for all parsed records
		List<RecordValue> rcdSeq = new ArrayList<>();
		try {
			String line = br.readLine();
			while (line != null) {
				// initialize arrays for field values [fields] and [values]
				List<UniqueString> fields = new ArrayList<>();
				List<Value> values = new ArrayList<>();
				// split string on seperator into array of filed and value
				String[] lnarr = line.split(",");
				// parse each entry of [lnarr] as a field-value pair
				parsePair(lnarr[0].split(":"), fields, values);
				parsePair(lnarr[1].split(":"), fields, values);
				// add record to the sequence
				rcdSeq.add(new RecordValue(fields.toArray(new UniqueString[0]), values.toArray(new Value[0]), true));
				line = br.readLine();
			}
		} finally {
			br.close();
		}
		// return the aggregated sequence of records
		return new TupleValue(rcdSeq.toArray(new Value[0]));
	}

	private static void parsePair(String[] pair, List<UniqueString> fields, List<Value> values) {
		fields.add(UniqueString.uniqueStringOf(pair[0]));
		if (pair[1].equals("false") || pair[1].equals("true")) {
			values.add(new BoolValue(Boolean.parseBoolean(pair[1])));
		} else {
			values.add(IntValue.gen(Integer.parseInt(pair[1])));
		}
	}
	/*
	 * <<[myId |-> 3, sid |-> 2], [myId |-> 3, sid |-> 1], [myId |-> 2, sid |-> 1]>>
	 */
}
```

4.TLA+ running produces the following error，why？
![image](https://user-images.githubusercontent.com/33443724/154627179-6577ae17-29de-4ff5-a4b6-8de0d5702cf0.png)

**Comment by lemmy** [comment]
@niuzhi Are you sure that the .class file is on TLC's classpath because it seems TLC doesn't load your module override?  That said, you don't have to build a module override but can use the [CSV module from the CommunityModules](https://github.com/tlaplus/CommunityModules/blob/07ef2bc96e2af839318bbd96ae3ef7b80985f5b4/modules/CSV.tla#L16-L22), or build a custom deserializer for the [generic IOUtils operator](https://github.com/tlaplus/CommunityModules/issues/53).  My [BlockingQueue tutorial](https://github.com/lemmy/BlockingQueue/blob/main/BlockingQueueSplitTrace.tla) shows how you verify an implementation trace that was serialized from a .csv file.

**Comment by niuzhi** [comment]
@lemmy thank you very much. your BlockingQueue very good，Can you give me the impl/out.csv csv format of this so that I can transform my trace。[https://github.com/lemmy/BlockingQueue/blob/main/BlockingQueueSplitTrace.tla]

**Comment by lemmy** [comment]
I added a note to the BlockingQueueSplitTrace.tla spec:

https://github.com/lemmy/BlockingQueue/blob/911773297f2f805d94ade47b2949e3ccff38bf66/BlockingQueueSplitTrace.tla#L13-L33
