### ISSUE TITLE
Parameterized operators cannot be used to define a property

### ISSUE THREAD

**Issue by craft095** [tlaplus/tlaplus#720]
Operators with parameters cannot be used to define properties:

This spec works good:

```
---- MODULE M0 ----
VARIABLE x
ap_0 == [][x' = TRUE]_x
Spec == x=TRUE /\ [][x'=~x]_x
Prop == ap_0
====
```

This spec is rejected with `Temporal formulas containing actions must be of forms <>[]A or []<>A`
```
---- MODULE M0 ----
VARIABLE x
ap_0(u) == [][TRUE]_x
Spec == x=TRUE /\ [][x'=~x]_x
Prop == ap_0(TRUE)
====
```

This one crashes with StackOverflow:
```
---- MODULE M0 ----
VARIABLE x
RECURSIVE ap_0(_)
ap_0(u) == IF u THEN [][TRUE]_x ELSE ap_0(~u)
Spec == x=TRUE /\ [][x'=~x]_x
Prop == ap_0(TRUE)
====
```

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/pull/1014 addresses your non-recursive example.  @craft095, do you strongly need support for recursive?

**Comment by craft095** [comment]
Thanks, @lemmy! 
>do you strongly need support for recursive?
No, I don't have any use cases for recursive operators in this context.

**Comment by lemmy** [comment]
Done: https://github.com/tlaplus/tlaplus/pull/1014
