### ISSUE TITLE
`-tool` mode ill-formed on some exceptions

### ISSUE THREAD

**Issue by AdrienChampion** [tlaplus/tlaplus#732]
## Description

When printing certain exceptions, TLC introduces a newline `\n` between the exception's description and the `:` preceding the context in which the exception was raised.

*Apparently* this is a feature, not a bug, as some TLC tests such as [this one](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/test/tlc2/tool/EvalExceptionLivenessTest.java#L59-L60) actually expect the output to have this form.

Here is the smallest example I could make that triggers this behavior.

<details>

```tla
\* top.tla
---- MODULE top ----

VARIABLES b
svars == <<b>>

init ==
    b = TRUE
next ==
    b' = ~b
    /\ 7

====
```

```tla
\* top.cfg
INIT init
NEXT next
```

Output:

```text
[...]
The exception was a java.lang.RuntimeException
: In computing next states, TLC expected a boolean expression,
but instead found 7.
[...]
```

</details>

It seems like a very minor problem that was never fixed.

It graduates, I'm pretty sure, to a bug when running in `-tool` mode because it breaks message tags. Here is the relevant part of the `-tool` output:

```text
@!@!@STARTMSG 1000:1 @!@!@
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: @!@!@STARTMSG 2247:0 @!@!@
In computing next states, TLC expected a boolean expression,
but instead found 7.
7
@!@!@ENDMSG 2247 @!@!@
@!@!@ENDMSG 1000 @!@!@
```

This seems like a bug to me, unless users should expect message tags to appear randomly after/inside plain text. Which I assume is not the case.

## Expected Behavior

All message tags should appear as one line in the output, without any spurious characters before or after in that line, so that programs relying on the `-tool` mode can parse the parts of the output that are actually structured.

## Actual Behavior

A minor (in non`-tool` mode) problem in exception printing introduces spurious characters in `-tool` mode right before some message tags, in the same line.

## Steps to Reproduce
1. put `top.tla` and `top.cfg` above in a directory
2. run TLC on `top.tla` in `-tool` mode

## Steps Taken to Fix

Considered changing my parser to account for this problem, but it seems like a TLC problem.

## Possible Fix

Properly printing exceptions.

## Your Environment

```
TLC2 Version 2.17 of 02 February 2022 (rev: 3c7caa5)
Running breadth-first search Model-Checking with fp 68 and seed 0 with 1 worker
on 8 cores with 3641MB heap and 64MB offheap memory
(Mac OS X 12.3.1 aarch64, Homebrew 18.0.1 x86_64, MSBDiskFPSet, DiskStateQueue).
```

**Comment by lemmy** [comment]
@AdrienChampion Thanks for the report.  What does the TLA+ Toolbox show in its error window for spec `top`?

**Comment by AdrienChampion** [comment]
I had no idea what you meant until I remembered there's a TLA+ IDE.

I don't know, I'm on macos and the only instructions I found for running the toolbox do not seem to apply to the current release. Can I run the IDE with some convoluted `java` command?

**Comment by AdrienChampion** [comment]
Probably a separate issue, but the error position is incorrect:

```
Error: In computing next states, TLC expected a boolean expression,
but instead found 7.
7

- triggered at
  module top, 9:5 → 9:11
        |     vvvvvvv
      9 |     b' = ~b
        |
```
