### ISSUE TITLE
Option  `-teSpecOutDir` has no effect if full path to TLA+ file is specified

### ISSUE THREAD

**Issue by craft095** [tlaplus/tlaplus#733]
If TLC is executed this way:

```
java -cp tla2tools.jar tlc2.TLC M.tla -teSpecOutDir <trace-dir>
```
`TTrace` file will be created in `trace-dir`. But if full path to `M.tla` is specified:

```
java -cp tla2tools.jar tlc2.TLC `pwd`/M.tla -teSpecOutDir <trace-dir>
```

`TTrace` file is generated near `M.tla`, ignoring `-teSpecOutDir`

**Comment by lemmy** [comment]
@craft095 I'm afraid I won't have time to look at this anytime soon.  Can you provide a PR?
