### ISSUE TITLE
"Temporal formula is a tautology (its negation is unsatisfiable)." when adding universal quanitifer to SF

### ISSUE THREAD

**Issue by JoshuaRoweMsft** [tlaplus/tlaplus#742]
I haven't been able to completely narrow down the scenario, but occasionally when trying to do write a universal quantifier over a SF conjuct, the error in the title is returned. An (obfuscated) portion of the example spec:

```
Spec = 
    /\ Init
    /\ Next
    /\  \A r \in RT :
        \A l \in LT :
        /\  SF_vars(
                /\  L = l
                /\  Action(r)
            )
```

I will follow up privately with the real spec (proprietary information).

**Comment by lemmy** [comment]
Similar: https://groups.google.com/g/tlaplus/c/gkInc70HJUc

**Comment by lemmy** [comment]
Before git commit https://github.com/tlaplus/tlaplus/commit/9b64867eba5b6301b307ea21b0b878eb4e3e8632, the second stage of liveness checking was a no-op if there was no `OrderOfSolutions`.  With 9b64867eba5b6301b307ea21b0b878eb4e3e8632, TLC started throwing an exception, which was turned into an error message with #302.
