### ISSUE TITLE
ALIAS doesn't have any effect for violations in initial state

### ISSUE THREAD

**Issue by fhackett-ms** [tlaplus/tlaplus#746]
## Description

When using ALIAS to enhance the counter-examples produced by TLC, only the original state variables are shown if the counter-example is just the initial state.

Minimal example spec:
```tlaplus
---- MODULE test ----

VARIABLE i

Init == i = 1

Next == UNCHANGED i

Spec == Init /\ [][Next]_i

Inv == i = 2

Alias == [
    i |-> i,
    foo |-> "bar"
]

====
```

Config:
```
SPECIFICATION Spec
INVARIANTS Inv
ALIAS Alias
```

## Expected Behavior

```
...
Computing initial states...
Invariant Inv is violated by the initial state:
foo = "bar"
...
```

## Actual Behavior

```
...
Computing initial states...
Invariant Inv is violated by the initial state:
i = 1
...
```

## Steps to Reproduce

Run the minimal example with the specified configuration, under otherwise default settings.

## Steps Taken to Fix

It can be worked around to an extent by guessing and adding prints.

## Possible Fix

N/A

## Your Environment
 - TLC version: 2.18 (rev: d5baa32)
 - Operating System: `Linux codespaces-3c4ad9 5.4.0-1086-azure #91~18.04.1-Ubuntu`

**Comment by lemmy** [comment]
I remembered why this isn't supported: an ALIAS is an action-level formula (one involving the prime operator), which cannot be evaluated on a single (initial) state.  Clearly, a state-level formula is a degenerated action-level formula, but I'm not convinced we want to go down that rabbit hole.

**Comment by fhackett-ms** [comment]
I see - that's interesting. I actually had no idea primes were allowed in ALIAS, and had guessed a rather different evaluation semantics.

As a user, I intuitively prefer the ability to handle state-level ALIAS defs in all places where state-level evaluation makes sense, somehow. This, or very clearly explaining in TLC's output why an ALIAS disappeared, is important, otherwise the definition gets silently "eaten" and the behavior looks like a bug.

The compromise of adding a self-loop seems fine to me - it removes the "silent eating" problem, the main thing I really care about here, and it seems like it was reasonable architecturally.

**Comment by lemmy** [comment]
Merged mku-gh746 into master.
