### ISSUE TITLE
Trying to build the ToolBox

### ISSUE THREAD

**Issue by zitro3** [tlaplus/tlaplus#750]
## Description
I am trying to build the ToolBox from source.

## Expected Behavior
Should build the ToolBox.

## Actual Behavior
[INFO] Resolving dependencies of MavenProject: tlatoolbox:org.lamport.tlatools:1.0.0-SNAPSHOT @ C:\Users\20273\Desktop\VERSA\tlaplus\tlatools\org.lamport.tlatools\pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.contribution.weaving.feature.group 2.2.4.202007241909
[ERROR]   Missing requirement: org.eclipse.core.jobs 3.10.100.v20180817-1215 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
[ERROR]   Missing requirement: org.eclipse.core.jobs 3.10.1000.v20200909-1312 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.contribution.weaving.feature.group 2.2.4.202007241909 depends on: org.eclipse.equinox.p2.iu; org.eclipse.core.runtime 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.15.0.v20180817-1401 depends on: osgi.bundle; org.eclipse.core.jobs [3.10.0,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.20.0.v20201027-1526 depends on: osgi.bundle; org.eclipse.core.jobs [3.10.0,4.0.0)
[ERROR]
[ERROR] Failed to resolve target definition C:\Users\20273\Desktop\VERSA\tlaplus\toolbox\org.lamport.tla.toolbox.product.product\TLAToolbox.target: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

C:\Users\20273\Desktop\VERSA\tlaplus>

## Steps to Reproduce
1. mvn verify
2. mvn install -Dmaven.test.skip=true
3.
4.

## Steps Taken to Fix
None. I just followed your instruction.

## Possible Fix
Thus, requesting the forum about the fix.

## Your Environment
 - TLC version: latest source from this repo
 - Toolbox version: latest source from this repo
 - Operating System: Windows 10

I appreciate the help.

Thanks,
Chris

**Comment by Calvin-L** [comment]
Are you using JDK 11? If not, could you upgrade (or downgrade) to JDK 11 and try again?

The error is indeed cryptic, but it suggests that you might be using an incompatible JDK. The toolbox does not compile with recent versions of OpenJDK (17 and 18 and perhaps others). It might not compile with recent versions of Oracle JDK either; I haven't tried.

**Comment by lemmy** [comment]
Please reopen if this remains an issue.
