### ISSUE TITLE
Missing items from the main menu bar

### ISSUE THREAD

**Issue by charpov** [tlaplus/tlaplus#760]
## Description
The Toolbox is only showing `File`, `Window`, and `Help` menus. Nothing on TLC or TLAPS.

<img width="768" alt="Screen Shot 2022-09-13 at 11 34 18 AM" src="https://user-images.githubusercontent.com/7649412/189945854-a700d1cd-edf1-4666-9f7c-1c031a58d466.png">

I tried to clear `.tlaplus`, but that did nothing. Are there other caches/preferences?

## Possible Fix
I can still get to TLC with a right-click somewhere, but no menu.

## Your Environment
I'm running the latest version from GitHub (1.7.1; there is a 1.7.2 release, but no corresponding files to download) on a non-Intel iMac, macOS 12.5, Java 18.  (I have the Toolbox running fine on an older Intel Mac similarly configured, so maybe the M1 chip part is relevant).

**Comment by charpov** [comment]
Upgraded my system to 12.6. After the reboot, the menus were back.

**Comment by lemmy** [comment]
Please reopen if the problem reappears.
