### ISSUE TITLE
Where is the code for the state space traversal algorithm in TLC?

### ISSUE THREAD

**Issue by niuzhi** [tlaplus/tlaplus#761]
When I use TLA+ for verification projects, I always encounter the problem of state space explosion, which causes the machine to crash or take a long time. Therefore, I want to look at the TLC state space traversal algorithm to see if the state traversal algorithm can be optimized.
question:
1. Where is the detailed location of the code for state space traversal in TLC?
2. Is there a good solution to the state space explosion problem in TLC? thanks

**Comment by Calvin-L** [comment]
Hello! 👋 

I've done my best to answer your questions on the mailing list:
https://groups.google.com/g/tlaplus/c/oEQiYh6ySOg/m/R16Mu799CQAJ

If you have specific optimizations in mind, please let us know! In the meantime, I am going to close this issue. However, I'm happy to continue this discussion on the mailing list. :)
