### ISSUE TITLE
JsonSerialize fails on modified Trace

### ISSUE THREAD

**Issue by dariusf** [tlaplus/tlaplus#764]
## Description

I get the following error when trying to generate a JSON trace from an invariant violation. Not using -dumpTrace because of -simulate.

```
Evaluating invariant JsonInv failed.

Attempted to apply the operator overridden by the Java method

public static synchronized tlc2.value.impl.BoolValue tlc2.overrides.Json.serialize(tlc2.value.impl.StringValue,tlc2.value.impl.TupleValue) throws java.io.IOException,

but it produced the following error:

Cannot cast tlc2.value.impl.FcnRcdValue to tlc2.value.impl.TupleValue
```

## Expected Behavior

Both trace.json and trace1.json should be written.

## Actual Behavior

Only trace.json appears.

## Steps to Reproduce

<details>
<summary>Inputs</summary>

```sh
java -cp ~/.vscode/extensions/alygin.vscode-tlaplus-nightly-2022.9.2719/tools/tla2tools.jar -XX:+UseParallelGC tlc2.TLC Counter_json.tla -simulate
```

```tla
---- MODULE Counter ----
EXTENDS Naturals

VARIABLE x
vars == <<x>>

Init == x = 1

Next == x' = x + 1

Spec == 
    /\ Init
    /\ [][Next]_vars

Inv == x < 3
      
====
```

```tla
------------------------------- MODULE Counter_json -------------------------------
EXTENDS Counter, TLC, TLCExt, Json, Sequences

JsonInv ==
    \/ RealInv:: Inv
    \/
      LET Trace1 == [i \in 1 .. Len(Trace) |-> Trace[i]] IN
      /\ JsonSerialize("trace.json", Trace)
      /\ JsonSerialize("trace1.json", Trace1)
      /\ TLCSet("exit", TRUE)

=============================================================================
```

```
SPECIFICATION Spec
INVARIANT JsonInv
```

</details>

The purpose of Trace1 is to apply some arbitrary transformation to Trace before writing it to a file, as some things serialize poorly to JSON, e.g.

```tla
ToJson([a |-> 1] :> 2)
```
becomes
```json
{"[a |-> 1]":2}
```

## Steps Taken to Fix

Strangely this works:

```
/\ PrintT(Serialize(ToJson(Trace1), "trace2.json", [format |-> "TXT", charset |-> "UTF-8", openOptions |-> <<"WRITE", "CREATE", "TRUNCATE_EXISTING">>]))
```

## Your Environment

 - TLC version: 3a75658ac036a85959f3b875d4bd8b4ca895ebf6

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/79b38cac674344be15c237c1e5bea059ceff5bd6 adds support for `dumptrace` in simulation mode.

**Comment by dariusf** [comment]
Awesome, thanks for the fixes!

I've tried both -dumpTrace and POSTCONDITION with -simulate in the new tla2tools.jar and they work great.

I wasn't actually using the community modules here though, just tla2tools.jar from the VSCode extension.

**Comment by lemmy** [comment]
The CommunityModules have been made part of the most recent VSCode nightly build: https://github.com/tlaplus/vscode-tlaplus/commit/06cee8b9d913146cebfd1289a0413e566414c0b8

**Comment by dariusf** [comment]
I see! Is it automatically added when running model checking from the command palette? I've been copying the invocation from the output panel to reproduce these issues, which only has `-cp tla2tools.jar`.

**Comment by lemmy** [comment]
`tla2tools.jar` automatically loads `CommunityModules.jar` if `CommunityModules.jar` is next to `tla2tools.jar`.
