### ISSUE TITLE
Is there an API client for TLA+ Toolkit?

### ISSUE THREAD

**Issue by volkanunsal** [tlaplus/tlaplus#765]
Hi, I'm assessing the feasibility of building a web based interface for TLA+ using a visual programming language. The most important thing it seems is an API client. If it doesn't exist, is it possible that I can use the commandline tool? 

My use case entails the following:

* Create a new module
* Translate PlusCal algorithm
* Run TLC model
* Read model checking results

**Comment by lemmy** [comment]
Related: https://github.com/will62794/tla-web

**Comment by volkanunsal** [comment]
Thanks @lemmy . I will try using the commandline for communication as in [this example](https://github.com/pmer/tla-bin/blob/master/bin/tlc). Is there a reference guide for what commands are available from the `tla2tools.jar` file?

**Comment by volkanunsal** [comment]
Regarding the example you posted above, my goal is to do something slightly different. I intend to use a visual programming language that compiles to PlusCal with the goal of lowering the barrier to entry. (PlusCal still has a learning curve.)

**Comment by lemmy** [comment]
> Thanks @lemmy . I will try using the commandline for communication as in [this example](https://github.com/pmer/tla-bin/blob/master/bin/tlc). Is there a reference guide for what commands are available from the `tla2tools.jar` file?

https://lamport.azurewebsites.net/tla/current-tools.pdf

> Regarding the example you posted above, my goal is to do something slightly different. I intend to use a visual programming language that compiles to PlusCal with the goal of lowering the barrier to entry. (PlusCal still has a learning curve.)

Wouldn't it be easier to translate to TLA+ directly?

**Comment by lemmy** [comment]
Depends on how restricted your visual language is going to be.  PlusCal is more restricted than TLA+.  Since all tools work at the level of TLA+, debugging spec bugs should be more straightforward. By the way, are you going to translate counterexamples back to the visual language?

**Comment by volkanunsal** [comment]
> By the way, are you going to translate counterexamples back to the visual language?

I haven't thought about that actually... That would mean I have to write a parser to PlusCal as wel.... Does the CLI output provide the counterexamples?

**Comment by lemmy** [comment]
By default, a counterexample is shown as a TLA+ trace:

```tla
Checking temporal properties for the complete state space with 1600 total distinct states at (2020-01-18 15:28:06)
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ buffer = <<>>
/\ waitSet = {}

State 2: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2>>
/\ waitSet = {}

State 3: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3>>
/\ waitSet = {}

State 4: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3, p2>>
/\ waitSet = {}

State 5: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3, p2>>
/\ waitSet = {p1}

State 6: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3, p2>>
/\ waitSet = {p1, p4}

State 7: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3, p2>>
/\ waitSet = {p1, p2, p4}

State 8: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3, p2>>
/\ waitSet = {p1, p2, p3, p4}

State 9: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p3, p2>>
/\ waitSet = {p1, p2, p3}

State 10: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2>>
/\ waitSet = {p1, p2}

State 11: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<>>
/\ waitSet = {p1}

State 12: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2>>
/\ waitSet = {p1}

State 13: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>
/\ buffer = <<p2, p3>>
/\ waitSet = {p1}

Back to state 5: <Next line 54, col 9 to line 57, col 45 of module BlockingQueue>

Finished checking temporal properties in 00s at 2020-01-18 15:28:06
12313 states generated, 1600 distinct states found, 0 states left on queue.
```

TLC allows you to reformat the trace to a different format.

**Comment by lemmy** [comment]
Please reopen if necessary
