### ISSUE TITLE
Improve contributor experience

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#778]
- [x] Tag issues with new ["good first issue"](https://github.com/tlaplus/tlaplus/labels/good%20first%20issue) label
- [ ] Separate TLA+ Tools and Toolbox build (ant & maven)
- [x] Documentation how to set up a lightweight TLC development environment and [full-blown Toolbox dev environment](https://github.com/tlaplus/tlaplus/tree/master/general/ide)
- [x] Polish and extend https://github.com/tlaplus/tlaplus/blob/master/README.md
- [x] Convert (?) [contributor guide](https://github.com/tlaplus/tlaplus/blob/master/CONTRIBUTING.md) into ]Github issue template](https://github.com/tlaplus/tlaplus/tree/master/.github/ISSUE_TEMPLATE)
- [ ] Convert [feature wishlist](https://github.com/tlaplus/tlaplus/blob/master/general/docs/contributions.md) into a more accessible format such as issues, projects, ... ?
- [ ] Document [performance test framework](https://github.com/tlaplus/tlaplus/actions/workflows/perf.yml)
- [ ] ...

/cc @konnov @Calvin-L @ZacAttack @thesammiller @muenchnerkindl @xxyzzn

**Comment by thesammiller** [comment]
I've added a PR (https://github.com/tlaplus/tlaplus/pull/791) for how to build TLC on the command line with ant. Not sure if it's too lightweight for "how to setup a lightweight TLC development environment", but happy to generate a longer document if that would be more helpful with additional context. If so, please just let me know where it should go.

Calvin has also provided instructions for setting up in IntelliJ. Can that be added to the `ide` file or should that exist somewhere else?

**Comment by lemmy** [comment]
Closing in favor of individual issues.
