### ISSUE TITLE
Build/create spec from Java with no parsing

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/tlaplus#779]
Hi o/ Is there a way of build the spec from Java only and running it? Without having to create a .tla file.

E.g. build the spec manually only by using Java classes, maybe a minimal example exists already?

**Comment by lemmy** [comment]
No, the code expects java.io.File in many places.  I once considered (search the issues) adding an in-memory fs to TLC to work around this issue.

**Comment by pfeodrippe** [comment]
Ok thanks o/
