### ISSUE TITLE
Nightly TE spec generation causes error in ABCorrectness.tla

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#785]
## Description
Nightly TLC produces the following error when run on https://github.com/tlaplus/Examples/blob/master/specifications/SpecifyingSystems/TLC/ABCorrectness.tla:
```
Semantic processing of module ABCorrectness
Semantic errors:

*** Errors: 5

line 15, col 12 to line 15, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 16, col 12 to line 16, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 17, col 12 to line 17, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 100, col 13 to line 100, col 20 of module TLCExt

Unknown operator: `ToString'.


line 19, col 12 to line 19, col 17 of module _TLCTrace

Unknown operator: `PrintT'.
```
This error also occurs on https://github.com/tlaplus/Examples/blob/master/specifications/SpecifyingSystems/TLC/MCAlternatingBit.tla

## Expected Behavior
I expected TE spec generation not to cause an error.

## Actual Behavior
TE spec generation caused an error.

## Steps to Reproduce
1. Clone https://github.com/tlaplus/Examples
2. Download nightly toolset jar to repo root
3. Download nightly community modules jar to repo root
4. From examples repo root, run `java -cp tla2tools.jar tlc2.TLC specifications/SpecifyingSystems/TLC/ABCorrectness`
5. Observe error

## Steps Taken to Fix
TLC runs without failure when given `-noGenerateSpecTE` parameter.

## Possible Fix
Don't know

## Your Environment
 - TLC version: TLC2 Version 2.18 of Day Month 20?? (rev: ad45483)
 - Operating System: Arch Linux

**Comment by lemmy** [comment]
It's good that the TLA+ examples are used as regression tests again.  Are there plans to automatically trigger TLC runs of the TLA+ examples after the TLC's [CI](https://github.com/tlaplus/tlaplus/actions/workflows/main.yml) finishes?  We used to have this but it has apparently fallen victim to bit rot. 

This one is a regression of https://github.com/tlaplus/tlaplus/commit/ae8917bbcfc591254d6d284d1fd60f561f6f0c1d and happens independently of the CommunityModules.  Further investigation pending...  By the way, there are no "nightly" CommunityModules because CM has rolling releases.

**Comment by lemmy** [comment]
Same issue with other specs:

```tla
tlc MCAlternatingBit
TLC2 Version 2.18 of Day Month 20?? (rev: ae8917b)
Running breadth-first search Model-Checking with fp 44 and seed 3874367671358925759 with 1 worker on 10 cores with 7282MB heap and 64MB offheap memory [pid: 58422] (Mac OS X 13.2 aarch64, Homebrew 11.0.18 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /Users/markus/src/TLA/_specs/examples/specifications/SpecifyingSystems/TLC/MCAlternatingBit.tla
Parsing file /Users/markus/src/TLA/_specs/examples/specifications/SpecifyingSystems/TLC/AlternatingBit.tla
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-14818193817901349786/_TLCTrace.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/_TLCTrace.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-14818193817901349786/Naturals.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/Naturals.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-14818193817901349786/Sequences.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/Sequences.tla)
Parsing file /Users/markus/src/TLA/_specs/examples/specifications/SpecifyingSystems/TLC/ABCorrectness.tla
Parsing file /Users/markus/src/TLA/_specs/examples/specifications/SpecifyingSystems/TLC/TLC.tla
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-14818193817901349786/TLCExt.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/TLCExt.tla)
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module AlternatingBit
Semantic processing of module TLC
Semantic processing of module TLCExt
Semantic errors:

*** Errors: 4

line 15, col 12 to line 15, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 16, col 12 to line 16, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 17, col 12 to line 17, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 100, col 13 to line 100, col 20 of module TLCExt

Unknown operator: `ToString'.



Semantic processing of module _TLCTrace
Semantic errors:

*** Errors: 5

line 15, col 12 to line 15, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 16, col 12 to line 16, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 17, col 12 to line 17, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 100, col 13 to line 100, col 20 of module TLCExt

Unknown operator: `ToString'.


line 19, col 12 to line 19, col 17 of module _TLCTrace

Unknown operator: `PrintT'.



Semantic processing of module ABCorrectness
Semantic errors:

*** Errors: 5

line 15, col 12 to line 15, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 16, col 12 to line 16, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 17, col 12 to line 17, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 100, col 13 to line 100, col 20 of module TLCExt

Unknown operator: `ToString'.


line 19, col 12 to line 19, col 17 of module _TLCTrace

Unknown operator: `PrintT'.



Semantic processing of module MCAlternatingBit
Semantic errors:

*** Errors: 5

line 15, col 12 to line 15, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 16, col 12 to line 16, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 17, col 12 to line 17, col 17 of module TLCExt

Unknown operator: `PrintT'.


line 100, col 13 to line 100, col 20 of module TLCExt

Unknown operator: `ToString'.


line 19, col 12 to line 19, col 17 of module _TLCTrace

Unknown operator: `PrintT'.



Starting... (2023-01-28 14:34:09)
Error: Parsing or semantic analysis failed.
Finished in 00s at (2023-01-28 14:34:09)
```

**Comment by lemmy** [comment]
This is only insofar a regression of commit ae8917b in that the commit introduces a dependency on the TLC module that has been part of TLC for at least the last 10 years.  However, the [`TLC.tla`](https://github.com/tlaplus/Examples/blob/master/specifications/SpecifyingSystems/TLC/TLC.tla) module next to `ABCorrectness.tla` is the version of *Specifying System*, lacking the `PrintT` and `ToString` operators.  I suggest we rename [`TLC.tla`](https://github.com/tlaplus/Examples/blob/master/specifications/SpecifyingSystems/TLC/TLC.tla) to `TLC.tla.SpecifyingSystems`

**Comment by ahelwer** [comment]
I have no immediate plans to do that CI work for the tlaplus/tlaplus repo but it would be quite easy to add once the CI changes are done in the examples repo. Just download the latest examples source tar.gz in the TLC CI and run the parse and model check python scripts using the CI build of TLC.

**Comment by lemmy** [comment]
Will rename TLC.tla in the examples repo.
