### ISSUE TITLE
Check that trace (TLCExt) is finished (or complete/done, ignoring any loops)

### ISSUE THREAD

**Issue by pfeodrippe** [tlaplus/tlaplus#786]
When running a spec, I can get the trace using TLCExt.getTrace (`Trace` in TLA+), is there a way of checking (not after it's finished, but _while_ running) that there are no new states for a given state in a trace? In other words, could I know that a state is the tail of a trace?

Even if this is not available in TLA+ yet, but it's available from Java, it should be fine.

**Comment by pfeodrippe** [comment]
Hunnn, I guess this is achievable using an action constraint, right? Maybe I could check (let's say that var is `v`) that `v = v' or check that `v'` is not contained in the trace states so far.

**Comment by Calvin-L** [comment]
Can you clarify what you mean by "finished"? In TLA+ all behaviors are infinite; there is no last state. Chapter 2 of [Specifying Systems](https://lamport.azurewebsites.net/tla/book-21-07-04.pdf) has more on this subject.

Perhaps `~ENABLED Next` would suffice? If `Next` is not enabled, then the remainder of the trace is guaranteed to be unchanging (only stutter steps are possible).

**Comment by pfeodrippe** [comment]
> Can you clarify what you mean by "finished"? In TLA+ all behaviors are infinite; there is no last state. Chapter 2 of [Specifying Systems](https://lamport.azurewebsites.net/tla/book-21-07-04.pdf) has more on this subject.

Hi @Calvin-L o/, yeah, I understand that, but let's also ignore stuttering and loops so we can have finite traces (also assuming that the spec states are bounded). 

> Perhaps `~ENABLED Next` would suffice? If `Next` is not enabled, then the remainder of the behavior is guaranteed to be unchanging (only stutter steps are possible).

Nice! So checking for `~ENABLED Next` would solve the case where I don't have loops, correct? Guess I would still need to check if the next state is not equal to a past state in that trace, wdyt?

**Comment by Calvin-L** [comment]
Yes, I think that sounds right.

**Comment by pfeodrippe** [comment]
> Yes, I think that sounds right.

Nice! I will close this, thank you very much, Calvin!
