### ISSUE TITLE
Operator substitution does not work for definitions from INSTANCE modules

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#792]
## Description

TLC configuration files allow operator definitions to be substituted with different ones at model-checking time. However, it seems that some operators cannot be overridden---or at least, I don't quite understand the rules. Consider:

```tla
---- MODULE InstanceSubstitution ----

EXTENDS Naturals

VARIABLE x

Evens == {i \in Nat : i % 2 = 0}
Init == x = 0
Next == x' \in Evens

====
```
```tla
---- MODULE InstanceSubstitutionMC ----

EXTENDS Naturals
VARIABLE x
INSTANCE InstanceSubstitution WITH x <- x

SmallEvens == {0, 2, 4}

====
```
```
\* InstanceSubstitutionMC.cfg
INIT Init
NEXT Next

CONSTANT Evens <- SmallEvens
```

## Expected Behavior
TLC should check the spec using the finite set `Evens == {0, 2, 4}` instead of the infinite set `Evens == {i \in Nat : i % 2 = 0}`.

Alternatively, TLC should fail with an error indicating that the definition of `Evens` cannot be overridden---although I am not sure why that would be the case.

## Actual Behavior
TLC appears to use the original definition of `Evens`, ignoring my substitution:
```
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: Attempted to enumerate { x \in S : p(x) } when S:
Nat
is not enumerable
Error: The behavior up to this point is:
State 1: <Initial predicate>
x = 0

Error: The error occurred when TLC was evaluating the nested
expressions at the following positions:
0. Line 5, column 1 to line 5, column 41 in InstanceSubstitutionMC
1. Line 9, column 9 to line 9, column 20 in InstanceSubstitution
```

## Steps to Reproduce
1. Create the files `InstanceSubstitution.tla`, `InstanceSubstitutionMC.tla`, and `InstanceSubstitutionMC.cfg` as above.
2. Run `tlc2 InstanceSubstitutionMC.tla`.

## Steps Taken to Fix
I get the expected behavior using EXTENDS instead of INSTANCE:
```tla
---- MODULE InstanceSubstitutionMC ----

EXTENDS InstanceSubstitution, Naturals

SmallEvens == {0, 2, 4}

====
```

## Your Environment

 - TLC version: e4961d3
 - Toolbox version: N/A
 - Operating System: MacOS 12.6.2

**Comment by ahelwer** [comment]
Oh yeah, the INSTANCE override syntax is super weird. You can see it here: https://github.com/tlaplus/Examples/blob/master/specifications/NanoBlockchain/MCNanoSmall.cfg

I think this would work for you:
```
CONSTANT Evens = [InstanceSubstitution]SmallEvens
```

Everything seems kinda backward of what you'd expect. You'd *think* it would be something like:
```
CONSTANT [InstanceSubstitution]Evens = [InstanceSubstitutionsMC]SmallEvens
```

**Comment by ahelwer** [comment]
@Calvin-L did the above work so this issue can be closed?

**Comment by Calvin-L** [comment]
Thanks for your suggestion! I had forgotten that it was possible to include the module name. (And sorry for my glacial response time on this one.)

This works: `CONSTANT Evens <- [InstanceSubstitution]SmallEvens`.

It is similar to your first suggestion but with `<-` instead of `=`. I believe `=` replaces a declared `CONSTANT` and `<-` replaces a definition. If anyone else encounters this, that's the quick fix.

----

But that said... there's something a little unsatisfying here. It isn't just that "everything seems kinda backward". If I add this to my config:

```
CONSTANT Foo <- 1
```

then TLC does what I expect:

```
Starting... (2023-03-31 16:06:31)
Error: In the configuration file, the identifier Foo does not appear in the specification.
```

So why does it accept `CONSTANT Evens <- SmallEvens` without actually overriding anything?

I think there's a somewhat important question here involving
 - the meaning of a name like `Evens` inside a module (and whether it matters if that name comes from an EXTENDS or INSTANCE declaration)
 - what it means to substitute one definition with another

But I can't quite put my finger on the right question. I don't know if it's me or TLC that's confused---but given that `CONSTANT Foo <- ...` and `CONSTANT Evens <- ...` behave differently, I'm still inclined to say it's the second. (Or both.)

**Comment by Calvin-L** [comment]
I did a little more investigation and now I actually think TLC is right about this, not me.

To illustrate, suppose you give the `INSTANCE` a name:

`inst == INSTANCE InstanceSubstitution WITH x <- x`

What you get is something like this (abusing syntax somewhat):
```
inst!Evens == {i \in Nat : i % 2 = 0}
inst!Next == x' \in inst!Evens
```

If you do not give the `INSTANCE` a name, you get extra definitions like
```
Evens == inst!Evens
Next == inst!Next
```

With those definitions it's clear that (1) `Evens` is a definition and can be overridden but (2) overriding it does not change how `Next` behaves. That is because `Next` does not use `Evens` at all: `Next = inst!Next = x' \in inst!Evens`. You have to override the definition of `Evens` in the `InstanceSubstitution` module to have any hope of changing how `Next` behaves.

I'm going to close this issue since I think I have my explanation, but I'll conclude with "maybe TLC should issue a warning in this case" since the behavior could be surprising to others as well.
