### ISSUE TITLE
TLA+ google group keeps auto-deleting my posts

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#796]
Don't know where else to report this. The TLA+ google group keeps auto-deleting my answers. See deleted answers in this thread: https://groups.google.com/g/tlaplus/c/5gq3yes_rTA

**Comment by lemmy** [comment]
There is nothing on our end that indicates why your messages have been deleted.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/88777/222975223-add4e348-9d64-45c4-9ea5-5119069bbd44.png">

**Comment by ahelwer** [comment]
I think between this and the lack of monospace it's an indicator we should move to a different platform, for example github discussions in the tlaplus/tlaplus repository

**Comment by lemmy** [comment]
At this point, this might be an isolated issue that could be resolved soon.  Also, the Google Groups does provide monospace fonts at its Email interface.  At any rate, this is not an ideal place for this discussion.  The TLA+ project meetings could be a better place.

**Comment by ahelwer** [comment]
Your email response with monospace doesn't render as monospace in the google group.

**Comment by lemmy** [comment]
It renders correctly in my MUA.

**Comment by lemmy** [comment]
FWIW: The Linux Foundation might have suitable infrastructure in place to host the TLA+ discussion group.

**Comment by lemmy** [comment]
https://github.com/tlaplus/CommunityModules/issues/88

**Comment by muenchnerkindl** [comment]
I replied to an issue yesterday (through email) and received an error message. Then posted my reply through the Web UI but it doesn't appear in the conversation thread. Just reviewed the settings of the Google group: everything looks OK, and there are no messages awaiting moderation. Searching the Web, I found a few similar reports from past years but no clear way to resolve the issue.

**Comment by ahelwer** [comment]
I wrote up a post on this surveying some formal methods projects and what they're using. Tried to submit this as a link to the google group forum but it deleted itself LOL https://ahelwer.ca/post/2023-03-08-google-groups/

**Comment by lemmy** [comment]
The lack of proper error messages suggests that somebody at Google hooked up an LLM to Groups that is running crazy.

http://discuss.tlapl.us could be turned from a read-only mirror into a full mailing list.  Because ownership of the `tlapl.us` domain will soon transfer to the LF/TLA+Foundation, we are future-proof and can transparently migrate the list to new infrastructure if necessary.  Migrating away from Group would be trivial because we can simply import the Group subscribers into the new mailing list.

**Comment by ahelwer** [comment]
Well thank goodness it's all archived. I do wonder whether it would be a good idea to set up a Discourse instance hosted by the foundation (or paying the Discourse project to host it out of foundation money). Another alternative someone linked in the r/programming thread is [Fossil](https://fossil-scm.org/home/doc/trunk/www/index.wiki). I was impressed by how fast the pages load when clicking around the demo website. Other people [really like Zulip](https://lobste.rs/s/mt2p8g/google_groups_has_been_left_die#c_omvlqu).

**Comment by lemmy** [comment]
Half of the current subscribers configured Groups to send them emails (digest/abridged/each), but somebody should correlate user activity with subscription status. Another data point, the Group is far more traffic compared to the *web-only* [reddit](https://www.reddit.com/r/tlaplus/).

**Comment by ahelwer** [comment]
Isabelle does the zulip/mailing list combo. As long as the mailing list has a good browse/search web interface I'm happy to use it.

**Comment by lemmy** [comment]
> I replied to an issue yesterday (through email) and received an error message. Then posted my reply through the Web UI but it doesn't appear in the conversation thread. Just reviewed the settings of the Google group: everything looks OK, and there are no messages awaiting moderation. Searching the Web, I found a few similar reports from past years but no clear way to resolve the issue.

Seems to be an ongoing issue: https://support.google.com/groups/thread/205048267/all-groups-messages-are-getting-automatically-deleted-as-soon-as-posted?hl=en

**Comment by rdivyanshu** [comment]
This issue has happening for me since last two days. 

I replied to this question https://groups.google.com/g/tlaplus/c/DY5uByHi6nA and my replies keep getting deleted. 
Further if I mail from inside gmail instead of groups, my emails doesn't reach google groups.

**Comment by muenchnerkindl** [comment]
Thanks for letting me know: I now indeed saw your messages in the moderation panel but had not received any notification from Google groups. I passed the latest copy of your message and blocked the others.

If you are a member of the Google group, moderation should not be necessary. Did you send the messages from the address that you used for registering with the group?

**Comment by rdivyanshu** [comment]
Thanks Stephen. Yeah it is same address.

**Comment by uguryavuz** [comment]
I have also been experiencing the same issue in [this thread](https://groups.google.com/g/tlaplus/c/FaHdiTe7CMU), I don't seem to be able to respond through the web interface.

**Comment by lemmy** [comment]
@uguryavuz Your three messages were held in the moderator queue. I approved the latest one and rejected the two older ones. Could it be that you are not subscribed with the email address you used to post?

**Comment by uguryavuz** [comment]
I tried subscribing and posting through another e-mail address when the issue came up (I had initially replied via my usual e-mail, which is also still subscribed), but that post was also deleted. So I'm not sure if that is the problem.

I also sent another reply to Damien's comment around half an hour ago, through e-mail. Did that response appear in any queues? I'm not currently seeing it in the thread.

**Comment by lemmy** [comment]
I am unsure why your original message from your usual email ended up in the moderator queue.  Previous messages from your other email were not approved when your subscription request with that email address was accepted (approval of pending messages doesn't happen automatically).

**Comment by lemmy** [comment]
@uguryavuz Google thinks your messages are spam.

<img width="1002" alt="image" src="https://github.com/tlaplus/tlaplus/assets/88777/dee1d7a0-f079-4cff-9c54-070ab5e06cd9">

**Comment by uguryavuz** [comment]
I suppose it makes sense it would think that now, since I tried to send the same post a number of times - but I'm not sure what would have triggered it in the first place, with my initial reply.

**Comment by rdivyanshu** [comment]
This happened to me just now. My first message from gmail web client didn't ended up in TLA+ mailing list and composing and sending from google groups show message as deleted.

**Comment by will62794** [comment]
@muenchnerkindl @ahelwer @lemmy Could we move to Github discussions as a forum instead of Google Groups? 

The auto-deletion issues have become very bothersome. And the general UI/interface of Google Groups feels increasingly dated/janky.

**Comment by lemmy** [comment]
IMO this is a decision to be made by the foundation's Outreach Committee.

**Comment by ahelwer** [comment]
I evaluated a few possibilities when this happened last year and presented them at the community meeting. I don't really like GitHub discussions since I'd rather use a FOSS solution hosted on foundation infrastructure instead of increasing ties with GitHub. Even switching to a LF-hosted mailing list with some kind of bridge would be an improvement.

**Comment by ahelwer** [comment]
This happened again. Love to have a post I spent ten minutes writing just get ethered. https://groups.google.com/g/tlaplus/c/l04R3AEnTFI
