### ISSUE TITLE
Use user.home/.tlaplus as universal location for Toolbox workspace

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#8]
The Toolbox creates its corresponding _workspace_ directory in the current directory from where it was launched. Unless users start the Toolbox via a static mechanism like the start menu or app launcher, they tend to end up with several workspaces. A newly created workspace has no references to existing specs and the Toolbox appears to have forgotten all specs.

Adding the property _-Dosgi.instance.area.default=@user.home/.tlaplus_ to the [product file](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product) will cause the workspace to universally be created in the user's home directory regardless of the actual path from where it's started. However, we have to tell our existing users to manually move their existing workspace to @user.home/.tlaplus once.

The current [.deb Toolbox package](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/org.lamport.tla.toolbox.product.product/src/deb/control/postinst) sets _osgi.instance.area.default_ already. This has to be removed with the change to the [product file](https://github.com/tlaplus/tlaplus/blob/770a070649e89e21487ffeea3fab50e02bcfff32/org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product).

**Comment by lemmy** [comment]
Change done in 85628f3717ef17288e1a293a0a4e299b62dfe108

**Comment by lemmy** [comment]
The top-level help page titled "In Case of Trouble" still refers to the old workspace location and needs to be updated.

**Comment by lemmy** [comment]
I revert this change with XXX for the 1.5.3 release. There is no way (I almost lost my sanity over this) to migrate user workspaces from their 1.5.2 location to the new 1.5.3 @user.home/.tlaplus location. The reason is, that once the Toolbox updated to 1.5.3 it already uses @user.home/.tlaplus and we have no way of knowing the 1.5.2 workspace location.

The intended Eclipse way is to use a touchpoint action [[1]](http://codeandme.blogspot.de/2011/11/custom-installation-step.html)[[2]](http://eclipsesource.com/blogs/2013/05/23/custom-touchpoints-in-p2/)[[3]](http://help.eclipse.org/neon/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_actions_touchpoints.html)[[4]](http://help.eclipse.org/kepler/index.jsp?topic=/org.eclipse.platform.doc.isv/guide/p2_customizing_metadata.html) during p2 update to handle this scenario. [Unfortunately, the functionality (two stage touchpoint) is broken](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469291). Instead, rolled out a change with a8f346b12d4899f88877980f0395bee9742190b4 which makes the 1.5.3 Toolbox collect all the workspace locations in a canonical file. With 1.5.4 we can then extract the locations and give detailed instructions to a user.

Related, if we want the Toolbox's welcome screen to force open after the upgrade to 1.5.4, we can use the IntroContentDetector extension in org.lamport.tla.toolbox.product.standalone with the implementation below:

     
     package org.lamport.tla.toolbox.ui.intro;
     
     import org.eclipse.core.runtime.preferences.ConfigurationScope;
     import org.eclipse.core.runtime.preferences.IEclipsePreferences;
     import org.eclipse.ui.intro.IntroContentDetector;
     import org.osgi.service.prefs.BackingStoreException;
     
     public class ToolboxIntroContentDetector extends IntroContentDetector {

	public boolean isNewContentAvailable() {
		// Read a preference values that indicates if the has shown the
		// Welcome/Intro screen to the user. The rational is, that we force the
		// intro to open up e.g. after an update in case we have
		// noteworthy/important news.
		final IEclipsePreferences preferences = ConfigurationScope.INSTANCE
				.getNode("org.lamport.tla.toolbox.ui.intro");
		final boolean showWarning = preferences.getBoolean("workspaceWarning", true);
		if (showWarning) {
			preferences.putBoolean("workspaceWarning", false);
			try {
				preferences.flush();
			} catch (BackingStoreException notExpectedToHappen) {
				notExpectedToHappen.printStackTrace();
			}
		}
		return showWarning;
	     }
     }

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/commit/a53477cdaa8e2431c29525caf42f53e9e66e2224

**Comment by lemmy** [comment]
Fixed with 102ce8b33345459fdd3788d250ccddabe14d6fc8

**Comment by hwayne** [comment]
Help files need to be updated too: we spent a while looking for the `workspaces` folder based on the troubleshooting section, which still says it's in the same folder.

**Comment by lemmy** [comment]
@hwayne Can you provide a PR?
