### ISSUE TITLE
TLA+ Toolbox fails to run on OS X Sierra 10.12.6

### ISSUE THREAD

**Issue by zbmott** [tlaplus/tlaplus#80]
When I run the program, I get a popup window with the message "An error has occurred. See the log file at `/Applications/TLA+ Toolbox.app/Contents/Eclipse/configuration/1507135529074.log`".

I have attached the indicated log file to this error report.
[tla_toolbox_error.log](https://github.com/tlaplus/tlaplus/files/1356674/tla_toolbox_error.log)

EDIT: Quick Googling suggested that my JRE (1.6) was too old, so I uninstalled JRE 1.6 and installed JRE 1.8. Now when I try to run TLA+ Toolbox, I get a message saying "To open "Toolbox" you need to install the legacy Java SE 6 runtime. Click "More Info..." to visit the legacy Java SE 6 download website."

**Comment by lemmy** [comment]
On macOS, please install Oracle JDK 1.8.

**Comment by zbmott** [comment]
Installing Oracle JDK 1.8 solved my issue. Thank you for your help.

**Comment by carlthuringer** [comment]
The JDK 1.8 (Java SE platform 8?) is End-Of-Life. Will the Toolbox work with Platform 9?

**Comment by lemmy** [comment]
According to the official [roadmap](http://www.oracle.com/technetwork/java/eol-135779.html), 1.8's EOL is September 2018.

Anyway, the next Toolbox release (and the current [nightlies](http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/)) will work with Java 9.
