### ISSUE TITLE
Feature request: show arguments to actions in bad behavior

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#807]
## Description

When TLC outputs a bad behavior it helpfully includes the names of each action taken.  It would be nice if it also included the _arguments_ to those actions.

For example, consider the following spec and config:

```tla
---- MODULE ActionArgs ----

EXTENDS Naturals, FiniteSets

CONSTANT Actors

VARIABLE shared_value, actor_state
vars == <<shared_value, actor_state>>

Init ==
    /\ shared_value = {}
    /\ actor_state = [a \in Actors |-> [pc |-> "INIT", value |-> {}]]

ReadValue(actor) ==
    /\ actor_state[actor].pc = "INIT"
    /\ actor_state' = [actor_state EXCEPT
        ![actor].pc = "ADD_SELF",
        ![actor].value = shared_value]
    /\ UNCHANGED <<shared_value>>

AddSelf(actor) ==
    /\ actor_state[actor].pc = "ADD_SELF"
    /\ actor_state' = [actor_state EXCEPT
        ![actor].pc = "WRITE",
        ![actor].value = shared_value \union {actor}]
    /\ UNCHANGED <<shared_value>>

WriteValue(actor) ==
    /\ actor_state[actor].pc = "WRITE"
    /\ actor_state' = [actor_state EXCEPT
        ![actor].pc = "DONE",
        ![actor].value = {}]
    /\ shared_value' = actor_state[actor].value
    /\ UNCHANGED <<>>

Step(actor) ==
    \/ ReadValue(actor)
    \/ AddSelf(actor)
    \/ WriteValue(actor)

AllDone ==
    /\ \A a \in Actors: actor_state[a].pc = "DONE"
    /\ UNCHANGED vars

Next ==
    \/ \E a \in Actors: Step(a)
    \/ AllDone

Spec == Init /\ [][Next]_vars

Inv == Cardinality(shared_value) <= 1

====
```

```
SPECIFICATION Spec
CONSTANT Actors = {Alice, Bob}
INVARIANT Inv
```

## Expected Behavior

TLC should include the arguments of each action, for instance:

```
Error: Invariant Inv is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
...

State 2: <ReadValue(Alice) line 15, col 5 to line 19, col 33 of module ActionArgs>
...

State 3: <AddSelf(Alice) line 22, col 5 to line 26, col 33 of module ActionArgs>
...

State 4: <WriteValue(Alice) line 29, col 5 to line 34, col 21 of module ActionArgs>
...

State 5: <ReadValue(Bob) line 15, col 5 to line 19, col 33 of module ActionArgs>
...

State 6: <AddSelf(Bob) line 22, col 5 to line 26, col 33 of module ActionArgs>
...

State 7: <WriteValue(Bob) line 29, col 5 to line 34, col 21 of module ActionArgs>
...
```

The arguments (`Alice` and `Bob`) can be enormously helpful in quickly understanding the behavior. 

## Actual Behavior

TLC outputs a bad behavior, but at a glance it is difficult to tell who acted when:

```
Error: Invariant Inv is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
...

State 2: <ReadValue line 15, col 5 to line 19, col 33 of module ActionArgs>
...

State 3: <AddSelf line 22, col 5 to line 26, col 33 of module ActionArgs>
...

State 4: <WriteValue line 29, col 5 to line 34, col 21 of module ActionArgs>
...

State 5: <ReadValue line 15, col 5 to line 19, col 33 of module ActionArgs>
...

State 6: <AddSelf line 22, col 5 to line 26, col 33 of module ActionArgs>
...

State 7: <WriteValue line 29, col 5 to line 34, col 21 of module ActionArgs>
...
```

Did Alice and Bob interleave to violate the invariant? There's no telling without inspecting every state.

## Steps to Reproduce
1. Create `ActionArgs.tla` and `ActionArgs.cfg` as above.
2. Run TLC on `ActionArgs.tla`.
3. Observe that the actions do not say who acted.

## Workaround
I can manually reconstruct the arguments to each action by inspecting what changed in each state. That works, but it gets tedious when states contain more many variables, and it is easy to get confused when your spec contains a typo that causes the delta between states to be different from what you expect.

## Your Environment

 - TLC version: `TLC2 Version 2.18 of Day Month 20?? (rev: e4961d3)`
 - Toolbox version: N/A
 - Operating System: MacOS

**Comment by lemmy** [comment]
This should be fairly easy to implement because TLC creates an Action instance for each argument and captures the argument in Action#con.  Thus, given an arity > 0, you can use the OpDef's formal params and lookup the value in the action's context.

**Comment by lemmy** [comment]
By the way, this information should be available in the TLA+ debugger's variables view if you debug an error trace/counterexample in VSCode.

**Comment by UnrealEugene** [comment]
> This would be super useful, and, luckily, should be fairly easy to implement, because TLC creates an `Action` instance for each argument and captures the argument's value in `Action#con`. Thus, given an arity > 0, you can use the `OpDef`'s formal params and lookup the value in the action's context.

Just looking up arguments in context is not enough. Consider this rough fix of `Action#getLocation(String)` method:
```java
public final String getLocation(final String actionName) {
	if (opDef.getParams().length == 0) {
		return String.format("<%s %s>", actionName, pred.getLocation());
	} else {
		ITool tool = TLCGlobals.mainChecker.tool;
		String paramsString = Arrays.stream(opDef.getParams())
				.map(p -> tool.lookup(p, con, false).toString())
				.collect(Collectors.joining(", "));
		return String.format("<%s(%s) %s>", actionName, paramsString, pred.getLocation());
	}
}
```

In the following spec action arguments are printed out correctly:
```tla
---- MODULE Test ----
EXTENDS Integers
VARIABLE x

Init == x = 0

Next(a) == x' = x + a

Spec == Init /\ [][Next(1)]_x

IsNotTwo == x # 2
====
```
```
Error: Invariant IsNotTwo is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
x = 0

State 2: <Next(1) line 7, col 12 to line 7, col 21 of module Test>
x = 1

State 3: <Next(1) line 7, col 12 to line 7, col 21 of module Test>
x = 2
```

But when action arguments are more complicated (e.g. they depend on variable values) it stops working as intended:
```tla
---- MODULE Test ----
EXTENDS Integers
VARIABLE x

Init == x = 0

Next(a) == x' = x + a

Spec == Init /\ [][Next(IF x = x THEN 1 ELSE 1)]_x

IsNotTwo == x # 2
====
```
```
Error: Invariant IsNotTwo is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
x = 0

State 2: <Next(line 7, col 6 to line 7, col 6 of module Test) line 9, col 20 to line 9, col 47 of module Test>
x = 1

State 3: <Next(line 7, col 6 to line 7, col 6 of module Test) line 9, col 20 to line 9, col 47 of module Test>
x = 2
```

It seems to work as intended if I were to pass previous and next states to `getLocation` method and evaluate arguments using those states when needed, but this looks wrong:
```java
public final String getLocation(final String actionName, final TLCState from, final TLCState to) {
	if (opDef.getParams().length == 0) {
		return String.format("<%s %s>", actionName, pred.getLocation());
	} else {
		Tool tool = (Tool) TLCGlobals.mainChecker.tool;
		OpApplNode opApplNode = (OpApplNode) pred;
		StringJoiner paramsString = new StringJoiner(", ");
		if (opApplNode.getOperator().getKind() == UserDefinedOpKind) {
			ExprOrOpArgNode[] nodeArgs = opApplNode.getArgs();
			for (ExprOrOpArgNode arg : nodeArgs) {
				Object val = tool.getVal(arg, con, false);
				if (val instanceof LazyValue) {
					val = ((LazyValue) val).eval(tool, from, to);
				}
				paramsString.add(val.toString());
			}
		} else {
			FormalParamNode[] params = opDef.getParams();
			for (FormalParamNode param : params) {
				paramsString.add(tool.lookup(param, con, false).toString());
			}
		}
		return String.format("<%s(%s) %s>", actionName, paramsString, pred.getLocation());
	}
}
```
Any thoughts?

**Comment by lemmy** [comment]
I have a feeling that Actions with state-level parameters/arguments are quite rare. This intuition is supported by our [examples](https://github.com/tlaplus/examples), where it seems that no specification includes state-level arguments.

**Comment by UnrealEugene** [comment]
I agree that action arguments are usually constants and are backed by existential quantifier. Also it would be very nice to show action arguments in dumped .dot files for better visualization.

**Comment by lemmy** [comment]
Sounds good, can you provide a PR that adds arguments to the dot output?

**Comment by lemmy** [comment]
Closed with e86829e722cc9b5e59c99a80089010aae672a307. Let's create new issues to address support for handling state-level arguments and auxiliary features, like dot output, if necessary.

**Comment by Calvin-L** [comment]
Thanks a ton @UnrealEugene :)

**Comment by lemmy** [comment]
Downstream commits VSCode extension:

https://github.com/tlaplus/vscode-tlaplus/commit/572747465b0281f1ee262b73b5ea52a081c48354
https://github.com/tlaplus/vscode-tlaplus/commit/4a0d7233df210ebada17ba2252da7a6b14560c3d

**Comment by lemmy** [comment]
@UnrealEugene Have you been able to construct a scenario where only a subset of the formal params resolve from the context?
