### ISSUE TITLE
Model Checker does not run on macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by carlthuringer** [tlaplus/tlaplus#81]
I'm attempting to follow [LearnTLA+](https://learntla.com/introduction/example/#assertions-and-sets) and when I reach the linked section and attempt the run the model by clicking the green circle-arrow icon on the default model, nothing happens.

The module:
```
------------------------------ MODULE transfer ------------------------------
EXTENDS Naturals, TLC

(* --algorithm transfer
variables alice_account = 10, bob_account = 10, money = 5;

begin
A: alice_account := alice_account - money;
B: bob_account := bob_account + money;

end algorithm *)
\* BEGIN TRANSLATION
VARIABLES alice_account, bob_account, money, pc

vars == << alice_account, bob_account, money, pc >>

Init == (* Global variables *)
        /\ alice_account = 10
        /\ bob_account = 10
        /\ money = 5
        /\ pc = "A"

A == /\ pc = "A"
     /\ alice_account' = alice_account - money
     /\ pc' = "B"
     /\ UNCHANGED << bob_account, money >>

B == /\ pc = "B"
     /\ bob_account' = bob_account + money
     /\ pc' = "Done"
     /\ UNCHANGED << alice_account, money >>

Next == A \/ B
           \/ (* Disjunct to prevent deadlock on termination *)
              (pc = "Done" /\ UNCHANGED vars)

Spec == Init /\ [][Next]_vars

Termination == <>(pc = "Done")

\* END TRANSLATION
```

I can't find any log or message to post to tell you further details of the problem.

**Comment by lemmy** [comment]
On Windows and Linux, the _.log_ file is in the folder  _workspace/.metadata_.  That folder is in the same folder as the executable file with which you run the Toolbox.  On the Mac, it is in the folder  _toolbox.app/Contents/MacOS/workspace/.metadata_, where  toolbox.app  is the folder that you execute to run the Toolbox.  (The log contains enough timestamped entries for you to figure out what part of it relates to the problem you are reporting.)

**Comment by carlthuringer** [comment]
https://gist.github.com/carlthuringer/997cf93056a34c2783783c2e5413d31f

Couple things sticking out to me:
```
!ENTRY org.lamport.tla.toolbox.jclouds 4 0 2017-10-05 13:14:49.270
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.lamport.tla.toolbox.jclouds [210]
```

```
!ENTRY org.lamport.tla.toolbox.tool.tlc.ui 1 -1 2017-10-05 13:14:58.319
!MESSAGE No source for Model_1 found.
```

Thank you for the prompt response.

**Comment by carlthuringer** [comment]
I found a workaround:
1) Create a new model
1.1) Replicate bug by clicking "Run", the model will not be checked.
2) Under "What to check?" check "Deadlock".
3) Uncheck "Deadlock".
4) Click "Run", the model will be checked.

**Comment by lemmy** [comment]
Your workaround refreshed my memory. I'm pretty sure your issue is addressed by https://github.com/tlaplus/tlaplus/commit/9e4cdfc3f53ced76186a841cd305a4488d44edb9 and thus fixed in a [current nightly build](http://tla.msr-inria.inria.fr/tlatoolbox/ci/products/).
