### ISSUE TITLE
TLATools in a separated repository from the Toolbox

### ISSUE THREAD

**Issue by teodorov** [tlaplus/tlaplus#811]
Hi

Would it be possible to split this repository so that the tlatools becomes isolated from the toolbox?

I believe that will simplify the build process for the tlatools and ease the setup for contributions to the backend.

Best regards,
Ciprian

**Comment by lemmy** [comment]
Changes to TLC can be made without the need for Eclipse or building the Toolbox.  Instead, you can compile and test TLC using the standalone Ant build: https://github.com/tlaplus/tlaplus/blob/master/DEVELOPING.md#building-tlc--tlatoolsjar

**Comment by lemmy** [comment]
Closing in favor of https://github.com/tlaplus/tlaplus/issues/880
