### ISSUE TITLE
NullPointerException when trying to place nested comments inside set enumerations in config.

### ISSUE THREAD

**Issue by UnrealEugene** [tlaplus/tlaplus#822]
## Description

Spec:
```tla
---- MODULE Test ----

EXTENDS Naturals, TLC

CONSTANTS S
VARIABLES x

Init == x = S

Spec == Init /\ [][FALSE]_x

====
```

Config:
```
SPECIFICATION Spec
CONSTANT S = { 1(*, 2(*, 3*) }
```

Error:
```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.NullPointerException
java.lang.NullPointerException
at tlc2.tool.impl.ModelConfig.parseValue(ModelConfig.java:495)
at tlc2.tool.impl.ModelConfig.parse(ModelConfig.java:401)
at tlc2.tool.impl.Spec.<init>(Spec.java:99)
at tlc2.tool.impl.Tool.<init>(Tool.java:211)
at tlc2.tool.impl.Tool.<init>(Tool.java:206)
at tlc2.tool.impl.Tool.<init>(Tool.java:196)
at tlc2.tool.impl.Tool.<init>(Tool.java:182)
at tlc2.tool.impl.FastTool.<init>(FastTool.java:54)
at tlc2.TLC.process(TLC.java:1217)
at tlc2.TLC.main(TLC.java:352) 
```

I tried to comment out twice some elements of set `{ 1, 2, 3 }` so it appeared like `{ 1(*, 2(*, 3*)*) }` but then VS Code plugin and IntelliJ IDEA plugin both highlighted that second `*)` is redundant. After removing the second `*)` the error above appeared. However if I were not to remove the second `*)` TLC runs without any issues (although plugins highlight incorrectly).

The same error is raised if the line `CONSTANT S = { 1(*, 2(*, 3*) }` is changed to just `CONSTANT S = { (*`

## Expected Behavior
Helpful error message to spot the problematic token. I was confused when IDE highlighting behaved like no errors are present but TLC raised an unexpected error.

## Actual Behavior
Described above.

## Your Environment

 - TLC version: 5b3286b
 - Operating System: Ubuntu 20.04.6 LTS x86_64

**Comment by lemmy** [comment]
Marking "cantfix" until somebody volunteers to drive this.
