### ISSUE TITLE
Stack trace is not printed if Java exception occurs while evaluating invariant

### ISSUE THREAD

**Issue by UnrealEugene** [tlaplus/tlaplus#826]
## Description
Spec:
```tla
---- MODULE Test ----
EXTENDS Integers
VARIABLE x

Spec == x = 1 /\ [][x' = x + 1]_x

Inv == <<1, 2>>[x] = x
====
```
Config:
```
SPECIFICATION Spec
INVARIANT Inv
```
Output:
```
Evaluating invariant Inv failed.
Attempted to access index 3 of tuple
<<1, 2>>
which is out of bounds.
The behavior up to this point is:
1: <Initial predicate>
x = 1

2: <Action line 5, col 21 to line 5, col 30 of module Test>
x = 2

3: <Action line 5, col 21 to line 5, col 30 of module Test>
x = 3
```
Although here the problem can be spotted instantly, in my large 1000 line spec I found the cause of problem only after putting several breakpoints in TLC source code and seeing stack trace from there.
 
## Expected Behavior
Error message containing stack trace to locate problematic expression like in the following spec:
```tla
---- MODULE Test ----
EXTENDS Integers
VARIABLE x

Spec == x = 1 /\ [][x' = x + 1 /\ <<1, 2>>[x] = x]_x
====
```
Output:
```
TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.RuntimeException
: Attempted to access index 3 of tuple
<<1, 2>>
which is out of bounds.
The behavior up to this point is:
1: <Initial predicate>
x = 1

2: <Action line 5, col 21 to line 5, col 49 of module Test>
x = 2

3: <Action line 5, col 21 to line 5, col 49 of module Test>
x = 3

TLC was unable to fingerprint.

Fingerprint Stack Trace:
0. Line 5, column 21 to line 5, column 49 in Test
1. Line 5, column 21 to line 5, column 30 in Test
2. Line 5, column 35 to line 5, column 49 in Test
3. Line 5, column 35 to line 5, column 45 in Test
4. Line 5, column 35 to line 5, column 42 in Test

Reason:
Attempted to access index 3 of tuple
<<1, 2>>
which is out of bounds.
```

## Actual Behavior
Described above.

## Your Environment
 - TLC version: a57a3a7
 - Operating System: Ubuntu 20.04.6 LTS x86_64

**Comment by lemmy** [comment]
@UnrealEugene Would you be able to verify whether this represents a regression from previous TLC releases?

**Comment by UnrealEugene** [comment]
Checked up until ab14a33e, the issue still presents. It's hard for me to check further though.

**Comment by lemmy** [comment]
Just so you know, the TLA+ debugger actually identifies the spec bug and gives you all the relevant details, including the desired stack trace: <img width="998" alt="image" src="https://github.com/tlaplus/tlaplus/assets/88777/6f50b765-dc69-422a-b3be-8c658aca1ac7">

**Comment by lemmy** [comment]
I believe this can be closed.  Please reopen if not.
