### ISSUE TITLE
Is there a way to get access to state information during model checking?

### ISSUE THREAD

**Issue by craft095** [tlaplus/tlaplus#828]
I wonder if it is possible by using Java overrides (or by some other means) to get following information "online" while TLC is working:
1. State information
2. Transition information - a pair of states and some action id

I am looking for a way to build state graph projection "on the fly", because dot files quickly become impractical for larger models. Projected graphs can be much smaller and problem-oriented so that they are easier to analyze.

Thank you!

**Comment by UnrealEugene** [comment]
It's kinda possible using Java module overrides with `@EvaluatingValue` annotation since it provides you with current and next state (but not sure if it's valid to work with next state when it's not fingerprinted) although you would need to put new overridden operator at the end of every action and sacrifice some readability of your spec. 

The other way is to fork the repository and write your own `IStateWriter` implementation using `DotStateWriter` class as a reference. This interface contains `writeState(...)` methods which are called when new state/transition is discovered by TLC. 

I tackled this problem myself some time ago the second way but it would be certainly be nice to have a way to export state graph without directly modifying TLC source code. Maybe add Java property for TLC to use custom `IStateWriter` implementation and then provide it in the classpath?

**Comment by lemmy** [comment]
> The other way is to fork the repository and write your own `IStateWriter` implementation using `DotStateWriter` class as a reference. This interface contains `writeState(...)` methods which are called when new state/transition is discovered by TLC.

We can add an (undocumented) system property that causes TLC to load a custom `IStateWriter` instance, but the IStateWriter` interface was never intended to be public and, thus, has [quirks](https://github.com/tlaplus/tlaplus/blob/04c46d87c1d58c87ed779c088461bbe5ec837a4c/tlatools/org.lamport.tlatools/src/tlc2/util/DotStateWriter.java#L220-L223).

@craft095 I'm aware that the dot files can become huge, but have you considered tools like [Gephi](https://gephi.org) to do projections offline?

**Comment by UnrealEugene** [comment]
> We can add an (undocumented) system property that causes TLC to load a custom `IStateWriter` instance, but the `IStateWriter` interface was never intended to be public and, thus, has [quirks](https://github.com/tlaplus/tlaplus/blob/04c46d87c1d58c87ed779c088461bbe5ec837a4c/tlatools/org.lamport.tlatools/src/tlc2/util/DotStateWriter.java#L220-L223).

I can provide a PR for this.

**Comment by craft095** [comment]
Awesome! I'll try this. Thanks, @lemmy , @UnrealEugene !

> I'm aware that dot files can become huge, but have you considered tools like [Gephi](https://gephi.org/) to do projections offline?

For 6M states + 16M edges I got dot file ~8G - just to parse this file takes time and memory. E.g. Gephi needs  [>160G RAM](https://gephi.org/users/requirements) for such graph.
One more reason to do it online is that I want to define projection as TLA+ state expression: I want to get comprehensible visual representations of the system behavior based on user-provided projections.

**Comment by lemmy** [comment]
> I wonder if it is possible by using Java overrides (or by some other means) to get following information "online" while TLC is working:
> 
> 1. State information
> 2. Transition information - a pair of states and some action id

A state- and action-constraint provide such a "hook" into TLC's state-space exploration.  Note, though, that *action ids* are just TLC artifacts, and highly dependent on the syntactic structure of the next-state relation.  Let `A`, `B, and `C`, an action constraint could look like this:

```tla
ActionConstraint ==
    PrintT(<<"s, t, A/B/C", vars, vars', A, B, C>>)
```

Additionally, if you run the TLA+ debugger or TLC's simulation mode, `TLCGet("action")` equals a record (amongst other including the action id) that TLC has given to the sub-formula of the next-state relation.

**Comment by craft095** [comment]
Thank you, @lemmy for your excellent suggestions! So far, I use following approach inspired by your ideas, which allows me to experiment with state projections without overrides at all:

```
---- MODULE Projection ----

EXTENDS TrafficLight, TLC

StateProjections ==
    [
        Go |-> state = State_InService \/ light = Light_Green,
        Stop |-> state = State_Working /\ light /= Light_Green
    ]


CurrentState == CHOOSE s \in DOMAIN StateProjections : StateProjections[s]

Transition == <<CurrentState, CurrentState'>>

Ix == 1
Report == TLCGet(Ix)
Capture == TLCSet(Ix, Report \union { Transition })

PInit ==
    /\ Init
    /\ TLCSet(Ix, {})

PNext ==
    /\ Next
    /\ Capture

PSpec == PInit /\ [][PNext]_vars

PostCondition == PrintT(Report)

====
```

**Comment by lemmy** [comment]
I believe this can be closed.  Please reopen if not.
