### ISSUE TITLE
1.5.4 OSX download is damaged

### ISSUE THREAD

**Issue by nworbekim** [tlaplus/tlaplus#83]
OSX 10.13 is refusing to run the latest 1.5.4 release of tla+.  I get a pop up message stating the file is damaged and to move the file to trash.

The earlier nightly build of 1.5.4 did not have this problem

**Comment by lemmy** [comment]
Where did you download it from? I just checked and neither the Github nor the alternate download site serve a broken file.

Did you extract "TLA+ Toolbox" to /Applications/ ?

**Comment by nworbekim** [comment]
I've been using the link https://github.com/tlaplus/tlaplus/releases/tag/v1.5.4

I downloaded it again tonight with the same result.  The steps I'm following are:  (1) download, (2) move from Downloads to /Applications & (3) execute file from either finder or launchpad.

Here's a screenshot showing the error when I try to run the file from /Applications.

<img width="1356" alt="screen shot 2017-10-11 at 8 56 35 pm" src="https://user-images.githubusercontent.com/5480401/31474247-82dfff98-aec7-11e7-881c-9db6ae3e6bd6.png">

**Comment by nelsonjchen** [comment]
What Java version do you have installed?

**Comment by lemmy** [comment]
Below are the sha1sums for the 64 bit downloads:

8c04794d897bf1d1f1c7d5a72db2216aabbca47c  TLAToolbox-1.5.4-linux.gtk.x86_64.zip
1510d0d63e93b2436b301facd7f62b58853c8b80  TLAToolbox-1.5.4-macosx.cocoa.x86_64.zip
f75905000593269a94a9b3b0aa2d3570c95ddba2  TLAToolbox-1.5.4-win32.win32.x86_64.zip

**Comment by nworbekim** [comment]
Hi,

The shamus of the zip file matches your sum and I  found  app runs when started from a terminal but not from Finder or Launchpad.

Here’s my java version (displayed in the terminal):
Mikes-MacBook-Pro:Applications mike$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
Mikes-MacBook-Pro:Applications mike$ 

The additional information on the error dialog shows the following information.  I've tried opening the app with ctrl-open from finder and still get the error.
<img width="964" alt="screen shot 2017-10-13 at 9 22 49 pm" src="https://user-images.githubusercontent.com/5480401/31571303-04d75fb8-b05e-11e7-8a51-370b734b2b0d.png">

**Comment by lemmy** [comment]
@nworbekim What output do you get when you run the following commands from Terminal?

_spctl --assess /Applications/TLA+\ Toolbox.app/
codesign -v /Applications/TLA+\ Toolbox.app
xattr -l /Applications/TLA+\ Toolbox.app/_

Below is what I get with which I'm able to run the Toolbox.

```
macbook:Applications makuppe$ spctl --assess TLA+\ Toolbox.app/
TLA+ Toolbox.app/: rejected
macbook:Applications makuppe$ codesign -v TLA+\ Toolbox.app/
TLA+ Toolbox.app/: code object is not signed at all
In architecture: x86_64
macbook:Applications makuppe$ xattr -l TLA+\ Toolbox.app/
com.apple.quarantine: 01c3;00000000;Safari;02D8A381-32BE-4BBC-AAB5-A501E73D6D23
```

**Comment by nworbekim** [comment]
@lemmy here's the results of the commands run on /Applications/TLA+\ Toolbox.app

Mikes-MacBook-Pro:~ mike$ ./tla-83
+ cd /Applications
+ spctl --assess 'TLA+ Toolbox.app/'
TLA+ Toolbox.app/: invalid Info.plist (plist or signature have been modified)
+ codesign -v 'TLA+ Toolbox.app/'
TLA+ Toolbox.app/: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
+ xattr -l 'TLA+ Toolbox.app/'
com.apple.quarantine: 0183;59e14324;Safari;8D0968F6-84D5-4692-AAB7-E2C14DABD84F
Mikes-MacBook-Pro:~ mike$

**Comment by lemmy** [comment]
@nworbekim What is the content of your /Applications/TLA+ Toolbox.app/Contents/Info.plist? Mine is below:

```
macbook:Contents makuppe$ cat /Applications/TLA+\ Toolbox.app/Contents/Info.plist 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">

<dict>
	<key>CFBundleExecutable</key>
		<string>toolbox</string>
	<key>CFBundleGetInfoString</key>
		<string>Eclipse 4.7 for Mac OS X, Copyright IBM Corp. and others 2002, 2016. All rights reserved.</string>
	<key>CFBundleIconFile</key>
		<string>Eclipse.icns</string>
	<key>CFBundleIdentifier</key>
		<string>org.lamport.tla.toolbox.product.product</string>
	<key>CFBundleInfoDictionaryVersion</key>
		<string>6.0</string>
	<key>CFBundleName</key>
		<string>Toolbox</string>
	<key>CFBundlePackageType</key>
		<string>APPL</string>
	<key>CFBundleShortVersionString</key>
		<string>1.5.4</string>
	<key>CFBundleSignature</key>
		<string>????</string>
	<key>CFBundleVersion</key>
		<string>1.5.4</string>
	<key>NSHighResolutionCapable</key>
		<true/>
	<key>CFBundleDevelopmentRegion</key>
		<string>English</string>
	<key>CFBundleLocalizations</key>
		<array>
			<string>ar</string>
			<string>cs</string>
			<string>da</string>
			<string>el</string>
			<string>en</string>
			<string>es</string>
			<string>de</string>
			<string>fi</string>
			<string>fr</string>
			<string>hu</string>
			<string>it</string>
			<string>iw</string>
			<string>ja</string>
			<string>ko</string>
			<string>nl</string>
			<string>no</string>
			<string>pl</string>
			<string>pt_BR</string>
			<string>pt</string>
			<string>ru</string>
			<string>sv</string>
			<string>tr</string>
			<string>zh_HK</string>
			<string>zh_TW</string>
			<string>zh</string>
		</array>
		
	<key>Eclipse</key>
		<array>
			<!-- to use a specific Java version (instead of the platform's default) uncomment one of the following options,
					or add a VM found via $/usr/libexec/java_home -V
				<string>-vm</string><string>/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Commands/java</string>
				<string>-vm</string><string>/Library/Java/JavaVirtualMachines/1.8.0.jdk/Contents/Home/bin/java</string>
			-->
			<string>-keyring</string>
      <string>~/.eclipse_keyring</string>
		</array>
<key>CFBundleDisplayName</key>
    <string>Toolbox</string>
  </dict>

</plist>

**Comment by nworbekim** [comment]
@lemmy "diff" reports I have the same contents as the Info.plist you put in your comment.  

Here's the contents from the Info.plist on my system

Mikes-MacBook-Pro:Contents mike$ cat Info.plist 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">

<dict>
	<key>CFBundleExecutable</key>
		<string>toolbox</string>
	<key>CFBundleGetInfoString</key>
		<string>Eclipse 4.7 for Mac OS X, Copyright IBM Corp. and others 2002, 2016. All rights reserved.</string>
	<key>CFBundleIconFile</key>
		<string>Eclipse.icns</string>
	<key>CFBundleIdentifier</key>
		<string>org.lamport.tla.toolbox.product.product</string>
	<key>CFBundleInfoDictionaryVersion</key>
		<string>6.0</string>
	<key>CFBundleName</key>
		<string>Toolbox</string>
	<key>CFBundlePackageType</key>
		<string>APPL</string>
	<key>CFBundleShortVersionString</key>
		<string>1.5.4</string>
	<key>CFBundleSignature</key>
		<string>????</string>
	<key>CFBundleVersion</key>
		<string>1.5.4</string>
	<key>NSHighResolutionCapable</key>
		<true/>
	<key>CFBundleDevelopmentRegion</key>
		<string>English</string>
	<key>CFBundleLocalizations</key>
		<array>
			<string>ar</string>
			<string>cs</string>
			<string>da</string>
			<string>el</string>
			<string>en</string>
			<string>es</string>
			<string>de</string>
			<string>fi</string>
			<string>fr</string>
			<string>hu</string>
			<string>it</string>
			<string>iw</string>
			<string>ja</string>
			<string>ko</string>
			<string>nl</string>
			<string>no</string>
			<string>pl</string>
			<string>pt_BR</string>
			<string>pt</string>
			<string>ru</string>
			<string>sv</string>
			<string>tr</string>
			<string>zh_HK</string>
			<string>zh_TW</string>
			<string>zh</string>
		</array>
		
	<key>Eclipse</key>
		<array>
			
			<string>-keyring</string>
      <string>~/.eclipse_keyring</string>
		</array>
<key>CFBundleDisplayName</key>
    <string>Toolbox</string>
  </dict>

</plist>
Mikes-MacBook-Pro:Contents mike$

**Comment by lemmy** [comment]
@nworbekim What happens if you configure a specific VM in Info.plist?

**Comment by nworbekim** [comment]
@lemmy No difference.   I enclosed my modified Info.plist if it will help.  Removing my .tlaplus directory, saved state and preferences files didn't change the behavior.

> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">

<dict>
	<key>CFBundleExecutable</key>
		<string>toolbox</string>
	<key>CFBundleGetInfoString</key>
		<string>Eclipse 4.7 for Mac OS X, Copyright IBM Corp. and others 2002, 2016. All rights reserved.</string>
	<key>CFBundleIconFile</key>
		<string>Eclipse.icns</string>
	<key>CFBundleIdentifier</key>
		<string>org.lamport.tla.toolbox.product.product</string>
	<key>CFBundleInfoDictionaryVersion</key>
		<string>6.0</string>
	<key>CFBundleName</key>
		<string>Toolbox</string>
	<key>CFBundlePackageType</key>
		<string>APPL</string>
	<key>CFBundleShortVersionString</key>
		<string>1.5.4</string>
	<key>CFBundleSignature</key>
		<string>????</string>
	<key>CFBundleVersion</key>
		<string>1.5.4</string>
	<key>NSHighResolutionCapable</key>
		<true/>
	<key>CFBundleDevelopmentRegion</key>
		<string>English</string>
	<key>CFBundleLocalizations</key>
		<array>
			<string>ar</string>
			<string>cs</string>
			<string>da</string>
			<string>el</string>
			<string>en</string>
			<string>es</string>
			<string>de</string>
			<string>fi</string>
			<string>fr</string>
			<string>hu</string>
			<string>it</string>
			<string>iw</string>
			<string>ja</string>
			<string>ko</string>
			<string>nl</string>
			<string>no</string>
			<string>pl</string>
			<string>pt_BR</string>
			<string>pt</string>
			<string>ru</string>
			<string>sv</string>
			<string>tr</string>
			<string>zh_HK</string>
			<string>zh_TW</string>
			<string>zh</string>
		</array>
		
	<key>Eclipse</key>
		<array>
			
			<string>-vm</string><string>/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java</string>
			<string>-keyring</string>
      <string>~/.eclipse_keyring</string>
		</array>
<key>CFBundleDisplayName</key>
    <string>Toolbox</string>
  </dict>

</plist>

**Comment by lemmy** [comment]
@nworbekim I'm pretty much in the dark... Can you try to upgrade to [Java 1.8.0_144](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) or [Java 9](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html)?

**Comment by nworbekim** [comment]
@lemmy - I learned this symptom results from OSX 10.13 security controls.  Unlike earlier releases (maybe before 10.12?)  OSX 10.13 doesn't allow installation of apps from "un-identified developers".

To eliminate the need for this work around, what would you need to become an "identified developer"?


The work around I used is:

1. open a terminal
2. enter command "sudo spctl --master-disable"
3. install app
4. open using finder with ctrl-open
5. tell OSX this app is ok to run... (tla+displays splash image and runs)
6. enter command in terminal - "sudo spctl --master-enable"

See the comments on the [page](http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/).

**Comment by lemmy** [comment]
"identified developer" means a annual subscription of the Apple Developer Program. That seems to be lot of overhead for very little to gain.

**Comment by nworbekim** [comment]
Hi Markus

Let me know if you’d like me to create a build with my ID.

Regards 
Mike

**Comment by dimiii** [comment]
@lemmy 

>  for very little to gain.
The gain is a working application and missing of need to move it to trash.

**Comment by lkuty** [comment]
I have the same problem with the file TLAToolbox-1.5.8-macosx.cocoa.x86_64.zip (2019-04-20 01:52) in the nightly builds and here is what I had to do to be able to launch it :
`xattr -cr /Applications/TLA+\ Toolbox.app`
I did not have the problem when I first downloaded the nightly build 1 or 2 weeks ago.

**Comment by lemmy** [comment]
@lkuty If possible, please narrow down the nightly version of when it last worked without setting xattr.

**Comment by lkuty** [comment]
It might be the one published on 15 April. I do not have it anymore but I started downloading TLA+ stuff (articles, videos, ...) on that date, so I guess I also took the toolbox that day. So the problem appeared between the 15 and the 20.
