### ISSUE TITLE
tla2tex with `-out` option fails if the output file does not exist already

### ISSUE THREAD

**Issue by nano-o** [tlaplus/tlaplus#855]
If `out.tex` does not exists already, running `java -cp tla2tools.jar tla2tex.TeX -out out.tex in.tex` fails with:
```
TLATeX unrecoverable error:

 -- Error while renaming files.


TLATeX unrecoverable error:

 -- I/O error: TLATeX unrecoverable error: -- Error while renaming files..

Exception in thread "main" tla2tex.TLA2TexException: TLATeX unrecoverable error: -- I/O error: TLATeX unrecoverable 
error: -- Error while renaming files..
        at tla2tex.Debug.ReportError(Debug.java:26)
        at tla2tex.TeX.main(TeX.java:411)
```

This seems to be because line 406 of `TeX.java` tries to rename the output file, which fails if the output file does not exist already. A workaround is to create an empty output file first.

**Comment by lemmy** [comment]
@nano-o I believe this is fixed.
