### ISSUE TITLE
TLA+ toolbox error when launching

### ISSUE THREAD

**Issue by Lilii13** [tlaplus/tlaplus#856]
Hi!
I have been working with TLA+ toolbox normally, until today, after closing the toolbox and trying to reopen it I get the following : 

![Screenshot from 2024-01-03 11-26-30](https://github.com/tlaplus/tlaplus/assets/90387323/2afef545-b90e-4b00-a34a-72c9cfad8b36)

Here is the error log I find when following the path (I don't understand much of it) : 
[.log](https://github.com/tlaplus/tlaplus/files/13817933/default.log)

I didn't change anything after closing the app so I really don't know what is the reason behind this.

Other information : 
 - Java version: JDK11 (now upgraded to 17)
 - Toolbox version: 1.7.1
 - Operating System: Ubuntu 20.04

Please enlighten me, I really need the toolbox for my work.
Thanks !
Lilia

**Comment by lemmy** [comment]
Please attempt to start the toolbox using the `-clean` flag. If this doesn't resolve the issue, consider creating a new workspace. To do this, rename the existing toolbox workspace folder. Change `/home/admin_local/.tlaplus` to something like `/home/admin_local/.tlaplus.old`. After doing this, you'll need to re-add your specifications to the newly created workspace.
