### ISSUE TITLE
Uses of different Vector implementations across codebase

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#86]
Some of our code uses `java.util.Vector<E>` and other of our code uses the [homegrown version](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/utilities/Vector.java).

We should probably standardize on one.

**Comment by lemmy** [comment]
Reducing the code size is a desirable goal in general.  However, a tiny reduction in size does not justifies the risk of introducing subtle bugs.  Whenever work is done to add a new feature, one should refactor related code when possible and warranted.
