### ISSUE TITLE
Bug in ThmOrAssumpDefNode.addLabel(LabelNode)

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#87]
`ThmOrAssumpDefNode.addLabel(LabelNode)` in checking existence in its Hashtable (which is `<UniqueString, LabelNode>`) [incorrectly uses the parameter value (an instance of LabelNode) as a check for the existence of a key](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/ThmOrAssumpDefNode.java#L316).

This is a simple fix - i'll pick it up.

**Comment by lemmy** [comment]
Fixed in b04265eb09833508baaecdebfe086fd703b097be
