### ISSUE TITLE
Normalize line endings as LF or CRLF and encode choice in .gitattributes file

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#872]
Currently files in the repo are a mix of LF or CRLF. Since contributions can be written on any of the major OS platforms, a .gitattributes file should be added enforcing that files are either CRLF (Windows-style) or LF (Linux-style). This is especially important because code generation is used in SANY, and depending on the platform it will generate files with either CRLF or LF endings. This can lead to spurious diffs if those generated files replace existing files & are then committed.

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by lemmy** [comment]
Based on the [execution statistics](https://metabase.tlapl.us/public/dashboard/cf7e1a79-19b6-4be1-88bf-0a3fd5aa0dec?jvm_vendor=&os_name=&ide_launched=&fp_set_type=&category=tlc), unix-based platforms are way more popular.

**Comment by kape1395** [comment]
I like this idea. And I'm for the Linux-style EOLs.

**Comment by lemmy** [comment]
Can we incrementally change all existing CRLF line endings to LF using a `.gitattributes` file, so that only the portions of a file modified by a commit have their line endings altered? Converting all CRLFs to LFs in a single operation would make comparing file versions to identify regressions very difficult.

**Comment by ahelwer** [comment]
I don't know, I think it would be better to get it out of the way in one large commit just called "Normalize line endings" so people know to ignore that one. If it's mixed in with another commit changing the file it can make it harder to see the actual change.

**Comment by ahelwer** [comment]
Documenting this to add to the confusion, some files have both LF and CRLF line endings within the same file. For example, this section:

https://github.com/tlaplus/tlaplus/blob/de0c1811f291fcb68e81873af1fba7eb3fa9814a/tlatools/org.lamport.tlatools/src/tla2sany/parser/TLAplusParserTokenManager.java#L4267:L4278

has LF line endings while (most of) the rest of the file is CRLF. You can see this by opening the file with `vim -b filename`; lines ending with CRLF will have a `^M` character displayed.

This is unfortunate because I'm trying to see what modifications have been made to the javacc-generated parser code but these line endings are confounding the diff attempt.
