### ISSUE TITLE
Enforce using either tabs or spaces, at least on a per-file basis

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#881]
Similar to https://github.com/tlaplus/tlaplus/issues/872 some of the files in this repo use tabs, other use spaces, some use tabs on some lines & spaces on other lines in the same file, and some mix tabs & spaces *on the same line*. It doesn't really matter whether tabs or spaces are used as long as the decision is uniform and consistent; ideally this would be uniform across the entire repo, but some method should be used to enforce this on a per-file basis at least. As with the LF/CRLF issue any such change should be done incrementally over time to avoid spurious diffs confusing debugging, but at very least a decision should be made and this process should be started.

One good concrete action would be to add a step to the PR CI which analyzes any new files to enforce that they are entirely tabs or entirely spaces (ideally we would enforce one), so at least the situation does not get worse, and ideally would check that for each file modified, if it previously was *entirely* tabs or spaces, the modifications do not change that.

**Comment by kape1395** [comment]
I would vote for spaces.

**Comment by lemmy** [comment]
Big bang reformatting of source code makes it difficult to bisect and (automatically) revert older patches.
