### ISSUE TITLE
Work proposal: add corpus of tests for SANY at syntax parsing level

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#882]
I would like to run this proposal past the maintainers before spending much time on it.

Tree-sitter grammars have a very nice method of writing parser tests, using a collection of .txt files with a very basic DSL; for example:
<details>
  <summary>Sample from tree-sitter-tlaplus test corpus</summary>

```
=============|||
Multiline Conjlist
=============|||

---- MODULE Test ----
op ==
  /\ 
   1
  /\
   2
====

-------------|||

(source_file (module (header_line) (identifier) (header_line)
  (operator_definition (identifier) (def_eq)
    (conj_list
      (conj_item (bullet_conj) (nat_number))
      (conj_item (bullet_conj) (nat_number))
    )
  )
(double_line)))

=============|||
Nested Conjlist
=============|||

---- MODULE Test ----
op ==
 /\ /\ 1
    /\ 2
 /\ 3
====

-------------|||

(source_file (module (header_line) (identifier) (header_line)
  (operator_definition (identifier) (def_eq)
    (conj_list
      (conj_item
        (bullet_conj)
        (conj_list
          (conj_item (bullet_conj) (nat_number))
          (conj_item (bullet_conj) (nat_number))
        )
      )
      (conj_item (bullet_conj) (nat_number))
    )
  )
(double_line)))
```
</details>

Each test involves a title, the source code input, and the expected parse tree output in an S-expression-like DSL.

I would like to take the fairly large corpus of tests already existing in the tree-sitter-tlaplus repo and write a simple translator so they can be run against SANY at the syntax parsing level. This would involve no changes to any SANY code itself. I believe there are the following benefits:

- SANY doesn't currently have any unit tests similar to this, so it seems an unqualified good thing to add them
- sharing test inputs across the various TLA+ parsers (perhaps TLAPM parser could also be added in future) increases incentive to expand the corpus and helps ensure conformance between the parsers
- Using a lightweight DSL such as this instead of encoding the expected parse tree as Java objects greatly reduces the difficulty of adding additional tests

You can see the current tree-sitter-tlaplus test corpus [here](https://github.com/tlaplus-community/tree-sitter-tlaplus/tree/main/test/corpus). There are some tests including unicode symbols which will be omitted.

If this work is performed, will it likely be merged? Follow-up decision if so: it would be nice to upgrade to JUnit 5 (currently we use version 4) so these corpus tests can be emitted at runtime as [dynamic tests](https://junit.org/junit5/docs/5.0.2/api/org/junit/jupiter/api/DynamicTest.html) instead of running all of them inside a single unit test, although this is not strictly necessary.

**Comment by kape1395** [comment]
I like this idea. The "DSL" sounds similar to the TLAPM tests, e.g. https://github.com/tlaplus/tlapm/blob/main/test/fast/basic/z3_false_test.tla. Here, the file contains relevant theorems, and the expected result is stated after the module. The part after the module is ignored by parsers, so the module itself is valid as is. The expectation definition has to be more elaborated in the case of the parser, compared to the proof tests.

**Comment by lemmy** [comment]
The more tests the better, although almost all TLC tests implicitly test SANY; its test coverage should not be too bad.

More importantly, will these tests be independent of the existing test suite unless we upgrade to junit5?  I see value in having a single, uniform test suite.  If this is the case, we should explore upgrading to junit5 first.

**Comment by ahelwer** [comment]
These tests will be added alongside the current test suite. It will just be a single junit test that runs the entire test corpus, and fails if any of them fail. The only real benefit to using dynamic tests in junit 5 is it should make each corpus test appear as a single individual unit test, although I haven't tested this so don't know how it looks in the UI or whether that means you can easily re-run single failing tests or anything.

**Comment by lemmy** [comment]
To evolve SANY, we not only requires blackbox tests but also whitebox tests that access and validate SANY's internal state during testing - SANY is more than a parser. It's fine if these blackbox tests cannot access SANY programmatically, but we want a seamless integration with the existing and future whitebox tests.  If Junit4 doesn't have the necessary features, upgrading to Junit5 seems like a sensible first step.

That said, I like to point out that  the fine-grained "debuggability" of the current test suite is worth the effort of writing what some call verbose/cumbersome/... tests for the existing test suite; it's a price we only pay once.  Moreover, I presume that Java's pre-formatted strings will make writing new tests a lot more convenient.



To evolve SANY, we not only require blackbox tests but also whitebox tests that access and validate SANY's internal state during testing - SANY is more than a parser. It's fine if these blackbox tests cannot access SANY programmatically, but we want seamless integration with the existing and future whitebox tests. If JUnit4 doesn't have the necessary features, upgrading to JUnit5 seems like a sensible first step.

That said, I would like to point out that the fine-grained "debuggability" of the current test suite is worth the effort of writing what some call verbose/cumbersome tests for the existing test suite; it's a price paid only once. Moreover, I presume that Java's preformatted strings will make writing new tests a lot more convenient.

**Comment by ahelwer** [comment]
Sure, I would like to have several levels of tests - syntax parsing being the lowest, unless the lexer can be accessed independently - then adding on semantic tests and finally level tests.
