### ISSUE TITLE
tla2sany.semantic.Context plays loose and fast with its ivar "table"

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#89]
The `table` ivar in the Context class should be `<UniqueString, SymbolNode>` per [its documentation](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/Context.java#L196) and [its usage in other code](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/Generator.java#L6405) however occasionally in the code in this class, instead [an instance of `SymbolTable.ModuleName` is used as a key](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/Context.java#L378).

Similarly, `SymbolTable` treats `Context`'s `table` [in this manner](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2sany/semantic/SymbolTable.java#L231).

Ideally we would avoid heterogeneity like this.

**Comment by lemmy** [comment]
Please reopen with a spec/test case that reproduces this issue.
