### ISSUE TITLE
Revise enablement and checkboxes in Trace Explorer

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#9]
- ~Deselecting an expression does not turn it off in exploration ("Explore")~ - no longer an issue on master as of April 28, 2019
- ~Can edit an expression after an exploration, but "Restore" resets it to its value prior to exploration (=> prevent edits after exploration)~ see c8a3f54d4b0963d28d2a42bf2519537223268f6d
- ~Edit button should be enabled even without a table selection iff there is one formula in the table~ see 1bae2106b4ff9e74b95f04cddeb927ab97ecd059
- ~Clicking edit with only a single but un-selected table item should implicitly edit it~ see 1bae2106b4ff9e74b95f04cddeb927ab97ecd059
- ~Deleting expressions has no effect unless a model save is somehow triggered (remove expression from trace explorer, change model constant on main page, hit save)~ see 6b5bb6ddf3fae2f6b8a65d73ace1c0d5fbb6c620
- ~Explore button is enabled when the TLC Errors view is first opened (and there are no entries in the Trace Explorer)~ see 95e3e22edab9701e60ba5934d7d525bb5ae23ea1

**Comment by lemmy** [comment]
@nikshinde1996

**Comment by lemmy** [comment]
```
diff --git a/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/traceexplorer/TraceExplorerComposite.java b/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/traceexplorer/TraceExplorerComposite.java
index 5f70cb6..239b999 100644
--- a/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/traceexplorer/TraceExplorerComposite.java
+++ b/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/traceexplorer/TraceExplorerComposite.java
@@ -472,6 +472,15 @@
 			job.setRule(ResourcesPlugin.getWorkspace().getRoot());
 			job.setUser(true);
 			job.schedule();
+			
+	        tableViewer.getTable().setEnabled(false);
+	        
+	        buttonExplore.setEnabled(false);
+	        buttonAdd.setEnabled(false);
+	        buttonEdit.setEnabled(false);
+	        buttonRemove.setEnabled(false);
+	        
+	        buttonRestore.setEnabled(true);
         }
     }
 
@@ -485,6 +494,15 @@
 
         // update the error view with this provider
         view.updateErrorView();
+        
+        tableViewer.getTable().setEnabled(true);
+        
+        buttonExplore.setEnabled(true);
+        buttonAdd.setEnabled(true);
+        buttonEdit.setEnabled(true);
+        buttonRemove.setEnabled(true);
+        
+        buttonRestore.setEnabled(false);
     }
 
     /**
@@ -494,6 +512,9 @@
     protected void changeButtonEnablement()
     {
         IStructuredSelection selection = (IStructuredSelection) tableViewer.getSelection();
+        if (!tableViewer.getTable().isEnabled()) {
+        	return;
+        }
 
         if (buttonRemove != null)
         {
```

**Comment by lemmy** [comment]
Looking at the callers of org.lamport.tla.toolbox.tool.tlc.model.Model.setTraceExplorerExpression(List<String>) shows that the table checkboxes have never been taken into account.

**Comment by lemmy** [comment]
With #265 the Trace Explorer also needs up/down buttons to reorder composed expressions.

**Comment by lemmy** [comment]
It would also be nice if the expression text box would be sashed to be expandable.

**Comment by lemmy** [comment]
LL: "The reason we want restore is that a trace expression may produce an error that prevents the entire trace from being displayed.  Also, having looked at the trace with the added expressions, you might want to go back to looking at the original trace but don't want to change the trace expressions because you might want to use them again after the next model checking run. "

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/289

**Comment by quaeler** [comment]
Instead of up/down buttons, the formulas table now allows drag re-ordering - f7efdd943aa029a7cc547f56ef90a3bdef98d7a7

**Comment by lemmy** [comment]
Add a hint "drag to reorder" somewhere?

**Comment by quaeler** [comment]
Trace Exploration has a sash - b8331199017d2ea6c569ff280a09cd7e4b017120

**Comment by quaeler** [comment]
Drag re-order hints - 4333a1e680bd4e37fc7ec683910d8f273968d12c

**Comment by quaeler** [comment]
Explore observes formula enablement checkboxes now - 7b355a263e288d3b6ff9811134479d910883c71f

**Comment by quaeler** [comment]
With the deletion of selected formula in the focused table via Delete or Backspace ( b954444c9bac490bd1131261a9f3e85bd82a382b ) i believe this issue is now closed; please reopen if i'm incorrect.
