### ISSUE TITLE
Feature proposal: parallelize tlatools unit tests

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#901]
Currently the tlatools unit tests take a long time to run: around 11 minutes on my machine, or 15 minutes on the github CI machines. This is because they run sequentially. If they were run in parallel, the test runtime would be pretty much divided by the number of cores on the computer. Github CI machines have two cores so the tests would take half as long, around 7 minutes.

I see three possible routes to achieve unit test parallelism:

1. Apache Ant [Parallel task](https://ant.apache.org/manual/Tasks/parallel.html). In some sense this is easiest to implement but by far the most annoying and least featureful. We would have to come up with our own partitioning scheme for the tests to parallelize them (branch based on first letter of test name or something).
2. Change to fully using Maven instead of Ant for tlatools build & test. Maven's testing plugin has [simple configuration options](https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html) to parallelize an existing corpus of JUnit 4 tests at the class or method level.
3. Upgrade to JUnit 5, which has built-in [parallel execution](https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution). This would let us keep the Ant build. However, it would require quite a substantial number of changes across the test code. A ballpark estimate is 5000 lines changed based on some quick rewrites I tried (mostly mechanical stuff like changing `import org.junit.Assert` to `import org.junit.jupiter.Assertions`).

Thoughts? I'm leaning toward option 2 although some preliminary attempts at getting all the unit tests to run under maven ran into some annoying errors. I guess I should also point out that if we want to go with option 3 I would pretty much have to implement option 2 anyway so I could use the [open-rewrite](https://docs.openrewrite.org/running-recipes/getting-started) maven plugin to help migrate to JUnit 5.

**Comment by lemmy** [comment]
I'd go with 1. (until we can get rid of the Toolbox) or 3.  Migrating to maven will be an uphill battle for as long as we have to build an OSGi bundle of org.lamport.tlatools for the Toolbox.

**Comment by Calvin-L** [comment]
If we want this feature in the short term then I also think 1 is the right choice, especially since (if I recall correctly) some tests are order-dependent. They cannot be naively parallelized.

> Change to fully using Maven instead of Ant

I have many (er, too many) thoughts about the future of the tools' build system, and one of those thoughts is that Maven might not be the best choice. When the time comes I might gently argue for [Gradle](https://gradle.org/) over Ant or Maven.

> some preliminary attempts at getting all the unit tests to run under maven ran into some annoying errors

I actually have a working Maven build file for the tools, partly based on the changes in #756. I have not shared it for a few reasons (it is _far_ from feature-parity with the Ant build file, and as stated above I am not sure Maven is the future build system we want)---but if you think it would be useful I can push it to a branch when I get back from vacation on the 8th.

**Comment by ahelwer** [comment]
I agree it would be nice to skip past maven and use gradle. I would appreciate getting access to your working maven file!

**Comment by lemmy** [comment]
Let's create a list of features/requirements that we ned from a new build system:

* Ant is missing a module system (but is that an issue given that tla2tools is a fat jar and the handful of dependencies are checked into git?)

**Comment by ahelwer** [comment]
I guess it depends whether we want to stick with all the jars checked into source control (aka "vendored dependencies" as the cool kids say) or move to referencing packages that are downloaded during the build. There is an actual example in our repo of a dependency not being available for download anywhere online with that 25-year-old version of JavaCC used to generate the configuration parser (see https://github.com/javacc/javacc/issues/279) although I want to tear out that code anyway. JavaCC 4.0 is available as a mvn package. Still, I don't think it is too concerning of an issue; our industry is definitely moving in the direction of long-term reproducible builds and software archiving without including all dependencies in a single repo (nixOS and guix are both working on this, which I want to onboard all the TLA+ tools to at some point).

**Comment by lemmy** [comment]
I've come to prefer build systems that are not distributed systems.

**Comment by ahelwer** [comment]
Fair enough, I was looking at maven yesterday and I *think* it supports a form of drawing dependencies from jars checked into source control, as long as they're laid out in a certain directory structure that maven identifies as a repository (see https://maven.apache.org/guides/introduction/introduction-to-repositories.html).

**Comment by lemmy** [comment]
Maven is very opinionated when it comes to how dependencies are made available.  Especially, it used to make it almost impossible to consume deps that are checked into the same repository (the Toolbox build has to consume such a dependency by downloading it from github.com/tlaplus/tlaplus/...).  In short, maven makes [simple things impossible](https://www.goodreads.com/quotes/8636264-simple-things-should-be-simple-complex-things-should-be-possible).

**Comment by Calvin-L** [comment]
> Let's create a list of features/requirements that we ned from a new build system:
>  - Ant is missing a module system (but is that an issue given that tla2tools is a fat jar and the handful of dependencies are checked into git?)

Here are some things we have today that probably need to be preserved:

 - Builds the tools in multiple configurations:
   - fat jar for CLI distribution (potentially with launch scripts and so forth)
   - OSGi jar for Toolbox
   - thin (?) jar for upload to binary repos (ossrh.xml and github.xml ...?)
   - with or without AspectJ sources (actually, when are these necessary? I've never been clear on their status)
 - Able to run various test flavors:
   - quick unit tests
   - unit tests against compiled jar
   - unit tests in a directory containing whitespace
   - long-running tests
   - JPF tests
   - JMH benchmarks

**Comment by lemmy** [comment]
My chopping block:
* Everything AspectJ (cool tech but no longer used)
* OSGi jar (once Toolbox is gone)
* JPF and JMH instructions good enough to run manually every once in a while

FYI: AspectJ was used back in the day to collect performance and scalability data from distributed TLC.  It was also used to build the first TLA+ debugger prototype.

**Comment by Calvin-L** [comment]
> I actually have a working Maven build file for the tools, partly based on the changes in #756.

@ahelwer https://github.com/tlaplus/tlaplus/blob/d035b25db314f94ac2544c0b49efef7a5e712748/tlatools/org.lamport.tlatools/pom.xml

**Comment by ahelwer** [comment]
To add to previous discussion about Java build tools (ant vs. maven vs. gradle) lately I've been trying out [sbt](https://en.wikipedia.org/wiki/Sbt_(software)) for the Java-based TLA+ parsing tutorial I'm writing ([link](https://github.com/tlaplus-community/tlaplus-creator)) and am really impressed. It's like the only Java build tool that doesn't require you to create ten nested directories and 100 lines of boilerplate config before it starts working. It's also used by Apalache. So I think sbt would be a good option to consider for a future build system as well.
