### ISSUE TITLE
Crash when accessing Preferences -> General -> Web Browser with version 1.8.0

### ISSUE THREAD

**Issue by matthias-g** [tlaplus/tlaplus#917]
## Description

When I try to access Preferences -> General -> Web Browser, the TLA+ Toolbox crashes.
This happens with version 1.8.0.
TLA+ Toolbox version 1.7.0 works fine.

## Your Environment

 - TLC version: 2.15
 - Toolbox version: 1.8.0
 - Operating System: Arch Linux with Gnome

## Screenshots

Preferences -> General -> Web Browser in version 1.7.0: 
![Screenshot from 2024-04-26 16-48-44](https://github.com/tlaplus/tlaplus/assets/1591161/14388ff0-95a9-4e53-bef1-1e123e99d751)
When clicking on Preferences -> General -> Web Browser in version 1.8.0:
![Screenshot from 2024-04-26 16-49-09](https://github.com/tlaplus/tlaplus/assets/1591161/a4140954-825e-4768-9e0a-2cabdf2c1299)

**Comment by Hi-Angel** [comment]
Additional info: *(from the duplicate issue)*: running `tla+toolbox` from terminal will give you more information about the crash. Here's the relevant snippet:

<details>
    <summary>Details</summary>

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000076d414a36f48, pid=1145680, tid=1145681
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4940r23.so+0x36f48]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/constantine/Projects/builds/tla-toolbox-nightly/core.1145680)
#
# An error report file with more information is saved as:
# /home/constantine/Projects/builds/tla-toolbox-nightly/hs_err_pid1145680.log
Compiled method (n/a)   52429 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
Compiled method (n/a)   52429 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
Compiled method (n/a)   52430 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```
</details>

Most interesting perhaps is that the crash seems to be coming from a 3-rd party project that TLA+ is using called `Adoptium`. However, the problem is currently on the TLA+ side and not Adoptium's, because TLA+ is using an ancient `14.0.1+7` version that hasn't been supported for a long time. As of writing the words the current one is `21.0.3+9`. For all we know, the bug may have been fixed long time ago, on the TLA+ we first need to update Adoptium to supported version.

**Comment by lemmy** [comment]
https://github.com/tlaplus/tlaplus/issues/835 blocks an upgrade to Java 21. Thus, somebody should investigate if upgrading to Java 17 LTS is sufficient to address #917.

**Comment by lemmy** [comment]
Unfortunately, we don't have the resource to work on this. Please provide a ready-to-merge Pull Request.
