### ISSUE TITLE
Add LOC counting to SANY

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#918]
https://github.com/microsoft/CCF/pull/6152 is an ad hoc LOC counter for TLA+.  @ahelwer Do you know enough about parsing TLA+ in general and SANY in particular to estimate how difficult it would be to build this into SANY?

**Comment by ahelwer** [comment]
Assuming we want to count "lines containing at least one element of non-comment TLA+ syntax" one possible algorithm would be to iterate over all leaf nodes in the parse tree and add their line numbers to a set (start/end lines should be the same for leaf nodes), then get the cardinality of that set. If you want to make a more scientific measure that you could use to, for example, compare the line counts of different specs then you would want to write a TLA+ code formatter first which does not yet exist and would be quite a lot of work.

**Comment by lemmy** [comment]
I guess this could be implement an `tla2sany.explorer.ExplorerVisitor`.

**Comment by lemmy** [comment]
Unfortunately, we don't have the resource to work on this. Please provide a ready-to-merge Pull Request.
