### ISSUE TITLE
TLC reports zero coverage for conjunct of the next-state action

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#92]
TLC reports 0 coverage for the indicated conjunct of the next-state action below:

```tla
  VARIABLE x
  Spec == /\ x = 0 
          /\ [][/\ x' = (x+1)%5
                /\ x' = (x+1)%5  \* <- 0 coverage
               ]_x
```

This is an oversimplification of a problem that occurred in a real spec.  A slightly more complicated example indicates how it can arise in practice.

```tla
   /\ A
   /\ \/ /\ x' # x
         /\ ...
      \/ /\ x' = x   \* <- 0 coverage
         /\ ... 
```
where

```tla
   A ==  \/ /\ ...
            /\ x' = ...
            /\ ...
         \/ /\ ...
            /\ x' = x
            /\ ...
```

Related, TLC reports zero coverage for the (automatically) generated `vars = <<x,y,z>>` definition of PlusCal unless `vars` appears as part of an UNCHANGED statement (see issue #152).

**Comment by quaeler** [comment]
From experimentation, it also appears that:
```tla
Is92 == /\ state = "eins"  
        /\ y' \in 800..1000
        /\ y' \in 0..5000
        /\ state' = "deux"
        /\ state' = "deux"
```
has zero coverage on the second NSA for both `y` and `state`.

```tla
Is92 == /\ state = "eins"  
        /\ y' \in 800..1000
        /\ y' \in 0..5000
        /\ state' = "deux"
        /\ state' = "three"
```
has zero coverage for all actions.

```tla
Is92 == /\ state = "eins"  
        /\ y' \in 800..1000
        /\ y' \in 0..5000
        /\ y' = y + 5
        /\ state' = "deux"
        /\ state' = "deux"
```
has zero coverage for all actions.

**Comment by quaeler** [comment]
This is happening because of the design of the code in `Tool.getNextStatesAppl(OpApplNode, ActionItemList, Context, TLCState, TLCState, StateVec)`

A second NSA for the same variable enters into this method carrying the `TLCState` (`TLCStatusMutSource`) which has already bound the variable to a value defined in the previous NSA.  The code handling as least the equals and in operators determines that the primed variable is already bound, and does not attempt to bind for the current pred.

It is the binding action, though, which marks an internal object array of `SemanticNode` in the `TLCState` which is later consulted for code coverage calculations.

I'll make a fix addressing this.

**Comment by lemmy** [comment]
Please add a JUnit test with a spec that shows the problem. The test class should be derived from https://github.com/tlaplus/tlaplus/blob/master/tlatools/test/tlc2/tool/liveness/ModelCheckerTestCase.java (don't mind _liveness_ in the package name)

**Comment by quaeler** [comment]
The organization of the [test-model directory](https://github.com/tlaplus/tlaplus/tree/master/tlatools/test-model) is a little rough. It _seems_ like the spec should go into a subdirectory with issues that deal with NSAs, but there isn't one yet.

Should i make a new directory or, if not, where do you recommend i place the test asset?

**Comment by lemmy** [comment]
I'm fine with restructuring test-model eventually. Also I don't have a strong preference where to put the spec in test-model. Feel free to create a new directory.

**Comment by quaeler** [comment]
After having written a unit test and debugged it, i see that it appears that MP is not giving the recorder any useful information concerning NSA coverage - which means there is nothing useful that this unit test can do.

I can improve MP as a new precursor to this issue, or maybe i'm missing something, or ?

**Comment by lemmy** [comment]
What's the reason the MP doesn't log coverage? tlc2.tool.AbstractChecker.reportCoverage(IWorker[]) sends the info to MP.

**Comment by quaeler** [comment]
That's a fine question - i'll find out hook into MP and see what's going on (my above comment comes from breaking in the test's single @Test method and seeing what `recorder` has lurking inside of it.

**Comment by quaeler** [comment]
`TLCGlobals.coverageInterval` is `-1` and so `MP` is not getting messaged in that AbstractChecker method.  I have no idea what that means, but i'll determine it.

**Comment by lemmy** [comment]
You can set the coverage parameter (see tlc2.TLC) via the ctor of your test (derived from tlc2.tool.liveness.ModelCheckerTestCase.setUp()).

**Comment by quaeler** [comment]
Done - thanks

**Comment by lemmy** [comment]
I pushed your change to master for it to show up in the [performance comparison](https://tla.msr-inria.inria.fr/performance/). Lets find out if it has a negative performance impact.

**Comment by quaeler** [comment]
What a great resource.

I haven't bookmarked the build page for the project and with no open PRs i don't have a known way to get to them. Could you link in the build page so i know when i can expect to see the performance chart updated?

**Comment by lemmy** [comment]
The Jenkins page is currently not public. I will think about opening it up.

**Comment by lemmy** [comment]
[Build id #48](https://tla.msr-inria.inria.fr/performance/) and onwards contain commit fb99862.

**Comment by quaeler** [comment]
I'm reading that performance page wrong - i would have thought a greater Y value blue dot and lesser Y value blue plus would have meant greater throughput and less runtime.

I don't know what those 4 values represent, but a 6% - 30% worse performance seems like something we shouldn't let float by; will do something about this.

**Comment by lemmy** [comment]
The reason why the webpage doesn't reflect the performance degradation is caused by the fact that the underlying tests currently disable coverage statistics. I will do something about it soon.

**Comment by quaeler** [comment]
I made a version of this which uses a ~sparse 3 dimensional object array (variable location, tree node start column, tree node start line) instead of HashSets here: https://github.com/quaeler/tlaplus/commit/63a23ec0f763c704382c41ca1fb43b1791fec7c0

The performance in speed tests (via mucking with the associated unit tests) has HashSet crushing the object array for small N (like N = 5000) - store is around 4ms v. 20ms - and i've got to believe that for all reasonable formulas in real-world modules, we're talking N << 5000 ((N <<<<<<<< 5000.))

Could you try [removing the `synchronized`](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/tool/TLCStateMutSource.java#L72) only and seeing the performance metrics (these instances don't appear to be being used concurrently anyway;) perhaps it's that synchronization that's killing performance and not the HashSet.

If it's still looking bleak, i'll do a different structure approach.

**Comment by quaeler** [comment]
With https://github.com/quaeler/tlaplus/commit/116dc25f73dcb6015b71c2a5cacabc3fbc13c728 i changed from a single HashSet to a class which more faithfully reproduced the previous storage into `Set<SemanticNode>[]` - it still performed better than the 3-d ~spare object array, but less Usain Bolt 2009, more Usain Bolt 2017.

I also included "tests" which compared insert performance in the synchronized and unsynchronized variants; the expected slowdown was seen to be ~1.5x-2.5x.

**Comment by lemmy** [comment]
https://tla.msr-inria.inria.fr/performance/ shows that fb99862c09cedf0bb02c59faeaddd6ca55c89bba does **not** negatively impact performance. However, the [Paxos](https://github.com/tlaplus/tlaplus/tree/master/general/performance/PaxosCommit) and [Grid5k](https://github.com/tlaplus/tlaplus/blob/master/general/performance/Grid5k.tla) specs might not be the most representative ones due to small numbers of variables.

**Comment by quaeler** [comment]
Thank you for doing the legwork to assess that; not that i think it should impact the acceptance of this (unless your answer is several times the magnitude of what i'm expecting, in which case it might give me pause) but in your knowledge of people's spec writing, what is a rough upper bound of variable count seen in practice?

**Comment by quaeler** [comment]
In doing the oh-so-exact test of code timing, with 5000 semantic nodes, varying variable count from 15 - 150, there is no detectable storage timing impact:
```
For potentially 15 variables and 5000 semantic nodes
	storage took: 3 ms
	retrieval took: 1 ms
For potentially 30 variables and 5000 semantic nodes
	storage took: 4 ms
	retrieval took: 4 ms
For potentially 45 variables and 5000 semantic nodes
	storage took: 3 ms
	retrieval took: 1 ms
For potentially 60 variables and 5000 semantic nodes
	storage took: 5 ms
	retrieval took: 2 ms
For potentially 75 variables and 5000 semantic nodes
	storage took: 4 ms
	retrieval took: 0 ms
For potentially 90 variables and 5000 semantic nodes
	storage took: 1 ms
	retrieval took: 1 ms
For potentially 105 variables and 5000 semantic nodes
	storage took: 2 ms
	retrieval took: 1 ms
For potentially 120 variables and 5000 semantic nodes
	storage took: 2 ms
	retrieval took: 0 ms
For potentially 135 variables and 5000 semantic nodes
	storage took: 1 ms
	retrieval took: 0 ms
For potentially 150 variables and 5000 semantic nodes
	storage took: 1 ms
	retrieval took: 0 ms
------------------------
For potentially 15 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 0 ms
For potentially 30 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 1 ms
For potentially 45 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 0 ms
For potentially 60 variables and 5000 semantic nodes
	synchronized storage took: 3 ms
	retrieval took: 3 ms
For potentially 75 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 0 ms
For potentially 90 variables and 5000 semantic nodes
	synchronized storage took: 1 ms
	retrieval took: 2 ms
For potentially 105 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 0 ms
For potentially 120 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 1 ms
For potentially 135 variables and 5000 semantic nodes
	synchronized storage took: 5 ms
	retrieval took: 1 ms
For potentially 150 variables and 5000 semantic nodes
	synchronized storage took: 2 ms
	retrieval took: 0 ms
```

**Comment by lemmy** [comment]
Obsolete due to f11c4ad92b0cdb5c3b1d918055c17bf64c8b0a93
