### ISSUE TITLE
Is TLA+ the right tool for protocol parsing?

### ISSUE THREAD

**Issue by mkravchik** [tlaplus/tlaplus#923]
This is a question to the TLA+ experts. I need to write code for network protocol messages' correctness and validity. I want to make sure I get everything correct. Is TLA+/PlusCal the right tool for the job? Are there any examples of applying it to similar tasks?

**Comment by lemmy** [comment]
Please check out the [TLA+ Examples repository](https://github.com/tlaplus/Examples/).

**Comment by mkravchik** [comment]
Is there any specific example that deals with protocol parsing there?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
