### ISSUE TITLE
tla2tex.TeX: overly restrictive \begin{document} requirement & \input support

### ISSUE THREAD

**Issue by vincent-hugot** [tlaplus/tlaplus#924]
Hello,

Large TeX documents are often structured with lots of \input s, but this is not supported by tla2tex.TeX:

If called on inputed file:
> TLATeX unrecoverable error: -- Input file has no \begin{document}

If called on main file: \input and \include are not recognised and followed, so nothing happens.

Needless to say, the tool does not _actually_ need to know where \begin{document} is to find tla environments and do its job...

... yet this check is unskippable: the logic is around here:

https://github.com/tlaplus/tlaplus/blob/72c23c95cbf1ae61908628d9dd65b712f1e4e2e0/tlatools/org.lamport.tlatools/src/tla2tex/TeX.java#L183

I don't get the point of that preamble logic, by the way; why would there be a tla env in the preamble in the first place? Why does it matter that it's not translated when in the preamble? It's kinda neat that you can store tla envs in the pre/postambles, I guess, but why does that matter _more_ than supporting sensibly structured documents with \input? No idea.

As a workaround for my personal use, I'll just write a small script to wrap the file in \begin \end document, call the utility, and then remove the extra lines. That should work.

Ideally the tool should be patched 
 - to follow \input and \include
 - to make the {document} logic conditional: IF there is a {document} env THEN do what you do ELSE translate everything.

Do you agree that the tool should ideally behave that way?

If so, if a pull request to that effect were to be submitted in a couple of months, would you be willing to consider it? (I have some student projects coming up shortly --- this could be a nice exercise for them)

(I'd also like to add support for an \inputTLA command equivalent to putting the contents of a .tla file in a {tla} env, but that's a separate feature request).

**Comment by lemmy** [comment]
You can put a *commented* `\begin{document}` and `\end{document}` in each .tex file that you include with `\input`.  Then run `tla2tex.TeX` on each .tex file individually:

```tex
% \begin{document}

\begin{tla}

TRUE \* Your TLA+ formula here

\end{tla}

% \end{document}
```

**Comment by lemmy** [comment]
> (I'd also like to add support for an \inputTLA command equivalent to putting the contents of a .tla file in a {tla} env, but that's a separate feature request).

I would find a new `\inputTLA` command more useful than changing/expanding the existing one.

**Comment by vincent-hugot** [comment]
Ok.

I'll open a small student project around TLA and LaTeX, starting with \inputTLA, because it should be fairly simple. If that works out fairly well, there'll be a PR.

After that, personally I'd be more interested in the following approach:
- write a simpler alternative to TeX.java that _just_ eats a TLA fragment and outputs the corresponding LaTeX in a separate file. 
- write a LaTeX package so that {tla} envs call that utility (with shell-escape) on their contents and \input the resulting {tlatex} env.

Something like [gnuplottex](https://ctan.org/pkg/gnuplottex?lang=en) seems to work in a similar way.

Pros:
- Let LaTeX itself worry about parsing \begin{document}s, \input, \include, comments, etc.
- Don't pollute the .tex files (and the git diffs!) with generated code.
- no manual preprocessing phase required of the user

Cons:
- shell-escape...
- stuff like `lineWidths[envNum]` and alignments may be harder to do.

**Comment by lemmy** [comment]
@vincent-hugot Please reopen to indicate ongoing/active work.
