### ISSUE TITLE
Crash when opening "Web Browser" preferences menu

### ISSUE THREAD

**Issue by Hi-Angel** [tlaplus/tlaplus#927]
## Description

`tla+toolbox` crashes while opening various menus. It was crashing on me while trying to import an example project *(but it seems this menu is only accessible on the first start, so I can't report)*, and it crashes upon opening `Web Browser` preferences menu.

It may be a problem in "adoptium", judging by the text in the stacktrace, however the text also claims the version to be `14.0.1+7`, whereas [the latest adoptiium is 21.0.3+9](https://adoptium.net/temurin/releases/). The `14.0.1` hasn't been supported for a looong time.

So until it's updated it is a TLA+ bug and not Adoptium's.

## Expected Behavior

The menu opens

## Actual Behavior

`tla+toolbox` crashes with the following stack:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000076d414a36f48, pid=1145680, tid=1145681
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (14.0.1+7) (build 14.0.1+7)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (14.0.1+7, mixed mode, sharing, tiered, compressed oops, parallel gc, linux-amd64)
# Problematic frame:
# C  [libswt-gtk-4940r23.so+0x36f48]  Java_org_eclipse_swt_internal_C_strlen+0xf
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/constantine/Projects/builds/tla-toolbox-nightly/core.1145680)
#
# An error report file with more information is saved as:
# /home/constantine/Projects/builds/tla-toolbox-nightly/hs_err_pid1145680.log
Compiled method (n/a)   52429 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
Compiled method (n/a)   52429 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
Compiled method (n/a)   52430 4877     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x000076d441d25410,0x000076d441d25798] = 904
 relocation     [0x000076d441d25568,0x000076d441d25598] = 48
 main code      [0x000076d441d255a0,0x000076d441d25790] = 496
 oops           [0x000076d441d25790,0x000076d441d25798] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

## Steps to Reproduce
1. Open menu `File → Preferences → General → Web Browser`

## Your Environment
 - TLC version: 2.15
 - Toolbox version: 1.8.0
 - Operating System: Archlinux

**Comment by Hi-Angel** [comment]
@lemmy why "can't fix"? 😊 Sounds a bit contradicting to "help wanted"

**Comment by lemmy** [comment]
@Hi-Angel "can't fix" is the label we use to indicate that we only have the bandwidth to review a ready-to-merge PR, but can't work on the issue ourselves.

**Comment by lemmy** [comment]
Related to if not duplicate of https://github.com/tlaplus/tlaplus/issues/927

**Comment by Hi-Angel** [comment]
Good point, it definitely is a duplicate. The other report seems to lack the crash information though, will add in a minute
