### ISSUE TITLE
Unicode operators break PlusCal

### ISSUE THREAD

**Issue by Hi-Angel** [tlaplus/tlaplus#928]
## Description

So, I'm following tutorials, and am trying some PlusCal code. One thing I really liked so far about TLA+ is it allows to enter everything with unicode, so `∈` instead of `\in`, `∧` vs `/\`, etc. I have [Compose key set up](https://github.com/kragen/xcompose/blob/master/dotXCompose), so entering math symbols is trivial.

But for some reason in PlusCal code this breaks.

## Expected Behavior

No errors

## Actual Behavior

Error <code>Unrecoverable error:  -- Illegal lexeme `∈' found at line 6, column 16</code>

## Steps to Reproduce
1. In a new Spec paste the following code:
    ```haskell
    ------------------------------ MODULE scratch ------------------------------

    EXTENDS Integers, Sequences, TLC

    (*--algorithm noop
      variable seq ∈ 1..3;
    begin
      Iterate:
        skip;
    end algorithm; *)

    =============================================================================
    ```
2. Translate PlusCal algorithm by pressing <kbd>Ctrl</kbd>+<kbd>t</kbd>

## Your Environment
 - TLC version: 2.15
 - Toolbox version: 1.8.0
 - Operating System: Archlinux

**Comment by Calvin-L** [comment]
I expect this will be fixed by #911.
