### ISSUE TITLE
Unable to fully select error message

### ISSUE THREAD

**Issue by Hi-Angel** [tlaplus/tlaplus#929]
## Description

While reporting https://github.com/tlaplus/tlaplus/issues/928 I found that for some unknown reason tlabox splits translation error messages to multiple widgets, and you can't copy complete message all at once e.g. for purposes of creating a bug or messaging to someone.

Here's a funny screenshot: you can see inside a single error message there are 3 unrelated selections:

![Screenshot_20240529_210337](https://github.com/tlaplus/tlaplus/assets/7935057/b7c9fe10-ea82-4397-bf24-0e2014fff9b2)

## Expected Behavior

You succeed

## Actual Behavior

You only manage to select a single line.

## Steps to Reproduce
1. In a new Spec paste the following code:
    ```haskell
    ------------------------------ MODULE scratch ------------------------------

    (*--algorithm noop
    error
    end algorithm; *)

    =============================================================================
    ```
2. Translate PlusCal algorithm by pressing <kbd>Ctrl</kbd>+<kbd>t</kbd>
3. Once a window with error pops up on the right, try selecting the complete error.

## Your Environment
 - TLC version: 2.15
 - Toolbox version: 1.8.0
 - Operating System: Archlinux

**Comment by lemmy** [comment]
Unfortunatey, we don't have the resource to work on this.  Please provide a  ready-to-merge Pull Request.

**Comment by Hi-Angel** [comment]
@lemmy yeah, it was pointed by `help wanted` tag. But why you closed the issue?

**Comment by lemmy** [comment]
@Hi-Angel This has been the workflow so far to manage the number of open issues (there are still too many).
