### ISSUE TITLE
Is there a formatter for tlaplus/pluscal that can be run in the CLI?

### ISSUE THREAD

**Issue by YuMuuu** [tlaplus/tlaplus#941]
I think I need a formatter for continuous development, so I would like to check the format in CI. However, after searching I only found the vscode plugin formatter.
Please let me know if you have a good solution.
thank you.

**Comment by ahelwer** [comment]
No such formatter exists. Creating one would be a large undertaking but is sure to be greatly appreciated by the community. You could use either the parse tree emitted by SANY in this repo or the one emitted by [the TLA⁺ tree-sitter grammar](https://github.com/tlaplus-community/tree-sitter-tlaplus/).

**Comment by YuMuuu** [comment]
thank you for replay. I will try to create one based on the contents of the link.　I've confirmed that there is no formatter for this issue, so I'm closing it.


By the way, I am trying to create: https://github.com/YuMuuu/prettier-plugin-pluscal
