### ISSUE TITLE
Establish monthly maintainer office hours virtual meeting

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#945]
As discussed during the last monthly community meeting.

I think it would be a good idea to establish a monthly maintainer office hours virtual meeting to run on a half-month alternation with the monthly community meeting. The meeting would have the following objectives:
1. Get all maintainers & developers in a synchronous meeting to finalize merging or rejecting PRs, or collaborate on a review in real time
2. Make maintainers & developers available to answer queries from new developers trying to onboard
3. Discuss general tools development aims, priorities, and problems

Reasons for establishing this meeting:
* Often tools development talk can dominate the monthly community meeting and cause it to run over time or take away time from more community-focused discussion topics
* It would be nice to have a monthly sync to clear out PRs that have continued to trundle along un-merged/closed due to lack of forcing function
* Improve developer onboarding mentorship experience

The monthly community meeting is on the second Tuesday of each month at 8 am PT/11 am ET; I suggest this meeting could be scheduled for the same time on the fourth Tuesday of each month. I am happy to commit to attending this meeting.

**Comment by Calvin-L** [comment]
Certainly---but I am not a morning person, and I'll push for 9 or 10am PT if I can. 😆

**Comment by ahelwer** [comment]
Either of those times work for me.

**Comment by lemmy** [comment]
Perhaps, alternate because early and late meeting to accommodate different geos.

**Comment by ahelwer** [comment]
It appears the fourth Tuesday of every month is actually already occupied with a TLA+ Foundation board meeting (marked as "busy" on the calendar), so this meeting should be on the fourth Thursday of every month instead.

If we have the meeting at 10 am PT, that will put it at 1 pm ET and 4 pm CET which hopefully captures @damiendoligez and @muenchnerkindl if they want to join. Although currently CEST is in use which means it would be 5 pm. India and China geos will have to go unserved at this time.

@damiendoligez and @muenchnerkindl what times work for you? Would you want to do alternating early/late meetings where you can catch the early one every two months? Don't want to push into your evening times.

**Comment by FedericoPonzi** [comment]
I'm in BST timezone.

**Comment by muenchnerkindl** [comment]
10 am works for me, but Thursdays are difficult. I believe we could still use the fourth Tuesday of every month.

@lemmy ?

**Comment by muenchnerkindl** [comment]
I spoke too fast. 10am PST corresponds to 7pm CEST, I'd really prefer one or two hours earlier (as the Community call).

**Comment by ahelwer** [comment]
Okay so how about this:

- Meeting is on fourth *Wednesday* of every month so as to not conflict with the board meeting on the fourth Tuesday of every month and to not conflict with @muenchnerkindl's commitments on Thursday
- Meeting alternates monthly between early (same time as community meeting) and late with a two hour shift (see table below)
- The first meeting will be a *late* meeting on Wednesday, June 26th, 2024, to be followed by an early meeting on Wednesday, July 24th, 2024 and so on

Here is a table of time values; hopefully I did the conversions correctly this time:

| Variation | PDT | EDT | BST | CEST |
|-------------|------|-----|--------|----------|
| Early      |  8 am | 11 am | 4 pm | 5 pm |
| Late       | 10 am | 1 pm | 6 pm | 7 pm |

If nobody objects to this then we can add it to the same calendar as the community meeting. I believe the calendar is administered by Markus. I'm sure there will be confusion as we switch off of summer time but hopefully the google calendar will handle that for us.

**Comment by lemmy** [comment]
We should consider on-demand meetings, similar to those done by the [Servo project](https://github.com/servo/project/issues/92).

**Comment by ahelwer** [comment]
This does not seem necessary for now.
