### ISSUE TITLE
SANY should output command line help text

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#947]
Related to #783.

SANY should output help text for its command line parameters in the following cases:

1. No parameters are given
2. Incorrect or unrecognized parameters are given

Currently the only way to figure out how the SANY command line parameters work is to read the code that processes them.

There is a `-help` parameter, but the documentation it prints out is incomplete. Also, it does not document the debug spec explorer shell commands.

**Comment by FedericoPonzi** [comment]
Though SANY supports -help:
```
java -cp ./dist/tla2tools.jar tla2sany.SANY -help

NAME

        SANY - provides parsing, semantic analysis, and level-checking for a TLA+ spec - Version 2.2 created 08 July 2020


SYNOPSIS

        SANY [-ls] [-error-codes] [-stat]
        SANY [-ls] [-error-codes] [-stat]

DESCRIPTION

        SANY is a parser and syntax checker for TLA+ specifications.
        It catches parsing errors and some "semantic" errors such as
        priming an expression containing primed variables.

OPTIONS

        -error-codes
                If enabled, error level will be reported as the tools'
                return value.
        -l
                Turns off level checking. Level checking won't be
                used, if the semantic analysis is disabled. 
        -s
                Turns off semantic analysis
        -stat
                Turns off reporting statistics about builtin operator
                usage.
```
It's incomplete but most of the parameters are there

**Comment by ahelwer** [comment]
Thanks for checking! I think I remembered being able to get it to print some things but not others (in particular dumping the parse tree, which I often use). This existing functionality will make implementing this fix a lot easier.

**Comment by MathieuBordere** [comment]
I'll take a stab at this one as suggested by @ahelwer via lobste.rs

**Comment by MathieuBordere** [comment]
`-help` would now output the following, still need to take a look at the `Semantic Graph Explorer` options.

- added -d option.
- minor rewording of existing options.
- added mandatory `FILE...` argument.

```
NAME

	SANY - provides parsing, semantic analysis, and level-checking for a TLA+ spec - Version 2.2 created 08 July 2020


SYNOPSIS

	SANY [-dls] [-error-codes] FILE...

DESCRIPTION

	SANY is a parser and syntax checker for TLA+ specifications.
	It catches parsing errors and some "semantic" errors such as
	priming an expression containing primed variables.

OPTIONS

	-d
		Opens the semantic graph exploration prompt for debugging.
	-error-codes
		The tools' return value will be the error-level.
	-l
		Turns off level-checking.
	-s
		Turns off semantic analysis and level-checking.
```

**Comment by ahelwer** [comment]
Looks pretty good, I would just reword `-error-codes` to be something like "Return nonzero exit code on parse error" or similar.
