### ISSUE TITLE
Lock and unlock of model broken

### ISSUE THREAD

**Issue by quaeler** [tlaplus/tlaplus#95]
(This is with the latest Toolbox code)

I don't know if this is a really long running TLC instance or because i have it paused in the debugger for long periods of time, but the observed behavior is that once TLC finishes and the Toolbox displays the result, the model stays locked:
* the title on all three tabs of the model editor part include "( model is locked )"
* on the Model Overview tab, all UI widgets except the unlock key are disabled
* clicking on the unlock key enables the radio buttons in the "What is the behavior spec?" section and nothing more (not the EP tool bar icons (exception the unlock key staying enabled), not the Deadlock checkbox, ...) The "( model is locked )" remains as well.
* Closing the editor pane tab and then reopening the model renders it as in the same state.
* Quitting the Toolbox and restarting shows the model as unlocked

**Comment by lemmy** [comment]
Functionality is generally broken (even if one manually locks a model).

This is definitely a regression which is most probably best found with git bisect.

**Comment by quaeler** [comment]
Will pick it up after #92 unless you beat me to it.

**Comment by lemmy** [comment]
The problem appears to be that the model gets locked but the unlock button remains disabled (a user cannot unlock the model). The disablement of the button might be (yet another) regression as a consequence of the recent upgrade to Eclipse 4.7.

The fact that the model editor has two buttons (lock & unlock) rather than a single one with state has always been a nuisance.

**Comment by quaeler** [comment]
Hmmm.. so with the 1.5.4 release, if i click on the lock button, the model doesn't lock and no UI widgets are affected (at least in terms of their enable state.)  This occurs also with basically the latest repository code.

When the above reported long running / paused in debug locking happens, the unlock button does become enabled; clicking on it does not disable it nor enable the lock button.

**Comment by lemmy** [comment]
We should/could consider removing _model locking_ altogether in favor of the newly introduced _model snapshot_ functionality. The latter is off by default but can be activated via _Preferences > TLA+ Preferences > TLC Model Checker > Take Snapshot of model..._

**Comment by quaeler** [comment]
Could you give the 50k foot blurb on why we have model locking? I see that it gets turned on while TLC is executing perhaps to avoid mixed states, or something, but aside from that, what is the use case for having a locked model?

**Comment by lemmy** [comment]
The idea is that one doesn't accidentally rerun TLC and thus lose the previous results (of a long running execution). This is exactly what the new snapshot functionality addresses, but better.

**Comment by quaeler** [comment]
For some reason, my _Take snapshot of model..._ is ticked on, though i've never touched it (i was noticing that after the upgrade from 1.5.3 -> 1.5.4, what i was calling "runs" and will now call "snapshots" were being listed as children elements of my model in Spec Explorer tree view and assumed it was automatically applied new 1.5.4 functionality.)

Do we really want it off by default (if it is coded that way)?

**Comment by lemmy** [comment]
You are right, it is on by default (https://github.com/tlaplus/tlaplus/blob/master/org.lamport.tla.toolbox.tool.tlc.ui/src/org/lamport/tla/toolbox/tool/tlc/ui/preference/TLCPreferenceInitializer.java).

Assuming nobody complains about this functionality and we can consider the feature working, I'm even more inclined to simply remove _model-locking_.

**Comment by quaeler** [comment]
I second the motion to remove model-locking; i'd also vote for removing the ability to turn on-and-off snapshotting in the preferences.

**Comment by lemmy** [comment]
Your comment about "snapshot" vs. "runs" made me think about terminology. Upfront the term "runs" is indeed more intuitive. However, "runs" hides the fact that the Toolbox not only keeps the result of the model run but also takes a snapshot of the spec as it were at the time of TLC startup. The latter is apparently easily missed and might require better UI support (open Snapshot and then TLC Model Checker > Open Saved Module. It opens a tab on the model editor). For snapshots, the Toolbox could open the "saved module" automatically.

Related, diff support for snapshots would be a handy feature. Infrastructure is already in place to diff revisions of a spec, but the Toolbox lacks support to diff models (non-textually).

Last, I can see that users wish to only keep a fixed number of snapshots and discard older ones automatically. Thus, the corresponding preference should be changed from on/off to a spinner that defines how many snapshots should be kept with zero meaning no snapshots.

**Comment by quaeler** [comment]
Yes, we should make it more clear that these snapshots contain the spec at time of run, as well. ... and the 2nd and 3rd paragraphs are also good ideas.

I will make additional issues capturing these ideas.

**Comment by lemmy** [comment]
Lets remove model locking/unlocking in the next release.
