### ISSUE TITLE
Deleting TLAPS Fingerprints from Toolbox

### ISSUE THREAD

**Issue by matthias-g** [tlaplus/tlaplus#963]
Is there a way to delete the TLAPS fingerprints from within the toolbox?

[This document](https://lamport.azurewebsites.net/pubs/toolbox.pdf) says that there exists such an option, however, I did not find such an option in version 1.8.0 of the toolbox.

The reason why I would find this useful is that I've encountered a situation where TLAPS fails to prove simple theorems. After deleting the TLAPS fingerprints, the proofs succeed.

**Comment by lemmy** [comment]
@matthias-g Please consider opening an issue at https://github.com/tlaplus/tlapm/issues about the underlying problem.

The editor's context menu (`TLA Proof Manager > Launch Prover...`) opens the following dialog where you can select `Forget all previous results`.  Does this have the desired effect?

<img width="832" alt="image" src="https://github.com/tlaplus/tlaplus/assets/88777/acf80fa2-e472-4c1c-98a1-baf71e971273">

**Comment by matthias-g** [comment]
Perfect, thank you!
