### ISSUE TITLE
Running liveness checking with multiple workers can cause unsoundness: TLC fails to report a violation of a property

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#971]
```tla
---- MODULE Github710 ----
VARIABLE x

Init ==
    x = FALSE

Next ==
    x' \in BOOLEAN 

Spec == 
    /\ Init
    /\ [][Next]_x

AtMostOnce ==
    [](x => [](~x => []~x))
====
```

```
SPECIFICATION Spec
PROPERTY AtMostOnce
```

Observe that the `Spec` in `Github710` above does not define a fairness constraints.  Thus, some valid counterexamples to the property `AtMostOnce` are stuttering after some state (e.g. `vio1`), or a (prefix of a) behavior where `x` transitions from true, to false, to true (`vio2`):

### vio1
```tla
@lemmy ➜ /workspaces/tlaplus/tlatools (a401ad390) $  cd /workspaces/tlaplus/tlatools ; /usr/bin/env /opt/java/11.0.14/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:36251 -cp /workspaces/tlaplus/tlatools/class tlc2.TLC Github866.tla -workers 2 
TLC2 Version 2.03 of 10 March 2011
Running in Model-Checking mode.
Parsing file Github866.tla
Semantic processing of module Github866
Starting... (2024-06-22 23:23:44)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated.
Progress(2) at 2024-06-22 23:23:47: 5 states generated, 2 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space...
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = FALSE

State 2: Stuttering
5 states generated, 2 distinct states found, 0 states left on queue.
Finished. (2024-06-22 23:24:00)
```

### vio2
```tla
TLC2 Version 2.18 of Day Month 20?? (rev: c9dadac)
Running breadth-first search Model-Checking with fp 22 and seed -4588059740923214664 with 1 worker on 10 cores with 7282MB heap and 64MB offheap memory [pid: 44885] (Mac OS X 13.6.7 aarch64, Homebrew 11.0.23 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /Users/markus/src/TLA/tla/tlatools/org.lamport.tlatools/Github866.tla
Semantic processing of module Github866
Starting... (2024-06-22 16:42:06)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2024-06-22 16:42:06.
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = FALSE

State 2: <Next line 9, col 5 to line 9, col 18 of module Github866>
x = TRUE

State 3: <Next line 9, col 5 to line 9, col 18 of module Github866>
x = FALSE

State 4: <Next line 9, col 5 to line 9, col 18 of module Github866>
x = TRUE

5 states generated, 2 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 2.
Finished in 00s at (2024-06-22 16:42:06)
```

Since at least [2011](https://github.com/tlaplus/tlaplus/commit/a401ad39044e5014cb07a9588611041c1d55596d), verifying the `Github710` with two (or more) workers can result in TLC finishing without reporting a counterexample:

```
@lemmy ➜ /workspaces/tlaplus/tlatools (a401ad390) $  cd /workspaces/tlaplus/tlatools ; /usr/bin/env /opt/java/11.0.14/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:41763 -cp /workspaces/tlaplus/tlatools/class tlc2.TLC Github866.tla -workers 2 
TLC2 Version 2.03 of 10 March 2011
Running in Model-Checking mode.
Parsing file Github866.tla
Semantic processing of module Github866
Starting... (2024-06-22 23:24:06)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated.
Progress(2) at 2024-06-22 23:24:09: 5 states generated, 2 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space...
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 3.3E-19
  based on the actual fingerprints:  val = 1.1E-19
5 states generated, 2 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 2.
Finished. (2024-06-22 23:24:20)
```

```
-> % java -cp class tlc2.TLC -note Github866 -workers 2
TLC2 Version 2.18 of Day Month 20??
Warning: Please run the Java VM, which executes TLC with a throughput optimized garbage collector, by passing the "-XX:+UseParallelGC" property.
(Use the -nowarning option to disable this warning.)
Running breadth-first search Model-Checking with fp 48 and seed 5508516891815624630 with 2 workers on 10 cores with 8192MB heap and 64MB offheap memory [pid: 47210] (Mac OS X 13.6.7 aarch64, Homebrew 11.0.23 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /Users/markus/src/TLA/tla/tlatools/org.lamport.tlatools/Github866.tla
Semantic processing of module Github866
Starting... (2024-06-22 17:01:02)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2024-06-22 17:01:02.
Progress(2) at 2024-06-22 17:01:02: 5 states generated, 2 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space with 2 total distinct states at (2024-06-22 17:01:02)
Finished checking temporal properties in 00s at 2024-06-22 17:01:02
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 3.3E-19
5 states generated, 2 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 2.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 1 and the 95th percentile is 1).
Finished in 00s at (2024-06-22 17:01:02)
```

This can occur if TLC follows the following worker (thread) schedule, leading it to incorrectly report that the specification satisfies `AtMostOnce`.

```tla
1. w1 pops x=FALSE from state queue
2. w2 blocks on the empty state queue
3. w1 pushes x=TRUE into the state queue (having evaluated Next for x=FALSE)
4. w2 pops x=TRUE from the state queue
5. w2 adds x=TRUE to the behavior graph before w1 adds x=FALSE to the graph
```

This issue was [initially discovered](https://github.com/tlaplus/tlaplus/issues/866#issuecomment-2176511930) by @FedericoPonzi when reproducing Github issue #866 by repurposing a spec from Github issue #710.  However, Github #866 is an issue where TLC may report a counterexample when the `RandomElement` operator is used.  Moreover, the [relevant code](https://github.com/tlaplus/tlaplus/blob/90245f32b67b8928eab46ec92294a9a6936b140d/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck.java#L601-L909) is not for the issue above is not exercised by Github issue #866 (regardless of `SpanTreeRandom!Safety` being checked as an invariant or property).

**Comment by lemmy** [comment]
# v1.4.9 6639bd91f
```tla
@lemmy ➜ /workspaces/tlaplus (6639bd91f) $ java -cp tlatools/class:tlatools/lib/javax.mail.jar tlc2.TLC Github866.tla
TLC2 Version 2.05 of 23 July 2013
Running in Model-Checking mode.
Parsing file Github866.tla
Semantic processing of module Github866
Starting... (2024-06-23 02:46:00)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated.
Checking temporal properties for the complete state space...
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = TRUE

State 2: <Action line 9, col 5 to line 9, col 18 of module Github866>
x = FALSE

State 3: Stuttering
5 states generated, 2 distinct states found, 0 states left on queue.
Finished. (2024-06-23 02:46:00)
```

# v1.5.0 d49729bb2
```tla
@lemmy ➜ /workspaces/tlaplus (d49729bb2) $ java -cp tlatools/class:tlatools/lib/javax.mail.jar tlc2.TLC Github866.tla
TLC2 Version 2.06 of 9 May 2015
Running in Model-Checking mode.
Parsing file Github866.tla
Semantic processing of module Github866
Starting... (2024-06-23 02:45:38)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated.
Checking temporal properties for the complete state space with 2 distinct states at (2024-06-23 02:45:38)
Checking temporal properties for the current state space with 2 distinct states at (2024-06-23 02:45:38)
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = TRUE

State 2: <Action line 9, col 5 to line 9, col 18 of module Github866>
x = FALSE

State 3: <Action line 9, col 5 to line 9, col 18 of module Github866>
x = TRUE

State 4: <Action line 9, col 5 to line 9, col 18 of module Github866>
x = FALSE

State 5: Stuttering
5 states generated, 2 distinct states found, 0 states left on queue.
Finished. (2024-06-23 02:45:39)
```

**Comment by craft095** [comment]
This is interesting issue. `[](x => [](~x => []~x))` is a safety property. Therefore, any stuttering-like counterexample is invalid one. The correct counterexample should be: FALSE, TRUE, FALSE, TRUE, which is minimal and finite.

**Comment by lemmy** [comment]
> This is interesting issue. `[](x => [](~x => []~x))` is a safety property. Therefore, any stuttering-like counterexample is invalid one. The correct counterexample should be: FALSE, TRUE, FALSE, TRUE, which is minimal and finite.

Agreed: https://github.com/tlaplus/tlaplus/commit/b740eef4056fdf58d664cf495bbcb2588e93eba8#diff-edd1211b4ce3ff9ab7692c42399f066338f5bc153939bc7268b8a007ce8ac730R78-R94

**Comment by lemmy** [comment]
## Behavior graphs

`vio2` is found (left), `vio2` is missed (right)

![BehaviorGraph svg](https://github.com/tlaplus/tlaplus/assets/88777/b7793118-d78d-4cf3-b519-bb95ef5e6840)


## Tableau graph (same as in https://github.com/tlaplus/tlaplus/issues/710#issuecomment-1023580446)
![TBGraph svg](https://github.com/tlaplus/tlaplus/assets/88777/eee28748-e2ac-4ec6-a2c9-ac83c79dc215)

**Comment by lemmy** [comment]
With multithreaded TLC, successor states may be added to the behavior graph before their predecessor state, leading to the omission of these successor states from the graph. This situation occurs when a worker `w_t` dequeues state `t` from the state queue and adds`t` to the behavior graph in the time between worker `w_s` enqueuing `t` in the state queue and adding `s` to the behavior graph. The omission of state `t` in the behavior graph can cause TLC to miss violations of temporal properties. Ignoring unusually shaped state graphs, such as a single behavior (think a counter spec), the probability of omitting `t` is particularly high at the beginning of the model checking process when the state queue is empty or nearly empty.

**Comment by lemmy** [comment]
I plan to send the following announcement to the TLA+ Google group later today. Please provide your feedback if you have any suggestions.

/cc @muenchnerkindl @xxyzzn @cnewcom

------

Federico Ponzi has identified a soundness bug in TLC that affects the verification of temporal properties, when TLC is configured with more than the default number of worker threads. This bug has existed since at least 2009 and possibly since the the verification of temporal properties was first introduced.

The bug is caused by a concurrency issue in TLC, and we consider the likelihood of encountering this bug to be very low.  However, it remains a critical issue that needs to be addressed.

For immediate mitigation, please check temporal properties using only a single worker (command line flag: `-workers 1`).  By default, TLC runs with a single worker.

We are working on a fix and will release a new version of TLC once the bug is resolved.  Announcements regarding the new release will be made here.  For technical details or to offer assistance, please refer to the GitHub issue at https://github.com/tlaplus/tlaplus/issues/971.

**Comment by muenchnerkindl** [comment]
Sounds good to me, thanks!

**Comment by craft095** [comment]
@lemmy does this bug affects the following kinds of properties:

1. Invariants and invariant-like properties ([] <state predicate>)
2. Action properties

Or we can assume that those are still checked correctly even if there are many workers?

> With multithreaded TLC, successor states may be added to the behavior graph before their predecessor state, leading to the omission of these successor states from the graph. This situation occurs when a worker `w_t` dequeues state `t` from the state queue and adds`t` to the behavior graph in the time between worker `w_s` enqueuing `t` in the state queue and adding `s` to the behavior graph. The omission of state `t` in the behavior graph can cause TLC to miss violations of temporal properties. Ignoring unusually shaped state graphs, such as a single behavior (think a counter spec), the probability of omitting `t` is particularly high at the beginning of the model checking process when the state queue is empty or nearly empty.

**Comment by lemmy** [comment]
@xxyzzn pointed out that the default number of workers is half the computer's cores when TLC is run from the Toolbox.

**Comment by lemmy** [comment]
Let `P` and `Q` be state predicates and let `A` be an action.

| property | [invariant check](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java#L552-L581) | [implied action](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java#L583-L614) | implied temporal | [tableau](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveCheck.java#L571-L909) | [scc](https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/LiveWorker.java#L149-L474) | note  | 
|---------           | ----- | -----| ------ | -----|  ----- | ----- |
| `INVARIANT P`                 |    +   |   |   |   |   |   | 
| `[]P`                 |    +   |   |   |   |   |   | 
| `<>P`               |          |    | +  |  + | + |  | 
| `[]<>P`            |          |    |  + |   |  + |  | 
| `<>[]P`            |          |    |  + |   |  + |  | 
| `[][A]_v`   |          |  +  |  |   |   | Refinement | 
| `<>[A]_v`   |          |    |   |   |    | SANY `<> followed by action not of form <<A>>_v` |
| `[]<<A>>_v`   |          |    |   |   |   | SANY `[] followed by action not of form [A]_v.` | 
| `<><<A>>_v`   |          |    | +  |   |   |  TLC `Error: Temporal formulas containing actions must be of forms <>[]A or []<>A.` |
|    `[]<>[A]_v`           |        |   |   |   |   | SANY `<> followed by action not of form <<A>>_v.` | 
|    `<>[][A]_v`          |        |   |  + |   |  + |  | 
|    `[]<><<A>>_v`    |        |   |  + |   |  + |  | 
|    `<>[]<<A>>_v`    |        |   |   |   |   | SANY `[] followed by action not of form [A]_v.` | 
|    `P ~> Q`    |        |   |  + |  + | +  |  | 
|    `[](P => []Q))`    |        |   |  + |  + |   |  | 
|    `[](x => [](~x => []~x))`    |        |   |  + |  + |   |  |

**Comment by lemmy** [comment]
Still work in progress but this appears to be a fix:

```diff
--- a/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/TableauDiskGraph.java
+++ b/tlatools/org.lamport.tlatools/src/tlc2/tool/liveness/TableauDiskGraph.java
@@ -104,7 +104,12 @@ public class TableauDiskGraph extends AbstractDiskGraph {
         */
        public void recordNode(final long fp, final int tidx) {
                assert tidx >= 0;
-               this.nodePtrTbl.put(fp, tidx, TableauNodePtrTable.UNDONE);
+               final int[] nodes = this.nodePtrTbl.getNodes(fp);
+               if (nodes != null && nodes.length == 2) {
+                       this.nodePtrTbl.put(fp, tidx, TableauNodePtrTable.UNDONE - 1);
+               } else {
+                       this.nodePtrTbl.put(fp, tidx, TableauNodePtrTable.UNDONE);
+               }
        }

        /**
```

**Comment by lemmy** [comment]
The bug has been fixed in https://github.com/tlaplus/tlaplus/pull/972.  Feedback and reviews of the fix are welcome.

**Comment by lemmy** [comment]
This soundness bug has been fixed and the update is available in the [latest nightly build of the VSCode extension](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly). However, the Toolbox's nightly update mechanism seems to be malfunctioning; the link http://lamport.org/tlatoolbox currently returns a 404 error but should redirect to our Inria machine.

We have to decide if it's worth back-porting c61bad9a00b5be5f18e121c19ab885e90d0e6c01 to the v1.7.x maintenance branch.

**Comment by muenchnerkindl** [comment]
Hmm, is this link correct? Shouldn't it be something like https://tla.msr-inria.inria.fr/tlatoolbox/products/ or perhaps http://lamport.org/tla/toolbox.html?

**Comment by lemmy** [comment]
http://lamport.org/tlatoolbox has been an "internal" URL of the Toolbox's update manager for years:

https://github.com/tlaplus/tlaplus/blob/aa01a374f7d7dd96b3f03ebf43523e1bf9dae766/toolbox/org.lamport.tla.toolbox.product.product/org.lamport.tla.toolbox.product.product.product#L101-L104

https://github.com/tlaplus/tlaplus/blob/aa01a374f7d7dd96b3f03ebf43523e1bf9dae766/toolbox/org.lamport.tla.toolbox.product.standalone/src/org/lamport/tla/toolbox/preferences/AutomaticUpdatesPreferencePage.java#L81

We should consider replacing `lamport.org` with the foundation-controlled `tlapl.us`. Unfortunately, we need the old update manager to rollout this change.

**Comment by craft095** [comment]
> This soundness bug has been fixed and the update is available in the [latest nightly build of the VSCode extension](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus-nightly). However, the Toolbox's nightly update mechanism seems to be malfunctioning; the link http://lamport.org/tlatoolbox currently returns a 404 error but should redirect to our Inria machine.
> 
> We have to decide if it's worth back-porting [c61bad9](https://github.com/tlaplus/tlaplus/commit/c61bad9a00b5be5f18e121c19ab885e90d0e6c01) to the v1.7.x maintenance branch (the commit does _not_ apply cleanly when cherry-picking).

@lemmy thanks a lot for fixing the issue! From a commit message I got impression that the bug only manifests when liveness checking is involved. Is it correct that this does not affect simple safety properties ([] P, [][Q]_vars and their conjunctions)? 
(If this is not true, we will need to back-port this patch.)

**Comment by lemmy** [comment]
The zip files at https://github.com/tlaplus/tlaplus/releases/tag/v1.7.4 are draft maintenance releases containing this bug fix.  Please download and test them on your machines and provide feedback.  I have verified that the macOS version works on an M1 chip, but I do not have access to other types of machines for testing at the moment.

**Comment by craft095** [comment]
> The zip files at https://github.com/tlaplus/tlaplus/releases/tag/v1.7.4 are draft maintenance releases containing this bug fix. Please download and test them on your machines and provide feedback. I have verified that the macOS version works on an M1 chip, but I do not have access to other types of machines for testing at the moment.

v1.7.4 introduces no regression in handling simple safety properties in our tests. However, it still produces stuttering trace instead of minimal finite one for Github710:

```
TLC2 Version 2.19 of 08 August 2024 (rev: 5a47802)
Running breadth-first search Model-Checking with fp 82 and seed 3907847984833576780 with 1 worker on 24 cores with 27305MB heap and 64MB offheap memory [pid: 3420728] (Linux 6.5.0-35-generic amd64, Ubuntu 17.0.12 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /home/dkulagin/certification-test-suite-generator/bug/Github710.tla
Semantic processing of module Github710
Starting... (2024-08-13 11:26:15)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2024-08-13 11:26:15.
Progress(2) at 2024-08-13 11:26:15: 5 states generated, 2 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space with 2 total distinct states at (2024-08-13 11:26:15)
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = FALSE

State 2: <Next line 8, col 5 to line 8, col 18 of module Github710>
x = TRUE

State 3: <Next line 8, col 5 to line 8, col 18 of module Github710>
x = FALSE

State 4: <Next line 8, col 5 to line 8, col 18 of module Github710>
x = TRUE

State 5: <Next line 8, col 5 to line 8, col 18 of module Github710>
x = FALSE

State 6: Stuttering
Finished checking temporal properties in 00s at 2024-08-13 11:26:15
5 states generated, 2 distinct states found, 0 states left on queue.
Finished in 00s at (2024-08-13 11:26:15)
```

**Comment by lemmy** [comment]
> v1.7.4 introduces no regression in handling simple safety properties in our tests. However, it still produces stuttering trace instead of minimal finite one for Github710:

The issue #710 was not backported to the 1.7.x branch because it was deemed less critical.  Additionally, addressing #710 requires a more complex code change.  If we were to backport #710, we would also need to backport commit f84d85b00760feaab3e834bac8c5d9101dd907b3.
