### ISSUE TITLE
Style guide for new code

### ISSUE THREAD

**Issue by Calvin-L** [tlaplus/tlaplus#983]
We should provide (or link to) a style guide for new code (with a disclaimer that we aren't interested in reformatting old code).

The TLA+ source code exhibits a wide variety of code styles. We care much more about substance than style, but the variety can be distracting for new contributors.

I don't think we need to strictly enforce anything; it can be a loose style guide. But I hope that having something to reference will help gradually reduce the distracting variety.

**Comment by lemmy** [comment]
+1 for not enforcing it.

**Comment by ahelwer** [comment]
Does Java have a linter that we can enable on a per-file basis, so that newly-added files are subject to it then checked in the CI?

**Comment by Calvin-L** [comment]
Not as part of the JDK. [Spotless](https://github.com/diffplug/spotless) is popular, but it lacks Ant integration.
