### ISSUE TITLE
Remove macOS unit test runners from CI?

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#986]
macOS runners were added to the PR CI matrix in https://github.com/tlaplus/tlaplus/commit/e17d73066ec53e155b5f44048cb41aa3eaa6587e. The unit tests take [up to 40 minutes](https://github.com/tlaplus/tlaplus/actions/runs/9796820820/job/27052092077) to run on the github macOS runners, because those runners are incredibly slow. This is in contrast with ubuntu, where the unit tests take only 10 minutes to complete. This is a very long time to add for not very much additional value in testing. Should the macOS runners be removed from the PR CI matrix? Having a fast CI is important for developer experience.

**Comment by lemmy** [comment]
IIRC, macOS is our most popular platform. Although Linux and macOS share some similarities, there are also many differences between them.  Moreover, are the macOS runners a bottleneck when people work on PRs?

**Comment by ahelwer** [comment]
I submit that we are encountering the [endowment effect](https://en.wikipedia.org/wiki/Endowment_effect) here; if we could travel back in time to two weeks ago before this change was made and discuss whether macOS should be added, I think it would be quite a hard sell to multiply our CI validation time by four.

**Comment by lemmy** [comment]
We don't need psychology here.  We should prioritize macOS, our most popular platform, which has had specific issues in the past.  If test execution time on macOS *becomes* a bottleneck, we should use the larger macOS runners.

<img width="1122" alt="Screenshot 2024-07-08 at 1 03 23 PM" src="https://github.com/tlaplus/tlaplus/assets/88777/fc846dfd-328a-488b-a93a-228340b3dc64">

**Comment by Calvin-L** [comment]
I agree with @lemmy. MacOS is an important platform for us, and I've never found the current CI duration to be a blocker.

Is there a sensible target time for PR builds? For the main branch build? I would probably accept up to 6 hours, and I would grudgingly cope with up to 24. (It looks like the [current maximum job duration](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration) is 6 hours. We should revisit this if the MacOS tests start creeping close to that boundary.)

**Comment by ahelwer** [comment]
I submit that CI execution time is an issue when you are developing the CI itself, and if you run into an issue where some test or task is failing on the CI but it cannot be reproduced locally. I have spent a lot of time dealing with both of these across various projects, so 10 minutes (15 at the outside) seems ideal based on my experience. Anyway, what does it take to upgrade to more powerful macOS runners?

**Comment by lemmy** [comment]
money from the foundation.

**Comment by Calvin-L** [comment]
> CI execution time is an issue when you are developing the CI itself

I hope that will be an uncommon activity and not one we need to optimize for. You might look into whether something like [act](https://github.com/nektos/act) could give faster local feedback.

(I am reminded of a very good tweet from a friend of mine. It read something like "doing Software Engineering" and had a screenshot of a dozen or so commits like "fix workflows", "fix workflows again", "fix yaml syntax", "see if github likes this better", etc. It's a shame that "upload to GitHub and let it run" is the best way to tell if your workflows do what you expect.)

**Comment by ahelwer** [comment]
Your friend's tweet is relatable, and @lemmy experienced that recently as well. My personal experience is that if the CI takes 10-15 to run you can expect to be able to finish a change to it in one day. If it takes an hour to run I don't even want to think about how long it would take.

**Comment by lemmy** [comment]
Execution time of GitHub Actions is not a concern for me.  However, reviving the performance tests would be a compelling reason to purchase compute credits.
