### ISSUE TITLE
Why is `tlc2.tool.distributed.DieHardDistributedTLCTest` skipped?

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#989]
Maybe this is a small thing but it's confusing me. I found it when I was trying to inject some unit test failures. The `tlc2.tool.distributed.DieHardDistributedTLCTest` unit test is skipped and I can't figure out why; here's how it looks in the CLI log:
```
>ant -f customBuild.xml compile compile-test dist test
...
test:
     [echo] Running tests across 8 threads
    [junit] Running tlc2.tool.distributed.DieHardDistributedTLCTest
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.064 sec
```
and if I put a `assertTrue(false)` into the top of the `testSpec()` method, which is definitely tagged with `@Test` and not `@Ignore`, no failure is recorded. I can't figure out why this test method is being skipped.

In total four tests are skipped within the `tlc2.tool.distributed` module:
- `DieHardDistributedTLCTest`
- `EWD840DistributedTLCTest`
- `EWD840DistributedWithFPSetTLCTest`
- `TSnapShotDistributedTLCTest`

These tests have one thing in common: they all extend `DistributedTLCTestCase`. I thought this might be because we have `<exclude name="**/DistributedTLCTestCase.java" />` in the JUnit Ant task, but removing that line doesn't make the tests not be skipped.

**Comment by ahelwer** [comment]
Ah, it's because of this line:

https://github.com/tlaplus/tlaplus/blob/cfd74fa2081bb62c4a53ce8bfc48f1de0bd5ae91/tlatools/org.lamport.tlatools/test/tlc2/tool/distributed/DistributedTLCTestCase.java#L68

**Comment by Calvin-L** [comment]
As you figured out, when an `assume` fails, JUnit skips the test. `assume /= assert`, despite the similar names.

We might consider adjusting this `assume` to capture in code what the English comment says:

```java
Assume.assumeTrue(
    "DistributedTLCTestCase broken with OffHeapDiskFPSet.",
    fpSetImplementation() != OffHeapDiskFPSet); 
```

But I'm not sure how easy that would be.

**Comment by lemmy** [comment]
All tests run with `OffHeapDiskFPSet`.

https://github.com/tlaplus/tlaplus/blob/cfd74fa2081bb62c4a53ce8bfc48f1de0bd5ae91/tlatools/org.lamport.tlatools/customBuild.xml#L505

https://github.com/tlaplus/tlaplus/blob/cfd74fa2081bb62c4a53ce8bfc48f1de0bd5ae91/tlatools/org.lamport.tlatools/customBuild.xml#L567
